moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.h

It never existed, because the class contains a mutex object (not copyable).
clang complained about this discrepancy.

delete IKCache copy constructor

---

moveit_ros/perception/point_containment_filter/include/moveit/point_containment_filter/shape_mask.h

Cherry-pick from Melodic to master
https://github.com/ros-planning/moveit/pull/1457/files

Allow subclassing of point_containment_filter::ShapeMask. (#1457)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Currently we're using the old single-template issue approach:
https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository
Switching to dual approach: bug vs feature request

Update issue template to non-legacy workflow

---

moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/moveit_cpp/CMakeLists.txt
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning_interface/moveit_cpp/src/planning_component.cpp
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/moveit_cpp.yaml
moveit_ros/planning_interface/test/moveit_cpp_test.cpp
moveit_ros/planning_interface/test/moveit_cpp_test.test

As already discussed in the last maintainer meeting we at PickNik have a need for a set of low-level interface classes that allow us to use, modify and exchange core components without the overhead 
to adjust message types. Also, we are implementing performance-critical functions that are not throttled by the ROS ecosystem. The first MVP is a MoveGroup-like set of features that allows basic planning and execution for different planning groups. I will follow-up with more detailed explanation of the goals, requirements, roadmap and design decisions.

Implement low-level interface moveit_cpp

---

moveit_experimental/moveit_jog_arm/CMakeLists.txt

We're [officially C++14](https://moveit.ros.org/documentation/contributing/code/), which was already reflected in all packages except this one

Unify jog_arm package to be C++14

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp

Add an entry "<previous"> in the Update Start/Goal State drop-down list for referencing a previous pose. 
Fixes #14

Add "<previous>" support robot state to RViz motion display #14.

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

This fixes a small bug introduced in https://github.com/ros-planning/moveit/pull/1428 where loadConstraintDatabase would load the parameter from rosparam and then try to recursively call itself.

fixing CADB loading bug

---

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/render_shapes.h
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/robot_state_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/render_shapes.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

Attached bodies were not included in the trail visualization of a trajectory, changing the type from rviz::Robot to RobotStateVisualization solves this issue (#190).
Anyway, the bodies color is always green, I didn't find a proper way to get the color of the attached object and set it in the update method.

Show attached bodies trail in RViz

---

moveit_core/macros/include/moveit/macros/class_forward.h
moveit_core/macros/include/moveit/macros/declare_ptr.h

Lately, we encountered a number of interfaces, where unique_ptr
would be the preferred smart pointer to use.
This adds them to the class forward macros.
Fixes  #1770 .

support unique_ptr.

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp

... to ensure that the most recent current state is actually used for planning
When testing #1766 I observed several times that planning, triggered from, rviz wasn't using the most recent RobotState (where I just added an attached object).
The reason was the following:
- The rviz plugin queried the current state on startup.
- Then I added an attached object, which was correctly reflected by the PlanningSceneDisplay.
However, the start state was still referring to the original state at startup.
- Planning didn't use the current robot state, but the one saved at some point in the past.
- I was wondering, why the attached object wasn't considered during planning.

rviz panel: pass <current> start state as empty to move_group

---

moveit_core/planning_scene/test/test_multi_threaded.cpp

As discussed in [this PR review](https://github.com/ros-planning/moveit/pull/1657#discussion_r348925925), instead of an extra test case the robot setup should be tested in each run.

Move ASSERT() into test setup function

---

moveit_ros/planning_interface/test/CMakeLists.txt

As we don't yet have a solution for the flaky test (#1780 and #1781 still fail), I suggest to disable the unit test for now. @JafarAbdi, please test #1781 locally and provide a stack trace if possible.

disable flaky moveit_cpp_test

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h

This is an alternative for #1741. Thanks to the very detailed analysis of @jschleicher, the race condition reported in #1493 was tracked down to an issue in actionlib: https://github.com/ros/actionlib/issues/155.
"As the done callback is really short" (https://github.com/ros-planning/moveit/pull/1741#issuecomment-557279556), the busy-waiting solution offered in #1741 is temporarily acceptable. Due to the same fact, I suggest to drop the remaining boilerplate (considering the timeout) of #1741 as well and keep the quick fix as simple as possible.

ControllerManager: wait for done-callback

---

moveit_ros/move_group/CMakeLists.txt
moveit_ros/move_group/default_capabilities_plugin_description.xml
moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.cpp
moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.h

This PR points to issue #1735 . I have implemented a move_group capability, which publishes frames of planning scene objects to the tf system.

move_group capability for publishing planning scene frames to the tf system

---

moveit_commander/src/moveit_commander/conversions.py
moveit_commander/src/moveit_commander/planning_scene_interface.py

Python3 related import fixes for moveit_commander package.
- force relative import in conversions.py and planning_scene_interface.py
- try to import StringIO from StringIO module first, then from io module
Related to #1722

[moveit_commander] python3 import fixes

---

moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h

There is a mismatch between the documentation and the implementation.
Implementation uses XYZ Euler angles, documentation says ZXZ.
The implementation can be seen in [kinematic_constraint.cpp](https://github.com/ros-planning/moveit/blob/acead73aae0df309eaeb1a71ebe3f0bffce8efba/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp#L601) and in [default_constraint_samplers.cpp](https://github.com/ros-planning/moveit/blob/acead73aae0df309eaeb1a71ebe3f0bffce8efba/moveit_core/constraint_samplers/src/default_constraint_samplers.cpp#L479).
I don't think the checklist below is relevant for such a small change (only a single line).
Is such a small change even worth a pull request?
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, …

documentation mismatch in kinematic_constraint.h

---

moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.cpp
moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.h

This PR adds functionality of publishing attached collision objects and their subframes to the TfPublisher capability.
It also fixes the timestamps for the transform msgs.

Publish attached collsion objects with the move_group TfPublisher capability

---

moveit_core/robot_model/src/robot_model.cpp
moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning_interface/moveit_cpp/src/planning_component.cpp
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/moveit_cpp_test.cpp
moveit_ros/planning_interface/test/moveit_cpp_test.test

As pointed out in https://github.com/ros-planning/moveit/pull/1780#issuecomment-558587911,
1. The robot model loader doesn't complain about malformed group states (having missing joints).
2. FakeControllers used those uninitialized joint values for publishing.
Both issues are fixed with this PR. This should fix the flaky moveit-cpp unit test.

Fix group states

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

If enabled, the internal state of of planners does not get cleared.
This can be enabled per planner. It only makes sense for roadmap-based
planners (or if the start state does not change). Additionally, for
PRM, PRM*, LazyPRM, and LazyPRM* it is possible (when using OMPL 1.5.0)
to load/save roadmaps from disk upon creation/destruction. This is
set in ompl_planning.yaml like so:
```
planner_configs:
PersistentPRM:
type: geometric::PRM
multi_query_planning_enabled: true
store_planner_data: true
load_planner_data: true
planner_data_path: /tmp/roadmap.graph
```
This commit also fixes a bug for PRM-family planners where they would
always run as optimizing planners and not terminate when the first
solution was found. This occurs when the default optimization objective
is set when none are …

add support for multi-query planning

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

When multi-query planning is enabled (a feature add in PR #1799), the roadmap is kept around between calls to solve. When the planning scene doesn't change between calls to solve(), this is not a problem. In pick-and-place tasks it often does, so it makes sense to recheck validity of nodes/edges. With LazyPRM / LazyPRMstar this is easy to do. For PRM / PRMstar it does not make sense.

clear roadmap validity for LazyPRM/LazyPRMstar when using multi-query planning is enabled

---

moveit_kinematics/test/benchmark_ik.cpp
moveit_planners/chomp/chomp_motion_planner/src/chomp_cost.cpp

Local variables are used as denominator in `measure_ik_call_cost.cpp` and `chomp_optimizer.cpp`.
These variables are initialized with zero and there are cases when they are used without changing value.
This fix adds checking the local variable against zero. (In `chomp_optimizer`, the fix is applied to the function `ChompCost::scale`)

[AIST-QA]Fix possibile division-by-zero issues.

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch

The name of the launch argument in the invoked launch file `moveit_rviz.launch` is `rviz_config` but is incorrectly called as `config`here. This fix was already merged with `demo.launch` but was missed for this file.   
Simply launching this launch file now throws the unused args error.

Fix Rviz argument in demo_gazebo.launch

---

MIGRATION.md
moveit_core/robot_trajectory/CMakeLists.txt
moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp

This PR points to issue #1660. I have deprecated the "normal" copy constructors and added two new methods, `RobotTrajectory::copy()` and `RobotTrajectory::deepCopy()`. Also documented these methods.

Add `copy()` and `deepCopy()` methods to RobotTrajectory class.

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/collision_check_thread.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_cpp_interface.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_interface_base.h
moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_experimental/moveit_jog_arm/src/cpp_interface_example/cpp_interface_example.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp

This moves thread handling to the JogBaseInterface class and adds atomic bool flags for stopping all main loops from outside their threads.
Also, this fixes an issue where the `CollisionCheckThread` would indefinitely wait for command messages and won't get to run any collision checks using the C++ API.

Improve JogArm thread handling

---

moveit_ros/warehouse/warehouse/src/import_from_text.cpp

The local variable `value` is not initialized and stored in `std::map <std::string, double> v[joint]` regardless of whether `maker` equals `"="` or not. For that reason, it may cause undefined behavior if `marker` is `"="` and `value` is not set via input stream.
This fix extends the scope of the conditional branch of `marker`: `value` is stored `v[joint]` only when `marker` equals `"="`.

[AIST-QA] Fix potential use of uninitialized variable in moveit_ros.

---

moveit_commander/src/moveit_commander/planning_scene_interface.py

Moveit commander's planning scene interface tries to spawn objects without accounting for the specified namespace.

Fix planning scene interface not respecting custom namespace

---

moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp

The member variable `scene_manager_` is not initialized in the constructor of `OcTreeRender`. Since a parameter called `scene_manager` exists in the constructor arguments, it appears to have been forgotten to initialize `sacene_manager_`.
This fix adds initialization of  `scene_manager_` to the `OcTreeRender` constructor.

[AIST-QA] Initialized scene_manager_ member varianle in OcTreeRender constructor

---

moveit_core/robot_state/src/robot_state.cpp

Fixes a memory leak described here: https://github.com/ros-planning/moveit/issues/1820

delete attached body before adding a new one with the same id

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

This fixes all issues outlined in #1115 (and some more) regarding the interactive marker for the selected planning scene object in the `Scene Objects` tab of the motion planning panel:
- Resize the interactive marker with the object shape
- Remove visual artifacts (showing a coordinate frame and black lines) when re-enabling the display
This was caused by the marker being re-enabled (with all its children nodes) before axes got disabled again. I fixed this by calling `MotionPlanningFrame::disable()` in `MotionPlanningDisplay::onDisable()` - instead of just hiding the panel (as introduced in #760) - and resetting the interactive marker there.
- This also resolved the third issue mentioned in #1115: The interactive marker showed up in the rendering panel even though the motion planning …

fix scene object marker in rviz plugin

---

moveit_ros/visualization/motion_planning_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/planning_scene_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/robot_state_rviz_plugin/CMakeLists.txt
moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/octomap_render.h
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp
moveit_ros/visualization/trajectory_rviz_plugin/CMakeLists.txt

Switching to a newer Ogre version (as supported by rviz' noetic version) requires some changes in MoveIt as well...

Fix compatibility issues with Ogre 1.10..1.12

---

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/octomap_render.h
moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/render_shapes.cpp

Require a valid `parent_node` to be passed (and drop `scene_manager` argument that was just used to retrieve the scene's root node in case parent_node was `NULL`).
Modified cherry-pick of #1817.

Cleanup OcTreeRender's constructor interface

---

moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp

Fix issue in collision_check_thread in jog_arm where link transforms aren't being updated before call to checkCollision.

update link transforms before calling checkCollision on robot state in jog_arm

---

moveit_setup_assistant/src/widgets/end_effectors_widget.cpp

In `end_effectors_widget.cpp`, `searched_data` variable is not deleted which causes a memory leak.
This issue may have been overlooked because the similar bugs were fixed in other source files (`virtual_joints_widget.cpp` and `robot_poses_widget.cpp`).
This fix adds `delete searched_data;` to the function `doneEditing()`.

[AIST-QA] Fix memory leak issue in end_effectors_widget.

---

moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
moveit_setup_assistant/src/widgets/end_effectors_widget.cpp

In the constructor of `RDFLoader` class, when `umodel` can not initialized, an error is shown and the constructor returns after showing an error message. In this case however, the `umodel` variable is not deleted which causes a memory leak.
This fix adds `delete umodel;` to the scope when constructor terminate prematurely.

[AIST-QA]  Fix memory leak issue in rdf_loader

---

moveit_setup_assistant/src/widgets/end_effectors_widget.cpp

Better fix for #1828: Avoid explicit use of new/delete when we use shared pointers anyway.
Cleanup #1829: Use range-based for-loop

Follow up on #1828 and #1829

---

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp

Added an implementation for TranslationXAxisAngle4D TranslationYAxisAngle4D and
TranslationZAxisAngle4D. @nxdefiant tested this with his robot arm for the
TranslationZAxisAngle4D IK type (see #548); the rest should be analogous.
Can be cherry-picked onto kinetic.
Fixes #548 .

ikfast: implement Translation*AxisAngle4D IK type

---

.travis.yml
moveit_core/CMakeLists.txt
moveit_core/CMakeModules/FindBullet.cmake
moveit_ros/planning/planning_components_tools/CMakeLists.txt

This PR adapts the build process in order to add the Bullet dependent code only if the available version is greater than Bullet version 2.86 (2.87 is the one available through apt on Ubuntu 18.04).

Adapt cmake for Bullet

---

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp

This fixes a pretty critical bug where the planning frame is different from the model frame and when the published twist commands are not in the default command frame. The original implementation seems to only work for cases where planning and model frame are the same or at least in the same orientation. This implementation fixes all command frames (which is a requirement for closed-loop control applications)

Fix command frame transform computation

---

moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp
moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp
moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h
moveit_ros/planning/plan_execution/src/plan_execution.cpp

This PR adds a list of controller names to `ExecutableTrajectory` which is passed to the `TrajectoryExecutionManager` (TEM) in `PlanExecution::executeAndMonitor()`. This allows users to specify which controllers should execute a certain trajectory (or only a part of it). The TEM already had the ability to manage different controllers for different trajectory parts, it just was not used before.
Additonally, the `FakeControllerManager` now reads the `default` parameter from the `controller_list` on the param server and initializes the `ControllerState`  accordingly. Before, each `ControllerState` had `default_` and `active_` set to `true` which lead the TEM's controller selection mechanism to choose any controller when no explicit controller name was given.
[The …

Allow specification of controller names for trajectories

---

moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp

- jog_arm loads a PSM which always had a warning because no tf_buffer was loaded.
- A number of ROS_INFOs I thought were unnecessary, so I moved to DEBUG
- Made one warning more useful

Reduce console output warnings

---

.travis.yml

This reverts commit 384c231b143b73ada9a8ee0eb11cf22435309ef3 as the offending tf2 release commit was reverted: https://github.com/ros/rosdistro/pull/23469#issuecomment-576669925.

Reenable ros-shadow-fixed on Travis

---

moveit_experimental/moveit_jog_arm/CMakeLists.txt
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/collision_check_thread.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_cpp_interface.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_interface_base.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_ros_interface.h
moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_experimental/moveit_jog_arm/src/cpp_interface_example/cpp_interface_example.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp
moveit_experimental/moveit_jog_arm/src/jog_server.cpp
moveit_experimental/moveit_jog_arm/src/low_pass_filter.cpp
moveit_experimental/moveit_jog_arm/test/jog_cpp_interface_test.cpp
moveit_experimental/moveit_jog_arm/test/jog_cpp_interface_test.test
moveit_experimental/moveit_jog_arm/test/launch/jog_arm_integration_test.test

- Separate LOGNAME into each file
- Add unit test
I need to pass in the PSM from a larger application. Previously it required creating a new PSM even in the same process

[jog_arm] Pass planning scene monitor into cpp interface

---

moveit_experimental/moveit_jog_arm/config/ur_simulated_config.yaml
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/test/arm_setup/config/jog_settings.yaml
moveit_experimental/moveit_jog_arm/test/integration/test_jog_arm_integration.py

Previously, the `scale/joint parameter` was also being used to check velocity limits. This was confusing (even to me!). It's also redundant with the SRDF velocity limits.
So that velocity check is removed.
This PR also adds:
-  a unit test for direct joint jogging commands.
- a check that publish_period is >0

[jog_arm] Remove scale/joint parameter

---

moveit_planners/sbpl/core/sbpl_interface/src/bfs3d/BFS_3D.cpp
moveit_planners/sbpl/core/sbpl_interface/src/bfs3d/Search.cpp

Add missing BSD license headers to Search.cpp and BFS_3D.cpp source files.

Add license headers to sbpl source files

---

moveit_ros/move_group/src/default_capabilities/get_planning_scene_service_capability.cpp
moveit_ros/move_group/src/default_capabilities/get_planning_scene_service_capability.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

This will eliminate that pesky warning message we've had for years:
> ros.moveit_ros_planning.planning_scene_monitor: Failed to call service get_planning_scene, have you launched move_group? at /moveit/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp:489
All you need to do is start the service for your master PSM.

Move get planning scene service functionality into PSM for reusability

---

moveit_plugins/moveit_ros_control_interface/moveit_ros_control_interface_plugins.xml
moveit_setup_assistant/src/widgets/controller_edit_widget.cpp

Added support for ros_control controllers:
- pos_vel_controllers/JointTrajectoryController
- pos_vel_acc_controllers/JointTrajectoryController
Adds the pos_vel_controllers/JointTrajectoryController and the pos_vel_acc_controllers/JointTrajectoryController to the moveit_ros_control_plugin_interface.

Add support for pos_vel_controllers and pos_vel_acc_controllers

---

moveit_ros/move_group/src/default_capabilities/get_planning_scene_service_capability.cpp
moveit_ros/move_group/src/default_capabilities/get_planning_scene_service_capability.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

This is a relaunch of #1852, which was prematurely merged and subsequently reverted.
To avoid calling its own service to initialize the PlanningScene, I added a protection in `requestPlanningSceneState()`.

Move get_planning_scene service into PSM for reusability

---

moveit_ros/planning_interface/CMakeLists.txt

I think this was a typo. In my tests libboost_python is being found and linked also with Boost 1.67.0 with this change. Related to #1850

Fix typo elseif() to else()

---

moveit_core/robot_state/src/robot_state.cpp

`hasLinkModel()` and `getLinkModel()` both search for the link name...

getFrameInfo(): avoid double search for link name

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/test/integration/test_jog_arm_integration.py

Fix the logic on empty trajectory check
Restore the integration test settle time.
Rename checkIfJointsWithingSRDFBounds -> enforceSRDFJointBounds
Credit to Henning for catching the logic error.
Hopefully fixes #1858

Fix the logic on empty trajectory check

---

moveit_commander/bin/moveit_commander_cmdline.py
moveit_commander/src/moveit_commander/conversions.py
moveit_commander/src/moveit_commander/interpreter.py
moveit_commander/src/moveit_commander/robot.py
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp
moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/serialize_msg.h
moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp
moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py

TL;DR In boost::python with Python 3, std::string (which are used for message serialization) are implicitly converted to Unicode objecs instead of Bytes (which represent binary data).
See #1869

Python 3 friendly message serialization (master branch)

---

moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

(At least partially) fixes  #1805.  Calls to `acos` can result in nan values if not careful due to numerical floating point errors.  If there is a possibility of calling `acos` on values that are approximately `-1`, then it will result in nan, which leads to a segfault later in totg. Also removes an incorrect comment that implies a section would avoid this error, but it actually handles a different case.

Fix segfault in totg

---

moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp

Fixes issue
https://github.com/ros-planning/moveit/issues/1682
by porting
https://github.com/OctoMap/octomap_rviz_plugins/pull/30
I took the liberty of using `getIndexKey` instead of `getKey`. AFAIK, `getIndexKey` returns the key of the first corner of the voxel. Then, all those ternaries in the original patch are not necessary.

Fix pruning of enclosed nodes when rendering octomap in RViz

---

moveit_experimental/moveit_jog_arm/CMakeLists.txt
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/test/arm_setup/config/singular_position.yaml
moveit_experimental/moveit_jog_arm/test/launch/jog_arm_halt_msg_test.test
moveit_experimental/moveit_jog_arm/test/launch/jog_arm_msg_reception_test.test
moveit_experimental/moveit_jog_arm/test/test_halt_msg/test_jog_arm_halt_msg.py
moveit_experimental/moveit_jog_arm/test/test_msg_reception/test_jog_arm_msg_reception.py

- Document the applyVelocityScaling() function better
- Rework the halt message so it includes singularities and collision proximity, as well as joint limits
- Add a test for this
The gif shows True being published when close to collision (you have to look fast though, true only flashes for a second).

[jog_arm] Rework the halt msg functionality

---

moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp

Workaround for #1875. Looks like `NodeHandle::searchParam` is buggy and returns true even if it hasn't found the parameter. Similar code proceeds in the same fashion, i.e. using an addition `hasParam()` test:
https://github.com/ros-planning/moveit/blob/1ec63725e998a377edb743bd33819fc9e304dab7/moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp#L302-L303

Fix spurious warning message (# IK attempts)

---

moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp

This cherry-picks the bugfix from #1685 to melodic-devel, previously applying the variable name changes originally introduced by clang-tidy on master branch.

Cherry-pick #1685 to melodic-devel

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_cpp_interface.h
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/test/test_msg_reception/test_jog_arm_msg_reception.py

- Fix a bug where the end effector transform jumped initially, when the first jog command is received.
- Reduce duplicate code between joint jogging and Cartesian jogging.
- Remove the joint velocity low-pass filters. I justify this because joint velocities are derived from joint positions (which do get filtered).
- This required some re-ordering of the algorithm. I think the flow makes a lot more sense now.

[jog_arm] Fix initial end effector transform jump

---

moveit_core/CMakeLists.txt
moveit_core/kinematics_base/CMakeLists.txt
moveit_kinematics/test/CMakeLists.txt
moveit_ros/perception/mesh_filter/CMakeLists.txt

Fix various build breaks found in Windows build:
* Conditionally guard some add_compile_options doesn't apply to `MSVC`.
* Add `zlib` as a dependency to look for in `Boost`. (On Windows, `boost::iostreams` depends on `boost::zlib` at linkage time.)
* Replace `glut` and `GLEW` with the CMake variables.

[Windows][master] Fix various build breaks found in Windows build

---

moveit_core/robot_state/src/robot_state.cpp
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp

Currently, when setting `copy_dynamics_` to `true`, the current state would not have any velocity or effort values (i.e. `RobotSate::hasVelocities()` is *false*) if the joint state message only contains zero values for dynamics. IMO the values should be written to the robot state initially so that a caller can check if dynamics have been updated or not even though the values are 0. With this PR, the robot state dynamics will always be updated if `hasVelocities()`/`hasEffort()` are false.

Initialize zero dynamics in CurrentStateMonitor

---

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp

Output an error message if the Occupancy map monitor fails to find the `sensors` parameter namespace with a list of sensors.  The current behavior is for the occupancy map monitor to silently not load.

Add error message on failure to load occupancy map monitor

---

moveit_core/planning_scene/src/planning_scene.cpp

This is another older patch I did not get around to pull-request before...
The world object already gets removed from the world [later on](https://github.com/ros-planning/moveit/compare/master...v4hn:pr-master-delete-once?expand=1#diff-8aac12a54166575f8df07630635ac4ffR1554), so it does not make a lot of sense to remove it here?

delete world object only once

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/low_pass_filter.h
moveit_experimental/moveit_jog_arm/src/low_pass_filter.cpp

These warnings and errors handle warning the user of bad input parameter values for the low pass filter in jog arm.  Here is the function of the feedback magnitude with respect to the `low_pass_filter_coeff` value: https://www.wolframalpha.com/input/?i=y+%3D+%281%2F%281%2Bx%29%29+*+%281-x%29
Here is a small python script that shows why these values are problematic:
```python
def run_filter(mu, length):
x0 = x1 = y1 = 0
y = x = [0 for i in range(length)]
x[0] = 1
for i in range(length):
x1 = x0
x0 = x[i]
y[i] = (1.0 / (1.0 + mu)) * (x1 + x0 + (1.0 - mu)*y1)
y1 = y[i]
print(mu, sum(y))
run_filter(2.0, 1000)
run_filter(1.0, 1000)
run_filter(0.5, 1000)
run_filter(0, 1000)
run_filter(-0.5, 1000)
run_filter(-0.999, 1000)
run_filter(-2, 1000)
```
output:
```
(2.0, 0.5000000000000002)
(1.0, 1.0) …
```

add warnings to jog_arm low_pass filter

---

moveit_ros/occupancy_map_monitor/CMakeLists.txt
moveit_ros/occupancy_map_monitor/package.xml

explicit dependencies to tf2_ros, geometric_shapes and boost are added.
I noticed some linking errors while compiling from source. Applies to master as well

[occupancy_map_monitor] add dependencies

---

moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp

Starting the main loop in a thread and immediately calling `JogCppAPI::getCommandFrameTransform()` can result in a segfault if `jog_calcs_` has not been created yet. This change checks if `jog_calcs_` is not null before testing `jog_calcs_->isInitialized()` so that early calls to `JogCppAPI::getCommandFrameTransform()` return `false`.

Fix segfault with uninitialized JogArm thread

---

moveit_experimental/moveit_jog_arm/CMakeLists.txt
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_interface_base.h
moveit_experimental/moveit_jog_arm/package.xml
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp
moveit_experimental/moveit_jog_arm/test/arm_setup/config/initial_position.yaml
moveit_experimental/moveit_jog_arm/test/arm_setup/config/singular_position.yaml
moveit_experimental/moveit_jog_arm/test/launch/jog_arm_drift_dimensions_service_test.test
moveit_experimental/moveit_jog_arm/test/test_drift_dimensions_service/test_drift_dimensions_service.py
moveit_experimental/moveit_jog_arm/test/test_halt_msg/test_jog_arm_halt_msg.py
moveit_experimental/moveit_jog_arm/test/test_msg_reception/test_jog_arm_msg_reception.py

Add a ROS service to turn redundancy on/off in specific dimensions. For example, maybe you could allow wrist rotation by `drift_x_rotation == true`. For now, the reference frame is the jogging command frame.
This depends on this moveit_msgs [PR](https://github.com/ros-planning/moveit_msgs/pull/63)
Here are 2 gif's starting from a singular position, without and with allowing drift respectively. It's trying to move in the world Y-direction. The first gif shows it stuck. The second gif moves past the singularity, no problem.

[jog_arm] a ROS service to enable task redundancy

---

moveit_core/CMakeLists.txt
moveit_core/collision_detection_bullet/empty_description.xml

Fair warning: This only fixes the install workspace, in the devel workspace if bullet was not found at compile you will still get errors from pluginlib.
Added an "empty" pluginlib xml file to be installed in place of `collision_detector_bullet_description.xml` if bullet is not found at compile time.
Related PR: #1839 

Installs an empty plugin description xml file if bullet is not found

---

moveit_planners/ompl/ompl_interface/src/parameterization/joint_space/joint_model_state_space_factory.cpp
moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space_factory.cpp

Fixes issue #1411 
So found two occurrences of ModelBasedSpacePtr() allocations and changed it to `std::make_shared` type allocations.
Any other places this performance fix may apply ? 

changes made to ModelBasedStateSpacePtr() calls

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_cpp_interface.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_interface_base.h
moveit_experimental/moveit_jog_arm/src/cpp_interface_example/cpp_interface_example.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/test/jog_cpp_interface_test.cpp

This cleans up a few things in jog_arm:
- Renames JogCppApi class to JogCppInterface to match the filename
- Fix a crash when the dimensions of the Jacobian changed
- Doxygenize some comments
- Make the inheritance of JogInterfaceBase public. I wanted this so I could call the functions from external C++ code, like this:  `jog_interface_ptr_->changeDriftDimensions(...)`

Jog cpp api fixes

---

moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

GCC 5 suffers from [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56480) bug, which means that you cannot have template specializations defined outside a scope (in the global namespace).

Fix for ompl 1.5.0 in g++5 (Xenial)

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h

Fixes issue #1908.
`setJointPositions` method is misleading for some users to believe that they can set positions for multiple joints. `setVariablePositions` is for that purpose. I have added documentation explaining the same.

Improves documentation for setJointPositions()

---

moveit_setup_assistant/src/widgets/robot_poses_widget.cpp
moveit_setup_assistant/src/widgets/robot_poses_widget.h

Without this patch, moving through the list with cursor keys
does not trigger the display to show the selected pose.

MSA: robot poses should be display on selection, not on click

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/robot_poses_widget.cpp

It looks ugly when robots start up in nonsensical poses when running `demo.launch`, and I don't think it should be the default behavior. Setting the robots' initial pose is perfectly possible, but it requires [a manual addition to `kinematics.yaml`](http://docs.ros.org/api/moveit_tutorials/html/doc/fake_controller_manager/fake_controller_manager_tutorial.html#yaml-file-examples) that users have to look up. This PR changes the behavior of the setup assistant so that if group states (robot poses) are defined in the setup assistant/SRDF, the first one is automatically exported to `kinematics.yaml` as the initial pose of that group.
I believe this will increase discoverability of the feature and be a better default setting.
When no pose is set, the default name "home" is exported. I confirmed …

Add initial poses to fake_controllers.yaml

---

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/tools/moveit_config_data.cpp

The old logic just picked the first one from each list,
not necessarily matching for non-trivial robots...

MSI: use matching group/state name for default state

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

When calling `PlanningSceneMonitor::requestPlanningSceneState` there is a 5 second wait for the service to be connected to a client.  This causes rviz to freeze for 5 seconds for each planning scene topic it is listening for whenever you try to connect to it, unless you specifically broadcast those topics before starting rviz.  ~~I propose removing this wait entirely, and simply failing if we are not connected.  If it is frequently necessary to wait in order to successfully get the full state of the planning scene when only diffs are being published, I suggest at least reducing the wait to a much lower time.~~
Changes to call the planning scene request as a background thread so that it does not freeze rviz.

Remove pause when connecting rviz to planning scene monitor

---

moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp

As pointed out in https://github.com/ros-planning/moveit/issues/1940#issuecomment-596104746, calling processEvents() results in an unintended recursion, calling TrajectoryVisualization::update() again from an only partially initialized state.
I wasn't able to reproduce the issue mentioned in https://github.com/ros-planning/moveit/pull/239#issue-86291573, that originally made me introducing this call.

Fix segfault in RobotStateVisualization: remove processEvents()

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

I just read through https://github.com/ros-planning/moveit/issues/1835 and https://github.com/ros-planning/moveit_task_constructor/issues/122 which describe a problem with collision checking of attached objects ending up in self-collision.
I am sorry. I debugged this problem in a hurry already back in October for a demo,
but did not get around to investigate further or create a thread for it. :frowning_face: 
This patch resolved the problem for me, although it is likely not the best solution.
Without digging deeper into this again, here's what I recall:
- Collision detectors maintain separate collision structures for padded and unpadded collision checking
- Apparently the unpadded collision checking is thought to be less popular and is only allocated when it is requested through API that …

"object" collides with "object": unconditionally allocate unpadded collision environments

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp

To execute MTC solutions from the rviz plugin, one needs a possibility to constrain RobotTrajectory messages to the actually moving joints. Usually, this is done via the associated JointModelGroup:
https://github.com/ros-planning/moveit/blob/ece0b7b44da2cfcf178e557557bc9d2693d17d5f/moveit_core/robot_trajectory/src/robot_trajectory.cpp#L226-L227
However, when deserializing received RobotTrajectory messages, I cannot infer the corresponding JointModelGroup anymore. Hence, this information is lost. But, remembering the involved joint names, it's possible to filter the RobotTrajectory for relevant joints during serialization into a message. This is what this PR proposes.

allow to filter for joints when creating a RobotTrajectory message

---

moveit.rosinstall
moveit_planners/trajopt/test/trajectory_test.test
moveit_ros/benchmarks/examples/demo_panda.launch
moveit_ros/benchmarks/examples/demo_panda_all_planners.launch
moveit_ros/benchmarks/examples/demo_panda_all_planners_obstacles.launch
moveit_ros/benchmarks/examples/demo_panda_predefined_poses.launch
moveit_ros/planning/launch/collision_checker_compare.launch
moveit_ros/planning_interface/test/moveit_cpp_test.test
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajopt_planning_pipeline.launch.xml

As pointed out in https://github.com/ros-planning/moveit/issues/1903#issuecomment-586569789, following our [install-from-source procedure](https://moveit.ros.org/install/source/), will install `panda_move_config` and, as their dependencies, several other MoveIt packages from debians.
This is usually not desired.
Interestingly, none of the MoveIt packages actually package-depend on panda_moveit_config.
However, `moveit_tutorials` does. As this, but not `panda_moveit_config` is listed in `moveit.rosinstall`, all these binary packages get installed.
Searching for panda_moveit_config in the source base, I found several uses of the package, which will get replaced by the corresponding `moveit_resources` package now.
Please merge as a merge-commit to keep all three, independent commits.
Fixes …

Fix usages of panda_moveit_config

---

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h
moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp

Fixes #1580. (C)Python has a Global Interpreter Lock (GIL) which should be released when doing long-lasting C++ calls.

[planning_interface] Release Python GIL for C++ calls

---

moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h
moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_manipulation.cpp

Supersedes #1950 .
I implemented an alternative way to construct a PSI, enabling users to detect issues with the ROS services instead of locking up the thread waiting for them.
It does not harm to have this option around.
Looking at the RViz display code again, I decided against making use of this feature here though.
The display already maintains a PSM, so I rewrote the logic to use this instead and  altogether got rid of the PSI.

Resolve PSI lock-up in RViz display

---

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp

I needed to use the parameter TranslationXY2D in IKFast, so I added 2 lines of code, it worked for me. Related issue : #1931

 Implementation of parameter TranslationXY2D IKFast

---

moveit_experimental/moveit_jog_arm/package.xml

I'm working on a build farm that uses the master branch for Debian releases, but running `git-bloom-generate -y rosrelease melodic` gives
```
RuntimeError: Two packages have different version numbers (0.0.3 != 1.0.1):
- /tmp/tmpuEevgo/clone/moveit_experimental/moveit_jog_arm/package.xml
```

Fix versioning for jog_arm package

---

moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp

In #1321 I added random wiggling of joints when the optimization is stuck in a local minimum.
However, I didn't clip those changes to the feasible joint range.

KDL IK: constrain wiggled joints to limits

---

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

I just reviewed https://github.com/ros-planning/moveit_tutorials/pull/468 and
thought this would be a nicer way to execute Cartesian trajectories...

mgi: add execution methods for moveit_msgs::RobotTrajectory

---

moveit_experimental/moveit_jog_arm/config/ur_simulated_config.yaml
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/collision_check_thread.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_cpp_interface.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_interface_base.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/status_codes.h
moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_experimental/moveit_jog_arm/src/cpp_interface_example/cpp_interface_example.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp
moveit_experimental/moveit_jog_arm/test/config/jog_settings.yaml
moveit_experimental/moveit_jog_arm/test/python_tests/halt_msg/test_jog_arm_halt_msg.py

Rather than just a boolean, this publishes a more detailed status message.
I thought about publishing a vector of status codes, but some downsides of that are:
- it would require a custom message type
- the vector would have to be resized, which isn't great from a performance perspective. The code to handle that would be more complicated.

[jog_arm] Publish more detailed warnings

---

moveit_commander/src/moveit_commander/planning_scene_interface.py

I fixed service call by using original name space.
This PR is related to #1815 .
And that PR is lack to fix this service call part.

Fix service call to utilize original name space

---

moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_panda.h
moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_core/collision_detection_fcl/test/test_fcl_collision_detection_panda.cpp

One line of code is changed in the *collision calculation* interface file for *FCL*.
Within the settings for a [distance request within *MoveIt!*](http://docs.ros.org/melodic/api/moveit_core/html/structcollision__detection_1_1DistanceRequest.html) the user can specify a [DistanceRequestType](http://docs.ros.org/melodic/api/moveit_core/html/namespacecollision__detection_1_1DistanceRequestTypes.html#ac754f7bfd3f776cb02a190e9a0fd893e).
I am using distance requests for avoiding collisions of the robot. Therefore, I want to check every *collision geometry* of a single *robot link* with the *world objects*. I am only interested in the closest point of each *robot link* to the *world object*, i.e. in the *collision geometry* of the *robot link* that is closest to the *world object*. Therefore, I …

Fix Condition for Adding current DistanceResultData to DistanceMap for DistanceRequestType::SINGLE

---

moveit_ros/planning_interface/CMakeLists.txt

I'd like to use the py_bindings_tools for my own Python C++ wrappers, but it's not yet included in `catkin_package()`. This results in a linking error (undefined symbol `moveit::py_binding_tools::ROScppInitializer::ROScppInitializer()`) when trying to load the Python C extension.
Btw., should this and #1870 be backported to melodic?

Export  moveit_py_bindings_tools library

---

moveit_commander/bin/moveit_commander_cmdline.py
moveit_commander/src/moveit_commander/conversions.py
moveit_commander/src/moveit_commander/interpreter.py
moveit_commander/src/moveit_commander/robot.py
moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp
moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/serialize_msg.h
moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp
moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py

Backporting #1870 and #1970 to melodic-devel.
* moveit_py_bindings_tools is exported with catkin
* Replaced `has_key()` with `in` statement (not available in Python 3)
* Message (de-)serialization via `bytes` in Python 3

Backport #1870 and #1970 to melodic-devel

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp

Ctrl+R is used by RViz to rename displays.
Overlaying the sequence semi-breaks the behavior
and the rename button gets selected, but not pressed.
This is an internal shortcut used in case the interactive markers
of the display fail to update correctly. This is seldomly (never?)
used, so remapping does not hurt anyone.
To the best of my knowledge Ctrl+I is not used in standard RViz.

MP display: change internal shortcut Ctrl+R to Ctrl+I

---

moveit_experimental/moveit_jog_arm/config/ur_simulated_config.yaml
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/status_codes.h
moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/test/config/jog_settings.yaml

Add a binary collision check to the distance-based collision check. This helps with edge cases like starting inside another body and reducing overall flakiness.
Also, delete the parameter _hard_stop_singularity_threshold_ which hasn't been used in some time.

[jog_arm] Add a binary collision check

---

.github/CODEOWNERS

Unfortunately I don't have time to be a maintainer or review pull
requests these days. I'm replacing myself with @tylerjw at the
suggestion of @davetcoleman.

Remove @jonbinney as a codeowner

---

moveit_kinematics/CMakeLists.txt
moveit_planners/ompl/CMakeLists.txt
moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt
moveit_plugins/moveit_ros_control_interface/CMakeLists.txt
moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt
moveit_ros/manipulation/CMakeLists.txt
moveit_ros/move_group/CMakeLists.txt
moveit_ros/perception/CMakeLists.txt
moveit_ros/planning/CMakeLists.txt
moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/robot_interaction/CMakeLists.txt
moveit_ros/visualization/CMakeLists.txt
moveit_ros/warehouse/CMakeLists.txt
moveit_setup_assistant/CMakeLists.txt

CI was failing because of missing CATKIN_DEPENDS errors from catkin_lint 1.6.7
See https://travis-ci.org/github/ros-planning/moveit/jobs/667658214#L694

Fix CATKIN_DEPENDS: catkin_lint 1.6.7

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp

This is a rebase of #1167. Essentially, changes in the panel are noted, such that rviz knows that the configuration has changed and will remind you for saving before closing.
This targets melodic and should be ported to master as well.
@agutenkunst, can you please validate?

Note changes in rviz planning panel requiring saving

---

.travis.yml

As we see once more at the moment, we *don't* **ever** want our CI to block because someone broke shadow-fixed. Assuming I didn't break anything, this should mitigate half [of your worries](https://github.com/ros-planning/moveit/pull/1999#issuecomment-606048430) @rhaschke ?
The other half being the incomplete migration to github apps that leads to github's guards waiting for completed CI jobs.
add a separate gcc shadow-fixed job as we still want the required clang check.
also adjust clang job to use global variables.
Job-variables are *all* included in the jobname on the website.

allow failure for shadow-fixed

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/collision_check_thread.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_cpp_interface.h
moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp

I ran into an issue where JogArm would initialize the low-pass position filters before processing the initial jog commands. The issue was that there was a separate "waiting loop" that initialized the filter  joint states which have never been updated. That caused an initial jump if the robot has moved between thread initialization and the first commands. Since the waiting loop and the main loop have a very similar structure, I thought it would be cleaner to just use a bool flag "wait_for_initial_commands" that leads to the same logic as before, just that the joint states are being updated, fixing the described issue. While debugging this issue I touched and refactored several other parts, including:
* Removing a duplicate joint increment with cartesian commands 4f47786
* Simplified the …

[jog_arm] Fix low-pass filter initialization

---

.travis.yml

Followup to #2003 .
I disapprove of shadow-fixed as a required CI check. Yes, we want to know about problems with shadow-fixed early, but not at the cost of contributors who see their jobs failing for no reason.
Instead, this pull-request adds a conditional job for the main branches only, so we still notice breakage after merge.
Here's my playground travis [with the additional job](https://travis-ci.com/github/v4hn/moveit/builds/158638495) and [without it for other branches](https://travis-ci.com/github/v4hn/moveit/builds/158638459).
Receiving email notifications for this particular job, [@rhaschke was worried](https://github.com/ros-planning/moveit/pull/2003#issuecomment-609445786), is not a problem in my opinion. All main web page on GitHub related to MoveIt as well as its travis pages …

run shadow-fixed for main branches only

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp
moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp

Switching back and forth between joint commands and Cartesian commands could be buggy sometimes. The change at line 203 of jog_calcs.cpp fixes that.
Some flags were renamed and their logic was flipped to help readability

[jog_arm] Fix valid cmd flags

---

moveit_ros/planning_interface/package.xml
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp
moveit_ros/planning_interface/test/move_group_interface_cpp_test.test

I realized there was no test of the c++ interface of move_group.  This PR fixes that to defend the interface used by our newest users against unintended breakages.

add tests for move_group interface

---

moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/test/config/jog_settings.yaml

This is a fix to a logic error in my PR that was just merged (#2008). I had `!A && !B` where `!(A && B)` is correct.

fix param logic bug for self- and scene-collision proximity thresholds

---

moveit_commander/src/moveit_commander/interpreter.py

There is certainly more, but this allows to `use <group>\ngo <named_state>`

commander: python3 fix

---

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
moveit_setup_assistant/src/widgets/group_edit_widget.cpp
moveit_setup_assistant/src/widgets/group_edit_widget.h
moveit_setup_assistant/src/widgets/planning_groups_widget.cpp
moveit_setup_assistant/src/widgets/start_screen_widget.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit_rviz.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/planning_context.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/run_benchmark_ompl.launch

This adds an option in MoveIt setup assistant to setup an additional yaml file with parameters for the kinematic solver(s). The main motivation for this is to improve integration of `opw_kinematics` [1] via the `moveit_opw_kinematics_plugin`[2]. Currently the kinematic chain needs to be described in parameters in the `kinematics.yaml` file. This makes it inconvenient to reuse the information from outside MoveIt (e.g. `descartes`) as other setups typically have no access to the group names defined in SRDF. This and alternative approaches was discussed at length in [3].
The plan is to distribute a MoveIt - independent YAML file along with the URDF description as can be seen in [4]. The user would then select the YAML file distributed along with the URDF file by ROS-Industrial. A separate …

Assistant: load additional file with kinematics parameters

---

.travis.yml

This should speed up builds by configuring travis to report success before code-coverage job finishes.  This shouldn't reduce the effectiveness of the testing as we are only using code-coverage for reporting and are not failing CI based on that report.

[ci] configure travis to report success before code-coverage finishes

---

.travis.yml
moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp

The mesh_filter test was disabled a long time ago. The test passes when relaxing the acceptance region to 1e-6.
Closes #1109 

[perception] fix mesh_filter test

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ompl_planning_pipeline.launch.xml

Some auxiliary PRAs can create additional waypoints,
so time parameterization must run *after* them on return of a successful plan,
which means it has to be loaded *before* them in the PRA chain.
Additionally, constraint names have to be resolved *before* fixing the input state w.r.t. them.
Look up the source code and documentation if you don't believe it.
This came up in https://github.com/ros-planning/moveit/issues/2052 .

fix ordering of request adapters

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

Also add some overdue helpers to `RobotState` while I was at it.
I'm happy to discuss naming if someone disagrees with my terminology.
The actual TOTG issue came up in:
https://github.com/ros-planning/moveit/issues/2052#issuecomment-624104306

TOTG: add zero parameterization for single-waypoint trajectories

---

moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_mimic_svd.hpp
moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h

Running locally, doxygen still manages to extract the correct comment.
See https://github.com/ros-planning/moveit/pull/2050/files#r420826217

move NOLINT instructions to intended positions

---

moveit_ros/move_group/src/default_capabilities/tf_publisher_capability.cpp

A silly mistake got through in #1792 . Without this PR, the scene looks like this:
After the change, it looks as expected.

Fix TfPublisher subframe publishing

---

moveit.rosinstall

`master` should always depend on our latest version of dependencies, although it pays to stay compatible with older versions.

depend on geometric_shapes `noetic-devel` branch

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

The value is treated as an integer internally and having a double for it in the GUI is just confusing...

MP display: planning attempts are natural numbers

---

moveit_core/planning_scene/src/planning_scene.cpp

To avoid issues like the one @tylerjw encountered in https://github.com/ros-planning/moveit/pull/2031, I think we should check for empty quaternions when adding objects to the scene. This is a lightweight operation compared to the `normalize` that we already apply to every message, so it seems reasonable to me. Please share your opinion.
Fundamentally this is only an issue because ROS quaternion messages default to an invalid value, but that's neither here nor there.
I'll run clang-format etc. when I am at my home machine.

Check for empty quaternion message when processing CollisionObjects

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

This adds the subframes to the text of the Rviz "Scene Objects" panel, makes the text copyable, increases its contrast and places it below the elements that move the selected object. 

Display subframes in Rviz plugin

---

moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

I was skimming through the internals and noticed this bit of logic which I think can be cleaned up.
Due to the check `priority > 0`, there is no time when `best == state_space_factories_.end()` while `priority <= prev_priority`, so `best == state_space_factories_.end()` is unnecessary. Then if you change the starting value of `prev_priority` then you don't need to separately check if `priority > 0`. 

Minor logic cleanup

---

moveit_core/robot_model/src/floating_joint_model.cpp
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/move_group_pick_place_test.cpp
moveit_ros/planning_interface/test/move_group_pick_place_test.test

Another test for basic functionality from our tutorials to protect the experience of new users.
There is a bunch of hard coded strings and magic numbers for the geometry for this test.  I would appreciate any way to reduce the complexity of the test code.  Most of the code for this was copied from the [tutorial](https://github.com/ros-planning/moveit_tutorials/blob/master/doc/pick_place/src/pick_place_tutorial.cpp) that does the same thing.  @mlautman do you see anyway to reduce the complexity of this test and the tutorial?
The actual test itself is just the return values of the `pick` and `place` method calls in the move_group.  Another potential improvement to this test would be to get the new location of the object that was placed and validate it is in the correct new position.  I'm …

[test] move_group pick place test

---

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp

Added a Point message to an empty joint_trajectory to prevent the jog server to crash on icall of invalid index.
- fixes #2047

[jog_arm] Fix crash on empty jog msgs

---

.travis.yml
moveit_commander/src/moveit_commander/interpreter.py
moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_planners/sbpl/core/sbpl_interface/include/sbpl_interface/sbpl_params.h
moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/package.xml
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp
moveit_ros/planning_interface/test/move_group_interface_cpp_test.test
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui
moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ompl_planning_pipeline.launch.xml

These are bug fixes for merging into melodic_devel for the upcoming release.
* remove unused angles.h includes (#1985)
* [ci] configure travis to report success before code-coverage finishes (#2041)
* Fix mesh_filter test (#2044)
* add tests for move_group interface (#1995)
* run shadow-fixed for main branches (#2012)
* fix ordering of request adapters (#2053)
* RS: add interfaces to zero and remove dynamics (#2054)
* totg: add a correct time parameterization for 1-waypoint trajectories (#2054)
* commander: python3 fix (#2030)
* add use_rviz to demo.launch in setup_assistant (#2019)
* MP display: planning attempts are natural numbers (#2076)
* fix signal for planning_attempts (#2082) 
* Wait and check for the grasp service (#2077)
* add aux check for shared-ptr (#2077)
* Added support for …

[melodic-devel] bug fix backport

---

moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/moveit_cpp/CMakeLists.txt
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning_interface/moveit_cpp/src/planning_component.cpp
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/moveit_cpp.yaml
moveit_ros/planning_interface/test/moveit_cpp_test.cpp
moveit_ros/planning_interface/test/moveit_cpp_test.test

This is a backport of MoveItCpp for melodic.  After talking with @henningkayser I realized we also need this released.  As far as I can tell backporting this does not break any existing API as it just extends a new API to a simplified internal interface.
This was a much simpler PR to build than the jog_arm one.

[melodic-devel] MoveItCpp backport

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/planning_scene_render.h
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/robot_state_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp

Alternative title: "MoveIt like it's 2020!"
This utilizes the `robot_state.is_diff` field in `PlanningScene` messages to send only joint state updates and teaches `PlanningSceneDisplay` to simply update the transforms in OGRE's scene graph instead of rebuilding the representation of both attached objects and collision objects. This reduces the time required for handling one update from 150-250ms down to 0.5ms in a simple scene typical for us. (one attached object (240kb), a couple more of those as collision objects, two boxes (few vertices) and  an octomap) (Note that updates where the scene geometry changes are still slow ...)
`AttachedObjects` are now attached to the corresponding link in OGRE as well, so their position no longer needs to be updated manually.
Furthermore this increases …

PlanningSceneDisplay speedup

---

moveit_core/distance_field/src/distance_field.cpp
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_ros/perception/point_containment_filter/src/shape_mask.cpp

As requested in https://github.com/ros-planning/geometric_shapes/pull/109#issuecomment-619560363.
I only found one candidate usage...

Utilize setScaleDirty() and setPaddingDirty() to improve performance

---

moveit_core/distance_field/include/moveit/distance_field/propagation_distance_field.h
moveit_core/distance_field/src/propagation_distance_field.cpp

This PR replaces `eucDistSq` with Eigen's built-in `squaredNorm`. This innocuous-looking change results in a speed-up of 25% for me when tested with a large set of points (benchmarked with >400k points).
Before: 1248ms
After: 956ms

[moveit_core] PropagationDistanceField: Speed-up insertion & update

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/planning_scene_render.h
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/robot_state_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp

This is a backport of #2049 done using
`git cherry-pick `26ec92850d4bae71bab1daf193981f66b0ad8beb`^..`2fc28767be58920fc74bdf57282b92424249a6b0
I'm including the command because I wasn't sure whether to include 736219d8a5d55d952b85eebf52ae6ea4e3220da8  as well
discussed also in #2066

[melodic-devel] PlanningSceneDisplay speedup backport 

---

moveit_core/robot_model/src/floating_joint_model.cpp

Backport of bugfix from https://github.com/ros-planning/moveit/pull/2031
@v4hn asked for this here: https://github.com/ros-planning/moveit/issues/2066
I didn't include the test that came with this.  LMK if you think I should backport that too.

[melodic-devel] change FloatingJointModel::getStateSpaceDimension return value to 7

---

moveit_core/collision_detection_fcl/src/collision_common.cpp

After clearing the octomap, the root node is set to NULL, which then causes FCL to segfault in collision checking. Maybe it's actually an FCL bug, but this was the most straightforward way I found to work around it.

prevent collision checking segfault if octomap has NULL root pointer

---

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/perception/semantic_world/src/semantic_world.cpp

Fix for https://github.com/ros-planning/moveit_task_constructor/issues/168.
This PR replaces:
- `PlanningScene::getTransforms().getTransform()` -> `PlanningScene::getFrameTransform()`
- `PlanningScene::getTransforms().canTransform()` -> `PlanningScene::knowsFrameTransform()`
throughout the whole MoveIt code base.
`getTransforms()` essentially yields the SceneTransforms instance of the `parent` scene only:
https://github.com/ros-planning/moveit/blob/272eaa01064df0b0184e2ad8766751ea27ef6c92/moveit_core/planning_scene/src/planning_scene.cpp#L630-L635
https://github.com/ros-planning/moveit/blob/272eaa01064df0b0184e2ad8766751ea27ef6c92/moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h#L172-L181
instead of creating a new layer of transforms as …

Fix getTransform()

---

moveit_ros/planning_interface/CMakeLists.txt
moveit_ros/planning_interface/move_group_interface/CMakeLists.txt

fix https://github.com/stack-of-tasks/eigenpy/issues/195
The issue there is that `eigenpy_INCLUDE_DIRS` doesn't provide numpy include dirs. Moreover, those `eigenpy_INCLUDE_DIRS` & `eigenpy_LIBRARIES` are backward compatibility artifacts from the pkg-config world and are now considered obsolete in modern CMake.
But thanks to https://github.com/ros-planning/moveit/pull/1737, eigenpy is found using `find_package`, so we can get all required information to find all the needed headers and link to all  the needed libraries with a `target_link_libraries` to the `eigenpy::eigenpy` imported CMake target.

[CMake] fix link to eigenpy

---

moveit_ros/visualization/CMakeLists.txt
moveit_setup_assistant/CMakeLists.txt
moveit_setup_assistant/package.xml

As you can see, right now the master branch is failing due to catkin_lint -- example: https://travis-ci.org/github/ros-planning/moveit/jobs/692499448

Fix catkin_lint

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
moveit_kinematics/test/test_ikfast_plugins.sh

This attempts to fix broken API in the IKfast plugins, which slipped in with the backport merge #1998.
Unfortunately, it was missed by Travis, because of other issues (missing python-lxml).

Fix Melodic 1.0.3 release

---

moveit_plugins/moveit_ros_control_interface/CMakeLists.txt
moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

Code states "This can be removed upon EOL Indigo", which MoveIt has EOL'd for master. Preparing for Noetic support instead.
Original PR: https://github.com/ros-planning/moveit/pull/551

Remove support for Indigo's ros_control

---

moveit_core/collision_distance_field/src/collision_distance_field_types.cpp
moveit_core/planning_scene/src/planning_scene.cpp

These fixes are related to the efforts and finding in this issue [https://github.com/ros-planning/moveit/issues/2075](https://github.com/ros-planning/moveit/issues/2075). However, this PR does not fix the leaks reported by @tylerjw, but rather these are new findings made using address sanitizer.
Running address sanitizer revealed couple memory leaks related raw pointer usage with `geometric_shapes` objects. I added two fixes to this PR since they are both very small.
First fix is wrapping return value of `shapes::constructShapeFromText(in)` in shared_ptr so that if the geometry being loaded is corrupted or malformed, the constructed shape will always be freed undepending on the code path.
Second fix is removing call to `clone()` in `BodyDecomposition::init()`. Prior to the fix, each of …

Fix geometric shapes related memory leaks

---

moveit_experimental/moveit_jog_arm/config/ur_simulated_config.yaml
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/collision_check_thread.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h
moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp
moveit_experimental/moveit_jog_arm/test/config/jog_settings.yaml

The old collision avoidance algorithm used manually-defined thresholds. This adds a new algorithm based on how fast the collision is approaching. It's optional, as you can see from the yaml file.
Video of it in action:
https://drive.google.com/file/d/1vMrrtflJme3Hexfo-685rKVS7uWIy14s/view?usp=sharing

[jog_arm] time-based collision avoidance

---

MIGRATION.md
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/robot_state_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/planning_scene_render.cpp

Fixes #1878 .
Please merge this as two commits, as we should only backport the internal usage, but not the API change.

remove robot_model:: and robot_state::

---

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp

Minor change to add throttle to warning message, which is currently printed for every joint in every iteration of the control loop.

Added throttle to jogarm accel limit warning

---

moveit_commander/package.xml
moveit_core/package.xml
moveit_kinematics/package.xml
moveit_ros/planning_interface/package.xml

This updates some packages to package.xml format 3 and sets up Python3 dependencies for noetic. It requires https://github.com/ros/rosdistro/pull/25263 to be merged before the new python3-pyassimp key will be available.

update dependencies for python3 in noetic

---

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_parameters.h
moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h
moveit_experimental/moveit_jog_arm/src/collision_check.cpp
moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp

These are changes I wanted to make (in addition to [https://github.com/ros-planning/moveit/pull/2103](https://github.com/ros-planning/moveit/pull/2103)) before starting on porting the jogger to ROS2 because I want these changes there as well. 
The changes consist of a lot of minor changes, see list below for details. Note that discussion and reviews exist here already: [https://github.com/PickNikRobotics/moveit/pull/8](https://github.com/PickNikRobotics/moveit/pull/8), because I wanted to start the review process before #2103 landed.
- General cleanup: defining `const` in functions where applicable, fixing comments, combining if statements and making them flow better
- I found a stale but nonzero command could make it through the timer callback function without updating the joint position …

[jog_arm] Changes before porting to ROS2

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

distance() respects unlimited revolute joints
Addresses an issue pointed out in #694 .

TEM: fix check for start state position

---

moveit_core/CMakeLists.txt

Backport fix from https://github.com/ros-planning/moveit2/pull/226.
The others (missing dependencies) don't apply here since `${catkin_LIBRARIES}` covers all of them.

Add missing Boost component

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

This PR simply adds two flags in model_based_planning context to give more control to the user over planning settings. 
- Flag `interpolate_` gives the user the ability to return non-interpolated trajectories when set to False. Default behavior is the old one which is true.
- Flag `hybridize_`  applies to `ompl_parallel_plan_`. When false, `ompl_parallel_plan_` returns the first solution found instead of waiting for all threads to terminate and hybridize between the found paths. Default behavior is the old one which is true.

Added hybridize/interpolate_flags for ompl planning

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

add support for setting interpolate_ and hybridize_ flags in ModelBasedPlanningContext via ompl_planning.yaml

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

This is a backport that exposes two parameters of the ompl_interface to the user API and ompl_planning.yaml

Pr ompl interpolate hybridize backport

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_states.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

While reviewing #2137, I realized that the Rviz panel has an option to import meshes that I have never discovered, because the buttons and dialog windows are not very instructive.
This PR should clarify the interface as shown in the screenshot below, and adds a dialog to fix STL files that are encoded with mm units. Sadly, scaling the mesh did not work as I expected, as described [here](https://github.com/ros-planning/geometric_shapes/issues/148). I will remove the WIP when that's fixed.

Clean up Rviz plugin, fix mesh scaling

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

MoveIt wrapper to Time Optimal Trajectory Generation downsamples trajectory, but its hard coded to keep waypoints with at least 0.001 radians of motion on a joint.  For very long and/or dense input trajectories, the downsampled trajectory is still way too large for the iterative optimization algorithm to finish in reasonable time.  I was seeing 3000 point trajectory taking ~15 seconds.  This fix allows the user to set this downsampling density in minimum radians of motion between two waypoints to something else (presumably higher like 0.5 degrees [0.00875 radians]) in order to drastically improve the speed of this algorithm.
- [ x ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

Parameterize input trajectory density of Time Optimal trajectory generation

---

moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/planning_component.h

A simple bug fix. Caught by Michael W, not me (not sure he has a Github account)

Fix a parameter switch in moveit_cpp loading

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ompl_planning_pipeline.launch.xml

This should never have been backported. The adapter is not available in melodic yet.
This reverts commit 7ae80b7a87c82a08f61554eb99a573ec51a906d6.
Yet another hot bugfix.
Should be merged before the release.

Revert "fix ordering of request adapters (#2053)"

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

I randomly ran into this, the warning message should be self-explanatory.

Fix segfault in PSM::clearOctomap()

---

moveit_ros/planning_interface/test/move_group_interface_cpp_test.test

Here is a PR for just changing `move_group_interface_cpp_test.test`.  The subframes test still doesn't work with moveit_resources but this one does.  @v4hn

use moveit_resources for testing

---

moveit_ros/planning_interface/test/moveit_cpp_test.test

This change is in master and was made here: 2de8471b8ffa8ae2be907c3d820b4144b87c2f4b
I wasn't able to get that commit to nicely apply no melodic-devel and only need the change to the one file so I created this.  This should be all that is needed to get melodic-devel to pass the pre-release tests.

use moveit_resources in moveit_cpp_test

---

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp

Every time I use MSA to generate config files for a package and use catkin_lint in the workspace I get [unconfigured-build_depend-on-pkg](https://fkie.github.io/catkin_lint/messages/#unconfigured-build_depend-on-pkg) error, grepping through the MSA's source code shows that urdf_pkg_name_ is only used as a run depend
Reproduce:
1- `sudo apt install ros-melodic-franka-description` (or any ROBOT-description package)
2- Select `Create New MoveIt Configuration Package`
3- Use `/opt/ros/melodic/share/franka_description/robots/panda_arm_hand.urdf.xacro` as URDF URL
4- Generate config files
5- Run `catkin_lint -W0 .`
```
catkin_lint: downloading melodic package index from https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
catkin_lint: downloading package manifest for …
```

MSA: Remove urdf package as build_depend from package.xml

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h

In `robot_state.h`, there was a mismatch between the docstring and the code. I updated the docstring to match the code.
I could also rename it to `link_model`, as in other parts of MoveIt. But I'm not sure this is necessary.
(I quickly tried to look for the reason of this change in git history but could not find it. But the why is not really relevant as long as the documentation and the code match I guess :) )

Fix mismatch between docstring and code in robot_state.h

---

moveit_planners/ompl/ompl_interface/scripts/generate_state_database.cpp
moveit_planners/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp
moveit_planners/ompl/ompl_interface/src/detail/constrained_valid_state_sampler.cpp
moveit_planners/ompl/ompl_interface/src/detail/constraints_library.cpp
moveit_planners/ompl/ompl_interface/src/detail/state_validity_checker.cpp
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp
moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp
moveit_planners/ompl/ompl_interface/src/parameterization/model_based_state_space.cpp
moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp
moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

As is done in other parts of MoveIt #1079 #1179, this pull request adds named logging to all source files of the `moveit_planners_ompl` package. (For some files with a single log statement, it might be overkill, but it is consistent...)
**Important** I'm not confident whether it is ok to put this outside a namespace. But in most source files of the OMPL interface, all code is put outside of a namespace and all names are prepended with `ompl_interface::`. Maybe this is worth another cleanup? Or is there a reason for this?

Add named logging with LOGNAME to OMPL interface

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/state_validity_checker.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/src/detail/state_validity_checker.cpp
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

Addresses issue #2209.
The attribute `std::vector<ModelBasedStateSpacePtr> subspaces_` inside [ModelBasedPlanningContextSpecification](https://github.com/JeroenDM/moveit/blob/d6666a9aee734acd1891a43657cf162c9ca4e9b7/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h#L71) is never used as far as I can tell. It is created in created in [PlanningContextManager::getPlanningContext](https://github.com/JeroenDM/moveit/blob/d6666a9aee734acd1891a43657cf162c9ca4e9b7/moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp#L363).
I suspect it was added with support for OMPL's [CompoundStateSpace](https://ompl.kavrakilab.org/classompl_1_1base_1_1CompoundStateSpace.html) in mind, but this is speculation.
**Note that I am biased**, as I plan to …

Remove dead code from ompl interface (related to subspaces)

---

moveit_commander/src/moveit_commander/move_group.py
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

The Python interface to MoveCommander was not exposing the `wait_for_servers` parameter as it does in C++. The wrapper already had it, so the only missing part was to add it to the Python interface. This should handle #1807 as now the timeout can be extended from the Python interface.
Edit: I also found that the getPlannerId python method was created but not interfaced, so I added it to too. 
I tested it in ROS melodic, so if this is merged it would be good if it could be ported to melodic too.

Exposed missing parameters from the MoveGroup Pyhton interface

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h

The `ompl_interface::ModelBasedPlanningContext` has two methods with the same name `getPlanningContext`. I think this is confusing because they do different things. Especially given that the `planning_interface::PlannerManager` also has [two of such methods](https://github.com/ros-planning/moveit/blob/dc909df5d2cf93868a1773db869e6767e339cf7a/moveit_core/planning_interface/include/moveit/planning_interface/planning_interface.h#L182), where overloading is used for a completely different purpose (both versions are public).
I also added docstrings to the header, to hopefully clarify a bit was is going on in these methods.
An alternative name could be `constructPlanningContext`.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free …

OMPL interface: add documentation

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/src/detail/constraints_library.cpp
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp

This makes it easier to spot new warnings when adding code.
Fix a single warning related to a variable name `solutionsWindow`.
```
warning: invalid case style for variable 'solutionsWindow' [readability-identifier-naming]
std::size_t solutionsWindow = 10u;
^~~~~~~~~~~~~~~
solutions_window
```
Ignore 6 warnings like this:
```
warning: string concatenation results in allocation of unnecessary temporary strings; consider using 'operator+=' or 'string::append()' instead [performance-inefficient-string-concatenation]
if (nh_.hasParam(group_name + "/" + k))
```
because I think fixing it would make it less readable, and the code is not in a performance-critical path. A simple `group_name.append("/").append(k)` does not work because `group_name` is `const`. Or *is* there a readable way to fix …

OMPL interface: fix / ignore clang-tidy warnings

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/robot_state/include/moveit/robot_state/attached_body.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp

Subframes were being forgotten when objects were detached/removed from the robot, and when they were moved. They also would have overwritten the old subframes during an APPEND call. This PR should fix all of that, and adds a line to the Rviz plugin that says "The object has subframes X, Y, Z."
Subframes are not updated if the object is moved from the Rviz plugin. I am filing another PR about this in a minute.

Fix subframes disappearing when object is detached/scaled/renamed

---

moveit_planners/ompl/ompl_interface/src/parameterization/model_based_state_space.cpp
moveit_planners/ompl/ompl_interface/test/test_state_space.cpp

A single line bug fix (that was punching far above its weight class in terms of causing debugging fun.)
Example of the issue in [an online C++ shell](http://cpp.sh/6snnu).
Previous [related discussion](https://github.com/JeroenDM/moveit/pull/3) with @tylerjw, where he created the example that I use in the C++ shell link above.
The joint data for a specific joint is copied from MoveIt to OMPL, it looks something like this:
Robot model memory (array of doubles), the bold values are copied.
| x1 | x2 | ... | ... **| y1 | y2 | y3|** ... | ... | ... | z1 | .. |
Copies into OMPL state memory (also an array of doubles)
| x1 | x2 **| y1 | y2 | y3 |** z1 |
The | ... | represent joint values for fixed joints (or mimic joints?) that are not relevant for OMPL.
I extended an existing test in …

fix memcpy bug in copyJointToOMPLState in ompl interface

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/chomp_planning_pipeline.launch.xml

CHOMPPlanner doesn't fill velocity, acc or time in a generated trajectory.
We need AddTimeParameterization to use this planner with ros_control (for gazebo simulation etc.).
I added the same planning adapters as in ompl_planning_pipeline.launch.xml.
As a reference https://github.com/ros-planning/panda_moveit_config/pull/31 adds these planning adapters in chomp's launch file.

Add planning_adapters for chomp in setup assistant

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/package.xml
moveit_ros/moveit_servo/src/servo_calcs.cpp

We were experiencing an issue where the arm starts in contact with a table. That initial collision needs to be reset before Servo works. This adds a ROS service to perform that reset.

A ROS service to reset the Servo status

---

moveit_ros/visualization/robot_state_rviz_plugin/include/moveit/robot_state_rviz_plugin/robot_state_display.h
moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
moveit_ros/visualization/trajectory_rviz_plugin/include/moveit/trajectory_rviz_plugin/trajectory_display.h
moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp

This is a cleanup of #2223. Fixes #2222.
Note that the melodic-devel branch is missing #1625. For this reason the PR here doesn't apply 1:1 to melodic.
I will file a similar PR for melodic.

Fix deferred robot model loading

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp

I still strictly prefer radian here, but this at least states units explicitly.
Fixes #2263 .

MP display: add units to joints frame

---

moveit_planners/chomp/chomp_interface/test/rrbot_move_group.launch
moveit_ros/move_group/test/test_cancel_before_plan_execution.test
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template

`/use_gui` is deprecated in Noetic and displays a deprecation warning in Melodic.
Is the MoveIt demo sometimes used with `use_gui:=true`? Otherwise we could just drop the option for a lighter launchfile.

Param /use_gui is not longer supported

---

moveit_core/collision_detection/CMakeLists.txt
moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
moveit_core/collision_detection/src/collision_common.cpp

I think @tylerjw merged #2275 too early (without having approvals from two maintainers). This PR realizes some changes required in my opinion (see below).

Cleanup: Add a utility to print collision pairs

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constrained_goal_sampler.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/state_validity_checker.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h
moveit_planners/ompl/ompl_interface/src/constraints_library.cpp
moveit_planners/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp
moveit_planners/ompl/ompl_interface/src/detail/constrained_valid_state_sampler.cpp
moveit_planners/ompl/ompl_interface/src/detail/state_validity_checker.cpp
moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp
moveit_planners/ompl/ompl_interface/src/ompl_planner.cpp
moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp
moveit_planners/ompl/ompl_interface/src/parameterization/model_based_state_space.cpp
moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp
moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp

I manually backported the commits mentioned in #2252:
- #2211: Add named logging with LOGNAME to OMPL interface
- #2214: Remove dead code from ompl interface (related to subspaces)
- #2226: Add documentation to ompl interface
- #2227: OMPL interface: fix / ignore clang-tidy warnings
There was not always a clear one-to-one mapping, so some minor things are different.
- Add named logging to a script that is removed in the latest version: 0c0d8aa
- Fixed another clang-tidy warning: `performance-implicit-conversion-in-loop` in [constraint_library.cpp](https://github.com/ros-planning/moveit/blob/8b5782cce98e93b9efa33a3269d11c0c84c2f536/moveit_planners/ompl/ompl_interface/src/constraints_library.cpp#L373).
- Correct some spelling errors, while I was going through it anyway: 8b5782c

Melodic backports in ompl interface (cleanup)

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/planning_groups_widget.cpp

Otherwise we get
```
arm:
default_planner_config: None
```
entries in the ompl_planning.yaml, where "None" of course does not describe an existing planner configuration
Why the hell do I have to write at least two issues and one pull-request every single time I actually use the setup assistant!
We desperately need more thorough tests and users reporting issues with the assistant.

MSA: only write default_planner_config fields if any is selected

---

moveit_ros/planning_interface/test/subframes_test.test

This fixes a failing test on the ROS buildfarm: http://build.ros.org/job/Ndev__moveit__ubuntu_focal_amd64/1

Replace panda_moveit_config -> moveit_resources_panda_moveit_config

---

codecov.yaml

This disables the "patch" status reporting from codecov.  I believe this is what is causing this:
https://github.com/ros-planning/moveit/pull/2305#issuecomment-690861772
Patch status documentation is here: https://docs.codecov.io/docs/commit-status#patch-status
Here is the documentation for disabling a status: https://docs.codecov.io/docs/commit-status#disabling-a-status

[maint] Remove patch status from codecov

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

This was fun to track down.  The short story here is that when `suddenHalt` is called sometimes there is a point in the `points` array so the code inside the if statement doesn't get run.  Then the code below uses the `operator[]` and writes past the end of heap memory allocations that are not large enough.
What made this fun is this was corrupting memory so that later the program would crash sometimes with an error about deallocating memory that was already deallocated and the stack trace was inside ompl.  In the end what helped me find this was building with address sanitizer.
```bash
catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address" -DCMAKE_C_FLAGS="-fno-omit-frame-pointer …
```

[fix] Servo heap-buffer-overflow bug

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch

It looks that the `planning_context.launch` is included twice when running `demo*.launch` (in `move_group.launch` and `demo*.launch`. Here's a simplification proposal.

planning context is already loaded in move_group.launch

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/test/config/servo_settings.yaml
moveit_ros/moveit_servo/test/servo_cpp_interface_test.cpp

The way I was doing acceleration & velocity limit enforcement before had some flaws. It was only applied to one joint at a time, so it could affect the direction of motion of the robot. It was causing some serious direction swings.
This simplifies the whole limit checking, only enforcing velocity limits.
Also renamed the functions from  enforceSRDFAccelVelLimits -> enforceVelLimits. I think this function name was misleading because limits actually get stored in joint_limits.yaml or the URDF, not the SRDF.

Refactor velocity limit enforcement and add a unit test

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

I had a go at making the plugin smaller. This version isn't perfect either, but what is? Here are the before and after images:
**Before:**
**After:**
Changes:  
- Added tooltips
- Reduced the minimum size of entry fields so they can partially hide numbers if required (users will resize the panel when they need to change the values). This should only affect the layout when the user resizes to _under_ the previous minimum size. The previous sizes should look the same as before.
- Reordered and renamed options in the Planning tab. Some of these had confused me when I started out. Most of these are just suggestions and up for discussion though. I just took the liberty while I was at it.
Notes:  
- I don't know if `allowReplanning` and `allowLooking` have any effect. I have a feeling that this …

Clean up Rviz Motion Planning plugin, add tooltips

---

moveit_commander/CMakeLists.txt
moveit_kinematics/ikfast_kinematics_plugin/CMakeLists.txt
moveit_kinematics/package.xml
moveit_ros/benchmarks/CMakeLists.txt
moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py

Fixes #2322:
* `ikfast` was missing some python dependencies
* [python scripts should be installed via `catkin_install_python()`](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs)

fix some more python3 issues

---

moveit_core/kinematic_constraints/src/utils.cpp

https://github.com/ros-planning/geometric_shapes/pull/161 attempts to backport a syntax simplification requiring this adaption here.

Adapt to geometric shapes

---

moveit_core/CMakeLists.txt

This is in preparation to use fcl 0.6.1 in Noetic. See https://github.com/ros/rosdistro/issues/26527 for details.
Our cmake code to find absolute library paths of FCL libs was only handling a single lib (namely `libfcl`). However, future releases of `libfcl` declare several link libraries. To correctly link to those, we need to find absolute paths for all of them.

Handle multiple link libraries for FCL

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp

Somehow this issue wasn't detected by clang-tidy before...

Fix clang-tidy warning

---

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp

This fixes https://github.com/ros-planning/moveit_tutorials/issues/533.
- set visibility of robot-state-display to true after reset()
- correctly update reference frame also on deletion of virtual joint
This needs to be backported to Melodic as well!

MSA: Fix disappearing robot on change of reference frame

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
moveit_core/collision_detection/include/moveit/collision_detection/collision_env.h
moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h
moveit_core/collision_detection/include/moveit/collision_detection/world.h
moveit_core/collision_detection/include/moveit/collision_detection/world_diff.h
moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/robot_model/include/moveit/robot_model/joint_model.h
moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
moveit_core/robot_model/include/moveit/robot_model/link_model.h
moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_spline_parameterization.h
moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_time_parameterization.h
moveit_core/trajectory_processing/src/iterative_spline_parameterization.cpp
moveit_core/trajectory_processing/src/iterative_time_parameterization.cpp
moveit_core/transforms/include/moveit/transforms/transforms.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/trajectory_monitor.h
moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h

Having switched to Noetic (and clang-tidy-10?) on Travis, we get some new clang-tidy issues reported:
https://travis-ci.com/github/ros-planning/moveit/jobs/393573194
Interestingly, locally I got even more issues!? There is also one "fix" applied that is nonsense:
```diff
-struct DistanceResultsData
+struct i0
```

Fix some clang-tidy issues on Travis

---

moveit_setup_assistant/src/widgets/robot_poses_widget.cpp

When the `item()` method is called it can return a `nullptr` if the row/column doesn't exist.  [Here is the documentation](https://doc.qt.io/qt-5/qtablewidget.html#item).  The way to reproduce this before was to create a pose, then click edit on that pose, and then click Save.  This would result in the stack trace below.  The basics of it are that row is set to -1 by `clearContents` and that causes the callback `previewClicked` to be called because the row value changed.  -1 is not a valid row index so `item()` returns nullptr and then we dereference it.
My fix just checks for `nullptr` before dereferencing and performing the rest of the logic in previewClicked.  I tested this manually and was not able to reproduce the segfault.
```c++
Thread 1 "moveit_setup_as" received signal SIGSEGV, …
```

[fix] Segfault when editing pose in moveit_setup_assistant

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

As discussed in #2310, the Clear Octomap button shouldn't be active when there is no octomap to clear. This PR disables the button by default and enables it when an octomap is in the planning scene. 
You can test this with `roslaunch moveit_tutorials detect_and_add_cylinder_collision_object_demo.launch` which publishes an octomap every 10 seconds, ~although the octomap doesn't actually seem to be cleared when pushing the button~.
**edit:** I think I fixed part of the problem that caused the octomap not to be cleared. There's still something quirky, though.

Fix Clear Octomap button, disable when no octomap is published

---

moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp

Add a more informative error message, and cover another potential failure condition.

moveit_cpp: Cover another failure path in planning pipeline loading

---

moveit_setup_assistant/src/widgets/robot_poses_widget.cpp
moveit_setup_assistant/src/widgets/robot_poses_widget.h
moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp

Fix #2344 and other issues:
- The joint values of the initial robot pose (shown in rviz window after loading) were not taking into account for saving poses.
- mimic joints were written to SRDF (with wrong values), overriding auto-updates of mimic joints (causing #2344)
- Cleaning up code to use a RobotState for robot poses (instead of a separate joint_states_map_)

MSA: fix pose definitions

---

.travis.yml
moveit_core/package.xml

After [having fcl 0.6 released](https://github.com/ros/rosdistro/pull/26706) into the ROS repos (additionally to fcl 0.5 in the standard Ubuntu/Debian repos) we can switch to this newer version of fcl now.
Probably, Travis will need to be switched to ros-testing (because it's not synced yet).

Depend on ros-noetic-fcl (0.6) in Noetic

---

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h

If an exception occurs while the GIL is released,
it won't be reacquired and the stack unwinding will take place
without the GIL. Releasing and Reacquiring wil be removed.
For example,
```c++
bp::object wrap_long_computation(bp::object arg) {
auto parsed_arg = parse_arg(arg);
GILReleaser gr;
auto res1 = do_long_computation_1(parsed_arg);
gr.reacquire();
bp::object res2 = do_more_python_stuff();
gr.release();
Result3 res3 = do_long_computation_2(res1);
gr.reacquire();
return encode_result(res2, res3);
}
```
is not exception safe, because  if `do_long_computation_2()` throws an exception, the Python object res2 will be destroyed without the GIL.
Instead,
```c++
bp::object wrap_long_computation(bp::object arg) {
auto parsed_arg = parse_arg(arg);
Result1 res1;
{
GILReleaser gr;
res1 = …
```

Make GILReleaser exception-safe

---

moveit_commander/src/moveit_commander/move_group.py
moveit_commander/test/python_moveit_commander.py
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

Finished up the work from #1966, and added another function `enforceBounds`

Python interface improvements. Fix #1966, add enforceBounds

---

moveit_ros/moveit_servo/src/pose_tracking.cpp

The [control_toolbox::Pid constructor](https://docs.ros.org/melodic/api/control_toolbox/html/classcontrol__toolbox_1_1Pid.html#ab081bfb241e6bb3da4911587cf789c7f) expects i_max followed by i_min (and does not check that the former is greater than the latter). The current arguments are passed in reverse order and this PR addresses that.

Fix ordering of windup args to control_toolbox::Pid

---

moveit_setup_assistant/launch/setup_assistant.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/edit_configuration_package.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit_rviz.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajopt_planning_pipeline.launch.xml

* Convert tabs to spaces
* Fix issue with overindentation of `VIRTUAL_JOINT_BROADCASTER`
The generated `demo.launch` is currently
```
<include file="$(find stretch_moveit_config)/launch/planning_context.launch">
<arg name="load_robot_description" value="true"/>
</include>
<node pkg="tf2_ros" type="static_transform_publisher" name="virtual_joint_broadcaster_0" args="0 0 0 0 0 0 map base_link" />
```
This is because the template is indented and the line added [here](https://github.com/ros-planning/moveit/blob/73416fb9fb1b242f5c6af05a628d076425c6ea25/moveit_setup_assistant/src/widgets/configuration_files_widget.cpp#L1097) are both indented. Since there could be multiple broadcasters, each requiring indentation, it made sense to remove it from the template. 
[//]: # "You can expect a response …

Convert tabs to spaces, fix over-indentation

---

moveit_planners/ompl/ompl_interface/CMakeLists.txt
moveit_planners/ompl/ompl_interface/test/load_test_robot.h
moveit_planners/ompl/ompl_interface/test/test_planning_context_manager.cpp
moveit_planners/ompl/ompl_interface/test/test_planning_context_manager.test
moveit_planners/ompl/package.xml

(This pull request could use some extra work, but early feedback would be really valuable.)
This test goes through the main steps in solving a planning problem with the interface;
1. Create a `PlanningContextManager`.
2. Call it's `getPlanningContext` with a specific request to get a `ModelBasedPlanningContext`.
3. Call the `solve` method on the planning context.
The main intent is to check if the `ModelBasedPlanningContext` has the correct type of `ModelBasedStateSpace` assigned for planning. (For a detailed explanation of this process, see [here](https://github.com/JeroenDM/moveit/pull/2#issue-449635219).)
Calling the `solve` method is just the cherry on top of the cake.
The `load_test_robot_class.h` is exactly the same as in #2247, so I assume that change will not be part of this pull …

Add test for PlanningContextManager in ompl interface

---

moveit_ros/moveit_servo/src/pose_tracking.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp

This PR removes trajectory point timestamping which causes warnings about trajectory points being dropped due to having old timestamps:
```
ros.joint_trajectory_controller: Dropping all 1 trajectory point(s), as they occur before the current time.
Last point is 0.000064s in the past.
```
By removing explicit timestamping, the stamps will default to 0, meaning the trajectory execution defaults to _start now_. For more details, see section 2.3: [http://wiki.ros.org/joint_trajectory_controller](http://wiki.ros.org/joint_trajectory_controller) 
Small time from start is added to the trajectory point generated in `suddenHalt` to prevent warnings about trajectory point being 0.0000 seconds in the past (not sure if this should be considered as a bug or not, but it is clearly a corner case). …

Fix servo trajectory point timestamping

---

moveit_ros/moveit_servo/config/ur_simulated_config.yaml
moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h
moveit_ros/moveit_servo/include/moveit_servo/servo.h
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/launch/cpp_interface_example.launch
moveit_ros/moveit_servo/launch/spacenav_cpp.launch
moveit_ros/moveit_servo/launch/spacenav_teleop_tools.launch
moveit_ros/moveit_servo/src/collision_check.cpp
moveit_ros/moveit_servo/src/cpp_interface_example/cpp_interface_example.cpp
moveit_ros/moveit_servo/src/cpp_interface_example/pose_tracking_example.cpp
moveit_ros/moveit_servo/src/pose_tracking.cpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/src/servo_server.cpp
moveit_ros/moveit_servo/test/pose_tracking_test.cpp
moveit_ros/moveit_servo/test/pose_tracking_test.test
moveit_ros/moveit_servo/test/servo_cpp_interface_test.cpp
moveit_ros/moveit_servo/test/servo_cpp_interface_test.test

The namespacing logic seemed odd when running multiple servo servers within their own namespaces. This PR attempts to fix/change the namespacing logic within Servo to make it more intuitive. I listed before/after comparisons below to better illustrate the changes made in this PR.
**Before**
- Service namespaces were a bit surprising for the services Servo advertises. Namespacing the node that made use of Servo into namespace `foo` resulted to service topics like this: `/foo/foo/<nodeName>/change_drift_dimensions` when I would have expected simple `/foo/<nodeName>/change_drift_dimensions`.
- User was forced to load parameters into separate parameter namespace **that matched the node name**. This was a bit confusing since the node namespace is where the parameters are loaded by default.
- …

Change servo namespacing logic

---

moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h

This PR fixes function comments that are described in opposite.
Correct description should be collisionCallback() checks collision and distanceCallback() checks distance.

Fix comments

---

moveit_planners/ompl/ompl_interface/CMakeLists.txt
moveit_planners/ompl/ompl_interface/test/load_test_robot.h
moveit_planners/ompl/ompl_interface/test/test_state_validity_checker.cpp

I added some minimal tests for the `ompl_interface::StateValidityChecker`. My intend is to better understand how all the pieces fit together, not necessarily thorough testing of this class.
The test uses a new generic test class to make it easy to run the same test on several robots. (See the documentation in the code.) Addmiditly it might come across as a bit overengineered, but I plan to use this for other tests in the future.
As mentioned in the comment, I could simplify it by using rostest and passing robot specific setup over the parameter server. But these tests would run slower and as this package is outside `moveit_ros` (so ideally ROS independent I guess).
Or is there a better way?
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything …

Add test to ompl interface for StateValidityChecker

---

README.md

FIxed the Documentation link in the README.
The previous link pointed to "https://moveit.ros.org/documentation/" which is not a page in the moveit.ros.org domain. A better fix may be to create a documentation index page on that domain. For now, this change points the link to the "souce-code-api" section of the documentation. 

Fix broken documentation link in README

---

moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h
moveit_ros/moveit_servo/src/cpp_interface_example/pose_tracking_example.cpp
moveit_ros/moveit_servo/src/pose_tracking.cpp
moveit_ros/moveit_servo/test/pose_tracking_test.cpp

This PR fixes issues where `target_pose` timestamp rewriting caused surprising and unwanted behaviour. This PR also fixes possible data races on the variable where it's value can be written in the subscriber callback function while it is simultaneously being read in another function.
- Timestamp rewriting was removed from the subscriber callback function to prevent outdated target poses being used in `moveToPose` function.
- Another instance of timestamp rewriting was removed from the `moveToPose` function itself to prevent situations where sending just one target pose message would occasionally result in situation where target pose would be sent with a reasonable timestamp, callback function would then process and store it, and finally moveToPose would be called which would rewrite the …

Fix pose tracking race condition

---

moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp

This fixes https://github.com/ros-planning/moveit_task_constructor/issues/211, where an attached object was "lost" during planning. Turned out that the `FixStartStateBounds` adapter, while creating a new _non-diff_ `start_state`, did not copy all the attached objects, which are part of the RobotState as well. Thus with new joints, also attached objects were overridden.
Interestingly this bug was undetected over all the years...

FixStartStateBounds: Copy attached bodies when adapting the start state

---

moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

Fix annoying Qt warning about unregistered `QVector<int>`. The reason was that the planning scene name was changed from a non-GUI thread, causing a `dataChanged()` signal emitted from this thread, which then needs to be queued for processing in the main event loop.
I fixed that by emitting a signal from the thread to change the name. Thus, a `QString` event is queued, which doesn't pose an issue.

Fix QObject::connect: Cannot queue arguments of type 'QVector<int>'

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp

There's a bug right now in the generation of fake_controllers.yaml such that if no poses are found, it will output invalid yaml. 
```
initial:  # Define initial robot poses.
```
(and then the end of the file)
This results in a cryptic error like
```
load_parameters: unable to set parameters (last param was [/controller_list=[SNIP]]): cannot marshal None unless allow_none is enabled
```
With this PR, it now generates
```
initial:  # Define initial robot poses.
[]
```

Fix empty sequence in moveit_setup_assistant

---

moveit_core/background_processing/src/background_processing.cpp

Updated `moveit_core/background_processing/src/background_processing.cpp` to use `std::make_unique` instead of `new` when spinning a background processing thread as mentioned in #2383 and #1411 .

Changed processing_thread_ spin to use std::make_unique instead of new

---

moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_core/kinematic_constraints/test/test_constraints.cpp

The implementation of OrientationConstraint::decide does not handle the case where the relative orientation of the target and current link poses are represented by Euler angles which were all +/- pi or zero.  For example, if a link's target pose is rotated 180 degrees about the X axis relative to the current pose, the decide() function returns a value indicating that the current pose satisfies the target pose constraint.
This PR corrects the behavior of decide() and adds a test case that fails without this change.
- [N/A] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [N/A] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [N/A] Include a screenshot …

Fix OrientationConstraint::decide

---

moveit_ros/moveit_servo/src/pose_tracking.cpp

Currently, if target_pose must be transformed to be in planning_frame (in `targetPoseCallback` function), and a URDF transform from the current frame to planning_frame is available, then TransformStamped time returned by lookupTransform will be 0. 0 is then copied into target_pose_'s stamp by doTransform. This will result in the timestamp checking in `haveRecentTargetPose` to cause `moveToPose` to always abort because it doesn't think it has received a target_pose recently. 
Two examples of when users could experience this behavior:
- They publish `target_pose` in world frame, but `planning_frame` is configured to be `base_link` (and world to base_link is defined in the URDF)
- They are running in a noise-less simulation, and in this simulation have the object they are servoing to as part …

Prevent moveit_servo transforms between fixed frames from causing timeout

---

.docker/source/Dockerfile

Going through pull request tutorial.

Add support for master-source docker container running clang-tidy commands from the instructions

---

moveit_planners/pilz_industrial_motion_planner/CMakeLists.txt
moveit_planners/pilz_industrial_motion_planner_testutils/CMakeLists.txt

to suppressing CMP0048 warning in Noetic.
@jschleicher

Upgrade cmake_minimum_required to 3.1

---

moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_core/utils/src/robot_model_test_utils.cpp

`RobotModelBuilder` used in unit tests to quickly assemble a `RobotModel`, was missing a feature to add end effectors.

RobotModelBuilder: Allow adding end effectors

---

moveit_core/kinematic_constraints/CMakeLists.txt
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_core/kinematic_constraints/test/test_orientation_constraints.cpp
moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_core/utils/src/robot_model_test_utils.cpp

After applying the following fix https://github.com/ros-planning/moveit/pull/2414 a pipeline I’m working on isn’t working anymore (with a bunch of errors about constraints not statisfied one of them is `ros.moveit_planners_ompl.constrained_goal_sampler: More than 80% of the sampled goal states fail to satisfy the constraints imposed on the goal sampler. Is the constrained sampler working correctly?`)
The reason is, right now we're calculating the error rotation matrix and call eulerAngles from Eigen to find the angles’ errors which return them in the following ranges `[0:pi]x[-pi:pi]x[-pi:pi]` ([link](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#ga17994d2e81b723295f5bc3b1f862ed3b))
The issues are
1- As shown in the first test, despite the error is 1.57rad around Z-axis, …

Fix orientation constraints failing on satisfied configurations

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h

I think the documentation [here](http://docs.ros.org/en/melodic/api/moveit_core/html/classmoveit_1_1core_1_1RobotState.html#a34d8fc133b4a21527ea0875fdb423e25) on setToIKSolverFrame() must be wrong. Here's what it says:
```
bool moveit::core::RobotState::setToIKSolverFrame ( Eigen::Isometry3d& pose, const std::string& ik_frame)
pose - the input to change
ik_frame - the name of frame of reference of base of ik solver
```
If that were correct, how would we know what the original frame of `pose` is? I think it should say:
```
bool moveit::core::RobotState::setToIKSolverFrame | ( Eigen::Isometry3d& pose, const std::string& ik_frame)
pose - the input to change
ik_frame - the **previous** frame of reference of the pose
```
Fixes #2460

Fix doxygen documentation for setToIKSolverFrame

---

moveit_ros/moveit_servo/src/pose_tracking.cpp

Forgot to put a sleep in the loop. The loop was running at 2kHz before this  :O
@Abishalini -- mentioned since you're porting this to ROS2

Servo: add an important sleep()

---

moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template

Adds a missing dependency on RViz to the MSA template. If not, the package will fail roslaunch checks if they are added. 

Missing RViz dependency in MSA template

---

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp

This fixes #2238 : 
> Somewhat recently (https://github.com/ros-planning/geometric_shapes/commit/07a5254b698ecc89e511dc5b3182ecb6c7d2258e) a check was introduced whether `Shapes` have negative lengths. This crashes whoever displays that URDF (`RobotStateDisplay`)
You can see the error message from the exception and also that negative dimensions are not checked in the code path for `rviz::Robot` and Ogre actually handles them quite fine (in contrast to fcl so it's good that we do have those checks).

Catch exceptions during RobotModel loading and display them in rviz

---

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
moveit_core/robot_model/src/joint_model_group.cpp
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp

this fixes #2442 and provides an less error prone alternative for https://github.com/ros-planning/moveit_visual_tools/pull/83
The general problem is that while usually you only concern yourself with the values of active joints when storing positions in a vector, the function `setJointGroupPositions` actually expects a vector/array containing the variables for *all* joints (including mimic joints). Ignoring this will lead to reading out-of-bounds memory at least and to a mismatch at worst (yes, there where physical crashes ...). Also the code might crash.
@felixvd suggested fixing `setJointGroupPositions` to actually work with only the variables of active joints. I have no objections except this being quite hidden and incompatible if anybody actually uses these functions correctly (I found …

Provide a function to set the position of active joints in a JointModelGroup

---

moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h
moveit_ros/moveit_servo/src/pose_tracking.cpp

I was trying to use Servo's Pose Tracking feature to point a camera in a specific orientation when I discovered this tiny problem: the angle error is only calculated when the Twist command is being calculated. So during the first check to see if the desired pose has been reached, the angle error is always 0 (from initialization, regardless of what the actual state of the robot is). The result is that if the position errors start within tolerance but the angular error does not, Pose Tracking will return success before sending any commands to Servo.
You can replicate this by running the pose tracking example with 2 modifications:
1. Set the position tolerances large e.g. `Eigen::Vector3d lin_tol{ 1.0, 1.0, 1.0 };`
2. Give an orientation change in the goal pose e.g. by setting the goal …

[Servo] Fix initial angle error is always 0

---

moveit_core/robot_state/src/robot_state.cpp

Fixed the drop*() methods to refer to the correct boolean variable. See also issue #2477 
resolves #2477 

Fix RobotState::dropAccelerations/dropEffort to not drop velocities

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/joint_limits_container.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/joint_limits_extension.h

On my (non-Ubuntu) system I get error messages about `std::string` being undefined in these two places.
Not sure why this does not happen to everyone, but maybe some upstream header changed its includes recently.

pilz planner: add string includes

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Fix #2451.
Remove the `joint_limits` prefix from parameters `default_velocity_scaling_factor` and `default_acceleration_scaling_factor` that `move_group_interface`  node gets.

Fix scaling factor parameter names

---

moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp

The current move group interface c++ tests will sometimes fail. The failure could be a result of a long sequence of planning steps (~10). I combined a pose goal, path (orientation) constraint, and collision detection into a single test. The success of this test should be more reliable and it also tests multiple move group interface functionalities. The reliability comes from the fact that one planning problem is being solved and that it is not overly complex. In terms of complexity the collision object is not blocking the arm's shortest path and the test does not require the arm to contort into an extreme position.  The orientation constraint keeps the gripper facing up as the arm moves along the x-axis while avoiding a box.
Bellow is the output of the test result. @tylerjw 
[//]: # "You …

Update move group tests

---

moveit_ros/planning_interface/test/subframes_test.cpp

Sometime the SubframesTests will fail. Planning on this particular problem
takes ~10s and the allotted planning time for move_group was set to 10s.
The planning time has been increased to 30s and the target pose offset was
increased from 1cm to 5cm. This should make the planning problem easier to
solve and therefore more likely to pass the test.
The result from the test is bellow: @tylerjw 

Update subframes test

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_functions.h

This should fix #2459.
Setting the default timeout to zero prevents it from overriding the kinematics solver timeout in the call to `robot_state::setFromIK`. See https://github.com/ros-planning/moveit/blob/664ae01803abf5e0b4649063102357262de9e05c/moveit_core/robot_state/src/robot_state.cpp#L1747
This makes the default `0.5`. See https://github.com/ros-planning/moveit/blob/664ae01803abf5e0b4649063102357262de9e05c/moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h#L73

Use kinematics solver timeout if not specified otherwise

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

We implemented this short circuit for efficiency, but in the case of `stop_requested_` we want to continue updating the current robot state and the low pass filters. This prevents a jerk from occurring when Servoing resumes.

Servo: Do not break out of loop -- need to update low pass filters

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp

In MoveIt Servo I was calling `setPaused()` from another thread while printing the value of `paused_` here in ServoCalcs. And I saw that it often didn't change. This fixes it.

Servo: protect paused_ flag, for thread safety

---

moveit_planners/pilz_industrial_motion_planner/CMakeLists.txt
moveit_planners/pilz_industrial_motion_planner/package.xml

Adding a missing dependency declaration on joint_limits_interface

Adding a missing dependency declaration on joint_limits_interface

---

moveit_ros/moveit_servo/CMakeLists.txt
moveit_ros/moveit_servo/include/moveit_servo/servo.h
moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
moveit_ros/moveit_servo/src/servo_calcs.cpp
moveit_ros/moveit_servo/test/basic_servo_tests.cpp
moveit_ros/moveit_servo/test/basic_servo_tests.test

The `enforceVelLimits` function struck me as bit odd so I figured I make this PR to start a conversation about what I think it is doing and I why I think it looks like it might not be correct.
Prior to my changes the function would calculate joint angle velocity for each joint based on the delta theta (joint angle change) and would determined the smallest scaling factor for the velocities based on the biggest out-of-bounds velocity value. So if one would have joint velocities of, say, `[1, 1, 1, 2, 3, 100]`, and each joint was bounded to `[-1, 1]` range, then the scaling factor would be `0.01` . That's at least how I interpreted it. This scaling factor was then applied to the delta thetas meaning if one joint received a command that would translate into very large velocity, the other …

Refactor Servo velocity bounds enforcement

---

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp

Fix a bug for the case when `it.second->parent_` is null (i.e. if the current Collision Detector is the parent or the only one).
Provide better Doxygen comments for `clearDiffs()`
This seems like a pretty deep bug. I guess it wasn't found previously because nobody is using >1 collision detection algorithm.

Fix logic in PlanningScene::clearDiffs() for multiple CollisionDetectors

---

moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h

The code uses `std::atomic<bool>` further below, but relies on other headers including it.
It's not always there though. Compiling failed for me on Lunar-Linux with ROS melodic.

Servo: add missing include

---

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp

An info message is fine. But octomap plugins are explicitly optional,
so a setup that does not define a plugin (the default!) must not report errors.
This is basically a fixup for https://github.com/ros-planning/moveit/pull/1873

It's not an error not to define a plugin

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h

Update documentation of `interpolate()` and `distance()` to clarify a few things:
- The `t` parameter of interpolate isn't a time, it's a fraction
- `distance()` just sums the joint difference, for all joints. It's not an L2 norm or SSE or anything like that. Verify [here](http://docs.ros.org/en/noetic/api/moveit_core/html/robot__model_8cpp_source.html#l01236).
Fixes #2527

Update doxygen comments for distance() and interpolate()

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

If the user calls setJointValueTarget with the wrong number of joint values, it just returns false without providing any information as to what went wrong. Personally when something in moveit goes wrong the first thing I do is turn on debug logging so this would help in that case.

Add debugging informative log statement for a common error

---

moveit_commander/src/moveit_commander/robot.py
moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_model/src/robot_model.cpp
moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp

Creates new API in C++ and Python for getting active joint names, including the case where no group is specified.

add get_active_joint_names

---

moveit_commander/src/moveit_commander/planning_scene_interface.py
moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp

I found a few very basic functions that I had added in the past, but apparently forgot to push upstream. The `ApplyPlanningScene` function seems to have been implemented already in `wrap_python_planning_scene_interface.cpp` but not exposed in the Python class, so I added that as well.
The interface seems not very useful without these functions and I'd like to use them in a different project where we don't build MoveIt from source, so it would be great if these found their way into the binaries.
This should be ported back to Melodic, possibly even Kinetic.

Add utility functions to Python PSI

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

As commented in https://github.com/ros-planning/moveit/pull/2320#issuecomment-746096098 I recently encountered some crashes when clearOctomap is being called while some planners still run. Even though that is a weird thing to do, it still shouldn't crash.
Also #2320 uses `UPDATE_SCENE` which causes a full scene to be transmitted while `UPDATE_GEOMETRY` should be sufficient.

ensure thread safety in clear octomap

---

moveit_planners/chomp/chomp_interface/src/chomp_interface.cpp
moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_parameters.h
moveit_planners/chomp/chomp_motion_planner/src/chomp_parameters.cpp
moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp

Return false when interpolation method is invalid.
Edit by v4hn: Additionally verify parameter during planner initialization.

Sanitize CHOMP initialization method parameter

---

moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp

Everything works as expected here, if you specify an empty RobotState it is a common pattern in MoveIt to use the current state instead.
The error message is a leftover artifact from #499.
Closes #2517.

Fix missing isEmpty check in compute_ik service

---

.travis.yml

master is currently still failing travis builds because of timeouts. If I got that correctly, picknick is paying for a travis plan, so the time limit of 90 minutes is no longer applicable?

increase travis time limit

---

moveit_ros/moveit_servo/src/pose_tracking.cpp

This PR is for a fix in moveit_servo with regards to clearing the stop_request_ flag. There were some situations where after a move was complete and the reset on the flag was called, another thread called stopMotion() again and set the flag back to 1. This prevents any bugginess by assuring that stop_requested_ starts out as false whenever moveToPose is called.

stop_requested_ flag clearing fix

---

moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/transform_provider.h
moveit_ros/perception/mesh_filter/src/depth_self_filter_nodelet.cpp
moveit_ros/perception/mesh_filter/src/transform_provider.cpp

The mesh filter was producing a flood of errors when it started, which stopped after a subscriber connected to its output. This prevents these errors, and instead produces a trickle of debug messages. I cleaned up a few little things, too, while I was at it.

Fixed flood of errors on startup for `mesh_filter`

---

moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_execution.h
moveit_ros/planning/plan_execution/src/plan_execution.cpp

Clearly differentiate between preemption signal and state.
Alternative to #2403.
Fixes https://github.com/ros-planning/moveit_task_constructor/issues/217

PlanExecution: fix leftover state after preempt

---

moveit_ros/moveit_servo/include/moveit_servo/pose_tracking.h
moveit_ros/moveit_servo/src/pose_tracking.cpp

Small change to make Pose Tracking publish a 0 twist message for Servo when it is stopping. Before this, if you were using a velocity controller and stopped Pose Tracking during a movement, the last published command to Servo would be nonzero and the manipulator would still move, see attached.
It might be worth exposing some kind of `halt()` function in Servo itself, which I can do here if needed. 
Haven't been able to replicate with the Servo demonstrations (position controllers), so attached videos on hardware. In the clip, I use Pose Tracking to point the left arm camera at the right gripper, but call `stopMotion()` and cancel the pose tracking before it gets there. In the first, the arm holds the last velocity command sent until I E-stop. In the second gif, a 0-twist command is sent …

[Servo] Halt Servo command on Pose Tracking stop

---

moveit_ros/manipulation/pick_place/src/pick.cpp
moveit_ros/manipulation/pick_place/src/place.cpp

The quality field was added by https://github.com/ros-planning/moveit_msgs/commit/cdb9e4aa964269f1a159a8f35c7b634365e86038.
The changes are adapted from pick.cpp, where the Grasps are also ordered by quality.

Order PlaceLocations by quality during planning

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp

happened when a group was defined in the launch file without a `ns` attribute.

msa: fix segfault

---

.github/workflows/format.yml
.github/workflows/industrial_ci_action.yml
.pre-commit-config.yaml

Fixes #2566 (hopefully). Works locally. The key was, I think, `pass_filenames: false`.

Shift catkin_lint to pre-commit checks

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

[This is a backport of a MoveIt2 bug fix](https://github.com/ros-planning/moveit2/pull/410/files)
We found out the hard way, when the suddenHalt() function was called for a robot in velocity control mode, it would send a command vector of all-zero positions. That could cause a really big joint jump depending what type of ros2_controller is active. This fixes that.
Also (really minor fix) it sets trajectory accelerations to 0 to match the comment.

Avoid joint jump when SuddenHalt() is called in velocity mode

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch

This should be the main entry point for simulated robot systems
and we specifically want to support `last point` here for rostests.
This was an oversight in #1893 .

Let users override fake execution type from demo.launch

---

moveit_commander/src/moveit_commander/planning_scene_interface.py

Setting the link name in `remove_attached_object` is not necessary. `planning_scene.cpp` treats the message as described.
I also added a `clear()` method because I could have used it today and saw that @mikeferguson also did in [moveit_python](http://docs.ros.org/en/api/moveit_python/html/classmoveit__python_1_1planning__scene__interface_1_1PlanningSceneInterface.html#aa36ea0b0171e79ddfea196aed4f9d8a4).

Fix remove_attached_object API in Python PSI, add clear()

---

moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp

Integration of https://github.com/PilzDE/pilz_industrial_motion/pull/328: Do not check joint model groups which contain fixed joints only (e.g. an empty endeffector group).

Velocity limit error

---

moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h

I was trying to plan a pure rotation today and noticed that `max_step` did not apply to the rotation anymore. If the motion is a pure rotation, `move_group.computeCartesianPath()` returns no intermediate points. It looks like this bug was introduced when we added `CartesianInterpolator`, which sets the rotation value of `MaxEEFStep` to zero by default.
This PR fixes the constructor of `MaxEEFStep` and sets the rotation to a reasonable value if it is not set. I chose a value of 1 cm = 2 deg, but I would be fine with 1 cm = 1 deg as well.

Set rotation value of cartesian MaxEEFStep by default

---

moveit_ros/occupancy_map_monitor/src/occupancy_map_updater.cpp
moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp
moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

Also move the log command to the base class (which even uses the same logname...)
I just spend some time on https://github.com/ros-planning/moveit_tutorials/issues/192
and found a solution eventually, but this could have been a no-brainer with more information...

document solution in ROS_ERROR on failed self-filtering

---

moveit_ros/planning/collision_plugin_loader/src/collision_plugin_loader.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

I rebased the patches from #2563 onto master. Assuming CI succeeds, this can be merged (it was reviewed before) and directly backported to `melodic-devel` as the original author proposed the PR for `melodic-devel`.

Simplify logic in PSM

---

moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp

Print an error indicating that the planning pipelines are empty before returning.  It was previously just switched around in the code, so it returned before getting a chance as to complain.

Print error before returning

---

moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp

It's always messy to synchronize these interfaces, so I don't use them in my own projects.
However, these are the only tests we have for the async method calls at the moment, so we should make them run ~~reliably~~ as reliably as possible.
There is no sense in running these updates asynchronously for testing the interfaces, so I added a (somewhat cumbersome) feedback channel to wait for the triggered updates.
I'm not aware of a better solution for this that does not consist of repeatedly polling the service.
Hopefully this closes #2636 .
Locally `CartPathTest` fails quite often over here, possibly due to a full debug build that could make IK requests time out, that's why I added the additional `ASSERT` there to ease debugging. I don't think I've ever seen it fail in CI though. :confused:

planning_interface: synchronize async interfaces in test

---

moveit_core/package.xml

In https://github.com/ros-planning/moveit/pull/2547 we use the RTD theme for python, but didn't add it as a dependency, which is causing [the docs job](https://build.ros.org/view/Ndoc/job/Ndoc__moveit__ubuntu_focal_amd64/15/consoleFull#console-section-24) to not generate python docs
rosdep does not look at `doc_depend` which might cause problems. I'm not sure how to trigger a build farm job to test this, but if that's a problem we can change it to a normal `depend`.

add python docs theme as a dependency

---

.github/workflows/ci.yaml
moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh
moveit_kinematics/test/test_ikfast_plugins.sh

auto_create_ikfast_moveit_plugin.sh fails due to sympy0.7.1 dependency not available from pip any more.  Fixed by installing directly from github
https://github.com/ros-planning/moveit/issues/2649

Install sympy0.7.1 from git as it is no long available from pypi

---

moveit_ros/planning/planning_pipeline/include/moveit/planning_pipeline/planning_pipeline.h
moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp

Fixes #2578.
#2127 introduced a child NodeHandle for initializing the PlanningPipeline. Since the display topics were generated from that one, the MotionPlanning panel wasn't able to receive any display markers from the "move_group" namespace anymore. By advertising the topics from a private NodeHandle (`"~"`) all markers and display messages are again published from the node's namespace, which in case of MoveGroup is "move_group". -> All fine!

Use private NodeHandle instead of child for PlanningPipeline topics

---

moveit_core/collision_detection/include/moveit/collision_detection/occupancy_map.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_monitor.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/perception/lazy_free_space_updater/include/moveit/lazy_free_space_updater/lazy_free_space_updater.h
moveit_ros/perception/lazy_free_space_updater/src/lazy_free_space_updater.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

We get crashes rarely where a collision check in FCL is ongoing while we update the octomap from another thread. This is due to the fact that we copy the `PlanningScene` maintained by `PlanningSceneMonitor` but the octomap shape/object is actually just a pointer and still shared with the one updated by the `PlanningSceneMonitor`. So far no locking of the octomap happens when doing collision checks this way (or in general?). Note that the octomap updater plugins in general only lock the octomap but not the `PlanningScene`.
I'm not super happy with this PR yet but would like to get some opinions already if I'm heading off completely in the wrong direction. Also I'm somewhat wondering why this doesn't impact people with a "live stream" 3d camera (we only update after each pick, ie every 5s …

Lock the octomap/octree while collision checking

---

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp

I forgot changing one include in #2596 which apparently does not bother the moveit-ci but does bother our internal ci
the relevant include is redundant as it's also included by `occupancy_map_monitor.h`, maybe that was the reason for MoveIt-CI being contempt
the include in the header could most likely be replaced by a forward decl, not sure if that would be worth the effort?

Fixup for #2596

---

moveit_ros/planning/package.xml

... that install to the same location.
Following the suggestion from https://github.com/ros-planning/moveit/issues/2648#issuecomment-836647351
Fixup for eb3bf6fdb6ece5324e3d1a81fd5d2b2197804710
Fixes #2648.

declare conflict after moving headers

---

MIGRATION.md
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp

I looked at these methods in the context of #2661 and was shocked they were in such a bad state.
Unifying the different overloads, I slightly changed the semantics of the method (for the better of course :cat: ).
The details are explained in fbecdeb .

Refine CSM::haveCompleteState

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_model/src/robot_model.cpp
moveit_core/robot_state/src/robot_state.cpp

Added warnings if the interpolation parameter `t` is outside the range [0, 1] or NaN. Would have helped in debugging something recently.
Maybe it would be good to also clamp the value to [0, 1] (and make a NaN a 0 or something)?

add warning if interpolation parameter is out of range [0, 1]

---

moveit_commander/src/moveit_commander/move_group.py
moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

I was trying out the `MotionPlanSequenceAction` today, and noticed that the planning pipeline cannot be switched from the initially loaded one. That makes it impossible to use e.g. LIN motions if OMPL is the default pipeline.
This PR uses the changes introduced in #2127 to allow switching the pipeline. The limitation is that only a single pipeline can be used per MotionSequence, but realistically no one will use this except for chaining `pilz` motions together, so I don't think this is a problem. I also don't think spending development time on it is worth it.
The PR also exposes the `constructMotionPlanRequest` function in the Python `MoveGroupInterface`, because defining a `MotionPlanSequenceRequest` without it is not feasible (unless you use a package like [the one linked in the …

Allow selecting planning pipeline in MotionSequenceAction

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_monitor.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/perception/lazy_free_space_updater/include/moveit/lazy_free_space_updater/lazy_free_space_updater.h
moveit_ros/perception/lazy_free_space_updater/src/lazy_free_space_updater.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

This reverts commit 0935d681b0141108e9695db30107184996963be7.
It introduced a deadlock in the standard MoveGroup planning pipeline.
Octomap is already locked in `PlanningSceneMonitor::lockSceneRead()` [before planning in the capability](https://github.com/ros-planning/moveit/blob/master/moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp#L222).
So the recursive locking calls (even in a different thread because OMPL spawns [a separate goal sampling thread](https://github.com/ros-planning/moveit/blob/master/moveit_planners/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp#L90)) can result in a deadlock if a writer lock is requested in the meanwhile.
@simonschmeisser To solve the issue you describe in  #2596, you will have to lock the `PlanningSceneMonitor` …

Revert "Lock the octomap/octree while collision checking (#2596)"

---

moveit_ros/occupancy_map_monitor/CMakeLists.txt

Hi there,
I had a linking issue regarding the moveit_ros/occupancy_map_monitor package and found a corresponding issue (https://github.com/ros-planning/moveit/issues/2560 ) without PR. Since it seemed to be an easy fix I decided to go for it. In the issue an undefined reference to octomath from the octomap package is described. I did elaborate in a comment on that issue and did provide some CMake snippets in order to support my PR. Sadly I am failing to reproduce the issue in a minimal example, but since another person reported the bug I thought it might still be helpful.
Since this linking issue does not pop up during the CI build and not during a manual source build of neither the melodic nor the noetic version of the entire moveit package, I was confused at first. However the CMake …

Add OCTOMAP_LIBRARIES and OCTOMAP_INCLUDE_DIRS to CMakeLists

---

.docker/ci/Dockerfile
.docker/source/Dockerfile
.github/workflows/ci.yaml
.github/workflows/downstream.rosinstall
.github/workflows/upstream.rosinstall

Same as #2654. Plus: adapts Dockerfiles to not install moveit anymore (fixes #2689).

Split upstream and downstream workspaces

---

.pre-commit-config.yaml
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/pilz_industrial_motion_planner.h
moveit_planners/pilz_industrial_motion_planner/test/test_robots/frankaemika_panda/launch/moveit_planning_execution.launch
moveit_ros/moveit_servo/README.md
moveit_setup_assistant/src/widgets/perception_widget.cpp

Absurdly this check exists for some of the auxiliary repositories,
but was not present in this the main repository yet.
Slightly modified because we use a number of `MoveitCommander` style
class names that should not be touched.

Misspelled MoveIt

---

moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_panda.h
moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
moveit_core/collision_detection_fcl/test/test_fcl_collision_detection_panda.cpp

For distance queries, FCL may report results in different order than what was requested (e.g. `fcl::distance(o1, o2, ...)` might give an `fcl::DistanceResult` with `o2, o1`. The MoveIt wrapper does not check if this is the case, and thus may report nearest_points in order `o2,o1` with `link_name` in order `o1,o2`.
This PR fixes this issue by explicitly using the collision objects referenced in the `fcl::DistanceResult` object. It also adds a unit test which demonstrates the issue.
I feel this is not applicable, since this is a pure bugfix.
I think the risk that somebody depends on the current broken behavior is quite low.

collision_detection_fcl: Report link_names in correct order

---

.github/workflows/ci.yaml
moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_bvh_manager.h
moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_cast_bvh_manager.h
moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_discrete_bvh_manager.h
moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_utils.h
moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_common_distance_field.h
moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_distance_field_types.h
moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_env_distance_field.h
moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/macros/include/moveit/macros/class_forward.h
moveit_core/macros/include/moveit/macros/declare_ptr.h
moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constraints_library.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/pilz_industrial_motion_planner.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/planning_context_circ.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/planning_context_lin.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/planning_context_ptp.h
moveit_ros/planning/constraint_sampler_manager_loader/include/moveit/constraint_sampler_manager_loader/constraint_sampler_manager_loader.h
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame_joints_widget.h

We rely on C++14 and should enforce standard-compliance (not just warning-free builds).
Potential followup to #2687
Let's see if anything/what breaks.

Make CI pedantic

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit_controller_manager.launch.xml

* Fix package path for Pilz pipeline: Use the launch file from the generated package, not from moveit_resources_prbt_moveit_config
* Add missing execution_type arg. This is necessary to avoid the following error:
RLException: unused args [execution_type] for include of [ [...]moveit_controller_manager.launch.xml]

Fix setup assistant template (execution_type, moveit_resources_prbt_moveit_config)

---

moveit_core/CMakeLists.txt

Octomap is a dependency of moveit_core, but in the catkin_package description it is listed under LIBRARIES, which suggests it is a library that originates from moveit_core.
This PR is opened in order to fix this false entry, pointed out by @v4hn on another PR https://github.com/ros-planning/moveit/pull/2671
Conceptually this line is probably wrong, because LIBRARIES should only list "the exported libraries from the project".
In theory the entry OCTOMAP in DEPENDS below should do the same the right way.
The corresponding line in moveit_core that you refer to is also 9 years old apparently and I guess nobody ever looked into it. 
Tested on a clean noetic build.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the …

Remove false octomap from catkin_packages LIBRARIES entries

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/perception_widget.cpp
moveit_setup_assistant/test/moveit_config_data_test.cpp

Fix for #1680. Properly writes each sensor config to file. Also fixes spelling mistakes and changes one EXPECT_EQ to an ASSERT_EQ to avoid accessing arrays where elements may not exist. 

Sensor config writing

---

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Before this commit, the padding parameters were read from the private namespace of the move_group node (unlike all the other PSM parameters).
Fixes #2699.

PSM: Don't read padding parameters from private namespace

---

moveit_core/collision_detection_fcl/src/collision_common.cpp

While reviewing #2682 I noticed there are some variables declared inside the FCL distanceCallback. That's pretty bad, performance-wise, for a function that should be fast.
This simply makes these variables `thread_local` so they don't have to be allocated with every callback.
I see a 52% reduction in distanceCallback duration. The spreadsheet is attached and you can see how it was tested in the commit history (std::chrono::high_resolution_clock). Mean duration drops from 8.75 microseconds to 4.23 microseconds. Worst-case duration drops from 43->21 us. I can give PickNik'rs guidance on how to reproduce the test setup.
[print_of_distance_callback.ods](https://github.com/ros-planning/moveit/files/6570886/print_of_distance_callback.ods)
I think there's lots of opportunity to do this type of …

Use thread_local var's in FCL distanceCallback()

---

moveit_planners/chomp/chomp_interface/include/chomp_interface/chomp_planning_context.h
moveit_planners/chomp/chomp_interface/src/chomp_interface.cpp
moveit_planners/chomp/chomp_interface/src/chomp_planning_context.cpp
moveit_planners/chomp/chomp_interface/src/chomp_plugin.cpp
moveit_planners/chomp/chomp_interface/test/chomp_planning.yaml
moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h
moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_parameters.h
moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
moveit_planners/chomp/chomp_motion_planner/src/chomp_parameters.cpp
moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/chomp_planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ompl_planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/pilz_industrial_motion_planner_planning_pipeline.launch.xml

This PR contains the following changes (see separate commits):
* CHOMP: Read parameters from proper namespace
* CHOMP: Rename param 'clearence' to 'clearance'
* MSA template: Put param jiggle_fraction into proper namespace
Fixes #2702.

CHOMP: Read parameters from proper namespace

---

moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp

While parsing through this code I saw a reversed sign on this check. This could cause two edge cases
Case 1: empty start_controllers and non-empty stop_controllers
This should cause the SwitchController to be made, but does not. Right now it is impossible for TrajectoryExecutionManager to pass in this condition though (if stop_controllers is non-empty, then by definition start_controllers will also be non-empty).
Case 2: empty start_controllers and empty stop_controllers
This should not cause the SwitchController to be made, but does. Right now TrajectoryExecutionManager does not invoke switchControllers if both lists are empty though.
TLDR This won't change anything behavior wise but should still be fixed.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't …

Fix reversed check in switchControllers

---

moveit_ros/benchmarks/examples/demo_panda_predefined_poses.launch
moveit_ros/benchmarks/examples/demo_panda_predefined_poses.yaml

This fixes the `CombinePredefinedPosesBenchmark` a custom benchmark example derived from the BenchmarkExecutor class.
- Change the benchmark node type to the custom benchmark node. 
- The predefined poses named _ready_ and _extended_ exists only in the panda_arm group.
Will have to investigate further this error message probably triggered [here](https://github.com/ros-planning/moveit/blob/master/moveit_ros/benchmarks/src/simple_benchmarks/CombinePredefinedPosesBenchmark.cpp#L103):
``` shell
[ERROR] [1623807614.550173309]: Found empty JointState message
```
The benchmark works regardless of the error.

Fix predefined poses benchmark example

---

moveit_ros/moveit_servo/include/moveit_servo/low_pass_filter.h

`moveit_servo::LowPassFilter` is not currently assignable. At times, this makes it difficult to use with a `std::vector` without pointer semantics. There isn't an inherit reason for the type to be non-assignable and the members are not exposed in the public interface https://abseil.io/tips/177

Refactor moveit_servo::LowPassFilter to be assignable

---

moveit_core/collision_detection_fcl/src/collision_robot_fcl.cpp

The CollisionRobotFCL class did not consider the scale and the padding when creating the collision geometry for the attached objects. This change would lead the padding and scale to be exactly the same as the ones of the link the objects are attached to.
Pull request made after reporting the bug in ros-planning/moveit#2719.

fixed padding collision attached objects

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch

As per subject.
See #2728 for discussion, and the commit comment for the rationale.

msa: capabilities-related args are args in template (fix #2728)

---

moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp

This is a pretty small optimization but I don't like to see `push_back()` called within a function that should be performant. This should be faster if there are multiple attached collision bodies.

Avoid push_back within getAttachedBodyObjects

---

moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/constraint_samplers/test/test_constraint_samplers.cpp
moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_core/kinematic_constraints/test/test_orientation_constraints.cpp

Depends on [this moveit_msgs PR](https://github.com/ros-planning/moveit_msgs/pull/96)!
MoveIt represents the error for orientation constraints as intrinsic XYZ Euler angles. This PR adds a second option that uses a rotation vector (rotation axis multiplied with the rotation angle). For more info on the math, see section "Rotation vector" on [this Wikipedia page](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation).
This new parameterization is not only a requirement for the new OMPL constrained planner (#2273), but it is also useful when we support path constraints with Trajopt. The same parameterization is used [there](https://github.com/ros-industrial-consortium/trajopt_ros/blob/a393abb99b221c97603ae40fcbd0f172f94a7fcc/trajopt/include/trajopt/utils.hpp#L161).
I originally …

New orientation constraint parameterization

---

moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_panel.cpp

This fixes a display bug in the rviz `TrajectoryPanel`, @v4hn mentioned today.
The second commit is some related, but independent code cleanup.

Fix trajectory panel

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

When both:
use_gazebo: true
command_out_type: trajectory_msgs/JointTrajectory
are set in the parameters a trajectory with redundant points is
published by servo_server. The 2nd point in this trajectory is always
empty (i.e. 0 timestamp and empty position/velocity/acceleration
arrays). This turns out to be because it is erroneously never filled in.
The timestamps need to be shifted relative to the point's index but all
of the points should still be filled in.
In the loop in `ServoCalcs::insertRedundantPointsIntoTrajectory`, be sure to populate index 1 of the outgoing array.
Corresponding issue: https://github.com/ros-planning/moveit/issues/2739
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank …

Fix an off-by-one error in servo_calcs.cpp

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

Fix issues of https://github.com/ros-planning/moveit/issues/2741 regarding the joints tab:
- switch order of `manipulation` and `joints` tabs
- correctly handle mimic joints (don't allow editing)

Fix joints tab

---

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

The fact that trajectory visualization ignored the time parameterization by default
and that the only way to change this is the special value "REALTIME" always bothered me.
I changed the default to a realtime factor of 3x to get a nice preview of the trajectory
when using the "Plan&Execute" button.
https://user-images.githubusercontent.com/680358/123707186-9cdfa400-d869-11eb-9e94-95935f15d163.mp4

support arbitrary realtime-factors in trajectory visualization

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/edit_configuration_package.launch

just a tiny annoyance nobody complained about before.

MSA: kill setup_assistant.launch after MSA finished

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/default_warehouse_db.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/run_benchmark_ompl.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/sensor_manager.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajectory_execution.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/warehouse.launch

Available since lunar. This simplifies the descriptions in moveit_resources
quite a bit because their package name does not match the include path
and we have to adapt the names everywhere after edits.
Note that two candidates for this replacement still remain -
they define the file path to the rviz config in an arg value.
Due to [a bug](https://github.com/ros/ros_comm/issues/1487) these two can not be replaced at this moment.
@gavanderhoorn Could you please review this patch?

use $(dirname) in MoveIt Setup Assistant

---

moveit_core/collision_detection/include/moveit/collision_detection/occupancy_map.h
moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_monitor.h
moveit_ros/occupancy_map_monitor/include/moveit/occupancy_map_monitor/occupancy_map_updater.h
moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
moveit_ros/perception/lazy_free_space_updater/include/moveit/lazy_free_space_updater/lazy_free_space_updater.h
moveit_ros/perception/lazy_free_space_updater/src/lazy_free_space_updater.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

This includes the useful components from #2596 .
The `PlanningScene` should create `OCTOMAP_NS` as the derived `OccMapTree` through all interfaces.
To get there we still have to move the header to `moveit_core/collision_detection`, so that part remains as well.
The third commit was pure cleanup.
@simonschmeisser please review, I did not even test-compile over here.
**EDIT**: The original PR description stated:
> The static cast is assumed to succeed in multiple places.
This is actually not true without the associated (invalid and reverted)  patches by @simonschmeisser as our code base performs all checks on whether an `occupancy_map_monitor` exists. Still, it is a good idea to ensure this is true, especially for code that creates diffs over monitored planning scenes and thus can't easily …

refactors for OccMapTree in PlanningScene

---

moveit_commander/src/moveit_commander/move_group.py

Fixes #2752 , which was introduced with the new feature in #2622. I should have made `get_planning_pipeline_id` without an argument.
It also adds some debugging prints, which should be helpful.

Fix get_planning_pipeline_id in Python MGI

---

moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/src/servo_calcs.cpp

Some fix, that seemed wrong from the code context.
The fix are minor and not serious.
-fixed a wrapper calling wrong member, though normally returning same value
-suppressed a wrong ROS_WARN message

Servo: minor fixups

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_core/robot_trajectory/test/test_robot_trajectory.cpp

Please look at the individual commits for details.

minor RobotTrajectory patches

---

moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp

So empty controller names are easier to spot.
Some MoveIt configurations have the controller `name` set to `""`. This is valid (although annoying), but the formatting of the log lines makes it difficult to spot this.
Without the quotes:
```
Controller  failed with error INVALID_GOAL: ...
```
With the quotes:
```
Controller '' failed with error INVALID_GOAL: ...
```

controller manager: enclose controller name in quotes

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_detector_allocator.h
moveit_core/collision_detection/include/moveit/collision_detection/collision_plugin.h
moveit_core/kinematics_base/CMakeLists.txt
moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
moveit_core/planning_scene/CMakeLists.txt
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h

This is a small cleanup for 4963f32849b4d20c423f6a29a4114f1d48526c0d of #2604.
The change from `NAME_` to `getName()` wasn't updated in a doc comment.
`getName()` doesn't need to be redeclared as abstract in `CollisionDetectorAllocatorTemplate`.

Cleanup CollisionDetectorAllocatorTemplate::getName()

---

.github/workflows/ci.yaml

So far, we only used ROS Melodic builds for CI (based on the `master-ci` docker container).
This PR attempts to switch to `noetic-ci` by default and using only a single `master-ci` build for Melodic.

CI: Switch to Noetic builds by default

---

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo_gazebo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch

Major change is to create a static_transform_publisher for each and every virtual joint type as suggested in https://github.com/ros-planning/moveit_resources/issues/89#issuecomment-879791874.
Additionally, some minor formatting changes.

Fix MSA templates

---

moveit_core/CMakeLists.txt

Fixes error C2338: 
```
You've instantiated std::aligned_storage<Len, Align>
with an extended alignment (in other words, Align > alignof(max_align_t)).
Before VS 2017 15.8, the member type would non-conformingly have an
alignment of only alignof(max_align_t).
VS 2017 15.8 was fixed to handle this correctly, but the fix inherently
changes layout and breaks binary compatibility (*only* for uses of
aligned_storage with extended alignments). Please define either
1. _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand
this message and that you actually want a type with an extended alignment
2. _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and
get the old non-conformant behavior.
```

Fix Windows CI

---

moveit_commander/src/moveit_commander/move_group.py
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

fix #2373 
Does not look like this message is used other than in very specific applications, but currently the python wrapper uses functions that do not exist, which seems like it is still worth fixing.

Readd missing TrajectoryConstraints functions for MoveitCommander

---

moveit_core/collision_detector_bullet_description.xml

Fix wrong plugin library path for the Bullet collision detector.
```shell
Exception while loading Bullet: Could not find library corresponding to plugin Bullet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

Fix bullet plugin library path name

---

moveit_ros/planning/planning_scene_monitor/src/trajectory_monitor.cpp

Thank you to @griswaldbrooks for [finding this in a routine review](https://github.com/ros-planning/moveit2/pull/570#discussion_r677004874).
This is such a rare use interface that this bug almost surely was never noticed...

Trajectory Monitor: fix obvious bug

---

moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_action.cpp
moveit_planners/pilz_industrial_motion_planner/src/move_group_sequence_service.cpp

In #2657 I added code to select the planning pipeline and planner to the `getMotionSequence` action. This is required to use the action and service when both OMPL and the Pilz planning pipelines are loaded, because `getMotionSequence` needs to use Pilz, but selects the default pipeline instead (OMPL).
I recently noticed that it should also be added to the service, which this PR does. It works, so if you need this feature you can use it. But it breaks some tests, and they seem to be in functionality (`Sequence`) that I don't have the time to dig into right now. Maybe @ct2034 or @jschleicher want to have a look.

Add planning_pipeline_id to MotionSequence service

---

moveit_ros/planning/rdf_loader/src/rdf_loader.cpp

`RDFLoader` implementation was wrong: it used the method field *before* it was used, leading to a null-pointer segfault. THis commit fixes that.

Fixed a crash bug due to uninitialized class field being used.

---

.github/workflows/ci.yaml
moveit_core/collision_detection_fcl/CMakeLists.txt

https://github.com/ros-planning/moveit/pull/2790 and https://github.com/ros-planning/moveit/pull/2674 currently show that the clang-tidy job broke, likely due to 55886f770b0f9ebe1f2297b92869e8ca97cfc60a .
Recovering the clang-tidy job might fail for a variety of reasons, so I will mark this as WIP.
Anyone, feel free to fix and merge this if you have time.

fix clang-tidy CI job

---

moveit_core/collision_detection_fcl/src/collision_common.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp

These two issues appeared in https://github.com/ros-planning/moveit/pull/2795 .
As clang-tidy only inspects files that changed, they did not show up before.
@tylerjw

more fixes for the clang-tidy job

---

moveit_core/robot_state/src/robot_state.cpp

This is a backport of a bug I fixed in moveit2.
It came from this PR: https://github.com/ros-planning/moveit2/pull/562/files
I am backporting the bug fix separate from that full PR because I believe it should be trivial to merge whereas that whole PR might require more discussion before we backport that pattern from moveit2 to moveit.  That doesn't mean that we can't backport the bugs we fix while applying that pattern even if we don't want to backport the pattern yet.

[fix] RobotState Constructor segfault

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

@corot [proposed to fix object color handling](https://github.com/ros-planning/moveit/pull/2785), but the handling itself does not seem to be broken the way they expect.
Instead, when trying to remove an attached object from the world, color/type was removed even when the object was not actually removed from the world (attached objects are not in the world, so their meta-data should stay around).
Additionally here is a test to verify handling of color and type works as expected when objects get attached/detached.
@corot The bugfix should help you find the culprit in your use case. Please have a look at the test as well.

Preserve metadata when detaching objects

---

moveit_core/kinematic_constraints/src/utils.cpp

The pair (above/below) substitution was inverted in setting JointConstraint.
There was no comment about inverting, and the code had little change from original, 
so I think it's a mistake.

code fix on wrong substitution

---

.docker/ci/Dockerfile

This was a workaround for https://github.com/catkin/catkin_tools/issues/594. It is no longer necessary since python3-catkin-tools 0.7 added the proper dependency.

Remove python3-osrf-pycommon from Dockerfile

---

moveit_core/collision_detection_fcl/CMakeLists.txt
moveit_core/collision_detection_fcl/src/collision_common.cpp

The culprit of #2792 was essentially an optimization I proposed for #2698 to avoid copying strings to generate a map key.
Looks like this optimization leads to a stack-use-after-scope issue (found with asan), both in clang and gcc.
Reverting it, fixes the issue.
However, I'm not sure why this code doesn't work - the string references should exist:
```c++
#include <map>
#include <string>
#include <iostream>
int main(int argc, char const* argv[])
{
using KeyT = std::pair<std::string, std::string>;
std::map<KeyT, int> map;
map.insert(std::make_pair(std::make_pair("foo", "bar"), 1));
map.insert(std::make_pair(std::make_pair("bar", "foo"), 2));
const std::string foo = "foo";
const std::string bar = "bar";
const std::pair<const std::string&, const std::string&> key =
std::make_pair<const …
```

Fix issue #2809 (broken test with clang)

---

.github/workflows/ci.yaml

Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619

[master] Fix ccache

---

.github/workflows/ci.yaml

Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619

[melodic] Fix ccache

---

.github/workflows/ci.yaml

Warnings in downstream or upstream workspaces (i.e. external packages) shouldn't make CI fail due to `-Werror`.
Addresses https://github.com/ros-planning/moveit_visual_tools/pull/96#issuecomment-897069559.
[This CI build](https://github.com/ubi-agni/moveit/runs/3354072333?check_suite_focus=true) illustrates that warnings in external packages don't harm the CI job anymore.

CI: Enable -Werror only for TARGET_WORKSPACE

---

moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_utils.h
moveit_core/collision_detection_bullet/test/test_bullet_continuous_collision_checking.cpp

When using Bullet collision, the collision response contact type is wrong. This is due to a typo in the bullet_utils.h which stores the first type into both contacts.
This PR fixes this issue and updates the continuous collision detection test to include a check for the contact type.

Fix Bullet collision returning wrong contact type

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp

If the MP plugin was created in a non-rviz context (e.g. directly via librviz),
there might be no window manager and thus no parent widget available for panels.
This fixes https://github.com/ros-visualization/rviz/issues/1653.

MotionPlanningFrame: Gracefully handle undefined parent widget

---

MIGRATION.md
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

This commit makes sure the RVIZ trajectory visualization plugin looks for the trajectory topic to be on the relative ns instead of the absolute ns when it is first added to Rviz (i.e. `move_group/display_planned_path` vs. `/move_group/display_planned_path`). This was done to make sure that it respects the namespaces that are set in launch files. This is useful when you are using MoveIt for multi robot control.
I did not find any images or text in the documentation that needs to be updates. Please let me know if I missed something.

Makes rviz trajectory visualization topic relative

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/utils/include/moveit/utils/message_checks.h
moveit_core/utils/src/message_checks.cpp

In #2816 , there was a fix for backwards compatibility for specifying a pose for a single collision shape. In that fix, I think there may be a bug. There is a check [here](https://github.com/ros-planning/moveit/blob/master/moveit_core/planning_scene/src/planning_scene.cpp#L1721) to determine if an object's pose has been set:
`if (object_pose.isApprox(Eigen::Isometry3d::Identity()))`
I think this check is problematic because if the pose is not set, all pose fields are zero. Checking if the pose is Identity assumes the unit quaternion which means that the "w" component is equal to 1. The way the code is currently, even if the object pose is set to identity, the shape pose will be used instead (which may not be aligned the same way as the object pose intended). This PR fixes this by …

Fix pose-not-set-bug

---

moveit_core/robot_state/include/moveit/robot_state/robot_state.h

I just saw these comments in #2799 and they should be updated.
We renamed the parameter earlier this year because MSVC apparently reserves "near" as a keyword.

update comments to current parameter name

---

moveit_core/collision_detection/src/world.cpp

As noted in https://github.com/ros-planning/moveit/pull/2816, I left a quick-and-dirty solution in #2037 . This commit was supposed to fix that, but it has a bug.
It's probably simple, so I'm putting this up for someone to make me look stupid.

Remove unnecessary subframes map copy

---

moveit_core/robot_state/src/robot_state.cpp

I stumbled upon this when helping @felixvd debug #2854  ... this PR would have prevented his long despair
C++ provides a default copy constructor if it reasonably can. `AttachedBody` is a simple data structure so indeed it can here. Using the copy constructor prevents forgetting to manually copy some member variables.

use default copy constructor to clone attached object

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajopt_planning_pipeline.launch.xml

This pull request adds the jiggle_fraction argument which is used in the 'FixStartStateCollision' planning adapter to the 'trajopt_planning_pipeline.launch.xml' template.

Adds jiggle fraction arg to trajopt template

---

moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

Otherwise we add "free" voxels outside the max_range volumes for no reason.
I did not test it myself but @FSund posted screenshots in the issue that demonstrate the impact.
Fixes #2709

clipped points should only be considered up to the max_range

---

moveit_core/planning_scene/src/planning_scene.cpp

The information in the diff is redundant because attaching an object implies its removal from the PlanningScene.
In the unlikely case you relied on the REMOVE entry in the diff message, use the newly attached collision object to indicate the same instead.
Since https://github.com/ros-planning/moveit/commit/fd88dd63469f2790b7d13864b425c813a2f95aa5 applying the message with both entries via `PlanningScene::usePlanningSceneMsg` fails, but messages generated by `PlanningScene::getPlanningSceneDiffMsg` should always be accepted there!
This currently breaks task execution through the MTC capability [here](https://github.com/ros-planning/moveit_task_constructor/blob/master/capabilities/src/execute_task_solution_capability.cpp#L179) whenever an object becomes attached (e.g., in the pick-place …

PS: do not list object as destroyed when they get attached

---

moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_utils.h

The `acmCheck` method in `bullet_utils.h` directly looked up the relevant entry in the `AllowedCollisionMatrix`, ignoring any default values. This PR replaced the method call with `getAllowedCollision`, which appears to be the correct method (please review).

Fixed Bullet collision checker not taking ACM defaults into account.

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

This fixes https://github.com/ros-planning/moveit_task_constructor/issues/291.
We need to update the pose of the PlanningSceneDisplay's scene node in each update() cycle.
So far, it was only updated if the PlanningSceneMonitor received any update.
The following video illustrates the new (left) vs. the old=released behaviour (right):
https://user-images.githubusercontent.com/5376030/133408681-e76f08c1-79cc-49e1-beac-6e046b7f8bc0.mp4
Without this PR, the planning scene is only updated once when it gets initialized (or when joint updates are received, which is not the case here).

PlanningSceneDisplay: always update the main scene node's pose

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

If we reload these values from the config, setting the ROS parameters is much less useful. The correct db should be set in the parameters instead of the RViz config!
At least the *type* of warehouse_ros plugin (mongo or sqlite) cannot even be selected in the display, so you will probably need to meddle with the parameters anyway if you want to connect to a different db.
search for parameters warehouse_host/port because they are usually set at the top level, but you might want to set them differently for different move_groups.
I noticed the values in rviz are not updated when following [the new `warehouse_ros_sqlite` tutorial](https://github.com/ros-planning/moveit_tutorials/pull/658), but you would very much expect them to be!

MPD: do not save/restore warehouse parameters

---

.github/ci_cross_platform_env.yml

Fix #2881 by pinning orocos-kdl to a working version.

Temporarily pin orocos-kdl to fix cross-platform CI

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/planning_pipeline.launch.xml

This PR
* renames launch files from *.launch.xml -> .launch
* clarifies that all planning pipelines are loaded into a namespace by doing it once in `planning_pipeline.launch`

Improve launch files

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

@tylerjw accidentally backported [a single change](https://github.com/ros-planning/moveit/pull/2630/commits/5b5d42e2f032b2c53a1d68886d95c6ab8841dc14) from the #1890 feature set to melodic [in May](https://github.com/ros-planning/moveit/pull/2630) and nobody noticed.
I vote to revert the commit in melodic even though we already released it there, accidentally breaking behavior on melodic once when the documentation says the change only exists in noetic.

broken melodic backport for default speed factors

---

moveit_core/robot_state/src/robot_state.cpp

Not an actual bug because both arrays share the same memory.
As mentioned in https://github.com/ros-planning/moveit2/pull/683#pullrequestreview-780447848

RobotState: write to correct array

---

moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp

Currently the minimum value you can specify for the the max velocity outputted for a joint during time optimal trajectory parameterization is 0.01 rad/s or m/s. For joints that are unable to move that fast and whose velocity limits are less than 0.01, the planned path outputted is unachievable with trajectory velocities being higher than the maximum velocity of the joint. 
Reduced the value to 0.001.

Reduced the minimum max velocity joint limit from 0.01 to 0.001 for totg

---

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/perception_widget.cpp
moveit_setup_assistant/src/widgets/perception_widget.h
moveit_setup_assistant/src/widgets/start_screen_widget.cpp
moveit_setup_assistant/test/moveit_config_data_test.cpp

The perception widget had several issues since its introduction in #969: 
- By reading both, the default and the existing package's `sensors_3d.yaml` into the config, the config file was growing by 2 configs each time.
- Not visiting the `Perception` tab, was writing the default config with 2 entries
- Selecting "None" was writing an invalid config:
```yaml
sensors:
- {}
- {}
```

Fix handling of sensors_3d.yaml

---

.github/workflows/ci.yaml

Added new job to automatically fast-forward push noetic-devel to master after a successful push of master on ros-planning. 
This will automate the process of keeping master and noetic-devel in sync.
Note, the job will not run on pull-requests, different branches than master being pushed, or on forked repos.

GHA: auto-sync noetic-devel to master

---

moveit_ros/perception/depth_image_octomap_updater/include/moveit/depth_image_octomap_updater/depth_image_octomap_updater.h
moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp
moveit_ros/perception/pointcloud_octomap_updater/include/moveit/pointcloud_octomap_updater/pointcloud_octomap_updater.h
moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

Added a `ns` parameter to the octomap updaters in order to fix #2846 . This avoids the `Tried to advertise a service that is already advertised` errors.

Add ns for depth image & pointcloud octomap updaters

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp

This pull request fixes an MSA bug that caused files in a loaded MoveIt config to incorrectly be classified as externally modified. This happened when the `Generate Package` button is clicked multiple times and we go back to other tabs.

fix(msa): fix modified files bug

---

moveit_core/robot_trajectory/test/test_robot_trajectory.cpp

Previously, only joint positions were tested.
This should settle the discussion [here](https://github.com/ros-planning/moveit/pull/2957#issuecomment-967195498) (PR #2957). The duration deep copy was correct, it seems.

Add waypoint duration to the trajectory deep copy unit test

---

moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning/moveit_cpp/src/planning_component.cpp

PR for issue [2958](https://github.com/ros-planning/moveit/issues/2958). Only minor difference from the corresponding moveit2 implementation is the change in the moveit_msg definitions.

MoveitCpp - added ability to set path constraints for PlanningComponent.

---

moveit_ros/robot_interaction/src/robot_interaction.cpp

For single groups, the old logic fell back to add a marker
for the last link if IK is supported for it and no endeffector is defined.
That (quite reasonable) fallback did not yet work for subgroups though.
For a subgroup definition like this in the srdf:
```
<group name="hand_all">
<group name="hand_mf_group" />
<group name="hand_rf_group" />
<group name="hand_th_group" />
</group>
```
Before:
After:

Add marker for subgroups even if no endeffector is defined for them

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

Currently a OMPL planner can only be canceled during the actual planning stage but will happily use up the timeout during simplification despite the request to cancel. This PR registers a termination condition for the simplification phase so this can be canceled as well.
This will still not cancel immediately as there is a default param `atLeastOnce` here https://github.com/ompl/ompl/blob/528f02cdc5ac785ba24e1dbdf1cf621a17020b7b/src/ompl/geometric/src/PathSimplifier.cpp#L677 that we cannot easily access and which ensures that the whole simplification process does at least one iteration of each simplification attempt.
Still this will hopefully save us some time as we need to wait for all planners to terminate before we can do some Octomap update. Can be 700ms or more currently and that …

OMPL: Register and use termination condition for simplification as well

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

This PR adds backwards compatibility for the old scene serialization format to `PlanningScene` following #2037, cf. the regression report for Noetic in #2985. It first checks which version of the syntax is provided (by checking the line following the start of a new object - previously the number of shapes, now the translational component of the pose) and deactivates the subframe-poses if using the old format, as well as maintains compatibility by resetting the pose to identity.
@felixvd @rhaschke Can you please review this PR, backport it to noetic-devel, and release? :-)
I've added unittests for the old format as well. Detail on changes/logic in the individual commits. 
Resolves #2985

Hotfix: Add backwards compatibility for old scene serialization format

---

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_core/planning_scene/src/planning_scene.cpp

This exposes the parameter "group_name" of the collision request in PlanningScene::getCollidingPairs" for convenience. We print out or visualize those pairs in a few places in our product and filter after the getting the full list.

Allow restricting collision pairs to a group

---

.github/robostack_env.yaml

@rhaschke let's see if this fixes the builds for now. 
We could also create a real "lock file" using a tool like [`conda-lock`](https://github.com/conda-incubator/conda-lock).

pin previous tinyxml2 for static lib

---

moveit_core/cmake/moveit.cmake

This is plain convenient and you always need it when you did not explicitly add it.
Follow @tylerjw's initiative to add it to MoveIt2: https://github.com/ros-planning/moveit2/pull/794
The downside (at least on my system) is that the cmake config for the package is not implemented correctly and yields this warning for each find_package call:
```
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
The package name passed to `find_package_handle_standard_args` (Backward)
does not match the name of the calling package (backward_ros).  This can
lead to problems in calling code that expects `find_package` result
variables (e.g., `_FOUND`) to follow a certain pattern.
```

quietly use backward_cpp/ros if available

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/gripper_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp

This pull request adds the `max_effort` parameter to the GripperCommand declaration in the `controller_list` (see issue #2956). This value is only used when the effort is set in the requested gripper trajectory.
1. Clone the [rickstaa/moveit#add_max_effort_param](https://github.com/rickstaa/moveit/tree/add_max_effort_param) branch into a catkin workspace.
2. Clone the [rickstaa/franka_ros#noetic-devel-panda_gazebo](https://github.com/rickstaa/franka_ros/tree/noetic-devel-panda_gazebo) branch into the catkin workspace.
3. Clone the [rickstaa/panda_moveit_config#noetic-devel-panda_gazebo](https://github.com/rickstaa/panda_moveit_config/tree/noetic-devel-panda_gazebo) branch into the catkin workspace
4. Install the ROS dependencies using `rosdep --from-path src --ignore-src -r -y`.
5. Build …

feat(simple_controller_manager): add `max_effort` parameter to GripperCommand action

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame_joints_widget.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

Resetting the `MotionPlanningDisplay` in rviz (or disabling+enabling it) issues the following warning:
```
[ WARN] ros.rosconsole_bridge.class_loader.ClassLoader: SEVERE WARNING!!!
Attempting to unload /vol/sandbox/ros/devel/lib//libmoveit_kdl_kinematics_plugin.so
while objects created by this library still exist in the heap!
You should delete your objects before destroying the ClassLoader. The library will NOT be unloaded.
```
The reason is that we don't release all references to the `RobotModel` (and thus it's IK solvers), before destroying the corresponding `RobotModelLoader`. I reduced the number of pending pointers from 21 to 7.
For now, I cannot immediately see where the remaining 6 refs are hidden. Thus, anybody who likes to contribute is highly welcome!

Fix `ClassLoader: SEVERE WARNING`

---

moveit_core/robot_state/src/robot_state.cpp

Fix for #3002 because the author there decided to ignore the problem.
Instead of the assert print a tag and the matrix.
Building a Quaternion from non-isometries is undefined behavior in Eigen, thus the split.
The new output looks like this when isometries are broken:
```
Joint transforms:
virtual_joint [dirty]: [NON-ISOMETRY] [6.92595e-310, 0, 0, 0; 6.92595e-310, 0, 7.41098e-323, 4.94066e-324; 8.98317e-317, 0, 0, 8.98318e-317; 0, 0, 0, 1]
panda_joint1 [dirty]: [NON-ISOMETRY] [0, 0, 0, -nan; 0, 0, 0, 0; 0, 0, 0, 0; 0, 0, 0, 1]
panda_joint2 [dirty]: [NON-ISOMETRY] [0, 1.63318e-319, 0, nan; 9.13379e-320, 0, 0, 0; 1.63318e-319, 0, 0, 0; 0, 0, 0, 1]
```
and usually like that (unchanged):
```
Joint transforms:
virtual_joint: T.xyz = [0, 0, 0], Q.xyzw = [0, 0, 0, 1]
panda_joint1: T.xyz = [0, 0, …
```

Do not assert on printTransform with non-isometry

---

moveit_planners/moveit_planners/package.xml
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/joint_limits_container.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator.h
moveit_planners/pilz_industrial_motion_planner/src/joint_limits_container.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp
moveit_planners/pilz_industrial_motion_planner/test/unittest_joint_limits_container.cpp

Improve usability. I kept getting out of range errors in a start state and needed to implement this code to figure out which joints triggered the problem...

pilz planner: report invalid joint

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

Setting the start state via the `MoveGroupInterface` with a RobotStateMsg that has missing joint state values will create a segfault when planning because the missing joint states are not [initialized](https://github.com/ros-planning/moveit/blob/master/moveit_core/robot_state/include/moveit/robot_state/robot_state.h#L92-L94). Using the classic panda `demo.launch` from moveit_resources. Maybe related to https://github.com/flexible-collision-library/fcl/issues/521.
Specifying only `panda_joint1` to `panda_joint7` and omitting `panda_finger_joint1/2` works using the PlanningPipeline. I guess it uses default values for the 2 missing joints in the MotionPlanRequest down the road (maybe in request adapters).
The obvious solution is to specify the missing joints. This PR makes the …

Fix MoveGroupInterface uninitialized RobotState

---

MIGRATION.md
moveit_core/collision_distance_field/test/test_collision_distance_field.cpp
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp
moveit_core/robot_state/test/test_kinematic_complex.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp

The method RobotState::attachBody(AttachBody*) expects an owning raw pointer. This can be seen from the comment above the method (see below).  This PR replaces that owning raw pointer with a `std::unique_ptr`. The old method is marked deprecated. This allows removing multiple `delete`'s in robot_state.cpp. Additionally two other `new` keywords were replaced in the __test__ code of robot_state.
~~~
/** \brief Add an attached body to this state. Ownership of the
* memory for the attached body is assumed by the state.
*
* This only adds the given body to this RobotState
* instance.  It does not change anything about other
* representations of the object elsewhere in the system.  So if the
* body represents an object in a collision_detection::World (like
* from a …

Removed raw pointer creation using new from robot state test

---

moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_pr2.h

Debug builds are significantly slower and thus shouldn't be considered for timing-based tests.
They frequently fail, e.g. https://github.com/ros-planning/moveit/runs/4648164688?check_suite_focus=true

Disable timing tests in DEBUG mode

---

MIGRATION.md
moveit_core/utils/include/moveit/utils/moveit_error_code.h
moveit_planners/chomp/chomp_interface/test/chomp_moveit_test.cpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp
moveit_ros/planning_interface/test/move_group_pick_place_test.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp

Remove duplication and make it easier to be used for other purposes (an example https://github.com/ros-planning/moveit_task_constructor/pull/319) without depending on either `moveit_ros_planning` or `moveit_ros_planning_interface`

Move MoveItErrorCode class to moveit_core

---

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
moveit_setup_assistant/src/widgets/start_screen_widget.cpp
moveit_setup_assistant/src/widgets/start_screen_widget.h

This PR factors out two simple commits from #2938:
- Pass xacro args to SRDF loading as well (fixes an issue reported by @rickstaa somewhere)
- Modernize some more loops (no idea why clang-tidy ignored them)

MSA cleanup

---

moveit_ros/robot_interaction/test/locked_robot_state_test.cpp

These tests are known to run for a very long time in debug builds.
So let's disable them in this case.
If you still insist to run them, you can do so via
`locked_robot_state_test --gtest_also_run_disabled_tests`
Inspired by #3012 .
This addresses the worst offender in #2107 .
The other long-running tests can probably be patched in similar ways if we deem it useful.
For documentation. This is an execution in debug mode of the first few tests on my local machine:
```
./devel/.private/moveit_ros_robot_interaction/lib/moveit_ros_robot_interaction/locked_robot_state_test
[==========] Running 16 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 16 tests from LockedRobotState
[ RUN      ] LockedRobotState.load
1640781730.871940801: …
```

disable robot_interaction tests without NDEBUG

---

moveit_core/utils/include/moveit/utils/moveit_error_code.h
moveit_planners/chomp/chomp_interface/test/chomp_moveit_test.cpp
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/moveit_cpp/src/planning_component.cpp
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp

In contrast to #3009, I decided to not deprecate the old definitions here (but only redirect them).

Backport #3009: Move MoveItErrorCode to moveit::core

---

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/planning_component.h
moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning_interface/moveit_cpp/src/planning_component.cpp

as required by clang-tidy: https://github.com/ros-planning/moveit/runs/4660515498

Add missing noexcept declarations

---

moveit_ros/planning/moveit_cpp/src/planning_component.cpp

The deprecation warning below shows up when building MoveIt from source.
This PR applies the suggestion given in the warning and removes the indirection through `moveit_msgs::MoveItErrorCodes`.
(Related to #3009)
```
Warnings   << moveit_ros_planning:make /home/jdm/ros/moveit_ws/logs/moveit_ros_planning/build.make.001.log                             
/home/jdm/ros/moveit_ws/src/moveit/moveit_ros/planning/moveit_cpp/src/planning_component.cpp:114:39: warning: 'MoveItErrorCode' is deprecated: Use moveit::core::MoveItErrorCode [-Wdeprecated-declarations]
last_plan_solution_->error_code = MoveItErrorCode(moveit_msgs::MoveItErrorCodes::INVALID_GROUP_NAME);
^
/home/jdm/ros/moveit_ws/src/moveit/moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/planning_component.h:54:27: note: …
```

Fix deprecation warning in moveit_cpp, add namespace to MoveItErrorCode

---

moveit_core/collision_distance_field/src/collision_distance_field_types.cpp

For optimization-based trajectory planning, collision bodies can be sampled with spheres with `collision_detection::determineCollisionSpheres`. The current implementation introduces a wrong relative transform, leading to a wrong positioning of these spheres. The error is only noticeable, when collision bodies have an offset from the respective link pose.
Before the fix:
With the fix:

Removed wrong transform in sphere decomposition

---

.github/workflows/upstream.rosinstall
moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h
moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_panda.h
moveit_core/collision_detection/src/collision_matrix.cpp
moveit_core/collision_detection_bullet/test/test_bullet_continuous_collision_checking.cpp
moveit_core/planning_scene/src/planning_scene.cpp
moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/collisions_updater.cpp
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
moveit_setup_assistant/src/widgets/default_collisions_widget.cpp

This is a first implementation of #2936, considering ACM defaults as a fallback again (instead of an overrride).
This **depends on https://github.com/ros-planning/srdfdom/pull/97**, which implements corresponding SRDF extensions.
I encountered one difficulty implementing this, namely serializing and deserializing ACM messages: 
- Always the full matrix is serialized (there is no simple/compact alternative)
- The previous code didn't correctly serialize pair entries (only if a pair was specified, the value was serialized).
Thus, when a default was specified, but no pairs, the wrong value was transmitted.
- Now, only if the pair deviates from the expected default, an explicit pair entry is created on the receiving side to keep the matrix as compact as possible.
An example application can be …

Rework ACM defaults

---

moveit_ros/perception/mesh_filter/src/depth_self_filter_nodelet.cpp

Fix compilation on osx:
```
FAILED: mesh_filter/CMakeFiles/moveit_depth_self_filter.dir/src/depth_self_filter_nodelet.cpp.o 
$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++ -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"moveit_ros_perception\" -Dmoveit_depth_self_filter_EXPORTS -I$SRC_DIR/ros-noetic-moveit-ros-perception/src/work/lazy_free_space_updater/include -I$SRC_DIR/ros-noetic-moveit-ros-perception/src/work/point_containment_filter/include -I$SRC_DIR/ros-noetic-moveit-ros-perception/src/work/pointcloud_octomap_up …
```

Fix use of std::bind

---

moveit_ros/move_group/include/moveit/move_group/move_group_context.h

Compile fails on Windows:
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DNOMINMAX -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"moveit_ros_move_group\" -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -Dmoveit_move_group_capabilities_base_EXPORTS -I%SRC_DIR%\ros-noetic-moveit-ros-move-group\src\work\include -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 -I%PREFIX%\Library\cmake\..\include -I%PREFIX%\Library\CMake\..\include -I%PREFIX%\Library\share\xmlrpcpp\cmake\..\..\..\include\xmlrpcpp /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD …

Fix missing include

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch

... from move_group.launch .
This was a clear bug introduced in 261a0c4c9041d6fd2df6e7cd7d1160321c047c8b .
MoveIt should not overwrite a previously uploaded robot description.
It should only provide it optionally in demo mode.
I just found this issue mentioned in https://github.com/ros-industrial/universal_robot/pull/538#issuecomment-930073835 ,
but nobody reported or addressed it back here since then. I guess @gavanderhoorn had too many other things to do or didn't take it to be an upstream issue. :)

do *not* automatically load robot description

---

moveit_commander/src/moveit_commander/move_group.py
moveit_commander/test/python_moveit_commander.py

Passing in a tuple of doubles triggers KeyError instead of TypeError.
This adds the appropriate test for the error and a integrates the fix from #3064 .
Fixes #3061 .

fix move_group_commander.go(tuple(...))

---

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

The Rviz MoveIt Trajectory Display uses wall time by default for state display timing. This leads to unexpected results when working with simulation time (e.g. gazebo, bag files) with less than real time. The simulated robot speed does not match the trajectory speed visualization since they follow different clocks.
This PR adds  an additional option to use simulation time instead of wall time named "Use Sim Time" (see screenshot).

Add option to use simulation time for rviz trajectory display

---

moveit_setup_assistant/src/collisions_updater.cpp

After debugging the issue in https://github.com/ros-planning/moveit/issues/3073 I found that the `CollisionPairLess` set comparison operator for `srdf::Model::CollisionPair`s somehow only checked uniqueness of `link1_` instead of both.
So, instead of making a set `{(a, b), (a, c), (a, d), (b, c), (b, d)}` it only allowed `{(a, b), (b, c)}`, which results in an incomplete allowed collision matrix. 

Fix collisions_updater set comparison

---

moveit_ros/perception/mesh_filter/CMakeLists.txt

long story short: it worked for Ubuntu's GLEW built before,
but not necessarily on other installs of GLEW.
It depends on the build system you use whether GLEW_LIBRARIES
is defined in the config or not, but the target should be there either way.

use GLEW linking target

---

moveit_core/collision_distance_field/src/collision_distance_field_types.cpp

For optimization-based trajectory planning, robot collision bodies are approximated with spheres. This is generally done by computing the bounding cylinder of every body and inserting spheres along the cylinder. This is done even in the case of a sphere collision body, even though the sphere decomposition of a sphere is trivial.
I fix this problem by adding a special case for sphere bodies in the sphere decomposition function.
Before:
After:

Added special case for sphere bodies in sphere decomposition

---

moveit_ros/benchmarks/scripts/moveit_benchmark_statistics.py

Count "-nan" and "-inf" as null value in the database.
In some configuration, the benchmarks can create "-nan" values in the log file. Those values where stored as string in the database, and caused issues when trying to plot them with `moveit_benchmark_statistics.py`.
This PR adds `-nan` and `-inf`, in addition with the already existing filter on `nan` and `inf`.
[Here is a .log file for testings](https://github.com/ros-planning/moveit/files/8206650/base_through_corridor_laloge-ThinkPad-P53_2022-03-08T09.35.44.083082.log.gz)

Filter more invalid values in moveit_benchmark_statistics.py

---

MIGRATION.md
moveit_ros/robot_interaction/src/robot_interaction.cpp

In the `panda_moveit_config` we observed that two interactive markers are created although corresponding end-effectors are associated to different JMGs. The reason is that marker creation doesn't consider the parent group as a required, but only as an optional criterium. This PR makes the parent group a required criterium.
|Before | After|
|--------------|------------------|
| ![image](https://user-images.githubusercontent.com/5376030/158656158-9e51e7a6-3ac2-44ab-a373-b54e3f005e6c.png) | ![image](https://user-images.githubusercontent.com/5376030/158656114-96d9b9ab-e547-4bc1-9c12-edd346e1ae05.png) |
Of course, multiple markers are still possible, if corresponding end-effectors are defined employing the same group:

Consider eef's parent group when creating eef markers

---

moveit_core/collision_detection/src/collision_matrix.cpp

When packaging the ACM as a ROS message, not all known (link) names were considered: `getAllEntryNames()` just returned names listed in `entries_`. Now, also consider names in `default_entries_`. Thus, corresponding entries were missing in the generated message.

ACM: Consider default entries as well when packing message

---

moveit_ros/robot_interaction/src/robot_interaction.cpp

The parent_group attribute is explicitly optional in MSA,
so a lot of configurations out there (including my robot :))
do not have these attributes set at all.
In this case, these end-effectors should be picked up automatically
wherever they are useful.
Fixup for 9271e6a2edbeed291b7c713f55000bbc59d37b9e
@rhaschke you dropped a few too many interactive markers. :)

always find end-effectors when parent_group is unset

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp

Rviz crashed when switching the move group while a motion was being executed through the plan and execute button.
The same issue was already fixed for the execute button (#1198) and is now also fixed for the plan and execute button.

Applied plan button fix to plan execute button

---

moveit_ros/benchmarks/examples/demo_panda.launch

Since #2888 / https://github.com/ros-planning/moveit_resources/pull/92 `planning_pipeline.launch.xml` loads into `pipeline` namespace by default, thus making an explicit specification of `ompl` redundant.
Fixes https://github.com/ros-planning/moveit/issues/3037.

Fix namespace of planning plugin for benchmarks examples

---

.github/workflows/ci.yaml
.github/workflows/downstream.rosinstall
.github/workflows/upstream.rosinstall

MoveIt GHA are broken for master-ci (running ROS Melodic), because `vcs` fails while importing the upstream workspace:
```
=== /home/runner/work/moveit/moveit/.work/upstream_ws/src/geometric_shapes (git) ===
Could not determine ref type of version: 
=== /home/runner/work/moveit/moveit/.work/upstream_ws/src/moveit_msgs (git) ===
Could not determine ref type of version: 
=== /home/runner/work/moveit/moveit/.work/upstream_ws/src/srdfdom (git) ===
Could not determine ref type of version: 
```
The `--debug` output of `vcs` isn't very helpful either.
Performing exactly the same actions locally in the very same docker container (i.e. installing vcstool and importing), yields no problems! Any hints are very welcome, @dirk-thomas, @tylerjw.

CI failure for master-ci due to broken vcs

---

moveit_commander/src/moveit_commander/move_group.py

We just don't have this function and it's not entirely trivial to implement it.
This sneaked in with c33e98f8c147b48805033f7ae5383b0225bb790d

remove broken branch from python

---

moveit_core/constraint_samplers/CMakeLists.txt
moveit_core/constraint_samplers/include/moveit/constraint_samplers/default_constraint_samplers.h
moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/constraint_samplers/test/constraint_samplers.test
moveit_core/constraint_samplers/test/test_constraint_samplers.cpp
moveit_core/package.xml

This PR adds the ability to specify a seed for constraint samplers through the parameter server, which would be useful in deterministic testing and benchmarking of these objects.

Constraint samplers with seed

---

moveit_core/constraint_samplers/test/test_constraint_samplers.cpp

Follow-up of https://github.com/ros-planning/moveit/pull/3112. This removes the flakiness from the constraint sampler test by adding another seed.

Remove flakiness from constraint samplers test.

---

.github/workflows/ci.yaml
.github/workflows/downstream.rosinstall
.github/workflows/upstream.rosinstall

Partially reverts #3126. It suffices to define git's `safe.directory`. See https://github.com/ros-planning/moveit/pull/3126#issuecomment-1126183675

CI: Restore original version names

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

This fixes a bug we had while executing an MTC task where having two different planning scenes diffs that add a collision object to the scene, the first commit is just a test that trigger the bug, the second commit sets `robot_state.is_diff` to true when calling `getPlanningSceneDiffMsg` which prevent [conversions.cpp#L369-L372](https://github.com/ros-planning/moveit/blob/master/moveit_core/robot_state/src/conversions.cpp#L369-L372) from deleting the aco from the robot state when applying the diffs, but now when calling [PlanningScene::setCurrentState](https://github.com/ros-planning/moveit/blob/master/moveit_core/planning_scene/src/planning_scene.cpp#L1146) while detaching an object that object is staying in the scene so the last commit fixes it by explicitly removing the aco in the case …

Fix bug in applying planning scene diffs that have attached collision objects

---

moveit_ros/move_group/src/move_group.cpp
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch

I noticed this was disabled when using the `TrajectoryMonitor` feature of the `MoveGroup` action which returns the actually executed trajectory.
With the additional flag the recorded trajectory would not include velocities because they were not copied internally.

move_group can optionally monitor dynamics

---

moveit_core/robot_model/src/planar_joint_model.cpp

Backport from https://github.com/ros-planning/moveit2/pull/1353

Fix PlanarJointModel::satisfiesPositionBounds

---

moveit_core/constraint_samplers/src/union_constraint_sampler.cpp
moveit_ros/planning_interface/test/CMakeLists.txt
moveit_ros/planning_interface/test/dual_arm_robot_state_update.py
moveit_ros/planning_interface/test/dual_arm_robot_state_update.test

I spent too many hours debugging this issue #3082 with not much progress.
My best guess as to the source of the issue is that the `Robot State` gets `dirty` (or just not updated as it used to), so the Sampler does not even bother trying to plan. I don't know why though.
Following @felixvd idea, I created a simple test case. I tested it on the `melodic-devel` branch and the master's branch commit [95ab9e](https://github.com/ros-planning/moveit/commit/95ab9eef58b552fe366f0513487a6f6db5a3e71e), and the test passes with no problem. Then in the `master/noetic-devel` branch, it fails. 
Now, I want to ask, is there an efficient way to use this test case to pinpoint the offending commit?
The test case depends on the [dual arm demo](https://github.com/cambel/dual_arm_demo) environment proposed by …

Add and fix dual arm test

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp

I was having a build error on my host os: Arch Linux x86_64 when trying to build the moveit setup assistant, and submitted to the below repo to fix an issue
https://github.com/ros-noetic-arch/ros-noetic-moveit-setup-assistant/issues/3  (build log is also present on this issue)
Originally, I made a patch to fix this build issue in trying to build this component as part of an AUR package, and I was requested to further submit a pull request here.

[moveit_setup_assistant] Fixes build error: "cannot convert ‘const YAML::Node’ to ‘boo ’ in initialization"

---

MIGRATION.md
moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

Part of #3156.
The idea is to first clean up the unused code of the API before adding new futures to handle the simultaneous execution of trajectories.

Clean up TrajectoryExecutionManager API: remove unused code

---

moveit_commander/src/moveit_commander/move_group.py
moveit_commander/test/python_moveit_commander.py
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

- Add tests of `moveit_commander.set_joint_value_target` with `JointState` argument
- Add test of `moveit_commander.set_joint_value_target` with incomplete `JointState` argument
Fixes #3186 

Test `moveit_commander.set_joint_value_target` with JointState argument

---

.github/workflows/ci.yaml

Unfortunately, CI is broken again:
- [gcc complains about `unused-but-set-parameter` in OGRE code](https://github.com/ros-planning/moveit/runs/8141833958?check_suite_focus=true)
- [clang creates hundreds of warnings cluttering the view for relevant issues](https://github.com/ros-planning/moveit/runs/8141834092?check_suite_focus=true)
- [`eigenpy` triggers linker issues](https://github.com/ros/rosdistro/pull/34283#issuecomment-1234806721)
This PR addresses the first two items, suppressing some compiler warnings.

Fix CI: Relax compiler warnings

---

.docker/ci-testing/Dockerfile
moveit_setup_assistant/src/widgets/start_screen_widget.cpp
moveit_setup_assistant/src/widgets/start_screen_widget.h

This is a (partial) backport of #3013 from noetic-devel. Running xacro for srdf loading in MSA is an important feature for `panda_moveit_config`.

Pass xacro_args to both, urdf and srdf loading

---

moveit_planners/trajopt/CMakeLists.txt
moveit_planners/trajopt/src/problem_description.cpp
moveit_planners/trajopt/src/trajopt_interface.cpp

fixes #2933 
This updates the trajopt motion planner plugin to the current trajopt API. It does not in any way improve or extend the functionality, so please be aware that it includes no collision checks afaik!

Trajopt update to current API

---

moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
moveit_core/robot_state/src/cartesian_interpolator.cpp
moveit_core/robot_state/test/test_cartesian_interpolator.cpp
moveit_core/robot_state/test/test_cartesian_interpolator.test
moveit_core/utils/include/moveit/utils/eigen_test_utils.h
moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_core/utils/src/robot_model_test_utils.cpp
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

So far, Cartesian interpolation only considered _link frames_ to move along a straight-line. This PR augments this to arbitrary frames by considering a configurable offset to the link frame. Thus, now the frame resulting from link * offset should move along a straight line towards the target. Obviously, this is only relevant for rotational motions - a fixed offset for linear motions doesn't change the resulting motion. For example, the new implementation [allows for circular motions around a non-link origin](https://github.com/ros-planning/moveit_task_constructor/pull/380).

Improve Cartesian interpolation

---

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/collisions_updater.cpp
moveit_setup_assistant/src/tools/collision_linear_model.cpp
moveit_setup_assistant/src/tools/collision_linear_model.h
moveit_setup_assistant/src/tools/collision_matrix_model.cpp
moveit_setup_assistant/src/tools/collision_matrix_model.h
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/default_collisions_widget.cpp
moveit_setup_assistant/src/widgets/default_collisions_widget.h
moveit_setup_assistant/src/widgets/start_screen_widget.cpp

As a follow-up to #2938, this PR aims to allow for editing the extended ACM in MSA, i.e. defining default-collision links, re-enabling and disabling collision pairs.
For now, the CollisionMatrixModel directly operates on the `SRDFWriter`'s members. While that's the native data structure holding the relevant info, accessing any info requires several `string` compares. In the past, the `reason` strings were mapped onto enums internally and a map (`LinkPairMap`) was used instead of vectors.
However, I didn't notice a dramatic slowdown with a robot of ca. 20 links. So, maybe it's not worth the effort...

MSA: extended ACM editing

---

moveit_planners/trajopt/include/trajopt_interface/trajopt_planning_context.h
moveit_planners/trajopt/src/problem_description.cpp
moveit_planners/trajopt/src/trajopt_interface.cpp
moveit_planners/trajopt/src/trajopt_planner_manager.cpp
moveit_planners/trajopt/src/trajopt_planning_context.cpp

These are tiny fixes to the trajopt plugin that allow it to work in obstacle-free cases when direct joint interpolation is a valid solution.

Trajopt fixes

---

moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp

When calling the PlanAndExcute action, there was a shortcut avoiding planning (and execution) at all when all goal constraints were already met. However, this check also succeeded when there was an error, e.g. resolving link names. As proper link resolution might require some planning request adapters to be executed, e.g. ResolveConstraintFrames, we should not skip planning.
Note, calling the PlanOnly action, didn't have this shortcut as well, resulting in inconsistent behavior.
I just decided to remove the shortcut check completely.
Fixes #3222

Drop shortcut avoiding planning when all constraints are already met

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/gazebo.launch

Otherwise tf is missing in Gazebo by default.
Triple empty line fixed.

Publish tf in gazebo

---

.github/workflows/ci.yaml
.github/workflows/format.yaml
.github/workflows/prerelease.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

moveit_core/planning_request_adapter/src/planning_request_adapter.cpp
moveit_core/utils/CMakeLists.txt
moveit_core/utils/include/moveit/utils/moveit_error_code.h
moveit_core/utils/src/moveit_error_code.cpp
moveit_ros/move_group/src/move_group_capability.cpp
moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_execution.h
moveit_ros/planning/plan_execution/src/plan_execution.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_collision.cpp
moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_path_constraints.cpp

This is an alternative implementation of #3258, without the need to change the return types of all planning request adapters.
This yields the following output as originally intended:
```
[ INFO] ros.moveit_ros_planning: Start state appears to be in collision with respect to group panda_manipulator
[ WARN] ros.moveit_ros_planning: Unable to find a valid state nearby the start state (using jiggle fraction of 0.050000 and 100 sampling attempts).
[DEBUG] ros.moveit_core.planning_request_adapter: Fix Start State In Collision: -10
[DEBUG] ros.moveit_core.planning_request_adapter: Fix Start State Bounds: -10
[DEBUG] ros.moveit_core.planning_request_adapter: Fix Workspace Bounds: -10
[DEBUG] ros.moveit_core.planning_request_adapter: Resolve constraint frames to robot links: -10
[DEBUG] …
```

Short circuit planning adapters

---

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp

This is a follow-up to #3257, cleaning up the code of parallel planning. This PR factors out common code into a lambda function and fixes the evaluation of the planning result (keeping the first successful plan).

Improve processing of multiple planning attempts

---

moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/robot_state/src/robot_state.cpp

Reviewing #3276, I noticed that the return value of `ikCallbackFnAdapter()` wasn't propagated through the lambda.
This issue was introduced in #3106.
As the [return value of this `IKCallbackFn` is actually never used](https://github.com/ros-planning/moveit/pull/3276#pullrequestreview-1190740340), it would be even cleaner to drop the boolean result and just rely on the error_code. Having two failure notification mechanisms, obviously results in confusion. Any thoughts?

Fix ik_callback_fn: propagate return value

---

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/chomp_planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ompl_planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/stomp_planning_pipeline.launch.xml
moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajopt_planning_pipeline.launch.xml

Capabilities are _global_ to the `move_group` node and not specific to pipleline configs. As the latter ones load their parameters into a namespace, e.g. `/move_group/planning_pipelines/ompl/*`, loading a capability as suggested by the comments, doesn't have any effect.

Remove capability declarations from pipeline configs

---

moveit_commander/src/moveit_commander/planning_scene_interface.py
moveit_commander/test/python_moveit_commander_ros_namespace.py
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/robot_state.cpp
moveit_planners/pilz_industrial_motion_planner/test/python_move_group_planning.py
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp

Fixes #3207, i.e.
1. attached objects missing in planning requests triggered from rviz, because automatic query state updates were only performed if the state was visible.
2. disabling execution if the attached bodies of the current RobotState and don't match those of the plan's start state.
Unfortunately, the trajectory execution [service](http://docs.ros.org/en/api/moveit_msgs/html/srv/ExecuteKnownTrajectory.html) and [action](http://docs.ros.org/en/api/moveit_msgs/html/action/ExecuteTrajectory.html) do not receive the plan's start state (but only the [`RobotTrajectory`](http://docs.ros.org/en/api/moveit_msgs/html/msg/RobotTrajectory.html)). Thus we cannot reject an invalid plan at that level (which would be the correct one in my opinion).

MotionPlanningDisplay: Fix RobotState inconsistency

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui

While working on #3263, I noticed several issues with planning scene editing, which I attempt to address here:
Note: interactive marker handles are shown for the _current_ item only
- [joint state updates are only considered, if the corresponding planning group was never selected before](https://github.com/ros-planning/moveit/blob/fe0c182a57b79f970eaca26c479e96d857242505/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp#L1216-L1234).
This partially makes sense, because we don't want a goal query state be overridden by actual robot movements.
However, [currently, updates are disabled as soon as the planning group was selected](https://github.com/ros-planning/moveit/blob/fe0c182a57b79f970eaca26c479e96d857242505/moveit_ros/visualization/motion_planning_rviz_ …

MotionPlanningDisplay: Fix PlanningScene editing

---

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
moveit_setup_assistant/src/widgets/simulation_widget.cpp
moveit_setup_assistant/src/widgets/simulation_widget.h

`config_data_->save_gazebo_urdf_` is True if and only if `config_data_->changes` has the `MoveItConfigData::SIMULATION` bit set. Thus we can replace the former with the latter check.
Fixes #3280

MSA: Cleanup SimulationWidget

---

README.md
moveit_core/version/CMakeLists.txt
moveit_core/version/version.cmake

Follow up on #2793:
Automatically recognize a devel build by comparing package.xml's version with available git tags. If they don't match, assume a devel version, increase the patch number and append `-devel`, e.g. yielding 1.1.10-devel instead of 1.1.9.
Note that this adapted version number is only reported in `version.h` and thus via `moveit_version`.
Libraries still get the old version number listed in `package.xml`. This was a deliberative decision: During development, it is convenient to (re)build individual libs/packages only. These should still have the same library version number to be found by existing downstream packages.

version.h: automatically bump patch number for devel builds

---

moveit_commander/src/moveit_commander/planning_scene_interface.py
moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/render_shapes.cpp

This fixes some more issues pointed out in #3291 (see individual commit messages for details).
Example of cone visualization:
|old mesh | new cone|
|--- | ---|
|![image](https://user-images.githubusercontent.com/5376030/207883804-143da405-19aa-42ec-b830-2ce1233ff2e1.png) | ![image](https://user-images.githubusercontent.com/5376030/207883857-c40642db-6e2f-4722-955b-c36b3e35b7b5.png) |
Plane example:
Shapes created programmatically via python:

Fix some consistency issues in PlanningScene handling

---

moveit_commander/src/moveit_commander/move_group.py
moveit_commander/test/python_moveit_commander.py

Fixes #2869
Just handle string and Pose arguments and rely on `MoveGroupCommander.set_joint_value_target()` to handle various joint-space arguments.

Fix MoveGroupCommander.plan() and add corresponding unit tests

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h

Add missing #include <unordered_map>

---

moveit_core/CMakeLists.txt

catkin was not made for cmake target dependencies.
We do the same with fcl right above, but when porting/merging ruckig nobody cared...
FTR: ruckig does not have any `INTERFACE_LINK_LIBRARIES` and adding them for good measures in case it changes sets the variable to `ruckig_INTERFACE_LINK_LIBRARIES-NOT-FOUND` (breaking the build).
Fixes #3310 .

fix ruckig dependency with catkin

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

While working on #3315, I stumbled over this weird API of `runRuckigInBatches()`.
@simonschmeisser, why does it require a `num_waypoints` parameter? This number can be determined via `trajectory.getWayPointCount()`, can't it?

runRuckigInBatches: drop num_waypoints parameters

---

moveit_ros/moveit_servo/launch/cpp_interface_example.launch
moveit_ros/moveit_servo/launch/pose_tracking_example.launch
moveit_ros/moveit_servo/launch/spacenav_cpp.launch
moveit_ros/moveit_servo/launch/spacenav_teleop_tools.launch
moveit_ros/moveit_servo/src/pose_tracking.cpp
moveit_ros/moveit_servo/src/servo.cpp
moveit_ros/moveit_servo/test/basic_servo_tests.test
moveit_ros/moveit_servo/test/pose_tracking_test.test
moveit_ros/moveit_servo/test/servo_cpp_interface_test.test

When trying to generalize moveit_servo's launch scripts to handle user-specific config files, I noted a weird mechanism to load these parameters: 
First, a private parameter `~parameter_ns` was declared and its value was actually used as a namespace to load all parameters into. Instead of this error-prone and indirect scheme, I suggest loading these parameters directly into the private namespace of the node. I don't see a need to share these parameters across different server instances.
If one really wants to load those parameters somewhere else first, one can simply start the node with the corresponding namespace as its name.
The original purpose of this PR was to add an argument `config` to specify a .yaml file with the desired parameters (instead of locking it to …

Simplify servo config + Reusable launch scripts

---

moveit_ros/planning/moveit_cpp/CMakeLists.txt
moveit_ros/planning/trajectory_execution_manager/CMakeLists.txt

It is only needed at *runtime* of the ros tests and there's no need to find_package.
catkin_lint is happy without these lines.

drop unnecessary cmake dependency on moveit_resources

---

MIGRATION.md
moveit_commander/src/moveit_commander/interpreter.py
moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

- improve documentation of all MGI::get* functions for joint names
- expose get_variables in MGI python wrapper
- add "group_state" command to commander
- rename MGI::getJointNames() to getVariableNames()
The API-incompatible method rename can be dropped if requested, but it took me a while to figure out which method is correct when implementing `group_state`, so I believe refactoring makes a lot of sense.

Disentangle joint name methods and add group_state to commander

---

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

This allows to hide some parts of the robot in the trail mode by applying the general link visibility to the trail as well.
It is currently only applied on new incoming trajectories but adding some signal-slots for live update would be possible as well of course

TrajectoryDisplay: hide links in trail

---

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp

zero-duration trajectories cause the default ROS joint trajectory controller to [fail](https://github.com/ros-planning/moveit_task_constructor/issues/433#issuecomment-1456178725): 
`Dropping all 1 trajectory point(s), as they occur before the current time. Last point is 0.000000s in the past.`
In contrast to https://github.com/ros-planning/moveit_task_constructor/pull/438, I looked for the _latest_ possibility to skip those trajectories. I explicitly decided not to prune in `RobotTrajectory` message generation already, but only just before execution.

Skip executing zero-duration trajectories

---

moveit_ros/move_group/src/move_group.cpp
moveit_ros/move_group/src/move_group_context.cpp
moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h
moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp
moveit_ros/planning/trajectory_execution_manager/test/test_execution_manager.cpp

- Fix `const` member accessors. They should return a `ConstPtr` instead of a `const Ptr&`!
- Fix SEVERE ClassLoader warning on destruction of `MoveItCpp`:
- PSM was released before copy of its RobotModel -> removed extra RobotModel copy
- `clearContents()` was broken:
- resets in wrong order: psm_ should be last
- trajectory_execution_manager_ was missing
I suggest to omit `clearContents()` and just rely on the (correct) ordering of member variables.
While this is not explicit, we ensure that we don't miss any newly added member variable.

Fix MoveItCpp issues

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

Currently, if a `PlanningScene` message is published on the `monitoried_planning_scene` topic with an empty `msg.world.octomap.octomap.data` field, the octomap is skipped altogether in if it is a `msg.is_diff` is True ([source](https://github.com/ros-planning/moveit/blob/master/moveit_core/planning_scene/src/planning_scene.cpp#L1292)). I think perhaps an empty `data` field is interpreted as the octomap field not being filled. But this makes it impossible to clear the octomap by sending an empty octomap message (for example via the "Clear octomap" button in the MotionPlanning panel in RViz).
This PR sets `octomap.id` to `"empty"` if the octomap is empty (this string can be anything except an empty string), and checks `octomap.id.empty()` instead of `octomap.data.empty()` to see if the …

Improve handling of empty octomap messages and "clear octomap" actions

---

moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h
moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp

Debugging #3380, I noticed several other issues than the main culprit which was already handled in #3134 (but not yet merged :disappointed:):
- fix a memory leak, not deleting octomap's scene nodes until the main PSD's node is destroyed
- react to changes of octomap rendering

Fix octomap display

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp

Hi, I am an undergad student working on my first PR to moveit. From the list of minor issues I found [here](https://github.com/ros-planning/moveit/issues/2741), I am working on the issue 14.
>In the RViz display, the property "Planning Group" under "Planning Request" allows to type in a custom string and goes blank if the string is not a valid group name. I'd propose to simply disallow custom strings here and turn it into a simple drop-down list
The property "planning group" under "planning request" in the display menu under Motion Planning Plugin is of the type `rviz::EditableEnumProperty`, which lets us enter any custom string. I changed this type to `rviz::EnumProperty` and accordingly included appropriate header files in the required files.`
Video …

Disallow custom string for planning group property in RViz Display

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h
moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

When smoothing a trajectory, sometimes it's not possible to avoid overshoot. An example is:
current state is (position = 0, velocity = 0), target state is (position = 1, velocity = -1)
However, the overshoot can be reduced by extending the segment duration, thereby reducing the velocity at the goal state. Here's a graphical explanation.

Mitigate Ruckig overshoot

---

moveit_ros/perception/mesh_filter/src/depth_self_filter_nodelet.cpp

This is to solve the issue  #3386. The cause of the issue is possibly due to incorrect handling of different encodings of a depth image. The original code assumed the depth image to be encoded in `32FC1` while the depth image returned by Realsense D415 is encoded in `16UC1`.  This issue already existed in the code before the change made to solve #3371.
By using the predefined filter base behavior for `GL_UNSIGNED_SHORT`, the depth image can be properly filtered.
However I don't have other RGBD cameras at hand so I can't know if there is any other encoding used by other cameras, thus I only considered `16UC1` case separately and used the same implementation for all other possible encodings. 
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything …

handling different encodings of depth images correctly

---

moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp

We want the ability to set custom joint jerk limits for the Ruckig smoother, but in MoveIt1, the RobotModel does not contain that info. My feeling is, there probably isn't a desire to create a large API-breaking PR in MoveIt1 for adding a jerk limit. Here's what adding jerk to the RobotModel would look like, from MoveIt2:  https://github.com/ros-planning/moveit2/pull/683
So, I made this small, simple PR to add a ROS jerk limit parameter.
I've been testing like this:
1. Add Ruckig jerk params to `panda_moveit_config/launch/demo.launch`
- `<param name="/ruckig/panda_joint1/jerk_limit" type="double" value="300.0" />`  (and so on)
2. Add the Ruckig smoothing adapter to the top of the list at ompl_planning_pipeline.launch.xml
- default="default_planner_request_adapters/AddRuckigTrajectorySmooth …

Check for a Ruckig jerk limit parameter

---

moveit_commander/src/moveit_commander/move_group.py

ChatGPT thought this would be valid and I agree that this simpler call makes sense. :)
Additionally the argument was named wrongly as it implies that the MoveGroupInterface::Plan class has a corresponding ROS message one might pass as argument.
Small quality of life improvement.

MoveGroupCommander.execute can take JointTrajectory argument

---

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp

- This addresses the use-case where multiple drivers publish joint
state messages. Of course these do not give any guarantees on the order of
incoming joint states and can lead to the CSM generating states
with non-incremental time stamps, thus leading to TrajectoryMonitor recording
trajectories with non-incremental waypoints.
A different fix for this might rework the CSM altogether to allow configuring what policy should be employed to synchronize between the different joint publishers, but I believe this approach to use the latest timestamp of anything received is sufficient for the class.
- The downside of the simple fix in the first commit is that the monitor does not work well with
looping rosbags anymore as the time resets. That's why I added a second commit with minor overhead to …

CSM: do not jump back in time

---

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp

This is a 2-line bug fix for this test failure:
```
/home/andy/ws_moveit/src/moveit/moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp:395: Failure
The difference between trajectory.getAcceleration(time)[0] and max_accelerations[0] is 4, which exceeds 1e-3, where
trajectory.getAcceleration(time)[0] evaluates to 32,
max_accelerations[0] evaluates to 28, and
1e-3 evaluates to 0.001.
Time: 0.01
/home/andy/ws_moveit/src/moveit/moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp:395: Failure
The difference between trajectory.getAcceleration(time)[0] and max_accelerations[0] is 28, which exceeds 1e-3, where
trajectory.getAcceleration(time)[0] evaluates to 0,
max_accelerations[0] evaluates to 28, and
1e-3 evaluates to 0.001.
Time: …
```

Fix: TOTG can return vels/accels greater than the limits

---

moveit_core/robot_model/include/moveit/robot_model/joint_model.h
moveit_core/robot_model/src/joint_model.cpp

We already have versions for satisfiesPositionBounds() and satisfiesVelocityBounds(), why not Acceleration too?

Add JointModel::satisfiesAccelerationBounds()

---

moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h
moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/NearestNeighborsGNAT.h
moveit_setup_assistant/src/tools/collision_linear_model.cpp
moveit_setup_assistant/src/widgets/simulation_widget.cpp

- drop implicit CC definition
- avoid deprecated std::random_shuffle
- Fix qt5 deprecation
- do not use deprecated QVariant::operator<
The first four should be rather uncontroversial.
@rhaschke, please have a look at the last one, I expect you don't want to merge this as-is for your generalized code?

Address deprecation warnings in Debian bookworm

---

moveit_core/robot_model/CMakeLists.txt
moveit_core/robot_model/include/moveit/robot_model/planar_joint_model.h
moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_model/src/planar_joint_model.cpp
moveit_core/robot_model/src/robot_model.cpp
moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_core/utils/src/robot_model_test_utils.cpp
moveit_planners/ompl/ompl_interface/test/test_state_space.cpp

This PR is a backport of https://github.com/ros-planning/moveit2/pull/390 that implements a differential drive model for planar joints.
After backporting JointProperties into srdfdom for ROS1 (merged in https://github.com/ros-planning/srdfdom/pull/109), we can now specify a planar joint to have a `motion_model` property, which can be set to `holonomic` or `diff_drive` with:
```
<virtual_joint name="position" type="planar" parent_frame="odom" child_link="base_link"/>
<joint_property joint_name="position" property_name="motion_model" value="diff_drive" />
<joint_property joint_name="position" property_name="min_translational_distance" value="0.01" />
```
This PR is a backport of differential drive kinematics from MoveIt2 that are used when the planar joint is set to `diff_drive`.
The …

Backport: Differential Drive for Planar Joints from Moveit2

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp

Fixes #3401
All MotionPlanningDisplays use the same fixed namespace for `RobotInteraction`:
https://github.com/ros-planning/moveit/blob/6c5203338bf305e1a9303839ded3afebee423c78/moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp#L1146
This causes ambiguities when resolving interactive markers for the same robot model.
My proposal is to prepend the (typically empty) parent namespace of the `robot_description` parameter.
In this fashion, most existing code accessing the interactive marker topics too, will continue to work.

MPD: Use different namespaces for RobotInteraction

---

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
moveit_setup_assistant/src/tools/moveit_config_data.cpp
moveit_setup_assistant/src/widgets/group_edit_widget.cpp
moveit_setup_assistant/src/widgets/group_edit_widget.h
moveit_setup_assistant/src/widgets/planning_groups_widget.cpp

MoveIt often fails to plan a valid path because goal joint position, goal position, and goal orientation tolerances are hard-coded as arbitrary/magic numbers. Other values in the same Move Group interface implementation are easily configurable.
These changes allow overriding the default (hard-coded) values of `0.1 millimeter` and `0.1 degree` in `kinematics.yaml` to relax the tolerances for debugging inverse kinematics or when using low-fidelity hardware such as potentiometers which jump by several degrees due to digital noise while reading arm joint positions.
The values made configurable by this pull request are:
* `moveit::planning_interface::MoveGroupInterface::MoveGroupInterfaceImpl::goal_joint_tolerance_`
* Read from `goal_joint_tolerance` value in `kinematics.yaml` under the joint …

Read goal tolerances from kinematics configuration

---

moveit_core/utils/include/moveit/utils/xmlrpc_casts.h
moveit_core/utils/src/xmlrpc_casts.cpp

This was broken upstream before, but seems to be fixed now (https://github.com/ros/ros_comm/pull/1978)

Make XmlRpcValue arguments const references

---

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
moveit_core/robot_model/src/joint_model_group.cpp
moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_torque_limit_parameterization.h
moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
moveit_core/trajectory_processing/src/iterative_torque_limit_parameterization.cpp
moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
moveit_core/trajectory_processing/test/test_iterative_torque_limit_parameterization.cpp
moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp

This fixes several issues introduced in #3412. Replaces #3426.
Apart from a lot of code redundancy introduced in #3412, this PR also fixes a severe bug introduced there:
Because the TOTG algorithm considers all group variables (including mimic joints), the lookup of velocity and acceleration limits cannot be restricted to active joint variables only. Differently sized vectors might lead to segfaults!
To be honest, I am somewhat disappointed about the poor quality of PRs and reviews from approved maintainers in the last few months. Please improve!

Fixup TOTG

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_model/src/robot_model.cpp
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/cartesian_interpolator.cpp
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp
moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp
moveit_ros/planning_interface/test/subframes_test.cpp

So far, `setFromIK` only accepted target (link) frames that were rigidly connected to a solver's tip frame. This, for example, excluded the fingertip of an actuated gripper, because that would be separated by an active joint from the arm's tooltip. However, as long as this joint is not part of the JMG, the corresponding transform can be considered as fixed as well.
This PR generalizes the functions `getRigidlyConnectedParentLinkModel()` in RobotState and RobotModel to receive an optional JMG pointer. If present, only (active) joints from that group are considered non-fixed. This PR also enables subframe support for `setFromIK` - simply by using `getRigidlyConnectedParentLinkModel()`, which already supported that.
There is one drawback of this approach: A repeated application of …

Generalize RobotState::setFromIK()

---

moveit_core/planning_scene/src/planning_scene.cpp

Old-style code, not specifying a pose for a CollisionObject is handled specially (using the only shape's pose for the object).
Thus, there is no need to apply poseMsgToEigen() on that empty pose, which would trigger a warning.

Silent "empty quaternion" warning from poseMsgToEigen()

---

moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/test_planar_joint_jacobian.cpp
moveit_core/robot_state/test/test_planar_joint_jacobian.test

While working on [this](https://github.com/ros-planning/moveit/issues/3436) I think I found a bug in Jacobian calculation for planar joints. 
The fix is simple, in lines performing `joint_axis` calculation, instead of `joint_transform`, `joint_transform.linear()` should be used, like for the other joint types. 
I've written a simple test, I don't think it needs to be merged, but it demonstrates the bug so you can check it.
For the example in the test, current `getJacobian` implementation calculates the `joint_axis` of the first joint to be [1, 0, 0]^T when q[0] = 0, and [11, 0, 0]^T when q[0] = 10, which results in different `Jacobian` values.

Fix planar joint Jacobian bug

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp

This fixes typos for the parameters `frontier_threshold` and `frontier_node_ratio` in `ompl_planning.yaml` for OMPL's TRRT and BiTRRT planners.

OMPL: fix TRRT parameters names

---

moveit_core/robot_model/include/moveit/robot_model/robot_model.h
moveit_core/robot_model/src/robot_model.cpp
moveit_core/robot_state/include/moveit/robot_state/attached_body.h
moveit_core/robot_state/include/moveit/robot_state/robot_state.h
moveit_core/robot_state/src/cartesian_interpolator.cpp
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp
moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp

The implementation of #3388 relied on an up-to-date RobotState to compute the relative transform in `getRigidlyConnectedParentLinkModel()`. However, as these transforms are all fixed, we are able to compute the transform from those fixed relative transforms only, w/o the need for updated global transforms.
Fixes #3467.

Fixup #3388

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp

This partially reverts d98a529a28ffe9bc283abe70828388a5b5b48c59, however, still updates the query states themselves.

Avoid costly updates of RobotInteraction on query state changes if they are not shown

---

moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py

Fixed typo in line 430 of create_ikfast_moveit_plugin.py. Changed "planing_group_name" to "planning_group_name"
Terminal message fixed: 
'Namespace' object has no attribute "planing_group_name'
When trying to run `create_ikfast_moveit_plugin.py`, I received a terminal error message:
```
Failed to update MoveIt Package:
'Namespace' object has no attribute 'planing_group_name'
```
I looked into the .py and noticed it was a recent typo on line 430: planing to planning
I tested my fix, and the error went away. Created a pull request.
- [n/a] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [n/a] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [n/a] Document API changes …

Fix typo in create_ikfast_moveit_plugin.py, line 430

---

moveit_core/CMakeLists.txt
moveit_core/constraint_samplers/CMakeLists.txt
moveit_core/package.xml

Since https://github.com/ros-planning/moveit/commit/6c5203338bf305e1a9303839ded3afebee423c78, `angles.h` is included in `moveit_core/robot_model/src/planar_joint_model.cpp`, and therefore `angles` must be more than a `test_depend`. Since the C++ `angles` library is header only, I made it a `build_depend`.

moveit_core: make angles a build_depend rather than a test_depend

---

moveit_core/planning_request_adapter/CMakeLists.txt
moveit_core/planning_request_adapter/src/planning_request_adapter.cpp
moveit_core/planning_request_adapter/test/test_planning_request_adapter_chain.cpp

When merging the `added_path_index` for the different planning request adapters, the `PlanningRequestAdapterChain` was adding them in the wrong order, causing wrong incrementation of the indices.
Closes #3463.

Fix the added path index vector merge in PlanningRequestAdapterChain

---

moveit_kinematics/test/test_ikfast_plugins.sh

The default was switched to `ros2` at some point.
Found due to these lines in CI:
```
[build] Found 7 packages in 0.0 seconds.
[build] Updating package table.
[build] Warning: Skipping package `moveit_resources_panda_description` because it has an unsupported package build type: `ament_cmake`
[build] Note: Available build types:
[build]  - `catkin`
[build]  - `cmake`
Starting >>> catkin_tools_prebuild
Finished <<< catkin_tools_prebuild                [ 2.4 seconds ]
[build] Summary: All 1 packages succeeded!
```

use correct resources branch in ikfast test

---

moveit_core/collision_detection/src/collision_octomap_filter.cpp
moveit_core/distance_field/test/test_distance_field.cpp
moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp
moveit_setup_assistant/src/widgets/robot_poses_widget.cpp

clang 16 warns about them and builds with Werror fail.

[clang16] do not define unused variables

---

moveit_core/collision_distance_field/src/collision_distance_field_types.cpp
moveit_core/collision_distance_field/src/collision_env_distance_field.cpp
moveit_core/collision_distance_field/test/test_collision_distance_field.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp
moveit_core/robot_state/test/test_kinematic_complex.cpp
moveit_core/utils/include/moveit/utils/robot_model_test_utils.h
moveit_core/utils/src/robot_model_test_utils.cpp
moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
moveit_ros/robot_interaction/test/locked_robot_state_test.cpp

Addresses a rather small inconsistency I pointed out [here](https://github.com/ros-planning/moveit/pull/3504#pullrequestreview-1657191555).
Two more helper patches are included to make the test nicer and the API slightly better.

consider distance field padding for spheres

---

moveit_core/robot_model/src/planar_joint_model.cpp

In my previous PR #3359, where I backported differential drive from MoveIt2, I noted in the "Open Issues with Differential Drive Planning in MoveIt" section that:
> When moveit_core is built as Debug, if the goal position of the base is rotated using the Rviz gui, the ASSERT_ISOMETRY [here](https://github.com/ros-planning/moveit/blob/326e9b5fe76bdf856f9c4a2be56ce7e136651ff2/moveit_core/robot_model/src/planar_joint_model.cpp#L228) fails and crashes the program. Despite this issue, when we build the package as Release, no error is reported and things seem to work correctly even if the assertion condition is not met.
In further testing, I also noticed that RRT* was segfaulting intermittently after generating 100 or so plans. It turns out these two issues are interconnected.
- In a rare case …

Fix segfault when planning with differential drive planar joints

---

moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp

Should fix #3035 (partially) and ros-planning/moveit_task_constructor/issues/411 by transforming the goal pose (CIRC, LIN and PTP) and the center point (CIRC) wrt. the planning frame.
Only computes the IK when there is a goal pose constraint. Removed unused `frame_id` initialisation. Transforms the goal pose for `CIRC`, `LIN` and `PTP` wrt. the planning frame. Transform the center point for `CIRC` wrt. the planning frame.
Rebased on #3519.
**TODO**
---
**This post has been edited prior discussion with the maintainers**

Tranform Pilz goal pose and center point wrt. the planning frame

---

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_functions.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator.h
moveit_planners/pilz_industrial_motion_planner/src/trajectory_blender_transition_window.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp
moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_blender_transition_window.cpp
moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_functions.cpp

Implement https://github.com/ros-planning/moveit/pull/3519#issuecomment-1804927996:
Trajectory generation needs to use the actual link_name's (and its offset's) start and goal pose in order to realize a straigh-line motion. We must not back-project the offset to the associated robot link. Instead, we need to consider the offset during computation of the IK. I implemented this for the CartesianInterpolator in #3197.
Unfortunately, the unit tests don't cover those cases yet - they only consider the final goal pose, but don't check the path in between :disappointed: 
https://github.com/ros-planning/moveit/assets/5376030/ae0bf3e2-3c2f-496c-8bc3-1d5b152c4f14
https://github.com/ros-planning/moveit/assets/5376030/ba6bde21-895f-4c26-930a-221ad0a00f12

Fix Pilz planner: consider link_name offset during IK computation

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame_joints_widget.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame_joints.ui

Issue #3513 Add a checkbox to display joints in radians
Need help to connect it to the flag.

Checkbox to display joints in radians

---

moveit_planners/pilz_industrial_motion_planner/test/test_utils.cpp
moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_circ.cpp

This is a cleanup and rebase of #3524: we don't need to change API of `checkCircResult()` and `getCircCenter()`.

Add Pilz unit tests, defining goal poses w.r.t. frame_id != planning frame

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h

- avoid code redundancy
- fix warning interval to 5s
Having an interval of timeout/3 is strange for very short or very long timeouts

Simplify code waiting for ActionBasedController

---

moveit_ros/planning/plan_execution/src/plan_execution.cpp

This can be intentional if replanning is allowed,
but usually it signals an error.
WARN seems a fair compromise to me.

warn if a trajectory becomes invalid mid-execution

---

moveit_setup_assistant/src/tools/compute_default_collisions.cpp
moveit_setup_assistant/src/widgets/default_collisions_widget.cpp
moveit_setup_assistant/src/widgets/default_collisions_widget.h

This PR solves #3526
- Replaced QLabel showing the number of samples with QSpinbox. Sampling spinbox and slider are connected to each other. Slider works in range (1.000-100.000), Spinbox works in range (1.000-100.000.000). Values are always rounded in 1000s. User can set high number of samples using Spinbox which may also increase the waiting time.
- Refactored the code to use the number of samples instead of density in the range 0-100.
- Added an interrupt button if the collision generation takes a long time for the user.
- Increased the progress bar update period from 5% to 1% but that caused Floating Point Exception somewhere in the code, so reverted the changes.
Default:
Number of samples set to maximum using the spinbox and generating:
Clicked on the interrupt button:
Experimented …

Enable higher number of self-collision checking samples

---

moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp

RobotState never updates the fixed joints transforms, thus reading unititalized memory in printTransforms.
It still prints `[dirty]` for the fixed joints but I don't think that's an issue.
Another way to fix it would be to remove the fixed joints optimization in `RobotState::updateLinkTransformsInternal`, but that's not worth the cost.
Closes #3540.
- I could, but it involves a bit of complex code to pollute the heap, I don't think it's worth it.

Correctly initialize RobotState joint transforms for fixed joints

---

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame_joints_widget.h
moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp

correctly edit radian and degree joint values
Without the patch, the radio button radian/degree choice is not respected when editing unbound joints - You had to type degree values which would be shown in radian upon finishing the edit.
I refactored the degree/radian logic with mouse interaction into a custom data role `JointRangeFractionRole` for interaction with the event filter.
Additionally add support for `<Return>` to manually type joint values.
@aaryanmurgunde @rhaschke

Radian/Degree joint value edits in RViz

---

moveit_ros/benchmarks/src/BenchmarkExecutor.cpp

Followup to #3546. I directly reverted the merged commit as it broke builds.
check for header to stay compatible with Ubuntu 20.04 with boost-timer 1.71.
Support boost >= 1.83
Slightly ugly due to the double alias, but boost::timer was a class before 1.72, so using `boost::timer::progress_display` in the code breaks with older versions and I did not want to stick with the old API.
Tested on Debian testing which can reproduce the original issue. 
@acxz @rhaschke

use boost::timer::progress_display if available

---

moveit_core/CMakeLists.txt
moveit_core/cmake/moveit.cmake
moveit_core/collision_detection_fcl/CMakeLists.txt
moveit_planners/ompl/CMakeLists.txt
moveit_setup_assistant/CMakeLists.txt

ompl's main branch changed omplConfig.cmake changed from `OMPL_*` variables to imported targets via `ompl::ompl` in October 2023 and the moveit:master build breaks with it at the moment because of that.
I generalized the way we handled fcl when it did the same and cleaned up a bit.

support new ompl cmake targets

---

moveit_core/robot_state/CMakeLists.txt
moveit_core/robot_state/src/robot_state.cpp
moveit_core/robot_state/test/robot_state_test.cpp

fix link names with slashes when looking up rigid parents.
Since subframes were added, `RobotState::getRigidlyConnectedParentLinkModel` did not see links anymore if they contained slashes.
We can debate whether `object/subframe` should have priority as a world object with subframe or as a link/object name, but subframes are definitely rarer and we do not want to forbid '/' in link/object names (too late for that).

find links with slashes again

---

moveit_core/CMakeLists.txt

I get this error building on Ubuntu 23.10 (I assume it would also occur in 23.04 and maybe 22.04, I'll try those out with Docker):
```
CMake Error at /usr/lib/cmake/pybind11/pybind11NewTools.cmake:189 (python3_add_library):
Unknown CMake command "python3_add_library".
```
The fix is to move pybind11_catkin up the list in find_package as suggested in https://github.com/pybind/pybind11/issues/3996#issuecomment-1689793861
I could make a github action build this in 22.04 and/or 23.04

need to find pybind11_catkin earlier to avoid python3_add_library build error

---

moveit_core/robot_state/src/cartesian_interpolator.cpp

the api suggests that you want to use either absolute or relative check in `CartesianInterpolator::checkJointSpaceJump` but does not enforce it (public parameters of JumpThreshold). If both are combined the minimum valid path should be returned instead of the product (which might be smaller if both checks trigger)

checkJointSpaceJump: use min instead of multiplication to combine relative and absolute check

---

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
moveit_core/robot_trajectory/src/robot_trajectory.cpp
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/joint_limits_container.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_functions.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_circ.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_lin.h
moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_ptp.h
moveit_planners/pilz_industrial_motion_planner/src/joint_limits_container.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_blender_transition_window.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp
moveit_planners/pilz_industrial_motion_planner/test/test_utils.cpp
moveit_planners/pilz_industrial_motion_planner/test/test_utils.h
moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_functions.cpp
moveit_setup_assistant/src/widgets/navigation_widget.cpp
moveit_setup_assistant/src/widgets/navigation_widget.h

This replaces const ref arguments to double or int with plain const arguments. 
There is no reason to perform an additional dereference in these cases.

Cleanup const-ref arguments

---

moveit_setup_assistant/src/tools/moveit_config_data.cpp

Debian testing finally warns about API that was already deprecated in Ubuntu 18.04 and builds with `-Werror` start failing.

[ROS-O] update Boost API (melodic-compatible)

---

moveit_planners/pilz_industrial_motion_planner/src/path_circle_generator.cpp
moveit_planners/pilz_industrial_motion_planner/test/integrationtest_command_planning.cpp

There are two unit tests consistently failing in Jammy:
- circle path generation failing with an exception attempts to double-free the passed `RotationalInterpolation` object.
Here, KDL 1.4.1 has fixed the memory leak itself. No need to handle that in Pilz code anymore.
- The accuracy for comparing quaternions is too high for another test.

[ROS-O] Fix Pilz unit tests

---

moveit_ros/planning/planning_scene_monitor/CMakeLists.txt
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
moveit_ros/planning/planning_scene_monitor/test/planning_scene_monitor.test
moveit_ros/planning/planning_scene_monitor/test/planning_scene_monitor_test.cpp

Alternative to https://github.com/ros-planning/moveit/pull/3537 without semantics change.
More modules than expected rely on `plan.planning_scene_` to be valid and point to the currently monitored scene (or a diff)
Before this patch, if the PSM would receive full scenes during execution,
`plan.planning_scene_` would not include later incremental updates anymore.
Required to get the pickplace test in https://github.com/ros-planning/moveit_task_constructor/pull/432
to pass again with support for backward scene modifications.
Closes #3433

PSM: keep references to scene_ valid upon receiving full scenes

---

moveit_setup_assistant/src/widgets/simulation_widget.cpp

The Gazebo tags added by MSA where erroneous. The `gazebo/plugin` tag was missing the `filename` attribute:
```xml
<gazebo>
<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
<robotNamespace>/</robotNamespace>
</plugin>
</gazebo>
```
This was causing the following error in Gazebo:
```
Error Code 4 Msg: Required attribute[filename] in element[plugin] is not specified in SDF.
Error Code 8 Msg: Error reading element <plugin>
Error Code 8 Msg: Error reading element <model>
Error Code 8 Msg: Error reading element <sdf>
```

MSA: Add missing filename attribute to gazebo plugin tag

---

moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h
moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
moveit_ros/planning/trajectory_execution_manager/test/test_execution_manager.cpp

Allow to specify a per joint allowed start tolerance for the TrajectoryExecutionManager.
Add the `/move_group/trajectory_execution/joints_allowed_start_tolerance`, a string/double map to specify an allowed start tolerance value for each joint. If the value is not set or set to 0 for a joint, it will fall back to the regular allowed_start_tolerance.
Closes #3266.
Unlike allowed_start_tolerance, this doesn't uses the dynamic reconfigure server, because it is not possible to use maps with it.

Add joints_allowed_start_tolerance parameter (#3266)

---

moveit_commander/src/moveit_commander/move_group.py

The doc string in moveit_commander/move_group.py/compute_cartesian_path() has an error where the return values of the function are reversed. Also, I added some line breaks so it's more readable on the web-based documentation.

Fixed some error in the doc string of compute_cartesian_path()

---

moveit_ros/warehouse/warehouse/src/broadcast.cpp
moveit_ros/warehouse/warehouse/src/import_from_text.cpp
moveit_ros/warehouse/warehouse/src/initialize_demo_db.cpp
moveit_ros/warehouse/warehouse/src/moveit_message_storage.cpp
moveit_ros/warehouse/warehouse/src/save_as_text.cpp
moveit_ros/warehouse/warehouse/src/save_to_warehouse.cpp
moveit_ros/warehouse/warehouse/src/warehouse_services.cpp

Standalone applications used the convenience function moveit_warehouse::loadDatabase() to load a database plugin. Internally, this uses a static plugin loader. As this static variable is released too late during app shutdown, we get an exception:
```
terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
what():  Attempt to unload library that class_loader is unaware of.
```
Explicitly instantiating the loader ensures correct destruction order and avoids the error.
Interestingly, the MotionPlanning plugin, using the same function, doesn't exhibit that issue. Maybe, because it is itself a plugin and unloading it also unloads the corresponding database loader - in correct order.

Fix warehouse database destruction

---

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp

This PR modifies the `considered_start_state_` member of `MoveGroupInterface` to use a `moveit_msgs::RobotState` rather than a `robot_state::RobotStatePtr`. This prevents unnecessary conversion to and from the message type when planning, and allows start states to be set with `RobotState` diff messages, preventing unnecessary passing around / conversion of entire `RobotState`s when planning.
Methods exposing the `considered_start_state_` member have been updated to avoid making breaking changes to the API.

Allows MoveGroupInterface to use RobotState diffs as start states

---

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/planning_scene_monitor/test/current_state_monitor_test.cpp

There are two main changes introduced by this PR that share the same core principle -- that is group-specific state monitoring capability.
I found https://github.com/ros-planning/moveit/issues/722 as the most relevant issue to target. This PR introduces: 
1. per-group current state time retrieval
2. per-group complete robot state waiting 
For 2, read the following scenario. I want to call `waitForCompleteState` on `group_A`, which the API already supports. There is also another joint `out_of_group_A` in the `robot_model_` that is not available until a certain time since the bringup. I'm making `waitForCompleteState(group_A, <timeout>)` way earlier than `out_of_group_A` is published by its source. The problem with the current implementation is that it waits until `<timeout>` elapses, but …

Allow waiting for joint model group states and retrieval of group-specific timestamps

---

moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp

#3569 describes propagation of error from updating collision objects with each update of the start state during a sequence motion plan.
#3589 attempts to speed up plans by updating only joints positions when updating the start state, though this may cause the RobotState to ignore collision objects entirely if the state being updated has no knowledge of them.
This PR attempts to fix both issues by only updating the joints of a sequence motion, without copying across attached collision objects, in the hope that the start state being updated is already populated with attached collision object information.

Disables copying of attached collision objects when updating start state

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Fixes #3538/#3609
If the message is not a diff and parent_scene is not set either, the message should be handled as a full planning scene message as before #3538.

PSM: Correctly handle full planning scene message

---

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp

Constrained-based planning enables the `PoseModelStateSpace` by default, meaning that state samples are created by sampling in SE(3) and then performing IK. This state space frequently caused issues, eventually leading to the introduction of the ROS parameter `enforce_joint_model_state_space` in PR #541 as a work-around.
A more detailed analysis shows that the state space's interpolation approach is the culprit - performing interpolation in Cartesian space. If the two interpolation ends are close in Cartesian but distant in joint space, the interpolated state (obtained from IK) can be far away from both start and end (particularly for redundant arms), while its Cartesian pose is naturally close to both interpolation states. This will lead to consecutive waypoints being close in Cartesian …

Fix constrained-based planning

---

moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp

... when no IK solver is defined for the planning group
Fixes https://github.com/moveit/moveit2/issues/2911

Fix PILZ/LIN segfault

---

moveit_core/collision_detection/include/moveit/collision_detection/test_collision_common_panda.h
moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp

Related to #3599.
Updating a MoveIt Collision object shape poses takes 0.3 seconds for an object with 3 meshes with a total of 48,064 triangles. 
When the FCL collision environment is notified by a World::CREATE | MOVE_SHAPE | ADD_SHAPE | REMOVE_SHAPE, the object is reconstructed from scratch as seen [here](https://github.com/moveit/moveit/blob/master/moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp#L424-L443).
This PR only updates the FCL object transforms when encountering the `MOVE_SHAPE` action. The time is reduced to an average of 16 microseconds.

Optimize FCL move shape

---

moveit_planners/pilz_industrial_motion_planner/src/plan_components_builder.cpp
moveit_planners/pilz_industrial_motion_planner/src/trajectory_blender_transition_window.cpp

Backport of https://github.com/moveit/moveit2/pull/2961
The Pilz planner generated trajectories with identical subsequent time stamps, which were rejected by the ROS controllers.
Pilz's `appendWithStrictTimeIncrease()` function had a single if-statement that encompassed two conditions:
1. trajectory is empty
2. the end state of one segment differs from the start state of the next segment
In both cases, the whole trajectory segment was appended with a dt=0. However, that's correct only for case 1. 
In case 2, we needed to apply a non-zero time offset dictated by the actual dt of that segment's first waypoint.

Fix Pilz trajectory time stamps

---

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp

When executing an MTC solution, colleagues observed the following warning. Subsequently, the solution execution was not continued:
```
[DEBUG] [1720618064.381530365]: new trajectory to arm_controller
[DEBUG] [1720618064.381566831]: sending trajectory to arm_controller
[DEBUG] [1720618064.381634257]: new trajectory to torso_controller
[DEBUG] [1720618064.381663195]: sending trajectory to torso_controller
[DEBUG] [1720618064.382548006]: arm_controller started execution
[DEBUG] [1720618064.382680992]: torso_controller started execution
[ INFO] [1720618065.533005312]: Controller 'torso_controller' successfully finished
[DEBUG] [1720618065.533084152]: Controller torso_controller is done with state SUCCEEDED: 
[ INFO] [1720618065.982645786]: Controller 'arm_controller' successfully finished
[ …
```

Fix race condition in trajectory execution

---

moveit_core/CMakeLists.txt

... even when ruckig is built with it.
When ruckig is built with the cloud client (which is on by default), it relies on the third_party nlohmann library bundled in the git. But it does not install these headers. If ruckig and MoveIt are built together and ruckig is built in an install workspace, that makes the MoveIt build fail by default.
Note that this problem does not occur when the debian package `nlohmann-json3-dev` is installed because it is implicitly picked up. But ruckig does not automatically pull in nlohmann_json through package.xml depends tags (because it's optional and bundled for dev builds).
I suggest to remove the WITH_CLOUD_CLIENT definition in MoveIt's use through the patch because we don't use it anyway.
This is relevant for me because I'm trying to set up a builder …

explicitly deactivate ruckig webclient support in MoveIt build

---

moveit_ros/moveit_servo/include/moveit_servo/collision_check.h
moveit_ros/moveit_servo/src/collision_check.cpp

- do not copy acm from monitored scene (ignoring later updates)
- also do not lock scene twice for related checks
- do not cache shared_ptr, but actual RobotState, caching the ptr is useless
Please have a look @torydebra
Alternative to #3640 .
Fixes #3639 .

servo: use ACM consistently

---

moveit_ros/moveit_servo/src/servo_calcs.cpp

See #3638 
I am not sure if this is the best way to get the joint state and populate the joint trajectory. 
For example, velocities are zero, should copyJointGroupVelocity be used instead? Probably will not change much.

Set joint trajectory with actual robot pose

---

moveit_ros/planning/moveit_cpp/test/moveit_cpp.yaml
moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

I was annoyed by continuos tf ROS warning like
~~~
[ WARN] [/cmd_to_moveit] [PlanningSceneMonitor::getUpdatedFrameTransforms]: Unable to transform object from frame 'box_cloud_0' to planning frame 'world' (Lookup would require extrapolation 1.067000000s into the past.  Requested time 607.296000000 but the earliest data is at time 608.363000000, when looking up transform from frame [box_cloud_0] to frame [world])
~~~
that was correctly happening because at some point one frame is not in published anymore (as wanted).
This was caused by:
https://github.com/moveit/moveit/blob/2e5b70cd480ddb1b43b21bc79a878512d4f3c93a/moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp#L1342-L1350
Since I do not care that the planning scene monitor consider such frames, I added an …

Ignoring links planning scene monitor

---

moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
moveit_core/kinematic_constraints/src/utils.cpp
moveit_core/kinematic_constraints/test/test_orientation_constraints.cpp

Address https://github.com/moveit/moveit_task_constructor/issues/619#issuecomment-2400756378.
While the old Euler tolerance cannot be adapted to the new link frame, the rotation vector tolerance can!
Also, I noticed that the tolerance vector was interpreted w.r.t. the target frame, while it should be interpreted w.r.t. the given frame_id. The difference can be seen in the following videos. In both cases, frame_id is world and rotation is allowed about the z-axis. However, in the left video, the object rotates about it's own z-axis (parallel to world's x) instead of world's one. Both videos run the same [MTC example](https://github.com/moveit/moveit_task_constructor/blob/1acf72e0b4347e0d4fe89a379de73f6d03a09633/demo/scripts/constrained.py).
|w.r.t. target frame|w.r.t. frame_id|
|--|--| …

Fix resolveConstraintFrames for orientation constraints

---

moveit_core/planning_scene/src/planning_scene.cpp
moveit_core/planning_scene/test/test_planning_scene.cpp

Backport of https://github.com/moveit/moveit2/pull/3183

Remove ACM entries when removing collision objects

---

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
moveit_ros/planning/planning_scene_monitor/test/current_state_monitor_test.cpp

... so do not wait for them.
joints that are not published at all do not have an entry in joint_time_. 0 on the other hand implies that the joint was published on tf_static and thus should be considered updated.
This resolves an edge-case lock-up I hit because *the last joint in the list* was a floating joint (in this specific setup) published on tf_static.

0 joint_times imply published static joints

---

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp

This annoyed me since 2016. I have no idea why I never made that patch...
0.9 is not actually very transparent and can introduce rendering artifacts with transparency in RViz. Especially when the scene includes meshes this often looks weird (I believe this issue was discussed in some RViz issues in the past but I can't find the thread right now).
Alpha=0.9 versus 1.0:
Independent of a potential improvement to rendering in RViz, I suggest to simply fix the non-intuitive default of 0.9.

use opaque scene alpha by default

---

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp

Follow up on #3676, implementing [@v4hn's suggestion](https://github.com/moveit/moveit/pull/3676#discussion_r1904504928) to update `state_update_pending_` and `last_robot_state_update_wall_time_` only within updateSceneWithCurrentState() - where the update is actually performed.
This nicely simplifies all the code :tada:

PSM: Fix handling of flag state_update_pending_

---

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp

The shared pointer is just not needed.
This incidently addresses a convolved symptom around object ownership in the World. See https://github.com/moveit/moveit/issues/3691 .

do not access object directly from rviz frame

---

moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp

There is a data race on trajectory_message_to_display_ shared pointer. In practice, this data race manifests itself as a TOCTOU bug.
One possible execution order that leads to a null pointer dereference:
- Thread A calls TrajectoryVisualization::update()
- Thread A locks update_trajectory_message_ mutex
- Thread A checks that trajectory_message_to_display_ is valid
- Thread B calls TrajectoryVisualization::incomingDisplayTrajectory
- Thread B invalidates the trajectory_message_to_display_ pointer by calling trajectory_message_to_display_.reset()
- Thread A tries to call trajectory_message_to_display_->getWayPointCount(), causing a null pointer dereference.
Since there is no reason to reset the pointer at that location, we fix the bug by simply removing the call to …

Fix race condition in TrajectoryVisualization::incomingDisplayTrajectory

---

.github/workflows/ci.yaml

Given that Noetic is EOL, I suggest to:
- stop supporting Ubuntu Focal and focus on ROS One development on Jammy and newer Ubuntu versions
- stop syncing the noetic-devel branch with master to indicate this freeze in the git branch structure

CI: Stop syncing noetic-devel with master

---

moveit_core/utils/src/lexical_casts.cpp

otherwise it can take a while to spot mistakes.
Just found this in my working checkout after some debugging a while ago.

informative error on invalid cast
