.travis.before_script
apt-get remove command now works properly. See issue #8.
=> Add -y to apt-get commands

moveit/CMakeLists.txt, moveit/package.xml
As mentioned at https://github.com/ros-planning/moveit/issues/22#issuecomment-239276345
Note:
- Once merged same commit can be cherry-picked into Jade and Kinetic branches IMO.
- Once https://github.com/davetcoleman/moveit_merge/issues/9 is agreed version can be updated.
- Not sure if the maintainer's emails are the ones they want.
=> Add meta package moveit.

moveit_core/robot_model/src/robot_model.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
These changes clean up some problems with handling an empty robot model.
=> minor fixes

README.md
- fully-qualified URL required
- docker moved into subfolder of this repo
=> fixed links in README.md

moveit_ros/move_group/src/default_capabilities/execute_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_service_capability.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
These PRs from `moveit_ros` were merged into `indigo` but not yet into `kinetic`.
indigo merges: be38cedd11483945499de1b2b1447c51e935c4c6 (713), 5fbc40006bd7f937c34181ea4f3d02eb86e92dcb (717)
=> cherry-picking #713 and #717

.docker/README.md, .docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile
cherry-picked from https://github.com/ros-planning/moveit/pull/55
=> [indigo] Add Docker to main MoveIt! repo

moveit_core/CHANGELOG.rst, moveit_ros/moveit_ros/CHANGELOG.rst
Successor of previous trials https://github.com/ros-planning/moveit/pull/90#issuecomment-241179296
=> [changelog] Bad encoding.

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
Fixes https://github.com/ros-planning/moveit/issues/20
=> Fixes #20 computeCartesianPath now accepts path constraints

moveit_ros/visualization/CMakeLists.txt, moveit_ros/visualization/package.xml, moveit_ros/visualization/test/test_moveit_joy.py
Indigo for: https://github.com/ros-planning/moveit/pull/149
=> [indigo] Alternative fix for joystick unittest (#149)

.docker/release/Dockerfile, .docker/source/Dockerfile
Currently shadow-fixed and regular ros repo are both added to sources
=> Fix Docker append tag

moveit.rosinstall
Travis is broken because SRDFDom has changed but it was not being built from source
https://travis-ci.org/ros-planning/moveit/jobs/155432553
Should me merged ASAP
=> URGENT: Add SRDFDom to Indigo ROS Install to fix breakage

moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp
We want to use get_planning_scene service in our grasp planning service, this will lock the planning scene.
The problem is that the planning scene is already locked in the fillGrasps method.
So the planning scene should be unlocked before we call the grasp planner.
=> unlock planning scene before next service call

moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/distance_field/include/moveit/distance_field/propagation_distance_field.h, moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h, moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controllers.h, moveit_plugins/moveit_ros_control_interface/include/moveit_ros_control_interface/ControllerHandle.h, moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/depth_self_filter_nodelet.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter.h, moveit_ros/perception/mesh_filter/src/mesh_filter_base.cpp, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
cherry-pick of https://github.com/ros-planning/moveit/pull/193 to indigo
=> [indigo] Use MOVEIT_CLASS_FORWARD for the last shared_ptrs to moveit types

moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/distance_field/include/moveit/distance_field/propagation_distance_field.h, moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h, moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controllers.h, moveit_plugins/moveit_ros_control_interface/include/moveit_ros_control_interface/ControllerHandle.h, moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/depth_self_filter_nodelet.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter.h, moveit_ros/perception/mesh_filter/src/mesh_filter_base.cpp, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
cherry-pick of https://github.com/ros-planning/moveit/pull/193 to jade
=> [jade] Use MOVEIT_CLASS_FORWARD for the last shared_ptrs to moveit types

moveit.rosinstall
Per https://github.com/ros-planning/srdfdom/pull/18
=> Change SRDFDom rosinstall to use kinetic branch

.travis.yml
Not sure if this will pass yet
=> Enable Travis builds for Kinetic non-shadow-fixed

.docker/ci/Dockerfile
Forgot to commit this fix during testing of https://github.com/ros-planning/moveit/pull/214
Fixes https://hub.docker.com/r/moveit/moveit/builds/bmhlrprs6r2faxugmxpvuoz/
=> Fix workspace removal bug

.docker/README.md, .docker/ci/Dockerfile, README.md
Also add comments and fix documentation in README
This is perhaps a temporary fix for https://github.com/ros-infrastructure/rosdep/issues/473
Fixes https://github.com/ros-planning/moveit_resources/pull/14
=> Add missing 'sudo' command in Docker container

moveit_setup_assistant/src/setup_assistant_main.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
* catch exceptions on unknown/wrong cmdline options
* choose new/exist mode in start screen based on cmdline options
* use checkable buttons to switch between new/exist mode
=> MSA: improve start screen

.docker/README.md, .docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/experimental/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile, README.md
Will open PR for indigo after this, also
=> Sync Kinetic changes of Docker to Jade

.docker/README.md, .docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile
Same as jade version https://github.com/ros-planning/moveit/pull/226
=> Sync Kinetic changes of Docker to Indigo

.travis.yml, moveit.rosinstall
Remove warehouse_ros from rosinstall
Add srdfdom to rosinstall
This applies fixes from kinetic branch to jade branch
=> Enable travis non-shadow-fixed

.docker/experimental/Dockerfile
https://github.com/ros-planning/warehouse_ros_mongo/pull/1
=> warehouse_ros_mongo moved to ros-planning

.docker/experimental/Dockerfile
https://github.com/ros-planning/warehouse_ros_mongo/pull/1
=> Fixed path to warehouse_ros_mongo

moveit_core/robot_state/src/robot_state.cpp
No functionality change, simply prepended some extra qualifiers to the names of variables. The word "tip" was used to describe both the frame of the query pose (desired pose) and the frame of the IK solver end point, which is sometimes different.
I intend to soon (after this is merged) separate the "choose the correct pose frame for a given IK solver" into a helper function so that other uses of IK solvers can benefit from this logic currently in the RobotState. But that discussion is for another PR.
Can be picked to I/J as there is no API change, only internal variables.
=> Clarify ambiguous tip frame variable names - solver tip vs query pose frames

moveit_ros/planning_interface/move_group_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
picked from https://github.com/ros-planning/moveit/pull/264
=> Add planGraspsAndPick method to move_group_interface #264

moveit/scripts/README.md, moveit/scripts/create_maintainer_table.py, moveit/scripts/maintainer_table_template.html
python script for creating html file with info similar to http://repositories.ros.org/status_page/ros_kinetic_default.html
however ours is optimized for moveit: easily shows many authors with their github names and is limited to the packages in one directory/catkin workspace
can be modified in future for even more info
=> Script for creating moveit table

moveit_core/CMakeLists.txt, moveit_experimental/CMakeLists.txt, moveit_experimental/kinematics_constraint_aware/src/kinematics_constraint_aware.cpp, moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_ros/manipulation/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/visualization/CMakeLists.txt
Per https://github.com/ros-planning/moveit/pull/252#discussion_r80627429
=> Replace broken Eigen3 with correctly spelled EIGEN3

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
kinetic version of #290 (which targeted indigo). Please merge-commit to keep the connection to the original PR #63.
=> normalize joints in start-state validation

moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
These two commits are unquestioned changes from #232, which @davetcoleman  anyway asked to be separate PRs.
=> some cleanup

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
This tries to account for dave's feedback [here](https://github.com/ros-planning/moveit/pull/301#discussion_r84151572)
=> rename static-const variable to CAPS

.travis.yml, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
This enables Travis to reject PRs that violate code style
=> Travis check code formatting

.travis.yml
Same as https://github.com/ros-planning/moveit/pull/309
=> Enable clang-format test for jade

.travis.yml
Same as https://github.com/ros-planning/moveit/pull/309
=> Enable clang-format test for indigo

moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/package.xml
picked https://github.com/ros-planning/moveit/pull/306
=> [indigo] Rename chomp_interface to moveit_planners_chomp (#306)

moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/package.xml
picked https://github.com/ros-planning/moveit/pull/306
=> [jade] Rename chomp_interface to moveit_planners_chomp (#306)

moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp
=> Modified OMPL default planner handling.

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
Fix for recent changes by@rhaschke in https://github.com/ros-planning/moveit/pull/94 
When the default constructor is used, such as in the [moveit_tutorials](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/move_group_interface_tutorial.html), the timeout for the capabilities of move_group is should be zero indicating wait forever. For the new execution actionlib interface, it would wait 0 time then throw a runtime error. In this PR I mimicked the behavior of the original ``waitForAction()`` function that the temporary ``waitForExecuteActionOrService()`` function was suppose to have, including renaming a variable to be the same for clarity. 
I also added some helper console feedback.
This fixes our tutorials in Kinetic.
=> [move_group_interface] unable to wait forever for execution capability to come online

moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
Cherry-pick of https://github.com/ros-planning/moveit/pull/335
=> Fix move_group_interface: unable to wait forever for execution capability

moveit_ros/planning_interface/move_group_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
This is *basically* a forward-port by #264, but I had to reimplement the changes by hand.
=> Forward-port #264

moveit/package.xml, moveit_commander/package.xml, moveit_core/package.xml, moveit_experimental/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_controller_manager_example/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_plugins/package.xml, moveit_plugins/moveit_ros_control_interface/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_setup_assistant/package.xml
Closes https://github.com/ros-planning/moveit/issues/259
@mikeferguson @rhaschke @v4hn @130s @sachinchitta @isucan @IanTheEngineer @gavanderhoorn @jrgnicho @dornhege @de-vri-es @ksatyaki @ipa-mdl @jonbinney
=> Updated package.xml maintainers and author emails

moveit_planners/chomp/README.md
webpage has not been generated by buildfarm yet, fyi (takes 24 hours)
=> Redirect CHOMP docs

moveit_ros/move_group/CMakeLists.txt, moveit_ros/move_group/default_capabilities_plugin_description.xml, moveit_ros/move_group/include/moveit/move_group/capability_names.h, moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.h, moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.h, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/demo.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
Cherry picked #94 from Kinetic, but removed deprecation warnings as agreed in https://github.com/ros-planning/moveit_msgs/pull/27#issuecomment-241218455.
=> cherry-pick #94 from kinetic-devel: execute action capability

moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
picked https://github.com/ros-planning/moveit/pull/353
was merge conflict so i created PR
=> [jade] planning_interface: add missing msg dependency #353

moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
picked https://github.com/ros-planning/moveit/pull/353
was merge conflict so i created PR
=> [indigo] planning_interface: add missing msg dependency #353

moveit_plugins/moveit_ros_control_interface/README.md
@davetcoleman please have a look, I'm not entirely sure about the
`ROBOT` -> `ROS_CONTROL_NODE` part.
=> Some minor README fixes

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/follow_joint_trajectory_controller_handle.h
=> fix assertion error when result not returned

moveit.rosinstall
See https://github.com/ros-planning/moveit_visual_tools/issues/12#issuecomment-265555804 .
=> add moveit_visual_tools to rosinstall

moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
This implements my comment https://github.com/ros-planning/moveit/pull/128#issuecomment-259990241
and supersedes \#128.
=> PSI: add apply* functions that use ApplyPlanningScene.srv

moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
* Update wrap_python_move_group.cpp
Cherry-pick (with cleanup) of https://github.com/ros-planning/moveit/pull/377
=> Fix issue 373 for Kinetic (#377)

moveit_ros/move_group/include/moveit/move_group/capability_names.h, moveit_ros/move_group/src/move_group.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
Applying the diff of #366 into `jade-devel` (`git cherry-pick` failed with bad object error for some reason).
```
$ cd moveit
$ wget https://patch-diff.githubusercontent.com/raw/ros-planning/moveit/pull/366.diff
$ git apply ./366.diff
```
@v4hn
=> [Jade] add list of default capabilities (#366).

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
=> Fix spelling

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_scenes.cpp
This breaks pull-request testing for the jade branch.
See https://travis-ci.org/ros-planning/moveit/builds/190645401
=> fix upstream clang-format in jade branch

moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
I see no reason why we should not make these functions available
in indigo/jade too.
=> cherry-pick apply* functions in PSI (#381)

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
=> [jade] Replace const_cast with static_cast where possible

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/trajectory_processing/src/spline_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_spline_parameterization.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
=> [indigo] Replace const_cast with static_cast where possible

moveit_commander/src/moveit_commander/move_group.py
Please have a look [here](https://groups.google.com/d/msg/moveit-users/wlg2FR-KJp4/_NCQcm5qCQAJ) for a reference 
Thank you!
=> added description for set_start_state

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
Implementation of https://github.com/ros-planning/moveit/pull/440 to Kinetic given file restructuring
=> [kinetic] Implementing getLinkNames function for MoveGroup interface.

moveit_core/CMakeLists.txt, moveit_experimental/CMakeLists.txt, moveit_kinematics/CMakeLists.txt, moveit_planners/ompl/CMakeLists.txt, moveit_plugins/moveit_controller_manager_example/CMakeLists.txt, moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt, moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt, moveit_ros/benchmarks/CMakeLists.txt, moveit_ros/manipulation/CMakeLists.txt, moveit_ros/move_group/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/robot_interaction/CMakeLists.txt, moveit_ros/visualization/CMakeLists.txt, moveit_ros/warehouse/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
Cherry pick of https://github.com/ros-planning/moveit/pull/423
=> [kinetic] address gcc6 build error

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
There was a conflict upon cherry-picking #452 into kinetic-devel, so instead of committing directly I'm opening a PR to have someone double-check.
=> [kinetic][Cherry-pick #452] correct "simplify widget handling"

moveit_core/CMakeLists.txt, moveit_experimental/CMakeLists.txt, moveit_kinematics/CMakeLists.txt, moveit_planners/ompl/CMakeLists.txt, moveit_plugins/moveit_controller_manager_example/CMakeLists.txt, moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt, moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt, moveit_ros/benchmarks/CMakeLists.txt, moveit_ros/benchmarks_gui/CMakeLists.txt, moveit_ros/manipulation/CMakeLists.txt, moveit_ros/move_group/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/robot_interaction/CMakeLists.txt, moveit_ros/visualization/CMakeLists.txt, moveit_ros/warehouse/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
Cherry-pick of https://github.com/ros-planning/moveit/pull/423
=> [jade] address gcc6 build error

moveit_core/robot_model/src/planar_joint_model.cpp
Fixed bugs in ``PlanarJointModel`` which I've found while I'm implementing whole body motion planning with a planar joint. Please see also commit messages.
=> [indigo] Fix planar joint

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
- [x ] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
Thank you!
cherry-pick from indigo #482 into jade
=> Cherry pick  #482 from renameDisplay PR

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_panel.h, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_panel.cpp, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp, moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp
Cherry-pick of https://github.com/ros-planning/moveit/pull/491
=> [jade] New panel with a slider to control the visualized trajectory

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_panel.h, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_panel.cpp, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp, moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp
=> [kinetic] New panel with a slider to control the visualized trajectory

moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
=> adjust cmake_minimum_required for add_compile_options

moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py
No more garbled author names for people with an umlaut in their name! :)
=> ikfast_kinematics_plugin: Write XML files as UTF-8

moveit_ros/planning/plan_execution/src/plan_execution.cpp
This is supposed to supersede #492 .
=> check plan size (cleanup of #492)

moveit_ros/planning/plan_execution/src/plan_execution.cpp
Fix gcc warning introduced in #535
=> Fix macro name

.docker/release-lunar/Dockerfile, .docker/source-lunar/Dockerfile
Do not merge until the test on my personal dockerhub account builds:
https://hub.docker.com/r/davetcoleman/moveit/builds/
=> Add source and release docker images for lunar

moveit_commander/src/moveit_commander/planning_scene_interface.py
Same fix as for Kinetic, see commit f1f1f435d3149c3f1545389ebc42aaf3fff9fef8
=> [Indigo] fixed numpy.ndarray indices bug (from #86) (#450)

moveit_planners/chomp/chomp_interface/include/chomp_interface/chomp_interface.h, moveit_planners/chomp/chomp_interface/src/chomp_interface.cpp, moveit_planners/chomp/chomp_interface/src/chomp_plugin.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
=> [indigo-devel] Chomp use PlanningScene (#546) from kinetic-devel

moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h, moveit_setup_assistant/src/tools/compute_default_collisions.cpp
Cherry-Pick #569 to indigo
remove tinyxml
spurious cmake_modules addition
=> find and link against tinyxml where needed (#569)

moveit_core/constraint_samplers/include/moveit/constraint_samplers/default_constraint_samplers.h, moveit_core/constraint_samplers/src/default_constraint_samplers.cpp, moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h, moveit_core/kinematic_constraints/src/kinematic_constraint.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
Adds better description for what value of 0 means
=> Document auto scale in Rviz plugin

moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template
=> add moveit_fake_controller_manager to run_depend of moveit_config_pkg_template/package.xml.template (#613)

moveit_ros/visualization/robot_state_rviz_plugin/include/moveit/robot_state_rviz_plugin/robot_state_display.h, moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
Cherry Picking #596  into indigo
=> Cherry Picking #596  into indigo-devel

.docker/gui-docker
This is a simple bash script to add the necessary elements to run gui programs inside docker. It is aware of nvidia-docker and will activate it if nvidia drivers and nvidia-docker is available.
You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!
=> add a helper script to more easily run docker containers with gui elements

moveit_commander/package.xml, moveit_core/package.xml, moveit_experimental/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/chomp/chomp_motion_planner/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_controller_manager_example/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_plugins/package.xml, moveit_plugins/moveit_ros_control_interface/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/perception/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_setup_assistant/package.xml
For the reasoning, see https://github.com/ros-planning/moveit/issues/259
=> [package.xml] Update maintainers (Add a release-maintainer etc.)

moveit_plugins/moveit_simple_controller_manager/include/moveit_simple_controller_manager/action_based_controller_handle.h
This cleans up and supersedes #655
=> optionally wait for controllers indefinitely

moveit_core/planning_scene/src/planning_scene.cpp
Fix segfault by including missing logWarn format parameter
=> Add missing logWarn format parameter

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
Had to be adapted for pre-c++11 standard
=> [indigo] cherry-pick #691

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp, moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp, moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_plugin.cpp, moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp
Cherry-pick #714 to `indigo-devel` branch.
=> [indigo] Use lookupParam() in kinematics plugins

moveit_core/robot_trajectory/src/robot_trajectory.cpp, moveit_ros/perception/mesh_filter/src/depth_self_filter_nodelet.cpp, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
This request supersedes #715.
Also there was a namespace wrong that didn't work back in indigo.
=> [indigo] Cherry-pick missing commits from kinetic

moveit/package.xml, moveit_commander/package.xml, moveit_core/package.xml, moveit_experimental/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/chomp/chomp_motion_planner/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_controller_manager_example/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_plugins/package.xml, moveit_plugins/moveit_ros_control_interface/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/perception/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_setup_assistant/package.xml
Cherry-pick https://github.com/ros-planning/moveit/pull/649 to Indigo
Had to also cherry-pick https://github.com/ros-planning/moveit/commit/dc388399c0076c5e64e88a91151b0484218da749#diff-585bfefdbf6dfac0cf5509be970972e3 to avoid numerous merge conflicts
=> CP Indigo: [package.xml] Update maintainers (Add a release-maintainer etc.) #649

.clang-tidy, moveit_core/CMakeLists.txt, moveit_core/README.md, moveit_core/collision_detection/include/moveit/collision_detection/collision_robot.h, moveit_core/collision_detection/src/allvalid/collision_robot_allvalid.cpp, moveit_core/collision_detection/src/allvalid/collision_world_allvalid.cpp, moveit_core/collision_detection/src/collision_matrix.cpp, moveit_core/collision_detection/src/collision_octomap_filter.cpp, moveit_core/collision_detection/src/collision_robot.cpp, moveit_core/collision_detection/src/collision_tools.cpp, moveit_core/collision_detection/src/world.cpp, moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/collision_detection_fcl/src/collision_robot_fcl.cpp, moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp, moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp
Rebase of #693 to get rid of reverted merge.
=> rebase of #693: clang-tidy collision_detection and collision_detection_fcl

moveit_core/robot_model/CMakeLists.txt, moveit_core/robot_model/include/moveit/robot_model/aabb.h, moveit_core/robot_model/include/moveit/robot_model/link_model.h, moveit_core/robot_model/src/aabb.cpp, moveit_core/robot_model/src/link_model.cpp, moveit_core/robot_state/CMakeLists.txt, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/test_aabb.cpp
Port of https://github.com/ros-planning/moveit/pull/699 to kinetic-devel.
=> Fixed bugs in computation of AABB in LinkModel and RobotState (kinetic)

moveit_core/robot_model/CMakeLists.txt, moveit_core/robot_model/include/moveit/robot_model/aabb.h, moveit_core/robot_model/include/moveit/robot_model/link_model.h, moveit_core/robot_model/src/aabb.cpp, moveit_core/robot_model/src/link_model.cpp, moveit_core/robot_state/CMakeLists.txt, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/test_aabb.cpp
Cherry-picked f6b85c6 from #703 and rebased changes from #699 on top of it.
=> Fixed bugs in computation of AABB in LinkModel and RobotState.

moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
This is another attempt to resolve #744, fixing the realtime display of trajectories.
Main issue was the reset of `current_state_time_` after progressing to the next state.
Now, time is incremented continuously and state is progressed up to `current_state_time_`.
=> fix realtime trajectory display

moveit_core/robot_model/src/link_model.cpp
cherry-pick of #766 for Indigo
=> cherry-pick #766: fix computation of shape_extents_ of links w/o shapes

moveit_core/robot_state/src/robot_state.cpp
- consider both, translational and rotational distance to compute number of interpolation of steps
- ensure that quaternions are on same half sphere before doing quaternion slerp
=> fix RobotState::computeCartesianPath

moveit_ros/perception/CMakeLists.txt
=> cleanup typo in perception CMakeLists.txt

moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.h
Bringing the code more into standard ROS format
=> Minor cleanup of execute trajectory action capability

.travis.yml
https://docs.travis-ci.com/user/caching/#ccache-cache
=> enable ccache for travis

moveit_experimental/kinematics_cache/v2/kinematics_cache/CMakeLists.txt, moveit_experimental/kinematics_constraint_aware/CMakeLists.txt, moveit_kinematics/CMakeLists.txt, moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt, moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/package.xml
This PR fixes various cmake warnings throughout the source code, most notably those introduced in #778.
=> fix various cmake warnings

moveit_core/background_processing/src/background_processing.cpp, moveit_core/collision_detection/src/collision_matrix.cpp, moveit_core/collision_detection/src/collision_robot.cpp, moveit_core/collision_detection/src/collision_tools.cpp, moveit_core/collision_detection/src/collision_world.cpp, moveit_core/collision_detection/src/world.cpp, moveit_core/collision_detection/src/world_diff.cpp, moveit_core/collision_detection_fcl/src/collision_robot_fcl.cpp, moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp, moveit_core/constraint_samplers/src/default_constraint_samplers.cpp, moveit_core/constraint_samplers/src/union_constraint_sampler.cpp, moveit_core/distance_field/src/distance_field.cpp, moveit_core/dynamics_solver/src/dynamics_solver.cpp, moveit_core/kinematic_constraints/src/kinematic_constraint.cpp, moveit_core/kinematics_base/src/kinematics_base.cpp, moveit_core/kinematics_metrics/src/kinematics_metrics.cpp, moveit_core/planning_interface/src/planning_interface.cpp, moveit_core/planning_request_adapter/src/planning_request_adapter.cpp, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/profiler/src/profiler.cpp, moveit_core/robot_state/src/conversions.cpp, moveit_core/robot_trajectory/src/robot_trajectory.cpp, moveit_core/transforms/src/transforms.cpp
Kindly merge this asap. This contains code cleanup. Also raised request #829 . But got lots of conflicts.
=> code clean up of moveit_core

moveit_core/robot_state/src/robot_state.cpp
I separated the source code cleanup of `testAbsoluteJointSpaceJump` from #850 to allow for early merging of the latter and thus fixing the ROS build farm.
@mlautman, @davetcoleman Please argue why do you think that this cleanup is not more readable.
I think, reducing the number of `joint->getType()` checks improves readability.
=> testAbsoluteJointSpaceJump: improve readability of code

moveit.rosinstall
Add moveit_tutorials to common build for improved test coverage and documentation
See also https://github.com/ros-planning/moveit.ros.org/pull/159
=> Update moveit.rosinstall for Melodic

.travis.yml, moveit.rosinstall, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_experimental/kinematics_cache/v1/kinematics_cache/include/kinematics_cache/kinematics_cache.h, moveit_experimental/kinematics_cache/v1/kinematics_cache_ros/include/kinematics_cache_ros/kinematics_cache_ros.h, moveit_experimental/kinematics_cache/v2/kinematics_cache/include/moveit/kinematics_cache/kinematics_cache.h, moveit_experimental/kinematics_constraint_aware/include/moveit/kinematics_constraint_aware/kinematics_constraint_aware.h, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_pinv_mimic.hpp, moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_pos_nr_jl_mimic.cpp, moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/chainiksolver_pos_lma_jl_mimic.h, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/chainiksolver_vel_pinv_mimic.h, moveit_kinematics/lma_kinematics_plugin/src/chainiksolver_pos_lma_jl_mimic.cpp, moveit_kinematics/lma_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp, moveit_planners/ompl/CMakeLists.txt, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/transform_provider.h, moveit_ros/robot_interaction/src/interaction_handler.cpp, moveit_ros/visualization/package.xml
These commits fix remaining compile errors on Melodic.
See commit messages of individual commits for details.
=> various fixes for Melodic build

moveit_commander/package.xml, moveit_setup_assistant/package.xml
to fix ROS build farm issues (#913)
=> add missing package dependencies

moveit_core/planning_scene/test/test_planning_scene.cpp
This is some kind of refactoring which will allow to add more tests easily. Related to https://github.com/ros-planning/moveit/issues/643
=> Added planning scene tests

MIGRATION.md
I just noticed the explanation here didn't mention a workaround yet.
=> add explanation to MIGRATION

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
based on comment https://github.com/ros-planning/moveit/issues/548#issuecomment-316298918 and I have tested on https://github.com/k-okada/SCORE/tree/master/src/scara_ikfast_plugin
=> add IKP_Translation{X,Y,Z}AxisAngle{Z,X,Y}Norm4D to the cpp template

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
=> SA Navigation hot fix

moveit_planners/ompl/ompl_interface/src/constraints_library.cpp
Address @rhaschke's comment:
https://github.com/ros-planning/moveit/pull/1038/files/5bc46e200bd4f378d4feeec843a004be8b6c7c78..d6061c8d9bbcca699c6b04a0ed2cef1260476877#diff-829c7d776240fe8b91eff42cff8bc7e7
=> Address OMPL Interface compiler warning

moveit_core/collision_detection/CMakeLists.txt, moveit_core/collision_detection/include/moveit/collision_detection/allvalid/collision_robot_allvalid.h, moveit_core/collision_detection/include/moveit/collision_detection/allvalid/collision_world_allvalid.h, moveit_core/collision_detection/src/allvalid/collision_robot_allvalid.cpp, moveit_core/collision_detection/src/allvalid/collision_world_allvalid.cpp, moveit_core/collision_detection/test/test_all_valid.cpp
some functions are missing for the allValid dummy collision checker plugin after latest changes
=> Add missing distance check functions to allValid collision checker

MIGRATION.md, moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Cherry-Picking #1033 into Kinetic, with appropriate adaptions to handle old tf.
=> Cherry-Pick #1033: Fix #868

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_ros/planning/package.xml, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp, moveit_ros/planning/planning_request_adapters_plugin_description.xml
Unfortunately, #1012 was merged while still containing severe issues:
- new PlanningScene methods were added to circumvent constness
- group name was hard-coded
- package dependency was missing
@davetcoleman or @bmagyar Please review and merge asap, as kinetic-devel is [broken](https://travis-ci.org/ros-planning/moveit/builds/441121506).
=> hot fix #1012

README.md
We have a new MoveIt! logo that should be on our README
Should be cherry-picked to Melodic
=> Update MoveIt! logo in README.md

.github/config.yml
> Thanks for opening this pull request! Please check out our contributing guidelines.
This was the default message from the bot documentation, but made people here at WMD think they did something wrong.
=> Fix bot message that makes users think they did something wrong

moveit_experimental/CMakeLists.txt, moveit_experimental/package.xml, moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/package.xml, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt
=> replaced obsolete cmake_modules with Eigen (#1134)

moveit_core/collision_detection/test/test_world.cpp, moveit_core/collision_detection/test/test_world_diff.cpp, moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/distance_field/test/test_distance_field.cpp, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_core/robot_model/test/test.cpp, moveit_core/robot_state/test/robot_state_test.cpp, moveit_core/robot_state/test/test_aabb.cpp, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_core/trajectory_processing/test/test_time_parameterization.cpp, moveit_experimental/collision_distance_field/test/test_collision_distance_field.cpp, moveit_planners/chomp/chomp_interface/test/chomp_moveit_test.cpp, moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp, moveit_ros/robot_interaction/test/locked_robot_state_test.cpp, moveit_setup_assistant/test/moveit_config_data_test.cpp
These are related to testing code, while #1038 targeted main source code only.
=> fix some more compiler warnings

moveit_ros/visualization/CMakeLists.txt, moveit_ros/visualization/package.xml
Per @IanTheEngineer 
https://github.com/ros-planning/moveit/pull/1144#pullrequestreview-169830220
=> Remove unneeded dependencies

moveit.rosinstall
- Panda must also be added because not released yet
Not sure if this will build yet, depends if Franka has released to melodic their other stuff
=> Add moveit_tutorials to CI build

moveit_core/robot_state/src/robot_state.cpp
The need for changes is described in this issue report:
https://github.com/ros-planning/moveit/issues/1191
=> Fixed problem with jacobian of prismatic joints

.docker/ci/Dockerfile
Install clang in docker image to allow building with clang as well.
=> docker.ci: install clang

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
=> fix several issues in rendering of attached bodies in rviz plugins

.clang-format, moveit_core/constraint_samplers/src/constraint_sampler_manager.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/kinematic_constraints/src/kinematic_constraint.cpp, moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_experimental/collision_distance_field/src/collision_robot_distance_field.cpp, moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h, moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/lma_kinematics_plugin.h, moveit_kinematics/lma_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp, moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.h, moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/constraints_library.h, moveit_planners/ompl/ompl_interface/src/constraints_library.cpp, moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp, moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp, moveit_ros/benchmarks/benchmarks/src/benchmark_execution.cpp, moveit_ros/perception/point_containment_filter/src/shape_mask.cpp, moveit_ros/perception/semantic_world/src/semantic_world.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_manipulation.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_scenes.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_states.cpp
=> Improve clang format

moveit_ros/robot_interaction/include/moveit/robot_interaction/interaction_handler.h, moveit_ros/robot_interaction/include/moveit/robot_interaction/robot_interaction.h, moveit_ros/robot_interaction/src/interaction_handler.cpp, moveit_ros/robot_interaction/src/interactive_marker_helpers.cpp, moveit_ros/robot_interaction/src/robot_interaction.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_param_widget.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_param_widget.cpp, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
Tracking down `shared_ptr` leaks, I stumbled over several minor issues in `robot_interaction` code for rviz plugins. For review, you best look at individual commits instead of the overall bulk.
**Please keep commit history.**
=> cleanup robot interaction code

.github/config.yml
In response to this discussion: 
https://github.com/ros-planning/moveit/pull/1146#issuecomment-441724060
See my rationale there.
=> Improve wording of probot for first pull request merged

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_core/robot_trajectory/src/robot_trajectory.cpp
Add append function for appending only part of a trajectory (#1213)
* Add append function for appending only part of a trajectory
* Replace old append() using default parameters
=> kinetic backport of #1213

.docker/ci/Dockerfile, .travis.yml
In addition to #1233, also make Travis to build once with clang.
=> Travis: add clang build

moveit_core/constraint_samplers/include/moveit/constraint_samplers/constraint_sampler.h, moveit_core/constraint_samplers/src/constraint_sampler.cpp
Improve readability of comments.
=> ConstraintSampler: cleanup

.travis.yml
=> Clone moveit_ci faster

moveit_core/robot_state/src/robot_state.cpp
To improve quality of Cartesian paths, use joint-space jump limits (if provided) as consistency limits for the IK solver.
=> computeCartesianPath: limit joint-space jumps with IK consistency limits

moveit/package.xml, moveit_core/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/visualization/package.xml, moveit_setup_assistant/package.xml
=> Update maintainer email address

moveit_setup_assistant/src/widgets/default_collisions_widget.cpp, moveit_setup_assistant/src/widgets/robot_poses_widget.cpp, moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp
Fix some memory leaks in MSA. Fixes #1277.
=> MSA: fix some memory leaks

.travis.yml
Enable warnings and catkin_lint checker on Travis.
=> Travis: enable warnings and catkin_lint checker

.travis.yml, moveit_core/constraint_samplers/CMakeLists.txt, moveit_core/kinematic_constraints/CMakeLists.txt, moveit_core/kinematic_constraints/src/utils.cpp, moveit_core/trajectory_processing/test/test_time_parameterization.cpp
Fix remaining warnings in [Travis](https://travis-ci.org/ros-planning/moveit/jobs/489678681#L565-L576) and [ROS buildfarm](http://build.ros.org/job/Kdev__moveit__ubuntu_xenial_amd64/394/warnings24Result/).
=> fix remaining warnings

moveit/CHANGELOG.rst, moveit_commander/CHANGELOG.rst, moveit_core/CHANGELOG.rst, moveit_experimental/CHANGELOG.rst, moveit_kinematics/CHANGELOG.rst, moveit_planners/chomp/chomp_interface/CHANGELOG.rst, moveit_planners/chomp/chomp_motion_planner/CHANGELOG.rst, moveit_planners/chomp/chomp_optimizer_adapter/CHANGELOG.rst, moveit_planners/moveit_planners/CHANGELOG.rst, moveit_planners/ompl/CHANGELOG.rst, moveit_plugins/moveit_controller_manager_example/CHANGELOG.rst, moveit_plugins/moveit_fake_controller_manager/CHANGELOG.rst, moveit_plugins/moveit_plugins/CHANGELOG.rst, moveit_plugins/moveit_ros_control_interface/CHANGELOG.rst, moveit_plugins/moveit_simple_controller_manager/CHANGELOG.rst, moveit_ros/benchmarks/CHANGELOG.rst, moveit_ros/manipulation/CHANGELOG.rst, moveit_ros/move_group/CHANGELOG.rst, moveit_ros/moveit_ros/CHANGELOG.rst, moveit_ros/perception/CHANGELOG.rst, moveit_ros/planning/CHANGELOG.rst, moveit_ros/planning_interface/CHANGELOG.rst, moveit_ros/robot_interaction/CHANGELOG.rst, moveit_ros/visualization/CHANGELOG.rst, moveit_ros/warehouse/CHANGELOG.rst, moveit_runtime/CHANGELOG.rst, moveit_setup_assistant/CHANGELOG.rst
Part of the tasks in https://github.com/ros-planning/moveit/issues/1326
1. While this is intended for 1.0.0 release, there's nothing special changelog-wise. If we decided to make sub-1.0.0 releases, the changes here can be used.
1. Once `master` branch is created, close this PR.
- AFAIUC from https://github.com/ros-planning/moveit/issues/1326#issue-403334754, version 1.0.0 is planned to be released from `master` branch, which doesn't exist ATM. This PR is targeted to melodic-devel instead.
1. Open a PR to `master` branch with the changelog files from this PR. Updating them might be needed if changes are added in between.
=> changelog 1.0.0

README.md, moveit.rosinstall
- Document what the master branch is
- Add Travis badge
- Update rosinstall
=> Switch to master branch

moveit_commander/src/moveit_commander/planning_scene_interface.py
This PR is a part of my attempt at reviving the Python interfaces. 
I've fixed the functions adding collision objects for now. 
The refactoring follows PEP recommendations.
We should probably add tests too.
Is anyone aware of a better way of implementing this?
=> Moveit commander planning scene interface fixup

moveit_ros/benchmarks/src/BenchmarkExecutor.cpp, moveit_ros/perception/mesh_filter/src/gl_renderer.cpp, moveit_ros/planning_interface/common_planning_interface_objects/src/common_objects.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_param_widget.cpp
Removed the unnecessary null pointer checks. Addresses issue #1389.
=> Removed the unnecessary null pointer checks. Solved issue # 1389

moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_robot_hybrid.h, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_world_distance_field.h, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_world_hybrid.h, moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h
Made some minor bug fixes in the distance field functionality. 
=> Minor bug fixes in (collision) distance field

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp
=> Normalize quaternions when adding new or moving collision objects (cherry-pick #1420 to master)

.docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/source/Dockerfile
Creating master branch docker images so that we can test against the most recent version of master without building moveit in travis. 
=> Create master branch docker images

moveit_core/CMakeLists.txt, moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_robot_hybrid.h, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_world_distance_field.h, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_world_hybrid.h, moveit_core/collision_distance_field/test/test_collision_distance_field.cpp, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h, moveit_core/kinematic_constraints/test/test_constraints.cpp, moveit_core/package.xml, moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_core/robot_model/test/test.cpp, moveit_core/robot_state/test/robot_state_benchmark.cpp, moveit_core/robot_state/test/robot_state_test.cpp, moveit_core/robot_state/test/test_aabb.cpp, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_core/trajectory_processing/test/test_time_parameterization.cpp, moveit_core/utils/CMakeLists.txt, moveit_core/utils/include/moveit/utils/robot_model_test_utils.h, moveit_core/utils/src/robot_model_test_utils.cpp, moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp, moveit_planners/chomp/chomp_interface/src/chomp_planning_context.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp, moveit_planners/ompl/ompl_interface/test/test_state_space.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit_rviz.launch, moveit_setup_assistant/test/moveit_config_data_test.cpp
This PR is just intended for Travis checking. I will fast-forward melodic-devel on success.
=> cherry-pick several commits from master

.docker/ci/Dockerfile, .docker/experimental/Dockerfile, .docker/source/Dockerfile
This is just a cherry-pick of #1451 from master.
=> cherry-pick #1451: define ROS_UNDERLAY in source docker container

moveit_core/collision_detection/include/moveit/collision_detection/collision_robot.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_robot_fcl.h, moveit_core/collision_detection_fcl/src/collision_common.cpp
As I am gaining a deeper understanding of the collision detection process using FCL due to my GSoC project #1427, I am adding more documentation to the current code as it is not sufficiently documented.
I need some feedback on:
Should i use `\brief` or `@brief` ? This is inconsistent through the whole codebase. Any other stylistic or general suggestions so I can correct before adding more comments?
~I don't want to get this merged now, as this is WIP.~
=> Adding documentation to collision detection

moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh, moveit_kinematics/package.xml, moveit_kinematics/test/test_ikfast_plugins.sh
Preparing a simplified tutorial for IKFast, I noticed some small issues with the plugin-generator script.
This PR fixes them.
Should be cherry-picked to Melodic.
=> Fix ikfast plugin-generator script

moveit_planners/chomp/chomp_interface/test/chomp_moveit_test.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_utils.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
Cherry-pick fix of "chomp start-state handling" from #1473. All other commits in #1473 are changing API and thus shouldn't be back-ported.
=> Partially cherry-pick #1473

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h, moveit_core/collision_detection/include/moveit/collision_detection/collision_detector_allocator.h, moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_world_fcl.h
Further adding documentation to the current collision detection in MoveIt. This PR consists of only comments, no code.
=> Adding documentation to the collision checking

.github/CODEOWNERS
Remove me as a default reviewer, due to overload of Github emails
=> Small tweak to CODEOWNERS file

moveit_core/collision_detection/src/world.cpp
Looks like World::getTransform is broken since 3e8feeb637 (#1439).
=> fix World::getTransform

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_core/robot_trajectory/src/robot_trajectory.cpp
came up in https://github.com/ros-planning/moveit_task_constructor/pull/97#discussion_r302957574
I would propose to pick this to melodic.
=> add RobotTrajectory::getDuration()

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_core/robot_trajectory/src/robot_trajectory.cpp
=> add RobotTrajectory::getDuration() (#1554)

moveit_ros/planning/planning_request_adapter_plugins/src/add_iterative_spline_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_optimal_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_parameterization.cpp
=> Ensure that if time parameterization fails, error is appropriately propogated (#1562)

moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
=> Use portable string() on filesystem::path. (#1571)

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Should fix the CI fails currently observed
=> clang-tidy fixup

.github/PULL_REQUEST_TEMPLATE.md
@mlautman and I brainstormed how to make this list more useful and relevant so we slightly tweaked and reordered the list. Also fixes old links.
The biggest change was removing
> - [ ] Decide if this should be cherry-picked to other current ROS branches
=> Small tweaks to the pull request template

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
Super simple code cleanup via better variable name... I was debugging this part of the code.
=> Rename lm to link_model

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
Currently the doxygen is misleading and the API is tricky to understand
Answers questions @mlautman and @tylerjw were asking.
=> Document discretization behavior in KinematicsBase

moveit_experimental/jog_arm/README.md
A tiny change to launch the jog_arm demo with pre-configured RViz
=> Update jog_arm README with rviz config

moveit_ros/benchmarks/CMakeLists.txt, moveit_ros/benchmarks/examples/demo_panda_predefined_poses.launch, moveit_ros/benchmarks/examples/demo_panda_predefined_poses.yaml, moveit_ros/benchmarks/include/moveit/benchmarks/BenchmarkOptions.h, moveit_ros/benchmarks/src/BenchmarkExecutor.cpp, moveit_ros/benchmarks/src/BenchmarkOptions.cpp, moveit_ros/benchmarks/src/simple_benchmarks/CombinePredefinedPosesBenchmark.cpp
Adds a benchmark executable that creates planner queries for all pair-wise combinations of named poses specified in the config.
=> Benchmark combinations of predefined poses

moveit_ros/benchmarks/examples/demo1.yaml, moveit_ros/benchmarks/examples/demo_panda_all_planners.launch, moveit_ros/benchmarks/examples/demo_panda_all_planners.yaml, moveit_ros/benchmarks/examples/demo_panda_all_planners_obstacles.launch
- Fix some names
- Remove empty trailing lines in .yaml
- Group pipeline configs in a `<group ns>` node in .launch files.
=> cleanup launch + config files

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h, moveit_core/collision_detection/include/moveit/collision_detection/collision_detector_allocator.h, moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h, moveit_core/collision_detection_fcl/src/collision_common.cpp
Backport relevant documentation to melodic-devel
pure comment and cleanup changeset
=> Adding documentation to collision detection (#1645)

moveit_core/robot_state/include/moveit/robot_state/cartesian_interpolator.h
`abolute` should be `absolute`.
=> Fix a typo

.github/CODEOWNERS
@mamoll should be tagged on all ompl related PRs
=> Add @mamoll to codeowners

moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_detector_fcl_plugin_loader.h, moveit_core/collision_detection_fcl/src/collision_detector_fcl_plugin_loader.cpp
Added missing licenses to files, `git blame` revealed that @BryceStevenWilley is the author.
=> Added missing licenses (#1716)

.github/config.yml
"We will have a look asap." feels misleading, as issues aren't always responded to super fast.
=> Don't over promise looking at issues 'asap'

moveit_core/distance_field/include/moveit/distance_field/distance_field.h, moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_core/macros/include/moveit/macros/deprecation.h, moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
* replaced MOVEIT_DEPRECATED with [[deprecated]]
* issuing a warning when including deprecation.h
=> Updating deprecation method (#1748)

moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
Make https://github.com/ros-planning/moveit/pull/1758/files more readable
=> [trivial] Improve variable naming in RobotModelLoader

moveit_core/robot_model/src/robot_model.cpp
Was working with @gonfreces on a feature and realized these variable names were confusing.
=> [trivial] Improve variable name in RobotModel

moveit_commander/src/moveit_commander/planning_scene_interface.py
The attach_*() functions didn't handle the synchronous service communication yet,
triggering an exception when serializing a CollisionObject instead of an AttachedCollisionObject.
=> Fix python PlanningSceneInterface's attach_*()

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/collision_check_thread.h, moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm_data.h, moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h, moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_ros_interface.h, moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/low_pass_filter.h, moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp, moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp, moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp, moveit_experimental/moveit_jog_arm/src/jog_server.cpp, moveit_experimental/moveit_jog_arm/src/low_pass_filter.cpp, moveit_experimental/moveit_jog_arm/src/teleop_examples/spacenav_to_twist.cpp
=> Update license formatting

.github/CODEOWNERS
We've had a number of new contributors get involved in the project, and we've had some new features / subfolders get merged in. This PR attempts to further improve how our bot auto-assigns reviewers, by spreading the workload out among more reviewers.
=> Added new CODEOWNERS for new folders and new core contributors

moveit_planners/chomp/chomp_interface/src/chomp_planning_context.cpp
=> Add Missing License

moveit_core/robot_trajectory/src/robot_trajectory.cpp
Fixup for 01ff0358b58ef14aeedb1ceee98887c3c49f8911 (#1760)
Fixes #1833.
=> Fix RobotTrajectory's copy constructor

moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp, moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp, moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp, moveit_experimental/moveit_jog_arm/src/jog_interface_base.cpp, moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp, moveit_experimental/moveit_jog_arm/src/jog_server.cpp, moveit_experimental/moveit_jog_arm/src/low_pass_filter.cpp
=> Move attribution below license file, standardize with MoveIt

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
Prevent the occasional crash when a velocity limit is exceeded.
=> jog_arm: prevent a crash at velocity limit

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp, moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp, moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h, moveit_ros/planning/plan_execution/src/plan_execution.cpp
@jliukkonen asked the difference between getGlobalLinkTransform() and getFrameTransform() so I cleaned up some stuff while verifying my recollection of the difference was correct.
=> Add and cleanup RobotState doxygen documentation

.github/PULL_REQUEST_TEMPLATE.md
Add more details for users making pull requests
=> Improve pull request template details with hyperlinks

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp, moveit_ros/occupancy_map_monitor/src/occupancy_map_server.cpp, moveit_ros/occupancy_map_monitor/src/occupancy_map_updater.cpp, moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp, moveit_ros/perception/lazy_free_space_updater/src/lazy_free_space_updater.cpp, moveit_ros/perception/point_containment_filter/src/shape_mask.cpp, moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp, moveit_ros/perception/semantic_world/src/semantic_world.cpp
Namespace logging for several perception pipeline files.
=> Namespace logging for core perception pipeline files

codecov.yaml
This yaml file configures how codecov comments on pull requests.  It should now "succeed" even when pull requests reduce coverage by up to 0.5%
@rhaschke here is the documentation for this: https://docs.codecov.io/docs/commit-status
=> codecov yaml

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
=> Revert change to moveit_setup_assistant default directory

moveit_core/robot_model/src/robot_model.cpp
Helpful for filling them in. :)
=> list missing joints when states are incomplete

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
Addition to #1934, providing corresponding feedback.
=> Provide feedback on success/failure of requestPlanningSceneState()

moveit_experimental/moveit_jog_arm/CMakeLists.txt, moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_calcs.h, moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp, moveit_experimental/moveit_jog_arm/test/arm_setup/config/jog_settings.yaml, moveit_experimental/moveit_jog_arm/test/launch/common_test_setup.launch, moveit_experimental/moveit_jog_arm/test/launch/jog_arm_halt_msg_test.test, moveit_experimental/moveit_jog_arm/test/launch/jog_arm_msg_reception_test.test, moveit_experimental/moveit_jog_arm/test/launch/jog_arm_vel_accel_limits_test.test, moveit_experimental/moveit_jog_arm/test/test_halt_msg/test_jog_arm_halt_msg.py, moveit_experimental/moveit_jog_arm/test/test_msg_reception/test_jog_arm_msg_reception.py, moveit_experimental/moveit_jog_arm/test/test_vel_accel_limits/test_vel_accel_limits.py
Read velocity and acceleration limits from the SRDF and enforce them
=> [jog_arm] SRDF velocity and acceleration limit enforcement

moveit_core/collision_detection_fcl/src/collision_common.cpp
=> fix SINGLE distance checks

moveit_commander/bin/moveit_commander_cmdline.py, moveit_commander/src/moveit_commander/conversions.py, moveit_commander/src/moveit_commander/interpreter.py, moveit_commander/src/moveit_commander/robot.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp, moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/serialize_msg.h, moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp, moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
<del>Some changes were missing on #1971, the PR has not been blocked by the CI Pipeline.</del>
Added the missing bits to #1971 which was rolled back.
=> Adapt message serialization for Python 3 (#1870)

moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp, moveit_planners/sbpl/core/sbpl_interface/include/sbpl_interface/sbpl_params.h
angles.h was included at various places, but wasn't used.
=> remove unused angles.h includes

moveit_experimental/moveit_jog_arm/src/collision_check_thread.cpp
Removed the second collision check since it's redundant right after the one with distance enabled.
=> [jog_arm] Remove duplicate collision check

moveit_kinematics/CMakeLists.txt, moveit_planners/ompl/CMakeLists.txt, moveit_plugins/moveit_controller_manager_example/CMakeLists.txt, moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt, moveit_plugins/moveit_ros_control_interface/CMakeLists.txt, moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt, moveit_ros/manipulation/CMakeLists.txt, moveit_ros/move_group/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/robot_interaction/CMakeLists.txt, moveit_ros/visualization/CMakeLists.txt, moveit_ros/warehouse/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
=> Fix errors: catkin_lint 1.6.7

.travis.yml
- modernize keys
- send emails to autor/committer
- enable clang-tidy-fix
- temporarily disable ros-shadow-fixed
=> Unify Travis config with master branch

moveit_core/collision_detection/src/world.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.cpp, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/src/conversions.cpp, moveit_core/robot_state/src/robot_state.cpp, moveit_experimental/moveit_jog_arm/src/jog_cpp_interface.cpp, moveit_experimental/moveit_jog_arm/src/jog_ros_interface.cpp, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.h, moveit_kinematics/cached_ik_kinematics_plugin/src/ik_cache.cpp, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp, moveit_ros/benchmarks/src/BenchmarkExecutor.cpp, moveit_ros/move_group/src/default_capabilities/query_planners_service_capability.cpp, moveit_ros/perception/mesh_filter/src/mesh_filter_base.cpp, moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp, moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h, moveit_ros/planning_interface/moveit_cpp/include/moveit/moveit_cpp/planning_component.h, moveit_ros/planning_interface/moveit_cpp/src/moveit_cpp.cpp, moveit_ros/planning_interface/moveit_cpp/src/planning_component.cpp, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/default_collisions_widget.cpp, moveit_setup_assistant/src/widgets/end_effectors_widget.cpp, moveit_setup_assistant/src/widgets/passive_joints_widget.cpp, moveit_setup_assistant/src/widgets/passive_joints_widget.h, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.h, moveit_setup_assistant/src/widgets/robot_poses_widget.cpp, moveit_setup_assistant/src/widgets/ros_controllers_widget.cpp, moveit_setup_assistant/src/widgets/ros_controllers_widget.h, moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp
Several clang-tidy issues slipped through our CI checker, which only considers changed files.
=> Fix some clang tidy issues

.travis.yml
A new eigenpy version is released to ros-shadow-fixed...
=> Travis: re-enable ros-shadow-fixed

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
@v4hn @rhaschke here is adding the variable to the setup assistant template for demo.launch.
Responding to your comment on https://github.com/ros-planning/panda_moveit_config/pull/63
=> Add use_rviz to demo.launch in setup_assistant

moveit_core/collision_detection/src/world.cpp
See https://github.com/ros-planning/moveit/issues/2025#issuecomment-614455384
=> collision world: check for empty shapes vector before access

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.h, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/moveit_rviz.launch, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/planning_context.launch, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/run_benchmark_ompl.launch
This is a backport of #1997  to melodic-devel. I used
```
git cherry-pick 2a98624b26f7ad0be42c272e0787e538436bfedb
```
Is that correct like this? @v4hn
=> [backport to melodic] Assistant: load additional file with kinematics parameters (#1997)

moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
=> Added support for PS4 joystick

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
Supersedes #2065 and includes more cleanup.
Closes #2064.
=> check for grasp service - general cleanup MGI

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
fixup for dfb00da5917f357f56b54db5b0e3038a3180e10a
=> fix signal for planning_attempts

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_ros/perception/semantic_world/src/semantic_world.cpp
Melodic backport of #2113. Best merge via `rebase and merge` from github.
=> Fix getTransform() (#2113)

moveit/package.xml, moveit_commander/package.xml, moveit_core/package.xml, moveit_experimental/moveit_jog_arm/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/chomp/chomp_motion_planner/package.xml, moveit_planners/chomp/chomp_optimizer_adapter/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_plugins/package.xml, moveit_plugins/moveit_ros_control_interface/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/occupancy_map_monitor/package.xml, moveit_ros/perception/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_runtime/package.xml, moveit_setup_assistant/package.xml
... as agreed on in maintainer meeting.
Fixes #2036.
=> Bump version to upcoming Noetic release: 1.1.0

README.md
- Remove ! in Logo
- Update some of the dates 
- Add description for MoveIt
- Cleanup badge headers
=> Cleanup MoveIt 1 README

moveit_noetic.rosinstall
Includes all repos that are not yet available from Debian. Based on @mikeferguson 's [initial notes](https://github.com/ros-planning/moveit/issues/2015#issuecomment-637647822)
=> Add temporary rosinstall for building Noetic

README.md
Follow up from https://github.com/ros-planning/moveit/issues/1973
=> Switch README to travis-ci.com

README.md
Melodic version of https://github.com/ros-planning/moveit/pull/2139
I don't think we need to bother with really old kinetic.
=> Switch Travis to .com

moveit_experimental/moveit_jog_arm/include/moveit_jog_arm/jog_arm.h
Bug that slipped through in my large change.
=> [jog_arm] pragma once in jog_arm.h

moveit_experimental/moveit_jog_arm/src/collision_check.cpp
Another small bug created by my refactor.  I don't think this did anything harmful but it also isn't right.
=> [jog_arm] remove duplicate line

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
Manually tracing the code I'm not sure how this is happening but it is and this causes odd behavior (sending trajectory data from seemingly random data).
=> [jog_arm] fix access past end of array bug

moveit_ros/moveit_servo/include/moveit_servo/collision_check.h, moveit_ros/moveit_servo/include/moveit_servo/joint_state_subscriber.h, moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h
Minor header file cleanup
@AdamPettinger
=> Minor moveit_servo header cleanup

moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/collision_distance_field/src/collision_distance_field_types.cpp, moveit_core/planning_scene/src/planning_scene.cpp, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
Here is the list of things I collected with #2189 that I consider important enough (or at least reasonable) to merge before the release.
No reason to keep memory leaks, a segfault and potential linking problems open issues in the release.
@tylerjw @rhaschke
=> melodic backports [pre-release]

moveit_ros/planning_interface/test/move_group_interface_cpp_test.test
=> [melodic-devel] backport: use moveit_resources for testing (#2194)

.travis.yml
... to (hopefully) fix Travis issue (see https://github.com/moby/moby/pull/36417)
=> Travis: Update dist to Bionic

moveit_ros/moveit_servo/config/ur_simulated_config.yaml, moveit_ros/moveit_servo/test/config/servo_settings.yaml
Simply remove an unused parameter
=> Remove unused yaml param

moveit_ros/moveit_servo/include/moveit_servo/collision_check.h, moveit_ros/moveit_servo/src/collision_check.cpp, moveit_ros/moveit_servo/src/servo_calcs.cpp
- Check collisions during joint motions (just like they are with Cartesian motions)
- Print colliding objects, for debugging
=> Check collisions during joint motions, too

moveit_ros/visualization/robot_state_rviz_plugin/include/moveit/robot_state_rviz_plugin/robot_state_display.h, moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp, moveit_ros/visualization/trajectory_rviz_plugin/include/moveit/trajectory_rviz_plugin/trajectory_display.h, moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp
=> [melodic] Fix deferred robot model loading

moveit_ros/moveit_servo/CMakeLists.txt
I went and verified that this line exists in all the other cmake files in moveit.
=> [maint] add soname version to moveit_servo

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h, moveit_ros/moveit_servo/include/moveit_servo/collision_check.h, moveit_ros/moveit_servo/src/collision_check.cpp
I had to create my own implementations for this several times while debugging. So I figure it is time to make easier collision debugging available publicly.
=> Add a utility to print collision pairs

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h, moveit_planners/ompl/ompl_interface/src/detail/constraints_library.cpp
Some minor spelling fixes in the OMPL interface, as mentioned in #2277.
=> fix some spelling errors in the ompl interface

codecov.yaml
These changes are in response to the discussion today in the meeting @v4hn.  These should make the codecov tests always pass.
=> [maint] adjust code coverage yaml to make it more forgiving

.travis.yml
Fixes https://github.com/ros-planning/moveit/issues/2294
=> [maint] Remove kinetic from Travis CI testing

moveit_ros/moveit_servo/include/moveit_servo/collision_check.h, moveit_ros/moveit_servo/include/moveit_servo/servo.h, moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h, moveit_ros/moveit_servo/src/collision_check.cpp, moveit_ros/moveit_servo/src/cpp_interface_example/cpp_interface_example.cpp, moveit_ros/moveit_servo/src/servo.cpp, moveit_ros/moveit_servo/src/servo_calcs.cpp, moveit_ros/moveit_servo/src/servo_server.cpp, moveit_ros/moveit_servo/test/servo_cpp_interface_test.cpp
=> Fix Servo interruption

moveit_commander/src/moveit_commander/move_group.py
Slightly improve the exception messages I ran into today.
=> MoveGroupCommander: Improve exception messages

.travis.yml, moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h, moveit_core/collision_detection_bullet/CMakeLists.txt, moveit_core/collision_detection_fcl/CMakeLists.txt, moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh, moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py, moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt, moveit_kinematics/test/test_ikfast_plugins.sh, moveit_ros/perception/mesh_filter/CMakeLists.txt, moveit_ros/perception/package.xml
Travis wasn't yet testing `master` branch against Noetic. Switching to Noetic revealed several open issues, which are tackled by this PR:
- Our ikfast unittests were failing and we didn't notice: https://travis-ci.com/github/ros-planning/moveit/jobs/391217949.
- `lxml` API has changed, giving rise to #2322. This PR fixes #2322.
- There were several new warnings, particularly by newer clang compiler.
=> Fix various issues with Noetic build

.travis.yml, moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh, moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py, moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt, moveit_kinematics/test/test_ikfast_plugins.sh
This is just a backport of the fixes to the IKfast unittests, which are part of #2327.
=> Fix IKfast tests

moveit_setup_assistant/src/setup_assistant_main.cpp, moveit_setup_assistant/src/widgets/controller_edit_widget.cpp, moveit_setup_assistant/src/widgets/double_list_widget.cpp, moveit_setup_assistant/src/widgets/end_effectors_widget.cpp, moveit_setup_assistant/src/widgets/end_effectors_widget.h, moveit_setup_assistant/src/widgets/group_edit_widget.cpp, moveit_setup_assistant/src/widgets/kinematic_chain_widget.cpp, moveit_setup_assistant/src/widgets/passive_joints_widget.h, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.h, moveit_setup_assistant/src/widgets/robot_poses_widget.cpp, moveit_setup_assistant/src/widgets/robot_poses_widget.h, moveit_setup_assistant/src/widgets/ros_controllers_widget.cpp, moveit_setup_assistant/src/widgets/ros_controllers_widget.h, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.h, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp, moveit_setup_assistant/src/widgets/virtual_joints_widget.h
Hunting down #2339, I came across several improvements of the (manual :cry:) GUI creation.
However, I didn't yet find the underlying reason why Qt cannot correctly layout the widget - the minimal size is incorrectly computed. Finally, I just increase the minimum height of the main widget...
Fixes #2339 for now.
=> MSA: Fix layout

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
Fixes #780. Note, that this builds on top of #2349!
=> MSA: Allow to show both, visual and collision geometry

moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.h
Fix #2292. Note, that this builds on top of #2349!
=> MSA: Fix group editing

moveit_ros/move_group/CMakeLists.txt, moveit_ros/move_group/src/default_capabilities/state_validation_service_capability.cpp, moveit_ros/move_group/test/test_cancel_before_plan_execution.test, moveit_ros/move_group/test/test_check_state_validity_in_empty_scene.py, moveit_ros/move_group/test/test_check_state_validity_in_empty_scene.test
Duplicate of PR https://github.com/ros-planning/moveit/pull/2319 but targeting the master branch.
=> [Master] Let the max number of contacts be the amount of world objects + link models with geometry

moveit_ros/move_group/CMakeLists.txt, moveit_ros/move_group/src/default_capabilities/state_validation_service_capability.cpp, moveit_ros/move_group/test/test_check_state_validity_in_empty_scene.py, moveit_ros/move_group/test/test_check_state_validity_in_empty_scene.test
Backport of #2355 to kinetic as requested by @LoyVanBeek .
=> [backport] Let the max number of contacts be the amount of world objects + link models with geometry

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md
* Add noetic to bug report template
* Replace tabs with spaces
=> Update .github files

.github/ISSUE_TEMPLATE/first_timers_only.md
Here is an issue template for `first-timers-only` issues.  See: https://github.com/ros-planning/moveit/issues/2384
=> [meta] first-timers-only issue template

moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h
=> [master] Update collision-related comments

moveit_ros/moveit_servo/src/servo_calcs.cpp
=> [Servo] Prevent race condition during initialization

moveit_ros/moveit_servo/CMakeLists.txt, moveit_ros/moveit_servo/config/ur_simulated_config.yaml, moveit_ros/moveit_servo/include/moveit_servo/servo_calcs.h, moveit_ros/moveit_servo/include/moveit_servo/servo_parameters.h, moveit_ros/moveit_servo/src/servo.cpp, moveit_ros/moveit_servo/src/servo_calcs.cpp, moveit_ros/moveit_servo/test/config/servo_settings.yaml, moveit_ros/moveit_servo/test/config/servo_settings_low_latency.yaml, moveit_ros/moveit_servo/test/servo_low_latency_test.cpp, moveit_ros/moveit_servo/test/servo_low_latency_test.test
This change allows the user to tie the output of servo to the input.  By using a condition variable in this new `low_latency_mode` servo will run each time it gets input.
Includes a test that validates this works as expected.
=> [feature] Low latency mode

.github/ISSUE_TEMPLATE/first_timers_only.md
Fixed the first_timers_only.md as instructed in Issue #2413 
=> Updated First Timers Only Issue Template #2413

moveit_core/collision_detection/include/moveit/collision_detection/collision_common.h
=> Delete CollisionRequest min_cost_density (unused)

moveit_ros/planning/plan_execution/src/plan_execution.cpp, moveit_ros/planning/plan_execution/src/plan_with_sensing.cpp
Fixed the typos in plan_execution.cpp and plan_with_sensing.cpp. This pull request resolves #2444 .
=> Fix typos in plan_execution.cpp and plan_with_sensing.cpp

moveit_kinematics/ikfast_kinematics_plugin/scripts/round_collada_numbers.py
=> Python3 compat print in round_collada_numbers

moveit_core/collision_detection_bullet/src/collision_env_bullet.cpp, moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
Minor cleanup of some collision-related comments that were obviously wrong
=> Minor collision comment cleanup

.github/ISSUE_TEMPLATE/first_timer_only.md
Fixed few typos in first-timers-only.md file
=> Fix typo in first-timer-only issue template

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
This fixes several issues with PSD/MPD, see individual commit messages for details. Please, keep them during merging.
Fixes #2582.
=> Fix PlanningScene / MotionPlanning displays

.github/ISSUE_TEMPLATE/first_timer_only.md
=> Add Readme line on how to ping someone

.github/workflows/ci.yml, .github/workflows/format.yml, .github/workflows/prerelease.yml
=> GHA: Add pre-release job

moveit_core/collision_detection_bullet/README.md, moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/collision_env_bullet.h, moveit_core/collision_detection_bullet/src/collision_env_bullet.cpp
Replaces #2481 and adds minor refinements.
Please review and merge @AndyZe. You disabled maintainer-pushes to your fork, so I had to create a new pull-request.
=>  Lock the Bullet collision environment, for thread safety

moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
These commits fix some minor issues I noticed when looking into #2612. See individual commit messages for details.
=> Minor fixups in PlanningSceneDisplay

moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
This does what the title says.
=> Add planning_pipeline_id setting to Python MGI

.github/workflows/ci.yaml, .github/workflows/prerelease.yaml
Don't use shell expansion for package names and to remove a directory tree
=> [prerelease test] Fix shell syntax

moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh, moveit_kinematics/test/test_ikfast_plugins.sh
Write stdout+stderr to an intermediate log file which is shown on failure.
=> Improve ikfast QUIET handling

.docker/source/Dockerfile
Fixes #2543. @cambel or @zark-zeugan could you please validate?
=> docker-source: Source environment of $ROS_UNDERLAY

.github/workflows/ci.yaml, .github/workflows/downstream.rosinstall, .github/workflows/upstream.rosinstall
Address https://github.com/ros-planning/moveit/pull/2650#issuecomment-833646732
=> CI: Split downstream and upstream packages

moveit_setup_assistant/src/widgets/author_information_widget.cpp
=> Fixed typo

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
Also fix a typo in a debug message.
=> MSA: Fix template (max_safe_path_cost)

moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/perception_widget.cpp, moveit_setup_assistant/test/moveit_config_data_test.cpp
Cherrypick #2708 for melodic branch
=> [melodic] MSA: Sensor config writing

moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
Fix this error:
> moveit_joy: RuntimeError: dictionary changed size during iteration
Please have a look @astroxyx , I did not even run the code.
Fixes #2625.
=> a dict must not delete items during iteration

moveit_core/robot_state/test/robot_state_test.cpp
I started writing these tests when I thought there was a bug in the interpolation code. There wasn't, I was just passing a bad parameter (hence #2664), but the tests are still worthwhile.
=> New RobotState interpolation test

moveit_core/collision_detection_fcl/src/collision_env_fcl.cpp
=> Port #2721 (fixed padding collision attached objects) to Master

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
Address https://github.com/ros-planning/moveit/pull/2684#discussion_r663106517 and adjust the single other use in this file as well.
=> use std::make_shared over new

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
=> MGI::setStartState: Only fetch current state when new state is diff

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h
Addresses https://github.com/ros-planning/moveit/pull/2751/files#r667319953
Please review @simonschmeisser
=> Trajectory: Improve docstrings

.github/workflows/catkin_tools_devel.sh, .github/workflows/ci.yaml, moveit_planners/ompl/ompl_interface/CMakeLists.txt, moveit_ros/manipulation/pick_place/CMakeLists.txt, moveit_ros/planning/plan_execution/CMakeLists.txt, moveit_ros/planning/planning_scene_monitor/CMakeLists.txt, moveit_ros/planning/trajectory_execution_manager/CMakeLists.txt
See individual commit messages. Closes #2763.
=> CI improvements

moveit_core/robot_state/src/robot_state.cpp, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/state_validity_checker.h
Switching to clang introduces more issues and can be considered separately.
=> Isolated fixes from https://github.com/ros-planning/moveit/pull/2792

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
I'm not sure why nobody thought about adding this before...
=> add trivial helper to RobotState

moveit/package.xml, moveit_commander/package.xml, moveit_core/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/chomp/chomp_motion_planner/package.xml, moveit_planners/chomp/chomp_optimizer_adapter/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_planners/pilz_industrial_motion_planner/package.xml, moveit_planners/pilz_industrial_motion_planner_testutils/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_plugins/package.xml, moveit_plugins/moveit_ros_control_interface/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/moveit_servo/package.xml, moveit_ros/occupancy_map_monitor/package.xml, moveit_ros/perception/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_runtime/package.xml, moveit_setup_assistant/package.xml
Bump version number as requested in #2831.
=> Bump version: 1.1.6

.docker/source/Dockerfile, .github/workflows/docker.yaml
* Ensure (re)building of source docker image
* Enable ccache
=> CI: Improve docker builds

moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
See https://github.com/ros-planning/moveit/issues/2875
=> get object.pose from new msg field

.github/ci_cross_platform_env.yml
=> pin openssl 1.1.1* for now

moveit_core/planning_scene/src/planning_scene.cpp
I wonder why I failed to see this during the review...
=> fix uninitialized orientation in default shape pose

moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/planning_context_base.h, moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_circ.h, moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_lin.h, moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_generator_ptp.h, moveit_planners/pilz_industrial_motion_planner/src/joint_limits_aggregator.cpp, moveit_planners/pilz_industrial_motion_planner/src/pilz_industrial_motion_planner.cpp, moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp, moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp, moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_ptp.cpp, moveit_planners/pilz_industrial_motion_planner/test/test_robots/prbt/launch/test_context.launch, moveit_planners/pilz_industrial_motion_planner/test/test_utils.h, moveit_planners/pilz_industrial_motion_planner/test/unittest_pilz_industrial_motion_planner.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_planning_context.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_planning_context_loaders.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_blender_transition_window.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_circ.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_common.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_lin.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_ptp.cpp
Address https://github.com/ros-planning/moveit/issues/2930#issuecomment-951944125 and various other weak error messages in Pilz planner:
- Downgrade ERROR to WARN
- Report affected joint name
- Quote (possibly empty) planner id
=> Improve error messages

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/simple_moveit_controller_manager.launch.xml
This is a fixup for 19ab01601 of #2932.
=> Upload controller_list for simple controller manager

moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui, moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame_joints.ui
In preparation of the Noetic release, I tackled two more items from the list in #2741, namely no. 2 and 11.
I'm not satisfied though, with hiding the "nullspace exploration" label as it just flickers up and one cannot read it anymore.
https://user-images.githubusercontent.com/5376030/140199990-f4d3bcb0-e31b-4800-b502-cdfc573d9c24.mp4
=> Various fixes

moveit_kinematics/ikfast_kinematics_plugin/scripts/round_collada_numbers.py
Minor change to fix round_collada_numbers.py script by opening files for reading and saving in binary mode. No reference issue.
=> fix round_collada_numbers.py by opening files in binary mode

moveit_core/collision_distance_field/src/collision_env_distance_field.cpp
Backport of https://github.com/ros-planning/moveit2/pull/942
=> collision_distance_field: Fix undefined behavior vector insertion

moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_spline_parameterization.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_time_parameterization.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_parameterization.h, moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
This's mainly for https://github.com/ros-planning/moveit_task_constructor/pull/333, but I had multiple cases in the past where I needed the parameterization algorithms to be polymorphic
=> Refactor parameterization algorithms to inherit from TimeParameterization class

moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_spline_parameterization.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_time_parameterization.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_parameterization.h, moveit_core/trajectory_processing/src/iterative_spline_parameterization.cpp, moveit_core/trajectory_processing/src/iterative_time_parameterization.cpp, moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp
Cherry-picking #3021 from master.
=> Make TimeParameterization classes polymorphic

moveit_planners/pilz_industrial_motion_planner/test/unittest_planning_context.cpp, moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_common.cpp
=> pilz: Add type for overloaded function specification

moveit_ros/move_group/src/move_group.cpp
Ensure that planning pipelines considered in `~/planning_pipelines/*` actually have a `planning_plugin` parameter defined.
Otherwise, issue an error message. Looks like that's a common error (e.g. #2812) when migrating from Melodic's config scheme.
=> Improve loading of planning pipelines

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
=> Switch to std::bind II

moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
Added the PS3 Dualshock controller as was explained [here](https://answers.ros.org/question/325567/unknown-joystick-exception-for-teleop-in-moveit/). Did this because I am looking to control a UR robot jog wise through a PS3 controller and noticed this small fix was not included.
=> Updated moveitjoy_module.py to add PS3 dualshock model

moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/include/moveit/setup_assistant/tools/xml_manipulation.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/tools/xml_manipulation.cpp, moveit_setup_assistant/src/tools/xml_syntax_highlighter.cpp, moveit_setup_assistant/src/tools/xml_syntax_highlighter.h, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.h, moveit_setup_assistant/src/widgets/header_widget.cpp, moveit_setup_assistant/src/widgets/simulation_widget.cpp, moveit_setup_assistant/src/widgets/simulation_widget.h, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/gazebo.launch
This replaces #2960 and adds some further improvements to the original Gazebo-URDF code:
- Allow saving of the augmented URDF
- Avoid duplicating XML elements
- Simplify code
=> MSA: Improve Gazebo-compatible URDF generation

.pre-commit-config.yaml, moveit_commander/src/moveit_commander/move_group.py, moveit_commander/src/moveit_commander/planning_scene_interface.py, moveit_commander/src/moveit_commander/robot.py, moveit_ros/planning_interface/test/serialize_msg.py
Running pre-commit with the current black version is broken, and should be updated as per https://github.com/ros-planning/moveit2/pull/1148
=> Update black version

moveit_commander/src/moveit_commander/interpreter.py
A tiny quality-of-life improvement
=> make current joint state copy&paste'able

moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/planning_scene/test/test_planning_scene.cpp
This adds another test case to #3124 and adds some further minor improvements to the original PR.
=> Addon to #3124

moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
Updating the logging name variable `name_` to `LOGNAME` to keep consistency with other modules.
=> Standardize logging with LOGNAME variable

moveit_commander/src/moveit_commander/planning_scene_interface.py
Another leftover from the migration to co.pose.
Fixes #3174.
=> adjust python PSI to co.pose interface

.github/workflows/ci.yaml, .pre-commit-config.yaml, moveit_commander/src/moveit_commander/move_group.py, moveit_commander/src/moveit_commander/planning_scene_interface.py, moveit_commander/src/moveit_commander/robot.py, moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh, moveit_kinematics/test/test_ikfast_plugins.sh
Backport of #3172, hopefully fixing [broken CI](https://github.com/ubi-agni/moveit/runs/8034517117?check_suite_focus=true).
=> [Melodic backport] Fix CI

.docker/README.md, .docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile, .dockerignore
Particularly #3126 is required to [fix GHA](https://github.com/ros-planning/moveit/runs/8135287587?check_suite_focus=true).
=> Backport Dockerfile changes

moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
=> Fix segfaults in CHOMP

moveit_setup_assistant/src/widgets/robot_poses_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
Replace fixed with adaptive sizing, based on available space and font metrics.
Fixes #3118.
=> MSA: Generalize sizing of joint list widgets

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame_joints_widget.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
Fixes #3220. Closes #3224.
- Add missing units to sliders in JointsWidget
- Add keyboard control to JointsWidget
=> Improve MotionPlanning plugin's JointsWidget

.github/workflows/ci.yaml, .github/workflows/docker.yaml, .github/workflows/format.yaml, .github/workflows/prerelease.yaml, .github/workflows/robostack.yaml
- Fix deprecation warnings
- Provide feedback on clang-tidy issues
=> Improve CI

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h, moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
This is a backport of this MoveIt2 PR:  https://github.com/ros-planning/moveit2/pull/1606
=> Convert OMPL status to MoveItErrorCode in the OMPL interface

.github/workflows/docker.yaml
I don't really understand why `dependabot` doesn't report these version updates (it doesn't report anything at all).
@tylerjw, do you have any idea?
=> CI: Update versions of docker github actions

moveit_core/planning_scene/src/planning_scene.cpp
This partially fixes #3291
Instead of adding shapes to an existing scene object, a conflicting object is now first removed before restoring the one from file.
=> Fix loading of PS from .scene text file: Replace existing world objects

moveit_core/trajectory_processing/CMakeLists.txt, moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp
In order to get this test passing reliably, increase the allowable trajectory duration.
=> Debug Ruckig tests

moveit_core/collision_detector_bullet_description.xml, moveit_core/collision_detector_fcl_description.xml, moveit_kinematics/cached_ik_kinematics_plugin_description.xml, moveit_kinematics/kdl_kinematics_plugin_description.xml, moveit_kinematics/lma_kinematics_plugin_description.xml, moveit_kinematics/srv_kinematics_plugin_description.xml, moveit_planners/chomp/chomp_interface/chomp_interface_plugin_description.xml, moveit_planners/chomp/chomp_interface/plugin_description.xml, moveit_planners/pilz_industrial_motion_planner/plugins/pilz_industrial_motion_planner_plugin_description.xml, moveit_planners/pilz_industrial_motion_planner/plugins/planning_context_plugin_description.xml, moveit_planners/pilz_industrial_motion_planner/plugins/sequence_capability_plugin_description.xml, moveit_planners/sbpl/ros/sbpl_interface_ros/plugin_description.xml, moveit_plugins/moveit_ros_control_interface/moveit_core_plugins.xml, moveit_plugins/moveit_ros_control_interface/moveit_ros_control_interface_plugins.xml, moveit_ros/perception/moveit_depth_self_filter.xml, moveit_ros/planning/trajectory_execution_manager/lib/plugin_description.xml
Pluginlib will search the default paths anyhow.
=> Don't hard code plugin path to lib/

moveit_core/trajectory_processing/include/moveit/trajectory_processing/ruckig_traj_smoothing.h, moveit_core/trajectory_processing/src/ruckig_traj_smoothing.cpp, moveit_core/trajectory_processing/test/test_ruckig_traj_smoothing.cpp
Previously I didn't understand the difference between `ruckig::Finished` and `ruckig::Working` so I focused only on `ruckig::Finished`. There's not much documentation but here it is:  https://github.com/pantor/ruckig/blob/master/include/ruckig/result.hpp
This corrects that error and adds a comment. A new test is also added.
=> [Ruckig traj smoothing] Add a test, termination condition bugfix

moveit_ros/perception/mesh_filter/src/depth_self_filter_nodelet.cpp
According [this issue](https://github.com/ros-planning/moveit/issues/3364) there is memory leak from mesh filter. I hotfixed the problem according to the issue
=> Memory leak hot fix for mesh filter

moveit_ros/moveit_servo/src/servo_calcs.cpp
Fixes #3408. The condition number of the Jacobian _grows_ towards a singularity.
=> Fix misleading comment

moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h
Solve the error occurred during compilation:
=> Update time_optimal_trajectory_generation.h: include <unordered_map>

moveit_ros/move_group/src/move_group_context.cpp, moveit_ros/planning/moveit_cpp/src/moveit_cpp.cpp
Uncaught exceptions thrown during planning pipeline initialization caused the move_group node to crash...
=> Gracefully handle exceptions thrown by planning pipelines

moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
Fix for #3007. The PR consists on transforming mesh/primitive poses by root pose to when checking if the object is within ROI (not simply mesh/primitive poses as now). More details on the issue description. 
I noticed that the same problem exists on ROS 2
=> Fix: consider collision_object's pose when checking if it's inside the ROI

moveit_core/collision_distance_field/src/collision_distance_field_types.cpp
=> Gracefully handle zero-size bodies in determineCollisionSpheres()

moveit_commander/src/moveit_commander/planning_scene_interface.py, moveit_commander/test/python_moveit_commander.py, moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp, moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp
This PR addresses several shortcomings of the current python API for PSI. See individual commit messages for details.
Closes #3527
=> Augment Python PlanningSceneInterface API

moveit_core/robot_state/CMakeLists.txt, moveit_core/robot_state/test/robot_state_benchmark.cpp, moveit_core/utils/src/robot_model_test_utils.cpp
From #3548, just keep the transition to the Google benchmark lib.
=> Benchmarking with Google benchmark

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h, moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp, moveit_ros/planning/planning_scene_monitor/test/current_state_monitor_test.cpp
This commit is a rebase of #3580 and introduces:
1. per-group current state time retrieval
2. per-group complete robot state waiting
This fixes the following issue: 
I want to call waitForCompleteState on group_A, which the API already supports. There is also another joint out_of_group_A in the robot model that is not available until some time after bringup.  I'm calling waitForCompleteState(group_A, <timeout>) way earlier than out_of_group_A is published by its source. The problem with the current implementation is that it waits until <timeout> elapses, but returns true since all joints of group_A exist. I don't see a point in waiting for an out-of-group joint in this case.
=> Allow waiting for joint model group states and retrieval of group-specific timestamps (#3580)

README.md
=> Add moveit pro tutorials reference

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp
Fixes #3612 implementing the proposed solution from there
=> nullspace exploration: reset sliders to zero before hiding

moveit_core/kinematic_constraints/src/kinematic_constraint.cpp, moveit_ros/robot_interaction/src/robot_interaction.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_joints_widget.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp
See commit messages for details
=> Fix several small issues with rviz gui

moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/test/chomp_moveit.test, moveit_planners/chomp/chomp_interface/test/chomp_moveit_panda.test, moveit_planners/chomp/chomp_interface/test/chomp_moveit_rrbot.test, moveit_planners/chomp/chomp_interface/test/chomp_moveit_test_panda.cpp, moveit_planners/chomp/chomp_interface/test/chomp_moveit_test_rrbot.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
Fixes #2542
@captain-yoshi, could you please verify and review?
=> Fix CHOMP segfault

README.md
=> Correct moveit logo path in readme.md file

moveit_core/robot_state/src/cartesian_interpolator.cpp
=> Fix Cartesian interpolation

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/ci.yaml, .github/workflows/docker.yaml, moveit_core/package.xml, moveit_core/robot_state/test/test_cartesian_interpolator.cpp, moveit_kinematics/package.xml, moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp, moveit_planners/pilz_industrial_motion_planner/package.xml, moveit_setup_assistant/src/tools/moveit_config_data.cpp
Drop Melodic from CI and remove Melodic-specific code branches.
=> Drop Melodic support

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
Updated a comment on line 136 per issue #3358
I updated a comment on line 136 of moveit/moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h to reflect the information posed in issue #3358. 
(As a note - this is my first ever pull request, my sincerest apologies if I did something wrong. I have followed the guidelines in the contribution documentation to the best of my abilities). 
=> Update joint_model_group.h doc

moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh
The script uses Docker containers itself and was attempting to share files with the spawned containers using bind mounts. I solved this by switching to explicit docker create and docker start commands, and used docker cp to copy files in and out, since docker cp supports being run from inside a container.
Backported from https://github.com/moveit/moveit2/pull/3517.
=> Support running IKFast script from a Docker container

moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp, moveit_ros/planning/plan_execution/src/plan_execution.cpp, moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
=> Fix race condition when stopping trajectory execution
