moveit/moveit

moveit.rosinstall
Probably superseded by https://github.com/davetcoleman/moveit_merge/pull/5
=> moveit.rosinstall: Use the unified repo from ros-planning

.travis.before_script
run apt-get and dpkg commands as sudo. Required when this script is being run on a local machine, rather than Docker. See issue #8.
=> Fix permissions in .travis.before_script

moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp
This simplifies the use of a custom external grasp planning service.
First commit:
We should be allowed to call the grasp planner in the fillGrasps method without specifying a type for the object.
Second commit:
If the object doesn't exist the method should return immediately and should not produce broken grasps.
Third commit:
The collision_object_name in the grasp planning request wasn't set.
=> Improve fillGrasp method for pick("object_name") interface

moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
This reverts commit a7414a5cf572673a05c99ec95a0a531374b3aff8 from https://github.com/ros-planning/moveit_ros/pull/730
This change causes the default Rviz to segfault in Kinetic (maybe earlier) when you load the MotionPlanningPlugin.
The backtrace is [here](https://gist.github.com/davetcoleman/cbb966e5916f2c72beb0e41bd9aefbfb)
The relevant line is 
```
#5  0x00007fff85a43b49 in moveit::core::RobotModel::RobotModel (this=0x7fffb4001c00, urdf_model=..., srdf_model=...) at /home/dave/ws_moveit/src/moveit/moveit_core/robot_model/src/robot_model.cpp:56
56	  buildModel(*urdf_model, *srdf_model);
```
The boost pointer throws an assertion when ``urdf_model`` is dereferenced.
There might be a fix for this segfault that perhaps @v4hn can address but this PR fixes what introduced the bug.
=> Revert "initialize RobotModel even if URDF is empty"

moveit_core/package.xml
Once https://github.com/ros/rosdistro/pull/12287 is merged in we will need to switch the dependency here
@j-rivero
note: do not cherry-pick with older distros
=> Switch FCL dependency to correct name

.docker/README.md, .docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile
This is the [first step](https://github.com/ros-planning/moveit/issues/52) towards deprecating moveit_docker with the advantage that for every code change to the repo, the dockers will be automatically triggered to rebuild.
=> Add Docker to main MoveIt! repo

moveit_ros/perception/depth_image_octomap_updater/CMakeLists.txt, moveit_ros/perception/lazy_free_space_updater/CMakeLists.txt
cmake complained on each build that the targets do not exist.
It's right.
I changed them to the more generic EXPORTED_TARGETS variable.
Please pick to j/k.
=> fix broken cmake dependencies

moveit_ros/move_group/src/default_capabilities/execute_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_service_capability.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
This was never cherry-picked to kinetic. Runs ExecuteService in a separate thread.
Use of AsyncSpinner is not problematic, because the service capability is initialized in the main thread.
indigo-devel merge: 5fbc40006bd7f937c34181ea4f3d02eb86e92dcb
=> cherry-picked moveit_ros#717

.docker/release/Dockerfile, .docker/source/Dockerfile
I forgot the kinetic branch still requires shadow-fixed, and the rosdep rules were just updated so an update() is called
Should have tested locally the first time, this time I verified it worked locally.
=> Fix kinetic docker build

moveit.rosinstall
manipulation_msgs and household_objects_database_msgs have been released into kinetic, this is no longer needed
Also I think we should just leave geometric_shapes and srdfdom in the rosinstall file, since they are part of ros-planning and are sometimes useful for moveit developers to use and see the source code
=> Removed now-released messages from rosinstall file

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajectory_execution.launch.xml
As per subject.
As this will only affect newly created configurations directly, I estimate the impact of this change for existing users to be low.
=> msa: push traj exec monitor params down into proper ns

moveit_plugins/moveit_fake_controller_manager/README.md, moveit_plugins/moveit_fake_controller_manager/doc/tutorial.rst, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controllers.cpp
Changed parameter name for interpolating controller to be more verbose:
move_group/rate -> move_group/fake_interpolating_controller_rate
Should be cherry-picked to Indigo/Jade.
=> use more verbose param name fake_interpolating_controller_rate

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
For https://github.com/ros-planning/moveit/pull/68#issuecomment-240586343
This is a bug.
=> [moveit_ros_planning] Fix missing dynparam setup for TrajectoryExecutionManager

.docker/ci/Dockerfile
This didn't get properly cherry-picked from the kinetic patch (my fault)
=> Remove unavailable debians from docker CI

moveit/package.xml, moveit_commander/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_controller_manager_example/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_plugins/package.xml, moveit_plugins/moveit_ros_control_interface/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/benchmarks_gui/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/perception/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_setup_assistant/package.xml
See https://github.com/davetcoleman/moveit_merge/issues/9 for more.
Updated version number of packages using a simple script (pasted at the bottom).
- Once this LGT, I'll do so for Indigo too. And maybe directly commit w/o PR to not bother maintainers if no objection (I don't mind opening PRs).
- Version here is 0.8.2 instead of `0.8.3` as discussed in https://github.com/davetcoleman/moveit_merge/issues/9#issuecomment-239541170; Once this gets merged, running `catkin_prepare_release` will increment all versions to 0.8.3.
- No package.xml found in some folders, incl. `moveit_experimental`, which indicates it's not ready to be released. So I leave then as they are.
- Version of `moveit_ikfast` not updated (https://github.com/ros-planning/moveit/pull/44). The script updates it but had to …
=> [Jade] Unify package version numbers 

.docker/source/Dockerfile
The jade-source docker build is timing out: https://hub.docker.com/r/moveit/moveit/builds/bonv9hzxwkrwhgvxtapvtkh/
Not sure if this was the reason, but this is def a bug
=> Jade fix Docker shadow-fixed url

moveit/CHANGELOG.rst, moveit_commander/CHANGELOG.rst, moveit_core/CHANGELOG.rst, moveit_planners/moveit_planners/CHANGELOG.rst, moveit_plugins/moveit_plugins/CHANGELOG.rst, moveit_ros/moveit_ros/CHANGELOG.rst, moveit_setup_assistant/CHANGELOG.rst
Usually I don't think we need PR for changelog update, but I do so this time since this is the 1st one for consolidated repo and it's 100% hand-made. Although I'm not sure what I want to be reviewed, any comment is appreciated.
- [`catkin_generate_changelog` didn't work for this consolidated repo for its initial release](http://answers.ros.org/question/242004/catkin_generate_changelog-issue-with-a-repo-that-consolidated-multiple-repos/), so manually compiled all changelog files.
- Prefixed almost all logs for visibility. The following list is ordered below by importance IMO, and the actual entries are ordered in this way as well: 
- `feat`: new feature
- `fix`
- `improve`: perfomance improvement
- `doc`
- `sys`: system change (e.g. Change for cmake, installation, CI etc.)
- Since the log …
=> [jade] Changelog 0.8.3

.docker/README.md, .docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile, README.md
Almost same as https://github.com/ros-planning/moveit/pull/53 and jade version, but doesn't use shadow fixed or call rosdep update
Tested locally
=> [indigo] Add Docker to main MoveIt! repo

moveit_ros/move_group/CMakeLists.txt, moveit_ros/move_group/default_capabilities_plugin_description.xml, moveit_ros/move_group/src/default_capabilities/execute_path_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_path_action_capability.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
Moved from https://github.com/ros-planning/moveit_ros/pull/719
Depends on https://github.com/ros-planning/moveit_msgs/pull/24
=> Add capability of execute known trajectory with a ROS action

moveit_ros/move_group/CMakeLists.txt
The capabilities include the message headers and therefore have to depend on them.
As reported in https://github.com/ros-planning/moveit/issues/92#issuecomment-241196766
we missed this dependency. Thanks to @jettan for the report!
Please cherry-pick to jade and kinetic
=> add missing cmake dependency

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/warehouse.launch, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/warehouse_settings.launch.xml, moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template
as suggested in #75, this makes it possible to connect to the database as long as you have warehouse_ros and warehous_ros_mongo properly built.
tested in kinetic only but there's no reason it wouldn't work on jade.
=> Modified launch file templates to be able to connect to the warehouse

moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
In #77 (cherry-picked from #70) a typedef for `ObjectConstPtr` was fixed to actually be a pointer-to-const, but it appears in the public API in a number of places. To avoid API breakage within indigo, this PR reverts the specific changes that touch the API. See also #98.
Note: This should not be cherry-picked to Jade or Kinetic.
=> Revert API change due to corrected ObjectConstPtr typedef.

moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_planners/ompl/ompl_interface/cfg/cpp/ompl_interface_ros/OMPLDynamicReconfigureConfig.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/constraints_library.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constrained_valid_state_sampler.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constraint_approximations.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space_factory.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
I'm working down grep results for `boost::shared_ptr` in pretty much arbitrary order. This PR tackles `moveit_planners/*` and `moveit_experimental/*`.
Additionally, I added a macro `MOVEIT_STRUCT_FORWARD`. When compiling with `-Wall -Wextra`, gcc will emit a warning when a forward declaration and definition mismatch in use of `struct` or `class`. The extra macro can avoid that warning.
I also added `MOVEIT_DECLARE_PTR` (and modified the other macros to use it) to support declaring `shared_ptr` types for more complex types. For example, there was a `typedef boost::shared_ptr<std::vector<ConstraintApproximation> > ConstraintApproximations`. That becomes `MOVEIT_DELCARE_PTR(ConstraintApproximations, std::vector<ConstraintApproximation>)` with the new macro (order of arguments chosen to match …
=> Reduce explicit mention of boost::shared_ptr in moveit_planners and moveit_experimental

moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_planners/ompl/ompl_interface/cfg/cpp/ompl_interface_ros/OMPLDynamicReconfigureConfig.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/constraints_library.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constrained_valid_state_sampler.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constraint_approximations.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space_factory.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
Cherry-pick from https://github.com/ros-planning/moveit/pull/97
=> [indigo] Reduce explicit mention of boost::shared_ptr in moveit_planners and moveit_experimental

moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_planners/ompl/ompl_interface/cfg/cpp/ompl_interface_ros/OMPLDynamicReconfigureConfig.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/constraints_library.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constrained_valid_state_sampler.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/constraint_approximations.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space_factory.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/work_space/pose_model_state_space.h
Cherry-pick from https://github.com/ros-planning/moveit/pull/97
=> [jade] Reduce explicit mention of boost::shared_ptr in moveit_planners and moveit_experimental

moveit_ros/move_group/CMakeLists.txt, moveit_ros/move_group/default_capabilities_plugin_description.xml, moveit_ros/move_group/include/moveit/move_group/capability_names.h, moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.h, moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.h, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/demo.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
This reopens #85/#60 against kinetic. As proposed in https://github.com/ros-planning/moveit_msgs/pull/27#issuecomment-241198797, I suggest to drop that new feature for Indigo, because we require user intervention to switch `moveit_config`'s launch files to the new capability.
Additional to @wkentaro great work (from #85), I cleaned up the waiting for required action servers and services to allow to issue the deprecation warning once on startup.
=> Reopen #85: Add capability to execute trajectory with a ROS action

moveit_core/collision_detection/include/moveit/collision_detection/world.h
The changes to support FCL 0.5 require geometric_shapes 0.5.0. Older versions will trigger ugly compile warnings such as the one belowx.
This PR adds a static assert to verify that the geometric_shapes used has the correct API (uses `std::shared_ptr`). I'm not entirely happy with the message since it doesn't explain why `geometric_shapes >= 0.5.0` is needed, but I guess the message would get very long otherwise.
Additionally, I think it would be even better to verify this during the configure stage in cmake rather than compile time. Preferably by checking the `geometric_shapes` version (if possible), or with a minimal compile test.
Checking in the cmake stage does not catch the situation where moveit is compiled with the proper `geometric_shapes`, but another packages using moveit headers …
=> Check geomtric_shapes API with static_assert.

moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp
Otherwise the tests won't compile on kinetic:
```
/home/jbinney/ws/moveit_hackathon/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:69:41: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double mesh_filter_test::FilterTrai
ts<short unsigned int>::ToMetricScale’ of non-integral type [-fpermissive]
static const double ToMetricScale = 0.001;
^
/home/jbinney/ws/moveit_hackathon/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:77:41: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double mesh_filter_test::FilterTrai
ts<float>::ToMetricScale’ of non-integral type [-fpermissive]
static const double ToMetricScale = 1.0f;
```
(it seems like the tests weren't run on kinetic after c++11 …
=> Add constexpr to static test member

moveit_core/collision_detection/include/moveit/collision_detection/world.h
Fix for https://github.com/ros-planning/moveit/pull/131
=> Fix geometric_shapes warning version

moveit_ros/visualization/CMakeLists.txt
A test case for joy node keeps failing https://github.com/ros-planning/moveit/pull/46#issuecomment-239901030 on ros.org buildfarm only. Since neither the particular test nor the component is critical to the entire moveit suite, Dave and I [agreed to disable it for now](https://github.com/ros-planning/moveit/pull/46#issuecomment-241915890).
Portable to JK.
=> Temporarilly disable a test that only fails on ros.org buildfarm.

moveit_ros/visualization/CMakeLists.txt, moveit_ros/visualization/test/test_moveit_joy.py
Instead of disabling the joystick unittest, I suggest to exit python without performing usual cleanup routines as proposed in https://github.com/ros-planning/moveit/pull/105.
This reverts commit f254737b8c1ef83ad4fce9501da12c46b7eaf88d / #143.
Should be cherry-picked to I/J again.
=> alternative fix for joystick unittest

moveit_ros/robot_interaction/include/moveit/robot_interaction/interaction_handler.h, moveit_ros/robot_interaction/src/interaction_handler.cpp
Simple fix for #5 (Warning: return returning reference to temporary).
=> Remove const& from getKinematicsQueryOptions to fix warning

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/demo.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
We missed two issues before merging #94:
* assignment doesn't work with `==`
* Switching to the correct `WallDuration` interface for `MoveGroupInterface`, made the constructors ambigue if not the full signature is specified. Hence, I propose to remove the default values for the old constructor. This will automatically choose the new version, which is preferred anyway.
Please also cherry-pick into Jade. #94 was not yet merged into Indigo. I will integrate this patch into #144 as well, which is the corresponding PR for Indigo.
=> fix remaining issues in #94

moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
It confused a generation of RViz users why the scene displayed in RViz
is not ok... Well, the reason is because the user should usually
look at the monitored scene instead.
Needs to be picked to j/k.
Fixes #156.
=> rviz display: make move_group/monitored_planning_scene the default

moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
This came up because the code does not complain when no parameter was set.
Before, the code did not print an error when the parameter was not set at all.
Should be picked to j/k
=> simplify RDFLoader & provide more/better error message

moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp, moveit_ros/visualization/test/moveit_joy.test, moveit_ros/visualization/test/test_moveit_joy.py
Follow up for #149. Again, ROS buildfarm failed on the joystick test...
This (hopefully) fixes the issue finally. 
Actually there seems to be a bug in rostest as well: Because our python bindings segfaulted due to an empty robot model (https://github.com/ros-planning/moveit_commander/issues/32), rostest didn't finish correctly, but reported the test as [`SUCCEEDED`](https://github.com/ros-planning/moveit/pull/149#issuecomment-242361420), while the unittest log file was empty. This made only ROS buildfarm to fail, which do some extra analysis of the log files...
=> fixed moveit_joy test

.docker/README.md, .docker/experimental/Dockerfile
As discussed in https://github.com/ros-planning/moveit_docker/pull/3
=> Creating an experimental moveit docker image - warehouse / mongo

moveit_core/collision_detection_fcl/CMakeLists.txt, moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/constraint_samplers/CMakeLists.txt, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/kinematic_constraints/CMakeLists.txt, moveit_core/kinematic_constraints/test/test_constraints.cpp, moveit_core/planning_scene/CMakeLists.txt, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_core/robot_model/CMakeLists.txt, moveit_core/robot_model/test/test.cpp, moveit_core/robot_state/CMakeLists.txt, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_core/robot_state/test/test_transforms.cpp, moveit_experimental/collision_distance_field/CMakeLists.txt, moveit_experimental/collision_distance_field/test/test_collision_distance_field.cpp, moveit_planners/ompl/ompl_interface/CMakeLists.txt, moveit_planners/ompl/ompl_interface/test/test_state_space.cpp, moveit_planners/ompl/package.xml
Depending on https://github.com/ros-planning/moveit_resources/pull/7 this is the second part of https://github.com/ros-planning/moveit/issues/17
- adapting source to match the renaming of test -> pr2_descriptionn in https://github.com/ros-planning/moveit_resources/pull/7
UPDATE: The integration tests will be filed as a separate PR. They should be disabled for now anyway, because they are blocked by:
- [`pyassimp` failure in `kinetic`](https://travis-ci.org/ros-planning/moveit/builds/153589357): **That's a `moveit_commander` regression!**
- cleanup.test: https://github.com/ros/ros_comm/pull/871
- validate_traj.test: https://github.com/ros-planning/moveit/pull/63
- robot_state_update.test: https://github.com/rhaschke/moveit/pull/1
=> adaptions to testing code to match ros-planning/moveit_resources#7

moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp
Although the mesh filter is disabled on build farms (because of missing `DISPLAY`), running it locally takes ages. It turned out, that the test is actually failing and filing an error message for each and every pixel of the 250.000 pixel test images. Using `ASSERT` instead of `EXPECT` macros, this PR makes the test fail immediately on the first failing pixel.
I'm not sure why the test actually fails. Someone with more background in the perception code should have a look!
By purpose, I didn't disable the test. As it doesn't run on CI build farms (this should be fixed too), their outcome will not be affected.
=> mesh_filter_test: don't report errors on all 250.000 pixels

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h
The interface looks quite similar to `PlanningScene::checkCollision`
and users might expect it to behave the same way.
However, that's not the case because the distanceToCollision function family
ignores self-collisions.
The additional note should reduce confusion as seen in #166.
should be picked to j/k
=> scene: add comment on self-collisions to distanceToCollision functions

moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/author_information_widget.cpp, moveit_setup_assistant/src/widgets/author_information_widget.h, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.h, moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template
This is the follow up of [this PR](https://github.com/ros-planning/moveit_setup_assistant/pull/124). I used filter-branch to restructure the old repo and cherry picked the commits afterwards.
This is a extension to the work of @v4hn who has included a widget which asks for the author's name and email adress. Following features have been implemented (as suggested by #16):
- It is now checked if a name and a valid email was entered and it is only possible to finish the assistant if the information was provided
- Name and email adress are stored in .setup_assitant and are loaded again when the configuration is edited again. In case an old configuration (with the old default email assistant@moveit.ros.org) is loaded, the author information is empty (since it was not stored in …
=> Require author information in gui

moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h
Fix for issue #136:
When dynamically attaching a object to a given robot link without geometry, it would be ignored during collision checking because links without geometry are not included in the active_comonents_only_ set.  
This was solved by exposing an existing JointModelGroup class member providing a complete set of updated links (with and without geometry) and using this method in collision_detection::CollisionData::enableGroup.
=> Fix issue #136

moveit_commander/package.xml, moveit_core/package.xml, moveit_ikfast/package.xml, moveit_planners/moveit_planners/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_controller_manager_example/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/benchmarks/package.xml, moveit_ros/benchmarks_gui/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/moveit_ros/package.xml, moveit_ros/perception/package.xml, moveit_ros/planning/package.xml, moveit_ros/planning_interface/package.xml, moveit_ros/robot_interaction/package.xml, moveit_ros/visualization/package.xml, moveit_ros/warehouse/package.xml, moveit_setup_assistant/package.xml
`package.xml` is the official manifest of a package and always needs updated with correct info, so here's an update.
=> [package.xml] Fix repository URLs.

moveit_ros/planning/trajectory_execution_manager/cfg/TrajectoryExecutionDynamicReconfigure.cfg
Adding the new parameter here broke ABI in two ways:
1. adding the new member
2. moving execution_velocity_scaling to a different position
We want to have the parameter here, so we will break ABI with 1.
Nevertheless, to avoid data-misinterpretation in case of ABI issues,
this commit undoes the second part.
This commit is only about ABI stability and there is no need to pick it to jade and kinetic.
=> undo reordering of dynamic reconfigure parameters in trajectory execution manager

moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/distance_field/include/moveit/distance_field/propagation_distance_field.h, moveit_core/distance_field/include/moveit/distance_field/voxel_grid.h, moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controllers.h, moveit_plugins/moveit_ros_control_interface/include/moveit_ros_control_interface/ControllerHandle.h, moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/depth_self_filter_nodelet.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/mesh_filter.h, moveit_ros/perception/mesh_filter/src/mesh_filter_base.cpp, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
This PR uses MOVEIT_CLASS_FORWARD (and friend) to remove the last explicit use of `boost::shared_ptr` to any moveit type in this repository, with the exception of `moveit_experimental/*` and the chomp and sbpl planners.
I looked for any remaining explicit `shared_ptrs` to moveit types with this pretty one-liner:
```
grep -rP 'boost::shared_ptr<(?!(?:const )?(?:tf::|srdf::|urdf::|rviz::|interactive_markers::|image_transport::|pluginlib::|ros::|KDL::|shapes::|actionlib::|QTimer|QSettings|QProgressDialog))'
```
=> Use MOVEIT_CLASS_FORWARD for the last shared_ptrs to moveit types

moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection/src/collision_octomap_filter.cpp, moveit_core/collision_detection/test/test_world.cpp, moveit_core/collision_detection/test/test_world_diff.cpp, moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/distance_field/include/moveit/distance_field/distance_field.h, moveit_core/distance_field/include/moveit/distance_field/find_internal_points.h, moveit_core/package.xml, moveit_core/robot_model/include/moveit/robot_model/link_model.h, moveit_core/robot_state/src/attached_body.cpp, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_ros/perception/semantic_world/include/moveit/semantic_world/semantic_world.h
As geometric_shapes 0.5.1 now requires C++11, we should try to reduce exposure of its headers to a minimum. Otherwise we enforce downstream code to compile with C++11 too.
Using forward declarations, in many cases, exposure can be avoided.
=> reduce exposure of geometric_shapes headers (that requires C++11)

.docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile, README.md
Currently [MoveIt!'s CI](https://github.com/ros-planning/moveit/blob/kinetic-devel/.docker/ci/Dockerfile) is using the non-shadow-fixed version of kinetic-desktop. This OSRF container is only retriggered when the base Ubuntu container is rebuilt, and it appears its been awhile. The image we're using for ROS is now [2 months old](https://hub.docker.com/r/osrf/ros/builds/).
This switches to use the main ROS container, instead of OSRF's. The ROS one was updated [10 days ago](https://github.com/docker-library/repo-info/blob/master/repos/ros/tag-details.md). The difference is that there isn't a desktop-full version, unlike what OSRF offers. This also runs a dist-upgrade to ensure we have the latest version of packages, which currently results in an increase of the container of 200 MB (not bad) …
=> Optimize size of Docker CI container and ensure newer version of packages

moveit_core/constraint_samplers/src/union_constraint_sampler.cpp, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp
This fixes the failing assertion in the unit tests. It fixes a bug where constrained samplers were being passed robot states with dirty link transforms. This is an issue when IKConstraintSamplers are used because they read the frame transforms to get the pose of the end-effector.
=> Update links in union constraint sampler and fix unit test.

.docker/README.md, .docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile
Currently Travis distinguishes between regular and shadow-fixed, but my recent change https://github.com/ros-planning/moveit/pull/214 I've realized causes all Travis builds to use shadow-fixed. This creates a new Docker image that is specifically for shadow-fixed: ``moveit/moveit:kinetic-ci-shadow-fixed``
I plan on back-porting these series of Docker changes to indigo and jade soon.
=> Create new shadow-fixed CI Docker image

moveit_ros/move_group/src/move_group_context.cpp, moveit_ros/planning/plan_execution/src/plan_execution.cpp, moveit_ros/planning/trajectory_execution_manager/CMakeLists.txt, moveit_ros/planning/trajectory_execution_manager/cfg/TrajectoryExecutionDynamicReconfigure.cfg, moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_ros/planning/trajectory_execution_manager/test/test_app.cpp, moveit_ros/planning_interface/test/python_move_group.py, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/trajectory_execution.launch.xml
Discussion continued from https://github.com/ros-planning/moveit/pull/63#issuecomment-247538638
@rhaschke feel free to make changes to this shared branch as necessary
=> [jade] validate trajectory before execution

moveit_setup_assistant/src/widgets/default_collisions_widget.cpp, moveit_setup_assistant/src/widgets/default_collisions_widget.h, moveit_setup_assistant/src/widgets/kinematic_chain_widget.cpp, moveit_setup_assistant/src/widgets/kinematic_chain_widget.h, moveit_setup_assistant/src/widgets/passive_joints_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.h, moveit_setup_assistant/src/widgets/setup_screen_widget.h
replacement for #203 using a better fix for the "highlighting on selection" issue
=> msa collision widget: highlight collision pairs in red/green, allow keyboard selection

moveit_core/robot_model/src/robot_model.cpp
A common tripping point for beginners is how to properly use virtual joints. Often (as I just did with the baxter_moveit_config in moveit_robots) users get the warning:
> No root joint specified. Assuming fixed joint
e.g.
http://answers.ros.org/question/165136/no-root-joint-specified-assuming-fixed-joint-moveit/
https://groups.google.com/forum/#!topic/moveit-users/a3W5sQcxRAM
https://groups.google.com/forum/#!topic/moveit-users/floIkUvtdyg
This adds very helpful feedback to diagnose the problem.
cherry-pick to I/J
=> Add better user feedback when virtual joint is misconfigured

moveit_core/constraint_samplers/src/default_constraint_samplers.cpp
The sampler uses the transforms, but never checked if they are dirty,
so it might return invalid/unexpected robot states.
@scottpaulin noticed this in #186 and fixed the calling code.
For safety reasons, we should also check in the sampler itself.
@scottpaulin could you please check out this patch and see if it triggers in the use-case you found?
=> add safety check to IKConstraintSampler

moveit_setup_assistant/src/widgets/start_screen_widget.cpp
From http://wiki.ros.org/xacro
> Because --inorder processing is much more powerful, in future version beyond Jade, the new processing style will become default and you should check the compatibility of your xacro files. 
Also in the console when using the MSA:
> xacro.py is deprecated; please use xacro instead
Do not cherry-pick to indigo, probably not jade either.
=> [setup_assistant] xacro fixes in kinetic

moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/src/conversions.cpp
This is part of the issue #103.
The current state is that the collision object will be removed from the planning scene when attaching
it to the robot with the asynchronous attachObject function of the move_group_interface.
So we want the same behavior with the synchronous apply planning scene service.
In this effect we added two error messages for the case that the roboState is_diff is not set.
=>  Remove of collision Object when attaching it with apply planning scene service

moveit_ros/planning/planning_request_adapter_plugins/src/add_time_parameterization.cpp
Reflexxes was never used for time parameterization but this commented out code has never been used. I noticed it will looking into https://github.com/ros-planning/moveit/issues/160
I've worked with Reflexxes extensively and in fact it does not provide the ability to choose the optimal time delta between two waypoints, it has a different purpose.
Can be cherry-picked to I/J
=> Remove commented out Reflexxes code

moveit_core/collision_detection/include/moveit/collision_detection/collision_world.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_world_fcl.h, moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp
There were already facilities in place to output debug information for the distance checks, but they were not connected to the verbose flag like the collision checking equivalent functions were.
This changes no functionality unless you do a collision request with verbose=true.
Also also clarified some distance messages that had just been copy-pasted from their collision checking equivalent, I moved one message, and added one.
I do not think this needs to be back-ported.
=> Allow distance checks to be verbose, just like collision checks

.docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/source/Dockerfile
Hack is for https://github.com/ros/ros_comm/issues/904
Also:
- Reduce memory footprint of ``shadow-fixed container`` by not depending on the ``ci`` container
- Force source CI to use 1 thread and show all output during build - hopefully this will stop the timeouts
- Make source CI build in release mode and install, to mimic the travis script builds
- Remove unnecessary rospack/rosbash dependencies
=> Add hack for rostest debian corruption

moveit_experimental/CMakeLists.txt, moveit_experimental/package.xml
Also: [moveit_experimental] Fix Eigen3 warning
fcl switched to libfcl-dev in kinetic, but somehow [Travis passed](https://travis-ci.org/ros-planning/moveit/jobs/162652412) but [Dockerhub did not](https://hub.docker.com/r/moveit/moveit/builds/bujkprszk2jbjpewwrenti6/)
=> [moveit_experimental] Fix incorrect dependency on FCL in kinetic

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
I falsely assumed the map is indexed by the name of the *links*
the objects are attached to and it took me a while to find evidence
that this is not the case.
should be picked to i/j
=> improve comment on internal class member

.travis.yml
https://github.com/ros-planning/moveit/pull/215 requires a version of pluginlib that is released but not synced yet, so we can only depend on shadow-fixed for now
=> Allow travis to pass only for shadow-fixed

.docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/source/Dockerfile
Build source image on shadow-fixed
Add wget for downloading package.xml files
I know I keep tweaking the Docker build and I apologize. Its hard to work around Docker's restrictive timeout constraints for our huge moveit build.
=> Fix source timeout

moveit_ros/planning_interface/move_group_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
This utilizes the new GraspPlanning service and provides a way to make use of external grasp
planners without also adding default grasps.
The service definition is proposed in:
https://github.com/ros-planning/moveit_msgs/pull/32
=> Add planGraspsAndPick method to move_group_interface

moveit_ros/planning/robot_model_loader/include/moveit/robot_model_loader/robot_model_loader.h, moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
In small test programs, I've been getting the following error:
```
[/kinematic_plugin_test] [1476222361.566864946]: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
```
I tracked this down to the order of the member variables in RobotModelLoader. Because the KinematicsPluginLoader is last, it gets destroyed before the robot model. The robot model contains shared pointers to the loaded kinematics plugins, so they haven't been destroyed yet. The kinematics plugin loader then gives the above "Severe Warning". Changing the order of variables corrects this.
To reproduce, compile the following program:
``` …
```
=> Destroy kinematics plugins before their loader

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
Without this, unlimited joints might get out of the bounds
in the trajectory and will fail the validation.
This resolves #283. In theory this deprecates #287 .
Feel free to improve the request, I pushed the request-branch to this repo.
The patch has been verified on our PR2.
Should be picked to j/k
=> enforce joint bounds for start state validation

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Allows one to turn off noisy debug messages from planning scene monitor while keeping on debug for moveit_planning package.
Can be backported to I/J
=> Namespaced console output for planning_scene_monitor

moveit_ros/moveit_ros/package.xml
Following https://github.com/ros-planning/moveit/pull/228
This change is required for `bloom` to make a release.
=> Remove an already-deleted moveit_ros_benchmark_gui from package.xml entry.

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/test/CMakeLists.txt, moveit_ros/planning_interface/test/movegroup_interface.py, moveit_ros/planning_interface/test/python_move_group.py
replaced deprecated MoveGroup with MoveGroupInterface in python-based unit test
re-enabled c++ unit test
=> Fix python movegroup usage

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp
This is a poor-man's-replacement for rhaschke's work that
waits for the current robot state. This can be removed after
his work is merged. (See https://github.com/ros-planning/moveit/pull/232)
Without the additional sleep the automatic update of the start state
will pick a point near the end of the executed trajectory instead of
the current state. Let's give the monitor a moment to catch up.
This is intended to be part of the next release because @rhaschke's code will probably not be in there.
=> wait a second before updating "current" in RViz

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h, moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp
.. to better reflect the actual semantics of the method.
To maintain API compatibility, the old function still exists, but is deprecated.
Again, this is extracted from #232.
=> renamed CSM::waitForCurrentState() to CSM::waitForCompleteState()

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
I merged #296 a little bit to early: I missed that the new member variable isn't class-global, which it actually should be. Also, assigning variables in the header works in C+11 only and fails (with a warning) on Indigo and Jade.
Please cherry-pick this to I/J too.
=> make new logger name_ a static member

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
...given time delta
This is being used by a project I'm working on to integrate [Descartes](http://wiki.ros.org/descartes) with MoveIt!, and is the same function as found within the Descartes [moveit_state_adapter](https://github.com/ros-industrial-consortium/descartes/blob/indigo-devel/descartes_moveit/src/moveit_state_adapter.cpp#L306) but with more of a MoveIt! flavor
@Jmeyer1292 @jrgnicho @shaun-edwards
=> isValidVelocityMove() for checking maximum velocity between two robot states

moveit_planners/chomp/chomp_interface/CMakeLists.txt
Since there isn't FindEigen3.cmake in cmake_modules of moveit on indigo branch, change this to find Eigen while require version greater than 3.
=> change find_package Eigen3 to 'Eigen 3' in chomp_interface

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Since clang-format is required now, I figured we should warn users with these templates
=> Add issue and pull requests templates for Github

moveit_setup_assistant/src/tools/moveit_config_data.cpp
Many users have complained about collision checking missing small obstacles ([ref](https://bitbucket.org/ompl/ompl/issues/100/solution-path-may-slightly-touch-on-an)). This will change the default value new users use when setting up a robot with MoveIt!. I'd actually prefer smaller (I use 0.005 in my configs), but I figure increasing the collision checking planning time by 5x is a big enough change for now.
Interestingly, the old arm navigation used [0.001](http://wiki.ros.org/arm_navigation/Tutorials/tools/Understanding%20and%20adjusting%20the%20autogenerated%20arm_navigation%20application), a very small value.
I think we should just keep this in kinetic, though we could pick it to IJ.
=> Increase the default discretization of collision checking motions

moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/package.xml
The [ompl_interface](https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_planners/ompl) folder is actually the package ``moveit_planners_ompl``. While I was updating the [list of moveit's packages](https://github.com/davetcoleman/moveit.ros.org/blob/b3522540426f63833eeaa7a7230592a9b383da5d/about/source_code.markdown) on the website yesterday I realized how inconsistent the naming convention is for the ``chomp_interface`` package:
> moveit - Metapackage
> moveit_core - Core functionality including RobotModel, RobotState, collision checking
> moveit_ros_planning - planning components, execution manager, plugin loaders
> moveit_ros_move_group - The move_group main node for using MoveIt! via ROS messages
> moveit_ros_planning_interface - Python and ROS msg interfaces to …
=> Rename chomp_interface to moveit_planners_chomp

moveit_core/CHANGELOG.rst
Quick fix to #318
@severin-lemaignan @v4hn Editor tools I'm using don't seem to handle correctly your name (I'll have to fix this in the near future). Hope this change would be ok for you for now.
- --> Not applicable; this is a fix.
- --> Not applicable; no GUI.
- --> Since this encoding issue have happened multiple times, I have to think of adding a check.
- --> Not applicable since this is required by kinetic-devel only.
=> Fix CHANGELOG encoding for 0.9.1 (Fix #318).

.docker/ci-wily/Dockerfile
As discussed https://github.com/ros-planning/moveit/issues/222, this will allow us to add a Travis test for Wily. Based on Docker image @tfoote suggested http://discourse.ros.org/t/drop-support-for-wily/727
=> Add Docker image for Wily

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
The default template launch files in the setup assistant generate lots of warnings in kinetic, same logic as described https://github.com/ros-planning/moveit/pull/238
Should not be picked to I/J
=> Fix xacro warnings in Kinetic

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
@mcevoyandy was mislead by [overlapping variable names](https://github.com/ros-planning/moveit_tutorials/pull/34/files#r85726172) so I've clarified the difference between planning time allowed for the solver, and the returned actual planning time. i do not think this should be backported to I/J
=> move_group_interface: Clarify variable name to reduce confusion

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
Reduces the verbosity of the planner configuration by setting the message to debug instead of info. As discussed in  #336
=> Change OptimizationObjective default message to Debug.

moveit_ros/manipulation/CMakeLists.txt, moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp, moveit_ros/manipulation/package.xml
The combination of the service support here and an optional hard-coded default grasp
is problematic because if the service is not available for any reason, but should be called,
the pick-request will end up with the hard-coded grasp.
This can create unexpected trajectories.
With MoveGroupInterface::planGraspsAndPick, a replacement for the removed functionality
is available.
This removes the dependencies on manipulation_msgs and household_objects_database_msgs.
(These were not even consistently specified in package.xml and CMakeLists.txt)
Should not be back-ported to retain current behavior.
=> remove grasp service support from pick_place's fillGrasp

moveit_setup_assistant/src/tools/moveit_config_data.cpp
I'm trying to improve the reliability of planning requests in the move_group_interface_tutorial as described in this [issue](https://github.com/ros-planning/moveit_tutorials/pull/34). I benchmarked two tests, 100 runs each:
1. Planning with orientation constraint
2. Planning around simple cuboid obstacle
I'm finding 3 problems:
- KPIECE solver is unreliable. Solution: remove projection_evaluator from ompl_planning.yaml (see https://github.com/ros-planning/moveit/issues/197)
- Planning time is too short. 10 seconds is much better than the 5 used by default for orientation
- longest_valid_segment_fraction (collision checking resolution) is too small
My results:
From this I recommend we change the default longest_valid_segment_fraction to **0.005**, even though I just recently had a similar …
=> Increase collision checking interval

moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp, moveit_setup_assistant/src/tools/moveit_config_data.cpp
This PR exposes the following OMPL planners:
geometric::FMT
geometric::BFMT
geometric::PDST
geometric::STRIDE
geometric::BiTRRT
geometric::LBTRRT
geometric::BiEST
geometric::ProjEST
geometric::LazyPRM
geometric::LazyPRMstar
geometric::SPARS
geometric::SPARStwo
Several other planners are available in OMPL, but from I found those to not work out of the box so some work would be required in integrating those.
To test: I have a forked moveit_resources (over [here](https://github.com/rbbg/moveit_resources/tree/kinetic-ompl-planners)) that has a ompl_planning.yaml with (parameter-less) configurations for these planners.
Due to the difference in OMPL version between kinetic and jade/indigo, this should not be cherry picked (I think).
=> Exposed planners from latest ompl release.

moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
We tested a new named target for our gripper, after an hour of searching we found out that the new target was not in our srdf. 
We expected that we get an error in this situation, so here is our suggestion.
=> Error message when requested target name does not exists

moveit_core/robot_state/src/robot_state.cpp
When using ``setFromIKSubgroups()`` it is actually tricky because the ordering of poses and tips must correspond exactly to the ordering of subgroups in a planning group in your SRDF. A much larger change is required to fix this sloppy API, but this PR simply adds better debug info to allow users to work around it easier.
Also, this PR makes it easier to understand why a group like "both_arms" might have more than just two subgroups "left_arm" "right_arm" but also for example "left_arm_6dof" etc
=> Improved RobotState feedback for setFromIK()

LICENSE.txt
I noticed on Github projects like [TensorFlow](https://github.com/tensorflow/tensorflow) there is now a license stat on the info bar
And I thought that would be nice for MoveIt! too. Adding this file will fix that for us. Should be picked to I/J
=> Add license file to root of project

moveit_setup_assistant/src/tools/moveit_config_data.cpp
Fixing a 2 mistakes in the default planner configuration of BFMT*. Note that the planner still seems to be a little slow on my system, so it doesn't always manage to find a solution with the default `moveit_resources demo.launch` within the alloted 5 seconds.
It should be identical to the default configuration now.
=> Fix BFMT default configuration parameters.

moveit_core/constraint_samplers/test/pr2_arm_ik.h, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/lma_kinematics_plugin.h, moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.h
@isucan pointed out in https://github.com/ros-planning/moveit_msgs/issues/3 that ``GetKinematicSolverInfo`` is no longer used. Here I replace an inappropriate dependency with the message ``KinematicSolverInfo``
=> Replace unused service dependency with msg dep

.travis.yml
The URDF header compatibility layer was removed because the fix was merged upstream, but now Travis does not pass for non-shadow-fixed until the next buildfarm sync
https://github.com/ros-planning/moveit/pull/319
=> Ignore non-shadow-fixed build failure

moveit_ros/move_group/include/moveit/move_group/capability_names.h, moveit_ros/move_group/src/move_group.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
Functionality in MoveIt!'s move_group node is implemented in terms of
MoveGroupCapability plugins. But until now the choice of which plugins
are loaded was solely left to the user who in many cases is not familiar
with these plugins at all. This entails that whenever we introduce or change
a basic capability we have to annoy the user with warnings on startup that
bug him to change and/or update his move_group.launch file.
This commit changes the startup behavior of move_group to load a specified
list of default capabilities and provides a new ROS parameter `disable_capabilities`
that can be used to disable default plugins.
I'm unsure about whether or not we should backport this to indigo/jade.
Personally I'm mildly in favor of backporting.
Fixes #125.
=> add list of default capabilities

moveit_core/constraint_samplers/test/pr2_arm_ik.h
Wily was still failing when building tests:
```
Errors     << moveit_core:make /root/ws_moveit/logs/moveit_core/build.make.001.log
In file included from /root/ws_moveit/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:39:0:
/root/ws_moveit/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.h:170:34: error: ‘**urdf::JointConstSharedPtr**’ has not been declared
void addJointToChainInfo(urdf::JointConstSharedPtr joint, moveit_msgs::KinematicSolverInfo &info);
^
/root/ws_moveit/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp: In member function ‘bool pr2_arm_kinematics::PR2ArmIK::init(const urdf::ModelInterface&, const string&, const string&)’:
/root/ws_moveit/src/moveit/moveit_core/constraint_samplers/test/pr2_arm_ik.cpp:61:3: error: …
```
=> Fix missing compatibility header for Wily

moveit_ros/move_group/include/moveit/move_group/capability_names.h, moveit_ros/move_group/src/move_group.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
This is a backport of #359. I'm not totally sure this *should* be backported,
but personally I'm slightly in favor of doing it. So here's the request.
Functionality in MoveIt!'s move_group node is implemented in terms of
MoveGroupCapability plugins. But until now the choice of which plugins
are loaded was solely left to the user who in many cases is not familiar
with these plugins at all. This entails that whenever we introduce or change
a basic capability we have to annoy the user with warnings on startup that
bug him to change and/or update his move_group.launch file.
This commit changes the startup behavior of move_group to load a specified
list of default capabilities and provides a new ROS parameter `disable_capabilities`
that can be used to disable default plugins.
=> add list of default capabilities (backport of #359)

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
I needed a way to overlay trajectory displays in an easy to distinguish way so I've added colouring to the trajectory_visualisation display. 
A video can be found here: 
https://www.youtube.com/watch?v=Vj0KNAOtFrw
**Please note that this is a PR to discover interest for this feature.**
Code is probably very dirty and doesn't meet any of the merging requirements, I haven't even rebased it on the current codebase yet, it's a few weeks old. **If I get a few thumbs up, I'd gladly tidy things up to be merged!**
PS: I love this checklist :+1:
=> WIP: Add colours to trajectory_visualisation display

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_core/robot_trajectory/src/robot_trajectory.cpp
So I spent some time yesterday trying to figure out why my code wouldn't compile. Turns out the `getWayPointDurationFromStart` function of `robot_trajectory::RobotTrajectory` wasn't using the same capitalization (Waypoint vs WayPoint) as all the other functions in the class. 
This PR fixes that but does keep the (deprecated using `MOVEIT_DEPRECATED` from `moveit/macros/deprecation.h`) old naming. I hope the deprecation is correct the way it is, but if not let me know.
=> Fix capitalization of getWayPointDurationFromStart in RobotTrajectory

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
Add colours to trajectory_visualisation display (backport of #362) for Jade
Thank you!
=> [jade] Add colours to trajectory_visualisation display (backport of #362)

.travis.yml
The buildfarm synced yesterday, so this is no longer needed.
=> Revert "Ignore non-shadow-fixed build failure (#360)"

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
Coloured trajectory visualisation (backport of #362)
Thank you!
=> [indigo] Add colours to trajectory_visualisation display (backport of #362)

moveit_commander/src/moveit_commander/planning_scene_interface.py
Error occurs when filename `str` is given
```
'str' object has no attribute 'empty'
```
Thank you!
=> Fix typo in moveit_commander planning_scene_interface.py

moveit_core/trajectory_processing/src/iterative_time_parameterization.cpp
These were defined above but not used?!
Should be picked to j/k
=> time parameterization: use constants

moveit_core/constraint_samplers/src/union_constraint_sampler.cpp
This extends #186 (0119d584bd77a754ed5108d0b222cbcb76326863).
Scott Paulin found that the UnionConstraintSampler should explicitly
update the LinkTransforms of the returned samples, because one of the
other samplers could require them to be valid.
Back then, we missed that the sampler also provides a `project` method
that has the same limitation. So I update the transforms there too.
This should be picked to j/k.
I triggered this today by adding a JointConstraint and an OrientationConstraint
as PathConstraints to a planning request.
**Update**: The JointConstraint alone is enough to trigger this, according to a mail on the mailing list.
Here's a stack-trace to reveal the calling code:
```
quat=..., ks=..., max_attempts=4)
at /home/v4hn/ros/indigo/moveit/src/moveit/moveit_core/constraint_sa …
```
=> update link transforms in UnionConstraintSampler::project too

moveit_kinematics/CMakeLists.txt
This should never have been merged into indigo.
- We do not support cmake 2.8.12 in indigo either.
@130s: this should fix the build failure in saucy you reported.
=> moveit_kinematics: should not be compiled with c++11 in indigo

moveit_setup_assistant/CMakeLists.txt
842b590cbe3cafa1e9e6e00989235ef26a6fcf91 introduced a minimum cmake of 2.8.12.
This was fully reasonable and worked at that time.
But the obsolete ubuntu saucy only provided 2.8.11 and it seems OSRF
now forces us to support this version more-or-less "for technical reasons".
This commit moves back to 2.8.11 and follows the advice of qt developers
to circumvent an old compile-flags problem with Qt5.
Notice that I did not have the chance to compile this on a saucy system!
=> re-enable support for cmake 2.8.11

moveit_core/CHANGELOG.rst
As per subject.
Made DOC job for Indigo fail ([job/Idoc__moveit__ubuntu_trusty_amd64/3](http://build.ros.org/job/Idoc__moveit__ubuntu_trusty_amd64/3/console) fi).
=> moveit_core: remove UTF char from v4hn's name in changelog.

moveit_core/planning_interface/include/moveit/planning_interface/planning_interface.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/ompl_interface.h, moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp
Eventually https://github.com/ros-planning/moveit/issues/197#issuecomment-257553968
made me look into this part of the code, and I cleaned it up a bit while I changed
ompl_interface to respect the default_planner_config setting ...
PR #340 introduced additional logic to select the configuration "group_name[default]" as
the default configuration and sets it to RRTConnect.
But there was already logic in place for this!
The previous default configuration is plainly called "group_name".
This basically reverts #340 and sets the (old and new) default config to RRTConnect.
Additionally, this unifies the default planner setup within the ompl_interface
with the variable "default_planner_config" that can be specified for
each group. This was previously only implemented in the RViz plugin
and could …
=> ompl_interface: uniform & simplified handling of the default planner

moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/test/CMakeLists.txt, moveit_ros/planning_interface/test/robot_state_update.py, moveit_ros/planning_interface/test/robot_state_update.test, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
This a new attempt to resolve #232. The core new idea is to wait until the robot has stopped moving before claiming the execution of a trajectory has finished.
=> fix race conditions when updating PlanningScene

moveit_ros/planning_interface/package.xml, moveit_ros/planning_interface/test/CMakeLists.txt
`moveit_resources` is used in multiple tests under `moveit_ros/planning_interface` ([here](https://github.com/ros-planning/moveit/blob/23d09fe7abbd77098657654bfb67fe8f8e409ff3/moveit_ros/planning_interface/test/python_move_group.test#L2), [here](https://github.com/ros-planning/moveit/blob/4bc43c56ca2a5293f3ef8d55796ec586cfde5f69/moveit_ros/planning_interface/test/cleanup.test#L2), [here](https://github.com/ros-planning/moveit/blob/4bc43c56ca2a5293f3ef8d55796ec586cfde5f69/moveit_ros/planning_interface/test/robot_state_update.test#L2)). 
I assume it's been luckily never an issue probably because the dependency has been met before the test jobs reach moveit_ros?.
I think this can be backported to IJ as well.
=> [moveit_ros] Missing test_depend.

moveit_setup_assistant/src/tools/collision_linear_model.cpp, moveit_setup_assistant/src/widgets/default_collisions_widget.cpp
As pointed out by @v4hn in https://github.com/ros-planning/moveit/pull/394#issuecomment-271185733, recent commit #394 broke Qt4 support for MSA. This is an attempt to fix it.
@v4hn I don't have a Trusty system around anymore. Could you please test this?
Feel free to push any necessary changes directly to this shared branch.
=> fix Qt4 compatibility for setup assistant

moveit_ros/planning_interface/test/CMakeLists.txt
Supersedes #414.
This test is reference in the tutorials and should also work with installed workspaces
http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html#integration-test
This should also be picked to i/j
=> install planning_interface python test

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
Copies the functionality used for setting and copying position values to a joint model group, but for velocities and accelerations. These are strictly helper functions for modifying the internal data of a RobotState more efficiently.  
Thank you!
=> Addition of Set Joint Model Group Velocities and Accelerations Functions

moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Something that has forever frustrated me is the warning when using a PlanningScene Rviz display:
> ros.moveit_ros_planning.planning_scene_monitor: Failed to call service get_planning_scene, have you launched move_group?
I would like to turn this into an INFO instead of a WARN, because often I startup Rviz in a separate terminal window from MoveGroup or whatever ROS node I'm using that publishes the planning scene.
Should be picked to J/K
=> Change planning_scene service warning to an INFO message

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
The documentation generated by osrf includes a broken
include path for this class, so let's set it to the correct
include explicitly.
This came up on answers.ros.org:
http://answers.ros.org/question/252157/where-is-the-document-for-namespace-of-move_group_interface/?answer=252189#post-id-252189
http://www.stack.nl/~dimitri/doxygen/manual/faq.html#faq_code_inc shows the correct syntax to fix this.
I tested it locally and it yields the correct documentation
=> mgi: show correct include path in doxygen

moveit_core/trajectory_processing/CMakeLists.txt, moveit_core/trajectory_processing/include/moveit/trajectory_processing/spline.h, moveit_core/trajectory_processing/include/moveit/trajectory_processing/spline_parameterization.h, moveit_core/trajectory_processing/src/iterative_time_parameterization.cpp, moveit_core/trajectory_processing/src/spline_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/src/add_spline_parameterization.cpp, moveit_ros/planning/planning_request_adapters_plugin_description.xml
As discussed in #160. I have used a GPL licensed spline fitting library ([this one](https://github.com/ttk592/spline)) to improve the performance of the iterative parabolic time parameterization algorithm that is used by MoveIt!. Unfortunately, the acceleration limits are still not satisfied completely, but it appears to be a step up from the previous approach.
Problems:
- The license. I am not too well versed in the what/why/how of open source licensing but I don't think GPL and BSD are compatible. Perhaps someone more knowledgeable on this front can offer some insight? If anyone is aware of a BSD licensed spline library that'd be great.
- The acceleration boundary conditions are not 0. This causes the waves you see between the first and second waypoints in the following figure:
=> Improved IPTP by fitting a cubic spline

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
This PR replaces `const_cast` with `static_cast` where possible. A `const_cast` is normally an indication of an API problem somewhere. The replaced casts only add `const`, so a `static_cast` will do just fine, with the added benefit that it doesn't look like dangerous things are happening.
Should be fine to pick to I/J. No API or ABI changes.
=> Replace const_cast with static_cast where possible

moveit_runtime/CMakeLists.txt, moveit_runtime/package.xml
Cherrypicking the change of https://github.com/ros-planning/moveit/pull/422. 
Note that for Jade (and Kinetic too), in addition to dropping `moveit_full` as suggested in https://github.com/ros-planning/moveit/pull/422#issue-202663652, we need to drop `moveit_full_pr2` as its dependency, moveit_pr2 is not met yet. Related https://github.com/ros-planning/moveit_pr2/issues/71
- J http://repositories.ros.org/status_page/ros_jade_default.html?q=moveit_pr2
- K http://repositories.ros.org/status_page/ros_kinetic_default.html?q=moveit_pr2
=> [Jade] Move a metapackage moveit_runtime from moveit_metapackage repo.

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Fixed copy paste error when mapping Python to C++ function
Kinetic-version of #437.
=> Fix typo in setMaxAccelerationScalingFactor mapping (kinetic #437)

moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
Fixed a bug with casting CallbackQueueInterface * to ros::CallbackQueue * without a check.
Without this additional check, creating an instance of MoveGroup in a nodelet causes a segmentation fault, because of different CallbackQueue implementations (nodelet::detail::CallbackQueue).
https://github.com/ros-planning/moveit/issues/425
=> move_group.cpp: seg fault bug fix

moveit_core/planning_scene/src/planning_scene.cpp
This implements a fix for #408.
When adding two different objects with color information one after the other (in two different PlanningScene updates), the color information of the first update is lost and overwritten during the second update.
As a result the color specified in the first update is lost and the existing (the first) object changes back to default-green in RViz.
In order to avoid memory leaks, I added explicit remove operations upon object removal.
However, this slightly changes current behavior: If you add an object with color information, remove it, and later on add that object back *without* specifying a color, the previous color was still cached - That is, unless any other PlanningScene update with color information was received in between.
Because of the changed behavior …
=> PS: Don't reset color information of existing objects when new entries are added

moveit_core/robot_state/src/robot_state.cpp
Objects with multiple collision shapes leave the question what the object's
internal frame is, because a pose is specified *for each shape* individually.
The RobotState::getFrameTransform function handled this by returning the first
registered pose as frame of reference.
This is a perfectly valid approach, so I changed the warning there to a debug message.
RobotState::knowsFrameTransform, however, returned false if asked whether the state knows the
transform for the object. That's inconsistant behavior: if `getFrameTransform` returns a valid result,
then the indicator should also reflect that.
Among other things, the pick-pipeline fails with objects with multiple collision shapes
without this change. I consider this a bug-fix, so I request to merge this into indigo (and forward-port it).
=> Handle multiple shapes in an attached collision object

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
This change connects the Motion Planning display with its widget and fixes these glitches:
Currently the Motion Planning panel is visible when RViz is started and the Motion Planning display is disabled:
After enabling and disabling the checkbox in the display panel the Motion Planning display is minimized: 
When the Motion Planning in the toolbar is disabled, nothing is visible when changing the entry in the display panel:
The changes of this pull request mirrors the way the image display handles this problem.
=> simplify widget handling

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group.h, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
Adds a convenience method to get all link names of a move group via the MoveGroup interface without the need to access the robot model hierarchy. This facilitates the configuration of allowed collisions between the move group and objects in the planning scene.
=> Implementing getLinkNames function for MoveGroup interface.

moveit_core/background_processing/src/background_processing.cpp, moveit_core/planning_request_adapter/src/planning_request_adapter.cpp, moveit_core/robot_state/src/conversions.cpp, moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp, moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp, moveit_ros/benchmarks/benchmarks/src/benchmark_execution.cpp, moveit_ros/benchmarks/src/BenchmarkExecutor.cpp, moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp, moveit_ros/manipulation/pick_place/src/manipulation_pipeline.cpp, moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp, moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp, moveit_ros/perception/mesh_filter/src/transform_provider.cpp, moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/robot_interaction/src/robot_interaction.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_context.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_manipulation.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_states.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
This adds the changes discussed on #270.
I have left only a couple of `catch (...)` instances where I think the changes can be omitted or I wasn't very comfortable with the change.
General logic copied over from the issue:
```
try
{
...
}
catch (std::runtime_error &ex)
{
logError("Exception caught while processing action '%s': %s", action_name.c_str(), ex.what());
}
catch (...)
{
logError("Exception caught while processing action '%s'", action_name.c_str()); // here important stuff may remain hidden
}
```
My proposed solution for the pattern above is this:
```
try
{
...
}
catch (std::exception &ex) // since std::runtime_exception < std::exception
{
logError("Exception caught while processing action '%s': %s", action_name.c_str(), ex.what());
}
```
Thank you!
=> Remove "catch (...)" instances, catch std::exception instead of std::runtime_error

moveit_commander/src/moveit_commander/planning_scene_interface.py
A fix for the numpy.ndarray indices bug, the second bug described in #86.
This fix was proposed by @lifangda01 in the same issue.
I was unsure what to do about clang-format, since it seems that it's for C++ only.
Thank you!
=> fixed numpy.ndarray indices bug (from #86)

moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
#377 against `jade-devel` was ported to kinetic-devel in #385 but never to indigo, so is this.
#437 seems also relevant, and is included in this PR.
Squashed into a single commit.
=> [indigo] cherry-pick #377 (Add set_max_acceleration_scaling_factor to moveit_commander).

moveit_core/CMakeLists.txt, moveit_experimental/CMakeLists.txt, moveit_kinematics/CMakeLists.txt, moveit_planners/ompl/CMakeLists.txt, moveit_plugins/moveit_controller_manager_example/CMakeLists.txt, moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt, moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt, moveit_ros/benchmarks/CMakeLists.txt, moveit_ros/benchmarks_gui/CMakeLists.txt, moveit_ros/manipulation/CMakeLists.txt, moveit_ros/move_group/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning/package.xml, moveit_ros/planning/planning_scene_monitor/src/trajectory_monitor.cpp, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/robot_interaction/CMakeLists.txt, moveit_ros/visualization/CMakeLists.txt, moveit_ros/warehouse/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
With gcc6, compiling fails with `stdlib.h: No such file or directory`,
as including '-isystem /usr/include' breaks with gcc6, cf.,
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129.
This commit addresses this issue for this package in almost the same way
it was addressed in various other ROS packages. A list of related
commits and pull requests is at:
https://github.com/ros/rosdistro/issues/12783
Particularly when searching for the Boost library CMake sets
Boost_INCLUDE_DIRS to @SYSROOT@/usr/include which should be
avoided in the `-isystem` option of gcc.
The same goes for OpenCV.
Fortunately neither Boost nor OpenCV trigger build warnings when their include dirs are not marked as system ones.
=> address gcc6 build error

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
The changes from the pull request #442 leads to an error.
Hiding the docking area when the motion planning panel is part of it disabled the whole display including the motion planning  *scene* that is displayed in the main window.
So instead of relying on the setAssociatedWidget mechanism, we have to implement the wanted behavior ourselves.
=> correct "simplify widget handling"

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
The class `ModelBasedPlanningContext` uses the initial robot state  `complete_initial_robot_state_`. This robot state might be dirty if transforms are not up to date, which can cause errors while planning. To prevent this the robot state needs to be updated after initialization and reset.
=> Always update initial robot state to prevent dirty robot state error.

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
I just tried to make use of this display for the first time
and now I keep wondering how people managed to use it in the first place...
Over here it segfaults when pressing Enter after changing the topic
and it does not connect to the topic when the display becomes enabled.
These patches address both problems.
Should be picked to jade.
=> Fix usability bugs in RobotState display

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h
As per title. definition was found to be missing: #456 
This should be cherry picked to both Jade and Kinetic as it's missing there as well.
=> Add definition of getStateUpdateFrequency in planningSceneMonitor.

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
This is the sister request to https://github.com/ros-planning/moveit/pull/455 .
The mentioned segfault appears on my (non-ubuntu) system with kinetic, so I'm not sure
how reproducible this is. Either way it probably makes sense to mark the required setup
of the robot model before connecting again.
=> improve RobotState display [kinetic]

moveit_ros/planning/CMakeLists.txt
This is a continuation for https://github.com/ros-planning/moveit/pull/423.
Somehow I overlooked the moveit_ros/planning package which also needs the same treatment.
=> address gcc6 build error (indigo-devel)

moveit_ros/planning/CMakeLists.txt
This is a continuation for #423.
Somehow I overlooked the moveit_ros/planning package which also needs the same treatment.
=> address gcc6 build error (kinetic-devel)

moveit_ros/warehouse/warehouse/src/warehouse_services.cpp
When launching the warehouse services, I got an error connecting to the warehouse which was due to not having the appropriate try/catch and also missing the conn->connect() call. With this pr, services are advertised correctly.
Thank you!
=> Fixing warehouse services

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
The MoveGroupInterface is meant to abstract away the ROS interfaces
used to communicate with the `move_group` node.
Nevertheless, it can be helpful to get the MotionPlanRequest that is
generated by the interface.
=> MoveGroupInterface: add public interface to construct the MotionPlanRequest

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui
The panel maintains an interactive marker by which the user can move
objects around in the planning scene.
Previously, this marker was created/updated whenever an object
was selected in the "Scene Objects" tab and geometry updates are received.
However, the marker should only be visible if the user actually
*wants* to manipulate the selected object, i.e. the correct tab is actually
active right now.
Because of the broken condition, the marker reappeared after
the user had selected an object (the marker appeared), selected a different tab
(the marker disappears), and the panel's planning scene monitor
received a geometry update afterwards. (This includes TRANSFORM updates that
are triggered by almost every interaction with move_group)
This should be cherry-picked to j/k.
Here's a …
=> rviz panel: Don't add object marker if the wrong tab is selected

moveit_ros/perception/mesh_filter/CMakeLists.txt, moveit_ros/robot_interaction/CMakeLists.txt
Without these `catkin_make -DCMAKE_ENABLE_TESTING=0` fails.
should be picked to j/k.
=> add missing cmake guards to catkin_add_gtest statements

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
Renaming the Motion Planning Display doesn't change the name of the Motion Planning Panel
right now.
These changes overrides the function setName of the display class, since we don't have a associated widget
the setName function from display doesn't work.
=> Renaming of display doesn't change panel name

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
Renaming of display doesn't change panel name
- [x ] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
Thank you!
Cherry picking from indigo #482 to kinetic
=> Cherry pick into kinetic from #482 renameDisplay

moveit_setup_assistant/src/widgets/group_edit_widget.cpp
Will prevent future users from having [this problem](https://github.com/ros-planning/moveit/issues/481) by providing better feedback. Can be backported
=> Add warning if no IK solvers found

moveit_core/robot_state/include/moveit/robot_state/attached_body.h
Apparently someone rearranged part of the code here but didn't move the comment.
=> Move comment to correct place

moveit_ros/visualization/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
This fixes #504 the compilation issue on Ubuntu Zesty and Debian Stretch.
This change is only for lunar and doesn't need to be cherry-picked into other branches 
Note: I settled for this solution because it seemed the least intrusive to me. There are several other fixes that could be considered:
- By changing the `-std=c++11` flag to `-std=gnu++11` in the `add_compile_option()` call but I preferred to keep the flags consistent across all packages of the moveit repository.
- By using (but needs to bump cmake minimum version to 3.0.2):
```
set(CMAKE_CXX_STANDARD 11)`
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Thank you!
=> add BOOST_MATH_DISABLE_FLOAT128

moveit_core/robot_state/src/conversions.cpp
=> checks that the joint_state field of the robot state message isn't empty

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_panel.h, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_panel.cpp, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp, moveit_ros/visualization/trajectory_rviz_plugin/src/trajectory_display.cpp
The new panel includes a slider to control the animated planned path.
It allows to display single waypoints of the trajectory.
There is a play/pause button which starts or pauses the animation at the current waypoint.
Pressing the play button after the animation is finished replays the trajectory.
This can also be used to pause the loop mode.
The panel is integrated into the trajectory visualization and is switched off by default.
That means the Trajectory display and the MotionPlanning display support this new panel and it can be activated in rviz' "Panels" menu entry.
The current behavior of loop and trail is retained.
This [video](https://tams.informatik.uni-hamburg.de/people/goerner/files/slider.mp4) shows the features of the slider.
=> New panel with a slider to control the visualized trajectory

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
**Issue**
When editing an existing moveit_config pkg, MSA opens the location of MSA package, which is useless.
**Approach with the suggested change**
Opens the directory where `setup_assistant.launch` was started, which is often where the existing moveit_config package you'd like to edit is located.
=> [MSA] Open a directory where setup_assistant.launch was started.

moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt
=> ikfast_kinematics_plugin: Add c++11 compile option

moveit_core/robot_state/src/conversions.cpp
Cherry-pick of #499 that fixes #496
=> [Indigo] checks for empty name arrays messages before parsing the robot state message data (cherrypick #499)

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
Don't needlessly cast away const.
Without this fix, compilation fails on platforms with urdfdom1.x (ROS Lunar on Ubuntu Yakkety, Ubuntu Zesty and Debian Stretch). This is because on urdfdom1.x, `urdf::LinkSharedPtr` etc. have switched from `boost::shared_ptr` to `std::shared_ptr`, which of course isn't compatible with `boost::const_pointer_cast`.
Unfortunately, all ikfast plugins have to be regenerated (using `update_ikfast_plugin.sh`) before being released into Lunar.
This fix is safe to merge into indigo, jade, kinetic and lunar.
Also see uos/katana_driver#22.
=> ikfast_kinematics_plugin: Fix for urdfdom1.x (Lunar)

.docker/ci-lunar/Dockerfile, .docker/ci-shadow-fixed-lunar/Dockerfile
Add docker images to ``kinetic-devel`` branch that test the build on lunar. See https://github.com/ros-planning/moveit/pull/503 for more info
This PR cannot be tested by CI due to the fact that it *is* CI, but a test can be found on my personal dockerhub account: https://hub.docker.com/r/davetcoleman/moveit/builds/
=> Add docker images for lunar

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
Adds an integer parameter **Trail Step Size** to the section _Motion Planning_->_Planned Path_ in RViz to adjust the density of visualized trajectory trails.
Since very dense trajectory trails can be difficult to recognize this parameter enables an easy way to make them arbitrarily sparse.
This is especially useful for creating snapshots or for other demonstration purposes. 
By default the step size is 1 so that every trajectory point is displayed.
With higher numbers the intermittent steps are hidden except for the first and last trajectory points.
The following pictures show examples of the default setting and the trail step size set to 4.
=> RViz - Trajectory trail step size

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
Instead just reset it to the default configuration.
This avoids needless urdf-parsing and retains a valid kstate_.
For changes to the robot description parameter,
there is a separate callback function.
On Ubuntu 14.04 indigo this also fixes a segfault during startup,
that seems to be related to calling loadRobotModel() twice in a row.
This should be forward ported to j/k.
Fixes #528
=> robot display: Don't reload robot model upon topic change

moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
#491 introduced a regression:
In TrajectoryVisualization::onInitialize the existance of a window_context is checked and the trajectory_slider_panel_ and trajectory_slider_dock_panel_ are only created if it exists.
However later on these two pointers are assumed to be valid (non-NULL) and not checked any further.
=> Fix crash if no window_context exists

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
This is a similar situation as in the pull request #523.
In the onInitialize function the frame_dock_ panel is only created if window_context exists.
Later on in the setName function the pointer is used without checking for existence.
=> Test if frame_dock_ exists in case of no window_context

moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt
simple_controller_manager: fix include order
The local header files of the packages should always be preferred.
Otherwise the same headers installed to /opt/ros/*/include would be used.
=> fix simple_controller_manager includes

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_panel.cpp, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
rviz display: stop trajectory visualization on new plan
It can be confusing to see the old trajectory even though
the user already requested a new plan.
This is especially annoying in case the second planning request fails!
Fixes #526
Should be forward-picked to j/k
=> make Isaac happier

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
If the trajectory fails validation (i.e. doesn't start at current robot state), there is never an update to the execution status causing plan_execution::PlanExecution::executeAndMonitor to loop indefinitely and never return.  I have added this callback.
=> Plan Execution never returns if trajectory fails validation.

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
It bugged me for quite some time now that one has to edit the launch file
just to be able to move the "real" robot around in demo mode.
Thus I want to expose the option as a parameter in the launch file.
=> setup assistant: add use_gui param to demo.launch

moveit_core/robot_state/include/moveit/robot_state/robot_state.h
The docstring says the format of the vector is `(minx, miny, minz, maxx, maxy, maxz)`, but according to both the method's implementation and use in moveit, the format is rather `(minx, maxx, miny, maxy, minz, maxz)`.
Thank you!
=> Fixed doc-comment for robot_state::computeAABB

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.h
This adds a checkbox to the Setup Assistant urdf loading widget on the start screen that allows users to enable 'Jade+ extensions' in xacro on Indigo installations. This is needed to support loading xacros that make use of those extensions.
The choice is persisted (`.setup_assistant`) so loading a config pkg that was created with the option enabled will enable them automatically. Bw-compatibility with existing config pkgs is maintained, as absence of the setting will just make the MSA use the default (`false`).
Extensions are also enabled in `planning_context.launch` if needed.
Screenshot of UI change:
Ref #511.
As xacro on Jade and newer ROS releases enables those extensions by default, these changes do not need to be cherry-picked to any other MoveIt versions.
=> MSA: support loading xacros that use Jade+ extensions on Indigo

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h
Fix for https://github.com/ros-planning/moveit/issues/506
This PR corresponds to this change in [robot_model](https://github.com/ros/robot_model/pull/206) that has just been released into kinetic & lunar. This should be safe to be merged now, and should not be backported.
=> [setup_assistant] Fix for lunar

moveit_core/planning_scene/src/planning_scene.cpp
This fixes a segfault due to missing string format parameter in logWarn call.
The message occurs when requesting the pose of a collision object that consists of multiple shapes and therefore contains multiple poses. The inserted parameter is now the id descriptor of the object.
=> Fixing segfault due to missing string format parameter.

.travis.yml
In [lunar/Migration](http://wiki.ros.org/lunar/Migration), there's `robot_model` metapkg split. For now I doubt that it would affect CI jobs for Lunar in MoveIt!, but in case job fails then that might be one thing to look at.
----
**TODOs** from @davetcoleman at https://github.com/ros-planning/moveit/pull/503#issuecomment-306454552
I can create these PRs now but am not able to test them locally currently
=> [CI] Add ROS Lunar.

moveit_plugins/moveit_ros_control_interface/CMakeLists.txt, moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp
At [the last developer meeting](https://discourse.ros.org/t/maintainer-meeting-recap-march-7th/1442) we agreed to allow patches that support to compile the `kinetic-devel` branch on ROS indigo.
I worked on that on the side and actually it's quite possible by now if you know what you're doing.
The only problems that are left are the API change in `ros_control` and https://github.com/ros/robot_model/pull/210 .
This patch adds preprocessor magic to support the old `ros_control` API.
=> add backward compatibility patch for indigo

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This will add a link at the top of every pull request for more information on contributing
https://github.com/blog/1184-contributing-guidelines
This also sets the expectation for response time on pull requests, as suggested by https://opensource.guide/best-practices/
=> Add CONTRIBUTING.md file

moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp
Adds an optional ompl group parameter 'force_joint_model_state_space' to enforce the use of JointModelStateSpaceFactory for problem representation. This is convenient to work around issues with planning problems represented in PoseModelStateSpace, as is the case with some cartesian path planning scenarios.
=> Optional forced use of JointModelStateSpaceFactory

moveit_planners/chomp/chomp_interface/include/chomp_interface/chomp_interface.h, moveit_planners/chomp/chomp_interface/src/chomp_interface.cpp, moveit_planners/chomp/chomp_interface/src/chomp_plugin.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
This PR includes some first steps to get Chomp planner to avoid collisions. It partially addresses #305 
This code requires that the "global" PlanningScene uses the "Hybrid" collision checker from moveit-experimental. I will open a separate PR against moveit-resources to add this to the example
Status after this fix:
- chomp knows there are collisions
- it tries and sometimes manages to avoid them
- there is a ROS_ERROR informing you that the path still contains collisions (even if it doesn't)
- but it will still return SUCCESS (unconditionally)
=> Chomp use PlanningScene

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
IKfast moveit plugin is expected to return the solution (when called with getPositionIK(ik_pose, ik_seed_state, solution, error_code,options)) which is closest solution to the ik_seed_state. Originally, the code was returning the first solution it could find. Modified the template to return the closest solution satisfying the joint limits after harmonizing it(returning the solution between -pi to pi).
@shaun-edwards! Can you please have a look?
=> Modify ikfast_template for getPositionIK single solution results

moveit_ros/visualization/rviz_plugin_render_tools/src/robot_state_visualization.cpp
This addresses the segfault reported by @simonschmeisser in https://github.com/ros-planning/moveit/pull/565 .
rviz::Robot deletes its complete SceneNode structure in the `load()` method.
However, `RobotStateVisualization::render_shapes_` keeps raw pointers
to some of these nodes (the attached objects), so these should be cleared
to avoid broken pointers.
Additionally the order of clearing was bad: the attached objects should
be removed first, and `rviz::Robot` only afterwards to avoid similar problems.
Should be cherry-picked to `indigo-devel`.
=> RobotStateVisualization: clear before load to avoid segfault

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
At the moment, if a trajectory with MultiDoFJointTrajectory points but no JointTrajectory point is sent to the executePart function, the whole [trajectory duration estimation](https://github.com/ros-planning/moveit/blob/3f00880b726833805364f4afa91fedc49478d35c/moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp#L1328-L1344) part is skipped. This PR addresses that.
The entire calculation is already supporting the case, it's just a matter of allowing it to process.
=> MultiDoFJointTrajectory only trajectory support

moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
#568 reminded me of this problem, and somewhat increased the pressure to change this...
This patch makes the `MoveGroup` interface behave the same as the RViz plugin
when the user specified a `default_planner_config` in their `ompl_planning.yaml`
Before, the RViz plugin automatically selected the default planner automatically, but the MoveGroup left the planner id unspecified in the MoveGroup action goals. The move_group node received the request with the unspecified field but didn't respect the parameter in indigo and uses `LBKPIECE1` even if the user specified a different default planner for the group.
To circumvent the old default planner `LBKPIECE1` in indigo, the user has to set the default planner **explicitly for each `MoveGroup`** using
``` …
```
=> set default planner by default in indigo's MoveGroup

moveit_core/robot_state/src/conversions.cpp
In case the incoming RobotStateMsg is a diff, the joint fields are allowed to be empty.
This is used to change attached objects and it's an intended use-pattern in MoveIt to modify the current state with some (possibly) incoming state (see e.g. [the fix_start_state_bounds adapter](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp#L85))
This needs to be cherry-picked indigo due to #518 .
Fixes #579
=> robotStateMsgToRobotState: is_diff==true => not empty

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
Currently computeCartesianPath of MoveGroupInterface ignores the end-effector link set by setEndEffectorLink. It uses the CartesianPathService which has a field link_name to provide this utility.
After this fix the provided poses are correctly transformed to the tip of the ik chain.
Like I wrote in #577, this could potentially break workaround user code, if they manually transform poses to the ik tip before giving them to computeCartesianPath and also calling setEndEffectorLink with their actual intended end-effector link. If their end-effector set by setEndEffectorLink or setEndEffector is the same as the ik chain tip, nothing will change.
=> MoveGroupInterface: Fixed computeCartesianPath to use selected end-effector.

moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h, moveit_setup_assistant/src/tools/compute_default_collisions.cpp
I noticed that several packages were using tinyxml symbols but were not explictely fingind it or linking against it. I modified the package.xml and CMakeLists of the relevant packages and hopefully didnt miss any.
=> remove references to TinyXML

moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
=> MoveGroupInterface: Fixed computeCartesianPath to use selected end-effector

moveit_commander/src/moveit_commander/planning_scene_interface.py
this PR just to skip import pyassimp, so if you need to build mesh, we have problem
But I think this still useful, because we can at least, start moveit_commander, until https://bugs.launchpad.net/ubuntu/+source/assimp/+bug/1589949
is get merged.
=> workaround for https://github.com/ros-planning/moveit/issues/86

moveit_core/constraint_samplers/include/moveit/constraint_samplers/default_constraint_samplers.h, moveit_core/constraint_samplers/src/default_constraint_samplers.cpp, moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h, moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Previously the transform was done before sampling poses, which only works for pure orientation constraints.
Now transforms after each sample.
Removed no longer needed methods swapLinkModel. They are no longer used anywhere in moveit and at least the position constraint version is not working as intended.
Fixes setPoseTarget part of #577.
=> IKConstraintSampler: Fixed transform from end-effector to ik chain tip.

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
Fixes #595
Note: I am not familiar with the problems that leaded to the delayed loading of the robot model so please review this solution especially regarding thread contexts of the methods..
=> RobotState rviz previewer: First message from e.g. latching publishers is not applied to robot state correctly

moveit_ros/manipulation/pick_place/src/approach_and_translate_stage.cpp, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
Giving an empty object into the picking pipeline was not supported before. `executeAttachObject` was given an empty object and returned false. This aborted the pick action server right after closing the gripper. To work around this, return true whenever an empty string is given as object id. 
In addition `planGraspsAndPick` was changed, so that it can take an empty string. In that case an empty `moveit_msgs::CollisionObject` is created for the further steps. Also, an empty string is now the default value for `planGraspsAndPick`. 
This change helps with the gpd integration.
=> Adapt pick pipeline to function without object

moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template
moveit_setup_assistant generate launch file using fake controller, but the package.xml does not incude this package
https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/fake_moveit_controller_manager.launch.xml#L4
=> add moveit_fake_controller_manager to run_depend of moveit_config_pkg_template/package.xml.template

moveit_core/robot_state/src/robot_state.cpp
It can be tricky to understand why MoveIt! is failing when using multiple eefs and desired poses
=> Better debug output for IK tip frames

moveit_ros/manipulation/pick_place/src/approach_and_translate_stage.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp
This is a selective backport and does not add the `""` default parameter for `planGraspsAndPick`.
Dave stated in https://github.com/ros-planning/moveit/pull/599#issuecomment-326664176 that he does not think it belongs in indigo.
I agree that we should not add the default parameter there.
But apart from that the patch adds support for an edge-case that was previously unused and does not break anything.
I would like to see this part back in indigo.
=> Adapt pick pipeline to function without object (#599)

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
Implementation of #571 for the no free parameter case of searchPositionIK. 
This implementation works without solution explosion and still returns the closest solution to the seed.
It should scale linearly with increased joint limits.
Implementation for the other case and other functions requires more code changes.
=> [IKFastTemplate] Expand solutions to full joint range in searchPositionIK

moveit_commander/src/moveit_commander/robot.py
1. `_joint_owner_groups` had a typo (line 152)
2. `RobotCommander.get_default_owner_group` was incorrectly called (line 116)
3. When executing a motion command (RobotCommander.Joint.move) the target values for **other** joints should be updated only once, at the beginning. Originally line 121 `   gc.set_joint_value_target(gc.get_current_joint_values())` updated target values for all the joints in the group, which is not correct and resulted in a drift of unrelated joints due to forces of gravity, etc. Whenever the group in a robot is used first, joint values are updated (lines 121-123, 153), but for subsequent movements unrelated joints (i.e. **not** a target joint) are left unchanged, only target joint is moving.
=> Bug fixes in moveit_commander/robot.py

moveit_commander/src/moveit_commander/robot.py
bug fixing in moveit_commander/robot.py:
(1) _joint_owner_groups had a typo (line 152);
(2) get_default_owner_group was incorrectly called (line 116);
=> [indigo backport] Bug fixes in moveit_commander/robot.py (#621)

moveit_core/CMakeLists.txt, moveit_experimental/package.xml
We export headers that include fcl, so this has to be exported.
This is required to properly overlay a system installation of fcl with a package in the local `catkin` workspace. Without it `moveit_experimental` will include system headers instead.
=> moveit_core: export DEPENDS on LIBFCL

moveit_ros/benchmarks/CMakeLists.txt
Before, on systems with package installations of MoveIt,
the sources of this module included headers from /opt/ros/kinetic/include/ ...
instead of the local ones.
I found this by `sudo chmod o-r /opt/ros/kinetic/include/moveit` before building the local workspace.
=> benchmarks: always prefer local header over system installations

moveit_kinematics/ikfast_kinematics_plugin/CMakeLists.txt, moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py
Apparently this was never changed after the move to the moveit_kinematics package.
Needs cherry-picking to indigo.
=> create_ikfast_moveit_plugin: fixed directory variable for templates that were moved to ikfast_kinematics_plugin

.gitignore
They're in the `.gitignore` twice already, but I think the regex is not matching files in sub dirs properly for some reason.
Without this, after running `moveit_commander` in a source build:
```shell
$ git status
On branch kinetic-devel
Your branch is up-to-date with 'origin/kinetic-devel'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
moveit_commander/src/moveit_commander/conversions.pyc
moveit_commander/src/moveit_commander/exception.pyc
moveit_commander/src/moveit_commander/interpreter.pyc
moveit_commander/src/moveit_commander/move_group.pyc
moveit_commander/src/moveit_commander/planning_scene_interface.pyc
moveit_commander/src/moveit_commander/robot.pyc
moveit_commander/src/moveit_commander/roscpp_initializer.pyc
```
After:
```shell
$ git status
On …
```
=> Really ignore pyc files.

.github/PULL_REQUEST_TEMPLATE.md
Many MoveIt! contributors forget to remove the info about expectations for pull requests. This change makes it a hidden comment in markdown format so, even if they don't remove it, it will be hidden
=> Add comments to pull request template

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/double_list_widget.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.cpp, moveit_setup_assistant/src/widgets/header_widget.cpp, moveit_setup_assistant/src/widgets/kinematic_chain_widget.cpp, moveit_setup_assistant/src/widgets/navigation_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
This pull request replaces uses of `"Arial"` with the default application font from Qt with `QGuiApplication::font()`.
- I think this should be cherry-picked to indigo as well, but that's up to the maintainers.
=> replace explicit use of Arial with default font

moveit_ros/perception/mesh_filter/src/depth_self_filter_nodelet.cpp
When auditing packages using deprecated pluginlib macros I found this commented out instance. This PR removes it
=> remove unused deprecated pluginlib macro

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/double_list_widget.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.cpp, moveit_setup_assistant/src/widgets/header_widget.cpp, moveit_setup_assistant/src/widgets/kinematic_chain_widget.cpp, moveit_setup_assistant/src/widgets/navigation_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
We recently remove the hard-coded "Arial" font family from MSA
and instead detect the default font via Qt.
However, the QGuiApplication class only exists in qt5 and thus
current kinetic-devel is broken with ROS indigo (qt4).
We agreed the current development branch should support
the target platforms of all other active branches of MoveIt
as long as someone is willing to provide the patches.
I propose to move from `QGuiApplication()::font().family()` to `QFont().defaultFamily()`.
The latter is pretty much a stub in Qt4 (it only provides one out of 5-6 different hard-coded strings),
but the API exists in both Qt4 and Qt5.
=> MSA: use qt4-compatible API for default font

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Related to #634 and #657, this PR presents the alternate solution where the `MoveGroupInterface` has its copy constructors disabled all-together. Note this requires changing the Python wrapper as well - not sure about the impacts there.
I also implemented a move constructor for those cases where you do need to move it around.
You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!
=> Disabled Copy Constructor

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/include/moveit/robot_state/conversions.h, moveit_core/robot_state/src/conversions.cpp
Issue #644 
- Added functionality to get CollisionObject(s) and ObjectColor(s) and the Octomap as ROS msgs from the Planning Scene object. This involved replacing existing private methods for those functions.
- Also added functions to get AttachedCollisionObject(s). For this I added to conversions.h/.cpp
- Note: the format for getCollisionObjects() basically involves getting the IDs for all of the objects and then iterating through the IDs and retrieving each CollisionObject msg separately using its ID. For getAttachedCollisionObjects(), it sort of works the opposite way. To get a single AttachedCollisionObject, you retrieve all of the AttachedCollisionObjects and then iterate through all the objects and look for the one with the right ID.
- If the above doesn't make sense, just ignore it …
=> Get msgs from Planning Scene

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp
this protects from bugs in code comparing one of the anonymous enums defined in moveit_msgs::MoveItErrrorCodes to the struct. Previously comparing
MoveItErrorCode::PLANNING_FAILED == MoveItErrorCode(MoveItErrorCode::PLANNING_FAILED)
would always return "false" except for MoveItErrorCode::SUCCESS. The reason is that the class MoveItErrorCode was implicitly downcast (via operator bool())
to a bool and then compared to the enum value which was also downcast first to int and then to bool.
This has led to some hard to catch bugs in code like the following in our software:
MoveItErrorCode ret = plan(...);
if (ret == MoveItErrorCode::NO_IK_SOLUTION) { // always false
ROS_ERROR("No ik solution found but you'll never know");
}
I think preserving some of the type safety is worth adding a bit of …
=> make operator bool() explicit in MoveItErrorCode

moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp
This is a proposal PR of #673.
With this PR, I get valid `error_code` such as `-1` when planning is failed.
I made this PR for `indigo-devel` because I only check in `indigo`.
I have no idea if the same issue happens in `kinetic` and others.
I'm not sure if we should always return `true` or not.
If you have better idea, feel free to tell me.
=> always return true in MoveGroupPlanService callback

moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py, moveit_kinematics/package.xml
Fixes the [create_ikfast_moveit_plugin.py](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_kinematics/ikfast_kinematics_plugin/scripts/create_ikfast_moveit_plugin.py) script so that it complies with format 2 of the `package.xml`.
This implies changing the `run_depend` tag into `exec_depend` tag.
Please do note that the [`package.xml` template](https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/templates/package.xml.in#L2) of `catkin_create_pkg` if format 2 by default.
=> [kinetic-devel] Fix create_ikfast_moveit_plugin to comply with format 2 (package.xml)

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
when starting robot_state_display with an empty robot_description it will crash
as kstate_ is not checked before attempting to update it. Changing to an empty
robot_description later on seems to be handled more gracefully on a higher level
and does not crash
How to reproduce:
roscore
rviz
add RobotState plugin
observe crash
=> don't crash on empty robot_description in RobotState plugin

moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
Add support for the arctic gamepad in `moveitjoy_module.py`, and, indirectly in `moveit_ros_visualization::moveit_joy.py`.
Arctic gamepad: https://www.arctic.ac/eu_en/usb-wireless-gamepad.html.
I'm ready to add the support for this gamepad somewhere if someone can point me where.
=> Add support for the Arctic gamepad

moveit_core/controller_manager/include/moveit/controller_manager/controller_manager.h
this is not as likely to cause bugs as the respective change in #670
as there is an implicit operator Value() [1] that gets used for comparison
still I think this should be explicit
[1] Value being the name of the enum
=> Make operator bool() explicit

.gitignore, moveit_ros/move_group/include/moveit/move_group/capability_names.h
Minor fixes
- The .gitignore regex for swaps doesn't work on my machine so I added a regex that does.
- Removing redundant capability names from the default capabilities list. 
=> removing redundant capabilities from capability names and adding swp to gitignore

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
Also warn that MultiDOFJointTrajectory validation is not supported
Fixes #539
Should be backported to indigo.
=> Avoid segfault when validating a multidof-only trajectory

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
Some kinematics plugins access parameters that are defined in the private namespace of their node.
With multiple nodes, each node needs to be initialized with the same parameters which can be
very inconvenient in some setups.
This commit resolves the issue by enabling plugins to query parameters from the
namespace 'robot_description_kinematics' so that they can be defined in the kinematics.yaml either under the corresponding group or directly.
This PR helps to resolve issues [with multiple arms](https://github.com/ros-industrial/universal_robot/issues/247) and when launching the plugin with [rviz and the moveit commander simultaneously](https://github.com/ros-industrial/universal_robot/issues/256) (also see [here](https://github.com/ros-planning/moveit/issues/545) and …
=> Adds parameter lookup function for kinematics plugins

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h
Cherry-pick of #701 to indigo-devel
Some kinematics plugins rely on certain parameters to be set in the private namespace of their node.
Running multiple instances requires each node to be initialized with these parameters which can be
very inconvenient in some setups.
This commit resolves the issue by enabling plugins to lookup parameters from the
namespace 'robot_description_kinematics' so that they can be defined in the kinematics.yaml.
=> [indigo] cp #701 - Adds parameter lookup function for kinematics plugins

moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp, moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp, moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_plugin.cpp, moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp
This PR replaces the _param()_ calls inside `moveit_kinematics` plugins with the lookup function _lookupParam()_ introduced [here](https://github.com/ros-planning/moveit/pull/701).
The lookup function looks for the parameters in the following locations:
*  ~/<group_name>/<param>
* ~/<param>
* robot_description_kinematics/<group_name>/<param>
* robot_description_kinematics/<param>
Using this function allows setting the required parameters inside the kinematics.yaml either with or without the corresponding group name.
Since all of the plugins query some parameters under `group_name` in their private namespace, this location is added to _lookupParam()_ [with this commit](https://github.com/ros-planning/moveit/commit/73d4df32c947ce706817c9d46cfc5b3f35294d58).
@v4hn
=> Use lookupParam() in kinematics plugins

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/include/moveit/robot_state/conversions.h, moveit_core/robot_state/src/conversions.cpp
This PR provides some cleanup to the previously merged PR #663.
As a major regression, after #663, displaying of attached collision objects didn't work anymore (#723).
Besides fixing this, the present PR provides some other minor improvements.
=> cleanup #663

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h, moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
MoveIt supports Floating and Planar joints throughout the pipeline... almost throughout the pipeline.
Whenever someone actually tried to use it, they encountered problems with how to get the current state information into the MoveIt system. For over at least 4(!!!) years.
See among others [here](https://groups.google.com/forum/#!topic/moveit-users/C07EZmTgSBQ) and [here](https://github.com/ros-planning/moveit_ros/issues/620).
This works (rather hacked) for floating joints as root joint of the robot, but they are also important for online calibration procedures and mobile objects that are inherent to the setup and should be part of the urdf.
Turns out most things that are required to get this to work in general have been done a long time ago.
I simply implement a proposal by @hersh and add …
=> Floating Joint Support in CurrentStateMonitor

moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group.cpp, moveit_ros/planning_interface/test/CMakeLists.txt, moveit_ros/planning_interface/test/robot_state_update.py, moveit_ros/planning_interface/test/robot_state_update.test, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp
This is another attempt to migrate changes of #350 from Kinetic to Indigo maintaining ABI compatibility.
A recent attempt () only considered a small fraction of the original PR, still leading to errors (#749).
Now I ported most of the other stuff, including the unit test.
@rkeatin3 However, as I don't have a running Indigo system anymore, I appreciate real-world testing. Particularly, check whether fetching the current state from the rviz MotionPlanning plugin works without issues.
=> cherry pick #350

moveit_core/trajectory_processing/CMakeLists.txt, moveit_core/trajectory_processing/include/moveit/trajectory_processing/iterative_spline_parameterization.h, moveit_core/trajectory_processing/src/iterative_spline_parameterization.cpp, moveit_core/trajectory_processing/test/test_time_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/src/add_iterative_spline_parameterization.cpp, moveit_ros/planning/planning_request_adapters_plugin_description.xml
Ruben's idea of fitting a cubic spline to a trajectory is a very good one: #382 .  Forcing the trajectory to a cubic should prevent the controller from overfitting the data, the problem presented here: #160 .  
I've taken the concept a little further by repeatedly fitting the spline and adjusting timestamps until all constraints are satisfied.  This is similar to the way IPTP works, but instead of using local averages, the instantaneous values are used instead.
This technique is presented as another trajectory time parameterization class that can be used instead of IPTP.  It also adds some simple unit tests.  Initial/final velocity and acceleration can be specified.  The constraints imposed are velocity, acceleration, and jerk.  Here is a straight-line trajectory of 11 points:
Ruben …
=> Iterative cubic spline

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
#748 introduced a new bug: passing std::string to %s debug argument...
=> fix newly introduced error

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
1. Improve user feedback - if using MoveIt! on two separate computers the clock can get out of sync and ``getCurrentState()`` will report no joint values when in reality it is getting joint values, the time difference is just greater than the default 1. This is common when a realtime robot PC is disconnected from the internet for weeks/months.
2. Allow the MoveGroupInterface ``getCurrentState()`` to specify a wait period greater than the default 1 second, so that if you do have the above problem you can quickly debug it / override it by allow timestamps that are greater.
This would have saved @liuxin00738 many frustrated hours debugging MoveIt!, he and I prepared this change together and tested it on hardware.
=> Allow wait time to be specified for getCurrentState()

moveit_ros/move_group/CMakeLists.txt, moveit_ros/move_group/package.xml, moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/move_action_capability.h, moveit_ros/move_group/test/test_cancel_before_plan_execution.py, moveit_ros/move_group/test/test_cancel_before_plan_execution.test
Preempt request could be dropped in `MoveGroupMoveAction` capability if it is sent shortly after goal is sent. 
The problem is that the `preemptMoveCallback` sets the `PlanExecution::preempt_requested_` as `true` but `executeMoveCallback_PlanAndExecute` resets the `PlanExecution::preempt_requested_` as `false`. If `preemptMoveCallback` is called before `plan_execution_->planAndExecute`, the preempt request is  lost. In this case the goal status is set to `PREEMPTING` but the goal is planned and executed. In the end a result with error code `SUCCESS` is received. A test is provided to reproduce the problem.
An easy fix is provided by adding a similar `preempt_requested_` flag in  `MoveGroupMoveAction` and checking this flag before `plan_execution_->planAndExecute` is called. At the end of …
=> MoveAction capability can drop cancel request if it is sent shortly after goal is sent

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_setup_assistant/src/tools/moveit_config_data.cpp
I have made two modifications for treatment of passive joints:
1. They are no longer output as part of a trajectory for whichever group they belong to.
2. They are no longer included in the joint list for the group's fake controller. 
See [Issue 640](https://github.com/ros-planning/moveit/issues/640) for more information. 
=> skip non-actuated joints for trajectory execution

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp, moveit_setup_assistant/src/tools/moveit_config_data.cpp
This is an adaption of #753 for Kinetic that allows for using C++11 features.
=> cherry-pick #753: skip non-actuated joints for execution

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
Fixes an issue mentioned in https://github.com/ros-planning/moveit/pull/653#issuecomment-346681760: Since, #452 / #466, enabling/disabling the rviz display, didn't show/hide the panel anymore. The original issue #633 doesn't pose an issue anymore.
Now, the following behavior is implemented:
1. Disabling the display also disables the panel, but not vice versa.
2. Enabling the display enables the panel and vice versa.
3. The saved state in .rviz config is restored (both for display and panel state).
=> show/hide panel if display is enabled/disabled

moveit_setup_assistant/src/widgets/robot_poses_widget.cpp, moveit_setup_assistant/src/widgets/robot_poses_widget.h
MSA restricted names of group states to be unique globally, although they only need to be unique within planning groups. This rendered the definition of hand poses "open" for both hands of a bimanual robot impossible. This is fixed.
Additionally, only _active joints_ are considered for the definition of named group states.
=> MSA: fix setting of group states

moveit_ros/move_group/CMakeLists.txt
For now disable the new unittest introduced in #756 as it fails 50% of the time.
@khupilz As you proposed the original PR #756, please can you have a look and fix this.
=> disable flaky unittest

moveit_core/robot_model/src/robot_model.cpp, moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp, moveit_ros/robot_interaction/src/robot_interaction.cpp, moveit_setup_assistant/src/widgets/end_effectors_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp
This is an attempt to slightly improve the association of IK solvers to joint model groups, which is essential to have interactive end-effector markers in rviz.
There are frequently issues reported related to this, e.g. #616.
This PR aims to 
* improve both code and user documentation
* improve on issued warnings
=> improve association of IK solvers to groups

moveit_core/robot_model/src/link_model.cpp
This fixes a newly introduced bug in #703.
If a link doesn't have any associated shapes, the bounding box stays maximal. However, we should return zero extents in this case.
=> fix computation of shape_extents_ of links w/o shapes

moveit_ros/robot_interaction/src/interaction_handler.cpp
Rotation angle for planar joint was computed based on Euler angles which exhibits discontinuities.
Better use dedicated method setJointPositions(joint_name, pose).
=> fix interaction with planar joints

moveit_core/robot_model/include/moveit/robot_model/robot_model.h, moveit_core/robot_model/src/robot_model.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
Improve documentation for `RobotState::updateStateWithLinkAt()`. For me it was unclear, which transforms were updated and which were marked dirty.
If argument `backward = true` is passed, mark all collision body transforms as dirty.
Provide utility function `RobotModel::getRigidlyConnectedParentLinkModel()` to find the top-most parent link that is ridigly linked to the given link. Usually, when placing a link with `RobotState::updateStateWithLinkAt()`, this parent link should be used.
=> improve RobotState::updateStateWithLinkAt()

moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
This PR adds a API to `MoveGroupInterface`  that get the current planner_id.
I need this to:
1. Call underlying `move_group` actions using an existing `MoveGroupInterface`'s settings
2. Use for visualization/debug
=> Add API to get planner_id

moveit_plugins/moveit_ros_control_interface/README.md
=> fixed a small typo in README

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
This gets rid of many warnings on incomplete robot states due to missing state information for all fixed joints. We don't expect that drivers publish the transforms for fixed joints
Fixup for 739a85a4820ec68fecd31f51519ecc92a50f8c7e
It wasn't a problem before because the checks used variable names
and fixed joints do not have variables. So nothing was checked.
=> CSM: wait for *active* joint states only

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/test_kinematic.cpp
Mimic joints were not correctly updated.
Although the joint transform was marked dirty, the corresponding link transform was not!
=> fix updateMimicJoint()

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
The MotionPlanningDisplay does not check if a parent widget exists. This causes the using application to crash if no parent widget was created. This issue happens when building a custom application using the rviz library.
=> MotionPlanningDisplay: check for parent widget

moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_interface/package.xml
Fixes #755.
Trivial change: added missing include and dependencies in `CMakeLists.txt` and `package.xml` of chomp_interface.
Without this, `catkin_make run_tests_moveit_planners_chomp` fails with:
```
[100%] Built target moveit_move_group_interface
Scanning dependencies of target chomp_moveit_test
[100%] Building CXX object moveit/moveit_planners/chomp/chomp_interface/CMakeFiles/chomp_moveit_test.dir/test/chomp_moveit_test.cpp.o
/tmp/moveit_ws/src/moveit/moveit_planners/chomp/chomp_interface/test/chomp_moveit_test.cpp:40:62: fatal error: moveit/move_group_interface/move_group_interface.h: No such file or directory
compilation terminated.
moveit/moveit_planners/chomp/chomp_interface/CMakeFiles/chomp_moveit_test.dir/build.make:62: recipe for target …
```
=> Fix dependencies for chomp interface test

moveit_ros/planning/rdf_loader/src/rdf_loader.cpp, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/header_widget.cpp, moveit_setup_assistant/src/widgets/header_widget.h, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.h
I stumbled about a robot urdf that required xacro cmdline arguments. This wasn't supported in MSA yet (although there was a TODO as reminder). I added support for specifying xacro arguments, both for the `urdf file` and `package` gui. The xacro args are remembered in `.setup_assistant` file and added to `planning_context.launch`.
Removed hard-coded `--inorder` option, but set `inorder` as default for new projects.
=> msa: added support for xacro args

moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
TLDR: 
* `trajectory_constraints` is a member of [`MotionPlanRequest`](http://docs.ros.org/kinetic/api/moveit_msgs/html/msg/MotionPlanRequest.html) yet the MoveGroupInterface doesn't allow for specifying it.
* `trajectory_constraints` can carry entire trajectories while `path_constraints` can't (in a clean way). 
----
The [`MotionPlanRequest`](http://docs.ros.org/kinetic/api/moveit_msgs/html/msg/MotionPlanRequest.html) message has a field `trajectory_constraints` but  `class MoveGroupInterface (C++)` doesn't allow for setting them. I've added support for this both to the C++ class and the Python wrapper. 
What's the motivation for this? Passing in _initial trajectories_, _initial guesses_ or _seed trajectories_ to optimization-based planners such as the case of …
=> MoveitCommander support for TrajectoryConstraints

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
issue #783 
With the current implementation, if you use computeCartesianPath with Eigen::Affine3d you can get different results than if you pass in a vector with a single waypoint to computeCartesianPath with EigenSTL::vector_Affine3d.  This fixes that bug. 
=> cleanup minimum steps for jump threshold test in computeCartesianPath [fix issue #783]

moveit_kinematics/CMakeLists.txt, moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt, moveit_kinematics/cached_ik_kinematics_plugin/README.md, moveit_kinematics/cached_ik_kinematics_plugin/config/kdl.yaml, moveit_kinematics/cached_ik_kinematics_plugin/config/kdl_cached.yaml, moveit_kinematics/cached_ik_kinematics_plugin/config/trac.yaml, moveit_kinematics/cached_ik_kinematics_plugin/config/trac_cached.yaml, moveit_kinematics/cached_ik_kinematics_plugin/config/ur5.yaml, moveit_kinematics/cached_ik_kinematics_plugin/config/ur5_cached.yaml, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin-inl.h, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.h, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/GreedyKCenters.h, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/NearestNeighbors.h, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/NearestNeighborsGNAT.h, moveit_kinematics/cached_ik_kinematics_plugin/launch/measure_ik_call_cost.launch, moveit_kinematics/cached_ik_kinematics_plugin/src/cached_ik_kinematics_plugin.cpp, moveit_kinematics/cached_ik_kinematics_plugin/src/cached_ur_kinematics_plugin.cpp, moveit_kinematics/cached_ik_kinematics_plugin/src/ik_cache.cpp, moveit_kinematics/cached_ik_kinematics_plugin/src/measure_ik_call_cost.cpp, moveit_kinematics/cached_ik_kinematics_plugin/test.sh, moveit_kinematics/cached_ik_kinematics_plugin_description.xml, moveit_kinematics/cached_ik_kinematics_plugin_description.xml.in, moveit_kinematics/package.xml
Added a kinematics plugin that caches IK solutions. It wraps around existing IK solvers. The [kinematics configuration tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/kinematics/src/doc/kinematics_configuration.html) could be updated with some of the documentation I put in `moveit/moveit_kinematics/cached_ik_kinematics_plugin/README.md`.
You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!
=> Cached ik kinematics plugin

moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/src/tools/moveit_config_data.cpp
While tracking down a bug in yaml parsing, which finally turned out to be a bug in yamp-cpp itself (https://github.com/jbeder/yaml-cpp/pull/568), I cleaned the code a little bit.
=> msa: cleanup yaml parsing

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/octomap_render.h, moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp, moveit_ros/visualization/rviz_plugin_render_tools/src/render_shapes.cpp
Fix for #728: The provided shape transform was not considered at all for octree visualization.
=> consider shape transform for OcTree

moveit_ros/perception/CMakeLists.txt
We make OpenGL parts optional, but build everything by default.
This commit is motivated by the work on the OpenEmbedded layer for ROS, a cross-compilation tool chain environment for ROS packages. We would like to allow to use moveit_ros_perception in embedded systems without OpenGL support.
Dmitry Rozhkov is the original author of this patch. I ported the patch from indigo to the current kinetic branch and elaborated the commit message.
=> moveit_ros_perception: make OpenGL parts optional

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
This PR represents minor improvements concerning the num_joints_ variable in IKFastKinematicsPlugin. I propose to declare num_joints_ as a constant and initialize it in the constructor. Also in getPositionFK() the size of input array joint_angles is compared against the value of num_joints_.
=> Improve ikfast kinematics plugin

moveit_commander/src/moveit_commander/robot.py
Follow-up to [https://github.com/ros-planning/moveit/pull/781](https://github.com/ros-planning/moveit/pull/781).
When using a parameter other than "/robot_description", `RobotCommander.get_group()` will fail in creating a `MoveGroupCommander`. The name of the parameter needs to be passed.
=> Pass robot_description parameter in RobotCommander.get_group 

moveit_core/planning_scene/src/planning_scene.cpp, moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
When calling `addCollisionObjects` or `applyCollisionObjects` with colors for the objects, each `ObjectColor` id had to be set to the corresponding object id.
This can lead to confusion as each method is already given a vector of `CollisionObjects`, so that one might think each `ObjectColor` is applied to the CollisionObject with the corresponding index.
Now, in case the `ObjectColor` id field is left empty, the id of the `CollisionObject` with the corresponding index is used instead.
This is done until one of the `ObjectColors` in the vector contains an id.
If there are still empty `ObjectColor` ids left after an `ObjectColor` already contained a non-empty id an error message is printed later in the `PlanningScene` class.
@v4hn
=> Simplify adding CollisionObjects with colors

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
The tfCallback method in CurrentStateMonitor disregards any TF lookups with a common time of zero. This makes it impossible to update a floating joint with a static TF because static TFs are published at time zero.
This fix adds support for static TF updates to floating joints in CurrentStateMonitor by also considering TFs with a common time of zero.
=> Support static TFs for multi DOF joints in CurrentStateMonitor

moveit_core/robot_model/src/fixed_joint_model.cpp, moveit_core/robot_model/src/floating_joint_model.cpp, moveit_core/robot_model/src/joint_model.cpp, moveit_core/robot_model/src/joint_model_group.cpp, moveit_core/robot_model/src/link_model.cpp, moveit_core/robot_model/src/planar_joint_model.cpp, moveit_core/robot_model/src/prismatic_joint_model.cpp, moveit_core/robot_model/src/revolute_joint_model.cpp, moveit_core/robot_model/src/robot_model.cpp, moveit_core/robot_state/src/robot_state.cpp
The repetitive namespace declaration of "moveit::core" has been removed from all the spaces. 
=> code clean up of robot_model

moveit_commander/demos/plan_with_constraints.py, moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
The `moveit::planning_interface::MoveGroup::computeCartesianPath` takes in an optional argument for path constraints, but the wrapper for using `move_group` in python using `moveit_commander` does not have the same option. 
This PR adds that feature to allow for constrained cartesian planning using `moveit_commander`.
=> Constrained Cartesian planning using moveit commander

moveit_commander/CMakeLists.txt, moveit_commander/src/moveit_commander/move_group.py, moveit_commander/src/moveit_commander/robot.py, moveit_commander/test/CMakeLists.txt, moveit_commander/test/python_moveit_commander.py, moveit_commander/test/python_moveit_commander.test, moveit_commander/test/python_moveit_commander_ns.py, moveit_commander/test/python_moveit_commander_ns.test, moveit_planners/chomp/chomp_interface/test/rrbot_move_group.launch, moveit_ros/move_group/test/test_cancel_before_plan_execution.test, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/planning_scene_interface/include/moveit/planning_scene_interface/planning_scene_interface.h, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp, moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp, moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp, moveit_ros/planning_interface/test/CMakeLists.txt, moveit_ros/planning_interface/test/movegroup_interface.py, moveit_ros/planning_interface/test/python_move_group.py, moveit_ros/planning_interface/test/python_move_group_ns.py, moveit_ros/planning_interface/test/python_move_group_ns.test, moveit_ros/planning_interface/test/robot_state_update.py, moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/demo.launch
Add namespace compatibility and tests to moveit commander
=> Add namespace capabilities to moveit_commander

moveit_core/robot_state/CMakeLists.txt, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/robot_state_test.cpp
This is a rework of #821, with cleaner implementation, particularly more readable unittests.
I also dropped the recently added flags `test_for_relative_jump` and `test_for_absolute_jump` in the `JumpThreshold struct`. @mlautman, @v4hn, @davetcoleman please review to finally merge this.
I also already included Michael's PR #831.
From my point of view, this PR can be squash-merged if finally accepted.
=> improved checking for joint-space jumps of Cartesian path

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp
In MotionPlanningRvizPlugin, the state of approximate_IK UI checkbox cannot be kept across sessions now. This patch adds the saving and resuming functionality. The slot function adds a init check, to prevent processing before `query_start_state_` and `query_goal_state_` in MotionPlanningDisplay is ready.
=> MotionPlanningRvizPlugin: Save and resume approximate_IK UI setting

moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
As pointed out in https://github.com/ros-planning/moveit/pull/350#issuecomment-378265191, the race condition in `waitForCurrentState()` was not fully resolved yet.
The reason was that only the first incoming `joint_state` update triggered a `PlanningScene` update, while later updates were throttled. To overcome this issue, we should explicitly trigger a scene update in `waitForCurrentState()`, if there were (further) updates.
As verified by @mmoerdijk, this PR finally resolves the issue. 
The unittest so far only involved fake controllers that didn't revealed the timing issue.
=> fix race condition

moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/kinematic_constraint.h
I removed the variable name in the `KinematicConstraint::print()` member function to avoid a compilation warning when gcc is used with the following flags: `-Wall -Wextra`
I discovered this warning when working on improving https://github.com/ros-industrial-consortium/descartes/pull/223
Example warning (from `descartes`):
```bash
In file included from /home/victor/code/catkin_workspace/src/descartes/descartes_core/include/descartes_core/robot_model.h:23:0,
from /home/victor/code/catkin_workspace/src/descartes/descartes_core/include/descartes_core/trajectory_pt.h:33,
from /home/victor/code/catkin_workspace/src/descartes/descartes_trajectory/include/descartes_trajectory/trajectory.h:29,
from /home/victor/code/catkin_workspace/src/descartes/descartes_trajectory/src/trajectory.cpp:25: …
```
=> Remove variable name KinematicConstraint::print() to avoid compilation warning

moveit_commander/src/moveit_commander/planning_scene_interface.py, moveit_commander/test/python_moveit_commander.py
Fixes an interface change on the C++ side of PlanningSceneInterface that was not changed on the python side. Adds a test that fails without this change.
=> Fix and Test for #842

moveit_core/robot_state/test/robot_state_test.cpp
The PR2-based testing for joint-space jumps introduced in #843 by @mlautman depends on `moveit_ros_planning`, which should be avoided in `moveit_core`. Hence, I removed the PR2 stuff again (which is not needed here to test for joint-space jumps).
Additionally, I hopefully improved code readability in `testAbsoluteJointSpaceJump`.
**This fixes the broken ros build farm**:
http://build.ros.org/job/Kdev__moveit__ubuntu_xenial_amd64/261/consoleFull#console-section-16
=> fix testAbsoluteJointSpaceJump

moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
This fixes an issue where where the chomp optimizer was requesting the parent joint of a fixed base joint without checking for Null [moveit_tutorials #164](https://github.com/ros-planning/moveit_tutorials/issues/164)
=> bugfix for chomp fixed base joint bug

.travis.yml
* Finally get ccache working for Travis, which dramatically reduces compile time (8-10min vs 40-50min):
https://travis-ci.org/ros-planning/moveit/builds/372196233
* Perform a single clang-format check only.
* ~~No need to specify ROS distro for clang-format~~
~~This depends on https://github.com/ros-planning/moveit_ci/pull/33.~~
=> improve travis checks

moveit_core/planning_scene/src/planning_scene.cpp
This should not be a public message.
Especially annoying because the RViz display calls this
function quite often when displaying trajectories with attached objects.
=> do not always print visible messages when attaching

moveit_core/robot_model/include/moveit/robot_model/link_model.h
GCC8 now comes with a static assert that checks that the value type of an `std::map` and it's allocator are the same. The value type of a map is `std::pair<Key const, Value>`.
In this particular case, the key type of the map is `LinkModel const *`, so the value type is `std::pair<LinkModel const * const, Eigen::Affine3d>`, not `std::pair<LinkModel const *, Eigen::Affine3d>`.
Without this PR, compiling moveit-core with GCC8 results in this error:
```
In file included from /usr/include/c++/8.1.0/map:61,
from /opt/ros/lunar/include/geometry_msgs/PoseStamped.h:11,
from /build/ros-lunar-moveit-core/src/moveit-release-release-lunar-moveit_core-0.9.11-0/kinematics_base/include/moveit/kinematics_base/kinematics_base.h:40,
from /build/ros-lunar-moveit-core/src/moveit-release-release-lunar-moveit_co …
```
=> Fix allocator type to pass GCC8 static assert.

moveit.rosinstall
This partially reverts 068dcc0b82e512c7405cfa51009652516ccc9b2b, which added the tutorials just recently. However, as the tutorials package is
broken, the main repo fails to build in Travis too now.
=> removing moveit_tutorials from moveit.rosinstall

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
The function TrajectoryExecutionManager::validate was checking the single joint names in the multi dof join case. I just change it to check the correct name. 
=> Fix multi dof validate trajectory

moveit_planners/ompl/CMakeLists.txt
The "OMPL" config was generated by the catkin/bloom infrastructure,
"ompl" is provided by upstream.
Recently, the former fails to work and we discussed
to change to the latter already half a year ago.
For more details see
https://github.com/ros/catkin/issues/938#issuecomment-390285366
https://github.com/ros-planning/moveit/issues/806#issuecomment-390353709
and
https://github.com/ros-planning/moveit/issues/169#issuecomment-353238742
@rhaschke this should resolve the missing cmake config problem you encountered with melodic too.
=> find_package ompl via upstream cmake config

moveit_core/robot_state/src/robot_state.cpp
Originally, if you were to try to get the Jacobian of a link that was at the end of a move group, but not a part of that move group (say a point on a gripper link at the end of a UR robot), then MoveIt would complain that this link was not a part of the move group, even though you should be able to find the jacobian for this point.
This change fixes that, and allows you to get the jacobian of any link that is a child of the move group being queried.
Don't quite have the time to make a test for this, considering there aren't any jacobian tests yet.
=> Can now get the jacobian of a child link of a move group.

moveit_core/planning_scene/src/planning_scene.cpp
Just like https://github.com/ros-planning/moveit/pull/878 ,
these messages should also not be printed every time by default.
At times they can also spam the terminal when a node uses
the PlanningScene internally.
=> make verbose PS INFO messages DEBUG

moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp
Fixes #719. Adds a custom `ompl::msg::OutputHandler` that uses `rosconsole` to log OMPL messages at the appropriate logging level.
=> OMPL logging that uses rosconsole

moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_execution.h, moveit_ros/planning/plan_execution/src/plan_execution.cpp
At the moment only `planAndExecute` is public API in `PlanExecution`, so previously created plans cannot be executed there . The proposed method can be used to do just that.
While this is nice to have standalone already, this pull request is in preparation to solve a problem mentioned in issue #468:
When using `plan()` and `execute()` with a `MoveGroupInterface` there is no check for collisions with newly added objects while executing the plan. 
In the `execute_trajectory_action_capability` the ` trajectory_execution_manager_` is used directly to execute the plan, but collision monitoring is only implemented in `PlanExecution`.
This problem can be solved by using the new method in `PlanExecution` instead.
A shortcoming here is that the capability receives a `RobotTrajectory` msg goal, …
=> Add method to monitor collisions while executing previously created plan

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.h, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
Adds a combo box to the MoveIt! Setup Assistant to choose a default planner.  PR fixes issue #637.
=> Added combo box to setup assistant for default planner

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
The monitor optionally kept track of velocities, accelerations & effort too,
but never wrote them to the output variable when asked for the current state...
With this change the monitored planning scene of the move_group node contains current dynamics information too, if enabled.
=> CSM: copy dynamics to output if enabled

moveit_plugins/moveit_ros_control_interface/README.md
The README text says "Just set the `moveit_controller_manager` parameter" but the example uses a `arg` instead of `param`.
=> Fix README example for using moveit_ros_control_interface

moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/virtual_joints_widget.cpp
As pointed out in #919, leading and/or trailing white space in group names (but also link and joint names) cause issues. The underlying reason is that srdfdom actually [trims those names during parsing](https://github.com/ros-planning/srdfdom/blob/kinetic-devel/src/model.cpp#L106). Hence, MSA should do the same. This PR fixes the most important occurences, but other names probably need trimming too...
=> MSA: trim group + link names

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/robot_state_test.cpp
These are the max_eef step changes from #844 I am separating the changes into 2 pr's. This one has everything except the additional Cartesian space jump tests, Changes include: the  MaxEEFStep parameter, minor changes to the tests to make them more comprehensive (and pass), and some minor fixes to comments and parameter names. 
@davetcoleman 
@rhaschke 
=> Max eef step

moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp
As discussed in maintainer meeting, quick fix for #868.
Later a separate EventQueue and spinner should be used.
@v4hn Please review
=> disable waitForCurrentRobotState()

moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
My third monitor is a tiny 1366x768 resolution portable monitor (but my other two are huge 32" screens :wink:) and the MoveIt! Rviz plugin doesn't fit anymore in Rviz on this monitor. I did some rework to shrink this down:
**Before**
**After**
I had to move some stuff on the first tab... **After:**
I also improved the naming of the trajectory slider panel from "Slider" to "Trajectory Slider"
=> Reduce size of Rviz MotionPlanning Window

moveit_experimental/package.xml, moveit_kinematics/package.xml, moveit_planners/chomp/chomp_interface/package.xml, moveit_planners/ompl/package.xml, moveit_plugins/moveit_controller_manager_example/package.xml, moveit_plugins/moveit_fake_controller_manager/package.xml, moveit_plugins/moveit_simple_controller_manager/package.xml, moveit_ros/manipulation/package.xml, moveit_ros/move_group/package.xml, moveit_ros/perception/package.xml, moveit_ros/visualization/package.xml
Follow-up of https://github.com/ros-planning/moveit/pull/827.
Some people having outdated version of pluginlib cannot compile the latest version of moveit that uses the new pluginlib headers.
Specifying the minimum required version in the package.xml makes the version constraint explicit and partially address the problem of users having mismatching versions.
=> add minimum required pluginlib version

moveit_core/robot_model/src/revolute_joint_model.cpp, moveit_core/robot_state/test/robot_state_test.cpp
Some continuous joints (e.g. joint1 on my Kinova Mico robot arm) will show as violating joint limits in some situations.   
This change returns true that continuous joints always satisfiesPositionBounds()
Originally, the urdf limits were set to -2PI to +2PI.  According to the Urdf Joint documentation, the limits should not be set for continuous joints; however, removing the limits gave the same joint violations in the moveit RViz window  for some continuous joints.
One could argue to set the limits to MIN_FLOAT and MAX_FLOAT, but that will not be defined with the "+/-margin" calculation in this file.
Thus, always returning true seems to me to be the safest for continuous joints.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel …
=> continous joint limits are always satisfied

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
Fixes issue #934: console spammed with warnings "Unable to update multi-DOF joint".
=> avoid warning spam: "Unable to update multi-DOF joint"

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/planning_scene_interface/src/wrap_python_planning_scene_interface.cpp, moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp, moveit_ros/visualization/src/moveit_ros_visualization/moveitjoy_module.py
This fixes another regression introduced by #835: The newly introduced optional ns args are not declared as optional to python, thus resulting in errors like the following if omitted:
```
Traceback (most recent call last):
File "/homes/rhaschke/src/ros/src/agni/agni-manipulation/agni_grasp_manager/scripts/grasp_manager.py", line 78, in __init__
r = RobotInterface("robot_description")
Boost.Python.ArgumentError: Python argument types in
RobotInterface.__init__(RobotInterface, str)
did not match C++ signature:
__init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```
=> allow optional namespace args

moveit_core/planning_scene/src/planning_scene.cpp
The robot state should be marked as diff, otherwise
PlanningScene::isEmpty(RobotState&) will not acknowledge
it as empty.
@rhaschke
=> fix PS getDiffMsg

moveit_ros/planning/plan_execution/src/plan_execution.cpp, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
This is useful because the plan_execution allows arbitrary callbacks
to run after successful execution of individual plan_components_.
So although the *trajectory* might be empty, we miss to run the
associated callbacks if we just skip the component/trajectory altogether.
This mechanism is very convenient for modular plans where some components
only invoke side effects.
@rhaschke
=> allow execution of empty trajectories

moveit.rosinstall
MoveIt! Visual Tools is now compatible with Melodic thanks to @IanTheEngineer
Its also just been bloomed by @davesteffen 
fyi @130s
=> Reinstate moveit_visual_tools to wstool

moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection/src/world.cpp
Provide a convienency method to move all shapes of a collision object. Before, for all shapes shapes we had to call `moveShapeInObject()`, which created overhead for finding the object over and over.
=> collision_detection::World::moveObject()

moveit_core/robot_state/src/conversions.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Currently once robot_state.is_diff has been set to true it will stay so. This breaks detaching attached objects. This is a fix for a regression introduced in #939
=> reset moveit_msgs::RobotState.is_diff to false

moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
`allowed_execution_duration_scaling` and `allowed_goal_duration_margin` were previously set globally and could not be specified for individual controllers.
This patch makes it possible to define the values for controllers in the `controller_list` parameter (they can be specified in the `controllers.yaml`).
A short example: 
``` 
controller_list:
- name: example_controller
type: FollowJointTrajectory
allowed_execution_duration_scaling: 1.2
allowed_goal_duration_margin: 0.5
```
The global value is still used whenever no controller-specific value was defined. 
@v4hn
=> Option for controller-specific duration parameters

.docker/ci-shadow-fixed/Dockerfile, .docker/ci/Dockerfile, .docker/release/Dockerfile, .docker/source/Dockerfile
- Building directly off of Ubuntu is no longer required because OSRF has now released for Melodic images
- A few improvements to ensure debians are the most up to date, inspired by https://github.com/ros-planning/moveit/pull/902
Replaces https://github.com/ros-planning/moveit/pull/902
=> Switch Docker to ROS Melodic base images

moveit_core/CMakeLists.txt, moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/kinematics_base/src/kinematics_base.cpp
To reduce potential bugs, I am enabling stricter warnings.
This PR also removed some unused variables that it found. There is still one warning this uncovers of potentially uninitialized variables, but debugging that is more complex and left as an exercise for the reader.
=> Enable gcc warnings, remove unused variables

moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ros_controllers.launch, moveit_setup_assistant/test/moveit_config_data_test.cpp
Adding functions to read and write `ros_contollers.yaml` file.
Adding an automated way to add FollowJointTrajectory action controller for each planning group, e.g. 
```
controller_list:
- name: g1_controller
action_ns: follow_joint_trajectory
default: True
type: FollowJointTrajectory
joints:
- joint1
- joint2
```
@davetcoleman @mcevoyandy 
- [needed] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
=> Read and write ROS controllers yaml file

moveit_planners/chomp/chomp_interface/package.xml
Fix the chomp package.xml to depend on cmake_modules, which is necessary to fix binary builds for it on the Melodic buildfarm.  An example problem is here: http://build.ros.org/view/Mbin_ds_dS64/job/Mbin_ds_dS64__moveit_planners_chomp__debian_stretch_amd64__binary/56/consoleFull
- [ N/A ] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ N/A ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ N/A ] Include a screenshot if changing a GUI
- [ N/A ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
[//]: # "You can expect a response from a maintainer within 7 days. If you …
=> Chomp needs to depend on cmake_modules.

moveit/CHANGELOG.rst, moveit_commander/CHANGELOG.rst, moveit_core/CHANGELOG.rst, moveit_experimental/CHANGELOG.rst, moveit_kinematics/CHANGELOG.rst, moveit_planners/ompl/CHANGELOG.rst, moveit_plugins/moveit_controller_manager_example/CHANGELOG.rst, moveit_plugins/moveit_fake_controller_manager/CHANGELOG.rst, moveit_plugins/moveit_simple_controller_manager/CHANGELOG.rst, moveit_ros/benchmarks/CHANGELOG.rst, moveit_ros/manipulation/CHANGELOG.rst, moveit_ros/move_group/CHANGELOG.rst, moveit_ros/perception/CHANGELOG.rst, moveit_ros/planning/CHANGELOG.rst, moveit_ros/planning_interface/CHANGELOG.rst, moveit_ros/robot_interaction/CHANGELOG.rst, moveit_ros/visualization/CHANGELOG.rst, moveit_ros/warehouse/CHANGELOG.rst, moveit_setup_assistant/CHANGELOG.rst, moveit_setup_assistant/src/tools/moveit_config_data.cpp
This removes the pesky trailing whitespace from the auto generated ompl_planning.yaml
You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!
=> removing trailing whitespace from autogenerated ompl_planning.yaml

.travis.yml, moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp, moveit_ros/perception/occupancy_map_monitor/src/occupancy_map_monitor.cpp
I fixed some more compiler warnings (due to more sensitive compiler flags introduced in 0b4600e2b41e8de61b53ee96272f6eb0539aeb93, but hidden due to #943).
Unfortunately, the unittest in move_ros_perception fails. This seems to be related to a bug in Mesa OpenGL - switching to nvidia OpenGL, the test passes flawlessly.
Hence, I disable this test for now.
=> fix moveit_ros_perception

moveit_ros/manipulation/pick_place/src/approach_and_translate_stage.cpp, moveit_ros/manipulation/pick_place/src/plan_stage.cpp
The current pick and place pipeline silently assigns a default duration of an arbitrary (and long) 7 seconds to each action of the gripper. This PR adds a message alerting the user to this behavior, and prompts them to define an appropriate wait time for their own gripper. This helps them identify a problem which is otherwise not trivial to debug, due to the structure of the planning stages. Case in point: it was [an issue](https://github.com/ros-planning/moveit_tutorials/pull/200) in the official pick and place tutorial.
I suppose this should have been a PR on melodic-devel and cherry-picked to Kinetic. Let me know if anything needs changing.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank …
=> Add info messages to pick and place routine

moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/resources/default_config/sensors_3d.yaml, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/perception_widget.cpp, moveit_setup_assistant/src/widgets/perception_widget.h, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.h, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/sensor_manager.launch.xml, moveit_setup_assistant/test/moveit_config_data_test.cpp
This perception screen works as the following:
if (package has a 3d sensors config file) loads it into the screen
else load the default values from `moveit_setup_assistanat/resources/config/sensors_rgbd.yaml` -name is not final-.
when the user leaves the screen, saves the new config values to the `sensors_rgbd.yaml` to the package, if the user selected `none` from the plugin type drop down then no config file is saved.
=> Perception screen added for the SA

moveit_ros/benchmarks/examples/demo1.yaml, moveit_ros/benchmarks/examples/demo2.yaml, moveit_ros/benchmarks/examples/demo_obstacles.yaml, moveit_ros/benchmarks/examples/demo_panda.launch, moveit_ros/benchmarks/examples/demo_panda_all_planners.launch, moveit_ros/benchmarks/examples/demo_panda_all_planners.yaml, moveit_ros/benchmarks/examples/demo_panda_all_planners_obstacles.launch, moveit_ros/benchmarks/src/BenchmarkExecutor.cpp
This PR is a work done by Raghavender as a part of 2018 Google summer of code. As a part of this PR, benchmarking works for different motion planners (CHOMP, STOMP, OMPL) available in MoveIt. For a particular benchmark(start sates, planning scene, goal states, queries, etc.), different planners can be evaluated.
=> Benchmarking with different Motion Planners (STOMP, CHOMP, OMPL)

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.h
Renamed widgets in setup assistant widget to follow naming convention
=> Renamed variable names in setup assistant widget to follow naming convention

moveit_setup_assistant/src/widgets/group_edit_widget.cpp
Planning Groups screen re-configured to solve spacing between items problems.
=> Planning Groups screen re-configured

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/gazebo.launch
Added a gazebo launch file template for the setup assistant.
For the ur10 robot it looks like [that](https://gist.github.com/MohmadAyman/5c4027155abd2bea929b9fa07738600f). 
=> Added gazebo launch file

moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/perception_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.h, moveit_setup_assistant/src/widgets/simulation_widget.cpp, moveit_setup_assistant/src/widgets/simulation_widget.h, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
This PR is a part of improving the integration between gazebo, moveit and ros [issue 894](https://github.com/ros-planning/moveit/issues/894).
For a robot to be rendered in gazebo [it has to has an `inertial` element for each link](http://gazebosim.org/tutorials/?tut=ros_urdf), this PR tells the user if the urdf didn't contain them.
and views the new `urdf` on the simulation window for the user.
Added `elements`  which the user should add to his `urdf` are colored in green.
Once this PR is merged, the `[gazebo.launch]`(https://github.com/ros-planning/moveit/pull/936) will point to this new urdf.
The documentation of the setup assistant are updated in this [PR](https://github.com/ros-planning/moveit_tutorials/pull/184).
[//]: # "You can expect a response from a maintainer within 7 days. If …
=> Simulation Screen for the SA

moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/perception_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.h
1. Fixing a bug that makes the SA crashes when switching from the perception screen.
2. Improve documentation.
=> fix bug in perception screen

moveit_ros/warehouse/warehouse/src/warehouse_services.cpp
Added retries param to re-attempt connection to db if timeout occurs.
Also added param for timeout.
=> added param for timeout, added retries

.github/PULL_REQUEST_TEMPLATE.md
From: Ridhwan Luthra via email:
> I am a part of the ROS quality assurance group and we were discussing a way to promote pull request reviewing. As a part of the discussions, we came up with a plan that whenever a contributor would submit a pull request they are supposed to review another pull request before their's is merged.
> In, the discussions that I had with mike and Michael yesterday they hinted that we need a lot of help in reviewing pull requests, so I suggested that we could pick MoveIt! as a pilot repository.
I was requested to make this change so I added a new line item to the pull request guidelines. I also:
- Clarified meaning of "Required"... its enforced by the continuous integration
- Removed "optional" since that is assumed when the first item is the only one bold and …
=> PR template: Suggest contributors review other PRs

moveit_core/collision_detection_fcl/src/collision_common.cpp
Fixed issue #988
Use method CollisionGeometryData::getID() instead of direct access to object field regardless its type.
=> Fixed bad_alloc in collision_detection::distanceCallback

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
Added the setup_assistant window icon to appear on the launcher
=> added a setup assistant window icon

moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template
Allows usage of setup_assistant.launch that is auto-generated by MSA
cherry-pick to Melodic
=> Add moveit_setup_assistant as depenency of all *_moveit_config pkgs

moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
trajectory_execution_manager wait for next robot state, this will stops ~1 sec when we override current executing trajectory.
```
[ INFO] [1533023405.479727020]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1533023405.484524626]: Planner configuration 'right_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1533023405.486173640]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1533023405.510122152]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1533023405.510232552]: Solution found in 0.024775 seconds
[ INFO] [1533023405.523313210]: SimpleSetup: Path simplification took 0.012476 seconds and changed from 3 to 2 states
[ …
```
=> do not wait for robot, when trajectory_execution_manager stopped with PREEMPTED mode

moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/gazebo.launch
Thisa regressions introduced in #658 which was raised in issue https://github.com/ros-planning/moveit/issues/955
This stops the setup assistant from appending ``kConfigDefault`` to planner names and correctly trims  ``kConfigDefault`` from existing ompl_planning.yaml files.
=> removing regression introduced in #658

moveit_core/distance_field/include/moveit/distance_field/propagation_distance_field.h, moveit_core/distance_field/src/propagation_distance_field.cpp, moveit_core/distance_field/test/test_distance_field.cpp, moveit_core/kinematics_metrics/src/kinematics_metrics.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp, moveit_ros/manipulation/pick_place/include/moveit/pick_place/manipulation_plan.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/stereo_camera_model.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/transform_provider.h, moveit_ros/planning/planning_components_tools/src/visualize_robot_collision_volume.cpp
I had some Eigen struct alignment issues on my system, thus I had to check all the used source code for alignment issues. However, I also had some in moveit.
These aligment issues caused segmentation faults, e.g. in kinematics_metrics.cpp, getManipulability, line 228 while creating the Eigen::JacobiSVD to calculate the manipulability index:
```
Eigen::MatrixXd jacobian = state.getJacobian(joint_model_group);
Eigen::JacobiSVD<Eigen::MatrixXd> svdsolver(jacobian);
Eigen::MatrixXd singular_values = svdsolver.singularValues();
for (int i = 0; i < singular_values.rows(); ++i)
ROS_DEBUG_NAMED("kinematics_metrics", "Singular value: %d %f", i, singular_values(i, 0));
manipulability = penalty * singular_values.minCoeff() / singular_values.maxCoeff();
```
However, after adding missing aligned …
=> Fix some alignment issuses due to missing aligned allocation

moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch
Enable the user to pass capabilities that should be loaded / inhibited
as arg to move_group.launch
I ran into the issue because I wanted to load capabilities into the move_group from another package.
Without this PR I would need to duplicate the move_group.launch file.
Passing it as an arg is the same way the other args are handled.
=> Added capabilties as arg to move_group.launch

moveit_setup_assistant/package.xml, moveit_setup_assistant/test/moveit_config_data_test.cpp
* Use panda robot in testing of `moveit_config_data` instead or pr2.
* Write test temp file to `/tmp` instead of `moveit_resources` package.
(http://moveit.ros.org/documentation/contributing/)
=> Use panda robot in testing instead or pr2

.docker/ci/Dockerfile, .docker/source/Dockerfile
Merging `wstool init + merge + update` into a single `wstool init` command, allows to use the new `--shallow` option to enforce shallow git clone.
However, the `source` container shouldn't use shallow clone.
=> shallow workspace checkout

moveit_core/robot_state/src/robot_state.cpp, moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
This PR fixes a bug in the CurrentStateMonitor::tfCallback() method. The old implementation does not take the joint's origin into account. This leads to wrong transformations in the PlanningScene of a PlanningSceneMonitor if the transformation to a floating joint's origin is not the identity.
A demo of the bug can be found here: https://github.com/xaver-k/floating_joint_test
We calculate the pose of a child link relative to its parent as the concatenation of the transformations `parent -> joint origin` and `joint origin -> child`, where `joint origin -> child` is dependent on the joint variable(s). With 1D-joint (rotational, prismatic) we can update the joint variable directly from the `/joint_states` topic.
In contrast, we update the joint variables of floating joints from TF. The data …
=> Fix CurrentStateMonitor update callback for floating joints with non-identity joint origin

moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h
Closes #1052. See the issue for further information.
=> Include boost/thread/mutex.hpp in trajectory_visualization.h

MIGRATION.md, moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
As described in https://github.com/ros-planning/moveit/issues/868#issuecomment-385127395, ROS service capabilities will essentially block the global event queue. Thus, key components as the PlanningSceneMonitor (and the associated CurrentStateMonitor) should use their own event queue and spinner to become independent of the global queue.
=> Fix #868: calling service capability locks PlanningSceneMonitor

moveit_setup_assistant/src/widgets/perception_widget.cpp
Updating perception tutorial link in the perception widget.
it has been changed from http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/perception_configuration_tutorial.html
to http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/perception_pipeline/perception_pipeline_tutorial.html
=> update perception tutorial link in SA

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/projection_evaluators.h, moveit_planners/ompl/ompl_interface/src/detail/projection_evaluators.cpp
Defined an OMPLProjection that is typedef'd to work with versions <= 1.4 of OMPL
It's not strictly necessary for most setups, but I believe there is no harm in having it in kinetic too.
=> backport (#903) to kinetic

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_ros/planning/planning_components_tools/src/publish_scene_from_text.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp
Before this PR, there was no error checking when loading planning scene geometry from a text file. This meant the caller couldn't tell whether the planning scene had been successfully loaded.
Not sure if this should be cherry-picked. It changes the return type of two PlanningScene member functions, so I think it would require people to re-compile their code.
=> Check errors when loading scene geometry from files

moveit_core/robot_state/src/robot_state.cpp
Documenting why the setFromIK call in computeCartesianPath uses a single attempt rather than the default.  
=> Documenting why setFromIK in computeCartesianPath does not use random restarts

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_trajectory.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp, moveit_ros/planning/planning_request_adapters_plugin_description.xml
This PR is a work done by Raghavender as a part of 2018 Google summer of code. As a part of this PR, CHOMP planning adapter works and can be used as an additional optimization technique in combination with other motion planners like OMPL. 
With this PR, CHOMP can act as a post-processor for other planners. one simply needs to add a line in their[ ompl_planning_pipeline.yaml ](https://github.com/ros-planning/panda_moveit_config/blob/master/launch/ompl_planning_pipeline.launch.xml)file if they want to use this. Just add this line in your planning_adapter= > `default_planner_request_adapters/CHOMPOptimizerAdapter` to add CHOMP a an additional post-processing optimizer.
Corresponding Tutorials PR available [here](https://github.com/ros-planning/moveit_tutorials/pull/204/)!
=> Addition of CHOMP planning adapter for optimizing result of other planners

moveit_core/robot_model/src/robot_model.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/conversions.cpp, moveit_core/robot_state/src/robot_state.cpp
Using `name_` variable for logging rather than `"robot_state"`
=> using LOGNAME variable rather than strings for logging

moveit_plugins/moveit_fake_controller_manager/src/moveit_fake_controller_manager.cpp
This change handles a bug in the fake_controller_manager where the initial pose message was being missed some large percentage of the time. 
The relevant code was initially added by Ioan and updated by @rhaschke in https://github.com/ros-planning/moveit/commit/e1d91fec2587c7f13533ab3c140600685c87ca52
=> fixing initial pose behavior when using the fake_controller_manager

moveit.rosinstall
Also encourage community to contribute by auto-checking out sourcecode
This is in response to a breakage over a recent API change with TF: https://github.com/ros-planning/moveit_tutorials/pull/232#pullrequestreview-165233009
=> Add tutorials to CI build to prevent breakages

.travis.yml
We do not have any plans to release another Lunar build and decided to our maintainer meetings to drop support for this a while back. This is reflected on our website, README.md, and elsewhere. Ergo, let's not test for it to avoid issues like this:
https://github.com/ros-planning/moveit/pull/1094
=> No longer support Lunar on Travis

moveit_ros/perception/point_containment_filter/src/shape_mask.cpp, moveit_ros/perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp
Moved error msg from callee (`getShapeTransform`) to caller (`maskContainment`).
Also I don't think it belongs in this lookup function in the first place.
The signature defines a bool return value for success/failure.
This builds on a change in geometric_shapes 0.5.4.
So I think this request can wait until the new version is rolled out.
=> Provide more informative error message if shape transform cannot be found

moveit_core/robot_model/include/moveit/robot_model/robot_model.h, moveit_core/robot_model/src/robot_model.cpp, moveit_core/robot_model/test/test.cpp
If the robot structure contains y-paths made up of fixed transforms, the
previous implementation missed these associations in the associated_transforms.
The structure
- a - b - c
\
- d
only added associationed fixed transforms for a and b to c, but missed d.
I missed to submit this request when I wrote it two months ago
and it just popped up again [here](https://github.com/ros-planning/moveit/pull/877#issuecomment-390494029).
=> include fixed tfs to siblings in links

.travis.yml, moveit_ros/visualization/motion_planning_rviz_plugin/CMakeLists.txt, moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/CMakeLists.txt, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp, moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
As part of MoveIt's tf2 migration for `melodic` in https://github.com/ros-planning/moveit/pull/830, there were upstream changes required to RViz, `tf1`, and `tf2`. The changes to RViz and `tf1` were not backwards compatible with Kinetic. 
The moveit maintainers have a desire to have MoveIt compile on both ROS Kinetic and Melodic with the same branch, summed up in this ticket:  https://github.com/ros-planning/moveit/issues/925 . The final step in #925 is to find an acceptable way to maintain tf2 buffers for interacting with RViz. In Kinetic, RViz doesn't easily expose its internal and protected tf2 buffers. I tried several ways to get at these buffers in Kinetic as described https://github.com/ros-visualization/rviz/issues/1215, without any success. 
In the end, for Kinetic, it is simplest …
=> Building melodic-devel on ROS Kinetic

moveit_planners/moveit_planners/package.xml
Per my suggestion https://github.com/ros-planning/moveit/issues/1083#issuecomment-432737000 that is based on the discussion at https://github.com/ros-gbp/moveit-release/pull/5#discussion_r227781794, `chomp` packages will be included in the list of released packages.
For the chomp packages to be easily installed by just installing `moveit` (e.g. `apt-get install ros-%DISTRO%-moveit`), those packages need to be included in the dependency chain that's rooted from `moveit`. The change in this PR realizes that.
=> Include chomp packages in a dependency chain starting from moveit metapkg

moveit_planners/chomp/README.md
Fixes the link to the chomp planning plugin documentation. Old link 404'd. Now links to the chomp tutorial on moveit.ros.org
- [x ] Decide if this should be cherry-picked to other current ROS branches
=> Update link to chomp documentation

moveit_core/collision_detection/src/world.cpp
This is a follow up to #957, which introduced World::moveObject().
When transform is the identity matrix, i.e. there is no movement, the object shouldn't be touched.
This follows the rule, only to create a copy of the parent planning scene, when there are actual modifications.
=> World::moveObject(): only apply changes if there is any non-zero motion

.clang-format, moveit_experimental/collision_distance_field/include/moveit/collision_distance_field/collision_common_distance_field.h, moveit_experimental/collision_distance_field/include/moveit/collision_distance_field/collision_robot_distance_field.h, moveit_experimental/collision_distance_field/include/moveit/collision_distance_field/collision_robot_hybrid.h, moveit_experimental/collision_distance_field/include/moveit/collision_distance_field/collision_world_distance_field.h, moveit_experimental/collision_distance_field/src/collision_robot_distance_field.cpp, moveit_experimental/collision_distance_field/src/collision_robot_hybrid.cpp, moveit_experimental/collision_distance_field/src/collision_world_distance_field.cpp, moveit_experimental/collision_distance_field/test/test_collision_distance_field.cpp
Fix pre request of @v4hn to allow https://github.com/ros-planning/moveit/pull/718 to be merged in
See documentation of [Standard](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
=> Prevent C++11 style enforcement in indigo-devel

moveit_core/collision_detection/include/moveit/collision_detection/world_diff.h, moveit_core/collision_detection/src/world_diff.cpp, moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/macros/include/moveit/macros/declare_ptr.h, moveit_experimental/collision_distance_field/src/collision_common_distance_field.cpp
Following the same scheme as for shared_ptrs, also define weak_ptrs.
Replace existing explicit occurences of weak_ptrs.
=> Add declarations of weak ptrs

moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp
Multiple values from the PlanningFrame (see Image) are not stored in the config.
Fixed by this PR. Still missing is the valueChanged notification to rviz. Will open seperate PR.
=> Fix values in PlanningFrame not beeing stored

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
- Will match the python MoveGroup API
The python tutorials have [this ability](https://github.com/ros-planning/moveit_tutorials/blob/melodic-devel/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py#L129) but the CPP one does not yet. This adds that.
Depended on by https://github.com/ros-planning/moveit_tutorials/pull/247
=> Get available planning group names from MoveGroup C++

MIGRATION.md, moveit_core/robot_state/include/moveit/robot_state/robot_state.h
This method only returns a single transform, hence a singular form name should be used.
Interestingly this method was never used inside MoveIt.
=> fix typo getCollisionBodyTransform(s)

moveit_commander/package.xml, moveit_ros/planning/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template
Alternative fix of Melodic release build (instead of #1169).
Remove all left-over tf1 stuff:
```
$ grep -r "<tf/" .
./moveit_ros/planning/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp:#include <tf/transform_listener.h>
$ grep -r ">tf[^2]" .
./moveit_commander/package.xml:  <run_depend>tf</run_depend>
```
=> remove left-over tf artifacts

moveit_planners/ompl/ompl_interface/src/model_based_planning_context.cpp
Remove a spurious dependency on `eigen_conversions/eigen_msgs.h` in model_based_planning_context.cpp; as far as I can tell, it is not necessary, and is causing the build to fail on the Melodic build farm: http://build.ros.org/job/Mbin_uB64__moveit_planners_ompl__ubuntu_bionic_amd64__binary/17/console
=> A spurious dependency on eigen_msgs is causing OMPL to fail to build.

moveit_planners/chomp/chomp_interface/test/rrbot_move_group.launch, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
The MoveIt setup assistant has the `optional xacro arguments` field set up to `--inorder` by default. As of Melodic specifying `--inorder` is not needed anymore and leads to warnings when reading the launch files.
This PR removes this default argument.
Do not cherry-pick this to any other branch.
=> Remove --inorder default argument in setup assistant

.github/PULL_REQUEST_TEMPLATE.md
As promised in the following comment https://github.com/ros-planning/moveit/pull/1027#issuecomment-414323201, the ROS code review guidelines are ready and added a link to the pull request template.
=> PR template: Add ROS code review guide (#1027)

moveit_ros/planning/trajectory_execution_manager/cfg/TrajectoryExecutionDynamicReconfigure.cfg
Trivial change: increase dynamic reconfigure upper limit for TrajectoryExecutionManager allowed_goal_duration_margin.
=> Change dynamic reconfigure limits for allowed_goal_duration_margin to 30s

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_model/include/moveit/robot_model/robot_model.h, moveit_core/robot_model/src/robot_model.cpp, moveit_core/transforms/include/moveit/transforms/transforms.h, moveit_core/transforms/src/transforms.cpp, moveit_ros/move_group/src/move_group.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
Lots of minor, non-behavior cleanup and commenting as I debugged an issue with the planning scene transforms. Changes are cleanly separated by commits and should be **Rebased and Merged** but not cherry-picked backwards.
- Cleanup PlanningScene
- Cleanup RobotModel
- Cleanup Transforms
- Cleanup various moveit_ros packages
=> Various Cleanup and Commenting

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_display.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/planning_scene_rviz_plugin/include/moveit/planning_scene_rviz_plugin/planning_scene_display.h, moveit_ros/visualization/planning_scene_rviz_plugin/src/planning_scene_display.cpp, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/trajectory_visualization.h, moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
Rebase of #1152. Splitted into the basic fix (this PR) and the additional new feature providing a BoolProperty to switch attached bodies on/off (#1200).
This fixes #512.
Also added bug fixes for several other rendering issues I observed during testing the initial commit.
Look into individual commits for details.
=> fix several issues in rendering of attached bodies in rviz plugins

moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_world_fcl.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/fcl_compat.h, moveit_core/collision_detection_fcl/src/collision_common.cpp, moveit_core/collision_detection_fcl/src/collision_robot_fcl.cpp, moveit_core/collision_detection_fcl/src/collision_world_fcl.cpp
The (still unreleased) fcl 0.6 changed paths to relevant headers as well as the name of many types.
This patch adds support for fcl 0.6 without breaking support for fcl 0.5.
This patch adds the header fcl_compat.h to check for the fcl version and include fcl headers accordingly.
The old types are exchanged to the newer ones throughout the package.
Compability to fcl 0.5 is ensured by creating type aliases that map the old types to the new ones.
The other way around might be the better choice for now, but the old type names are still in use in the new versions (as templates), so the alias trick only works this way around.
For this a lot of code from @Levi-Armstrong was used, who already created a branch with support for fcl 0.6 but without support for fcl 0.5: …
=> add support for fcl 0.6

.docker/source/Dockerfile
Seems the build is too long for Dockerhub:
https://hub.docker.com/r/moveit/moveit/builds/bqpkzerbe3yoeagszguchwu/
=> Remove catkin build from source docker

.clang-format, moveit_core/constraint_samplers/src/constraint_sampler_manager.cpp, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/kinematic_constraints/src/kinematic_constraint.cpp, moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_experimental/collision_distance_field/src/collision_robot_distance_field.cpp, moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp, moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp, moveit_kinematics/lma_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp, moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/constraints_library.h, moveit_planners/ompl/ompl_interface/src/constraints_library.cpp, moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp, moveit_plugins/moveit_simple_controller_manager/src/moveit_simple_controller_manager.cpp, moveit_ros/benchmarks/benchmarks/src/benchmark_execution.cpp, moveit_ros/perception/point_containment_filter/src/shape_mask.cpp, moveit_ros/perception/semantic_world/src/semantic_world.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_manipulation.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_scenes.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_states.cpp
This is an attempt to improve the results of clang-format. Particularly:
* increase penalty to break literal strings
* ~~increase penalty to break before first argument in function calls~~
* reduce penalty to put return type on its own line
I think the resulting code is much better readable.
=> Improve clang format

moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
Use namespace to shorten source lines.
=> RobotModelLoader: use namespace robot_model_loader

MIGRATION.md, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/kinematics_base/CMakeLists.txt, moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_core/kinematics_base/src/kinematics_base.cpp, moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h, moveit_core/robot_model/src/joint_model_group.cpp, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin-inl.h, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/cached_ik_kinematics_plugin.h, moveit_kinematics/cached_ik_kinematics_plugin/src/ik_cache.cpp, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h, moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/lma_kinematics_plugin.h, moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_plugin.cpp, moveit_kinematics/srv_kinematics_plugin/include/moveit/srv_kinematics_plugin/srv_kinematics_plugin.h, moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp, moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp
This is an alternative implemenation of #150 and #1153 to directly pass a RobotModel (RM) to kinematics plugins, thus
1) saving some loading time by reusing the `RobotModel` (particularly if there are dozens of groups)
2) ensuring a consistent RM (particularly, joint limits) is used throughout the code
#150 eventually got stuck due to circular reference of `RobotModelPtr` as detailed in https://github.com/ros-planning/moveit/pull/150#issuecomment-433106660.
To avoid/break this circular reference #1153 transferred ownership of KinematicSolvers (KS) from JointModelGroup (JMG) to KinematicsPluginLoader (KPL) / RobotModelLoader (RML). While this works, I think this is an evil hack. Ownership definitely belongs to JMG. This already becomes obvious from the fact that a RM with JMGs can …
=> Pass RobotModel to kinematics plugins

moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
add `ROS_ERROR_STREAM_NAME` for `INVALID_MOTION_PLAN` and `GOAL_CONSTRAINTS_VIOLATED` in `chomp_planner`
=> add more ROS_ERROR_STREAM_NAMED in chomp_planner.cpp

moveit_core/robot_state/src/robot_state.cpp
Both are critical failure conditions that went without error message before.
=> add additional error output logging in setFromIK

moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
Use case: I want to execute a trajectory asynchronously while also being able to monitor its execution and perhaps abort it.
* `MoveGroupInterface::asyncMove()` lets me start asynchronous execution
* `MoveGroupInterface::stop()` lets me abort it
* but there is no way to monitor the execution or get the result
This PR simply adds a getter for the internal `move_action_client`. This enables code like shown in the usage example below. I'm not sure that exposing the internal `move_action_client` is the nicest API (comments welcome), but at least it seems more elegant than replicating all of the client's API one-by-one. In the example below, I've only used `getState()`, `getResult()` and `cancelGoal()`; but the other methods are useful as well (for example `waitForResult()`).
```cpp …
```
=> Add getMoveGroupClient() to move_group_interface

moveit_planners/chomp/chomp_interface/CMakeLists.txt
Apparently I did not see this solution the last time
I looked into it.
An isolated `find_package(catkin REQUIRED)` to define CATKIN_ENABLE_TESTING works just fine.
This is meant to be a better fix for https://github.com/ros-planning/moveit/pull/1203
(esp. the melodic version of it that robert merged already).
I verified this allows to build the melodic-devel tests on current ubuntu 16.04 + ROS kinetic.
=> chomp correctly sort test dependencies

moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp
Current `last_state` implementation in `chomp_planner` regards `active joints == all joints`, which does not happen for dual arm robot such as `baxter`.
=> set last_state only for active joints in chomp_planner

moveit_planners/chomp/chomp_interface/CMakeLists.txt
chomp correctly sort test dependencies (#1224)
Apparently I did not see this solution the last time
I looked into it. This is meant to be a proper fix
for https://github.com/ros-planning/moveit/pull/1203
(esp. the melodic version of it that robert merged already).
=> Kinetic Backport of #1224

moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_core/robot_trajectory/src/robot_trajectory.cpp
As a solution to #1212, we propose adding an append function to robot_trajectory::RobotTrajectory, which takes a start- and end-index for appending only a part of the trajectory. By this, we avoid re-assembling or removing points from an existing trajectory.
A cherry-pick to kinetic would be desirable.
=> Add append function for appending only part of a trajectory

moveit_core/CMakeLists.txt, moveit_experimental/CMakeLists.txt, moveit_kinematics/CMakeLists.txt, moveit_kinematics/ikfast_kinematics_plugin/templates/CMakeLists.txt, moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_planners/chomp/chomp_motion_planner/CMakeLists.txt, moveit_planners/ompl/CMakeLists.txt, moveit_plugins/moveit_controller_manager_example/CMakeLists.txt, moveit_plugins/moveit_fake_controller_manager/CMakeLists.txt, moveit_plugins/moveit_ros_control_interface/CMakeLists.txt, moveit_plugins/moveit_simple_controller_manager/CMakeLists.txt, moveit_ros/benchmarks/CMakeLists.txt, moveit_ros/manipulation/CMakeLists.txt, moveit_ros/move_group/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/robot_interaction/CMakeLists.txt, moveit_ros/visualization/CMakeLists.txt, moveit_ros/warehouse/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
On Ubuntu 18.04, gcc-7 defaults to C++14.
On Ubuntu 16.04, C++14 is available, but only used if explicitly set.
http://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023
> Targeted Languages:
>  *   C++14
=> [C++14] Use C++14 in Melodic

moveit_core/constraint_samplers/CMakeLists.txt, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_kinematics/CMakeLists.txt, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_pinv_mimic.hpp, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/chainiksolver_pos_lma_jl_mimic.h, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/chainiksolver_vel_pinv_mimic.h
- The previous VERSION_LESS check is broken,
the orocos_kdl_VERSION is not evaluated in this context
- The definition is not exported to third-party projects
that might include the header. After all these headers are public API.
Verified to compile with ROS kinetic + external kinematics plugin that include the headers (ur_kinematics).
=> fix compatibility with KDL 1.3

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui
Fixes #1069.
The request consists of multiple commits.
The first one fixes rviz crashing when the planning group is changed while executing a trajectory.
The problem was the destruction of a MoveGroupInterface that also holds the SimpleActionClient used to execute the trajectory. The proposed solution here creates a local shared pointer of the object for execution to ensure that the object is not destroyed asynchronously. 
The other two commits change the gui in the planning tab.
This is the old state of the planning tab: 
The first addition is a dropdown menu for choosing a planning group:
Previously it was only possible to choose the planning group in the MotionPlanning display. The dropdown menu is synchronized with the display property.
The final commit tries to streamline the …
=> select planning group in planning tab and simplify selecting goal and start states

moveit_ros/planning/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp
The parameter updated for `"trajectory_initialization_method"` was `use_stochastic_descent_` instead, possibly due to a copy-paste leftover.
This caused a segfault when trying to load this plugin with this parameter set, as the value of `params_.trajectory_initialization_method_` was never actually read.
This should also be forward-ported to `melodic`.
=> Use correct trajectory_initialization_method param

moveit_ros/perception/CMakeLists.txt
The build is broken without it for a long time already
and it is not reasonable to compile the octomap updater
plugins without OpenMP speedup.
=> enforce OpenMP support for perception

moveit_core/collision_detection/include/moveit/collision_detection/collision_detector_allocator.h, moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_common.h, moveit_core/distance_field/test/test_distance_field.cpp, moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/robot_model/src/robot_model.cpp, moveit_kinematics/cached_ik_kinematics_plugin/src/ik_cache.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/multivariate_gaussian.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp
fix clang issues
- use MOVEIT_STRUCT_FORWARD for structs
- fix initialization of dynamic-size array
- fix implicit conversion for SortableDisabledCollision -> srdf::Model::DisabledCollision
- virtual destructors for classes with virtual methods
- use delete[] for memory allocated with new[]
=> Selective backport of #1196 (clang fixes)

moveit_ros/visualization/motion_planning_rviz_plugin/include/moveit/motion_planning_rviz_plugin/motion_planning_frame.h, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_display.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_planning.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/ui/motion_planning_rviz_plugin_frame.ui
Rebase of #931 for Melodic, with additional cleanup and fixes:
- remove `cartesianPathToggled()`
- reduce code duplication in `computeCartesianPlan()` and `computeJointSpacePlan()`
- fix seg-fault occuring when there is no unique end-effector link
- save/load status of new checkbox
- report planning time as requested by @felixvd
@k-okada, please review.
=> motion_planning_rviz_plugin : add CartesianPath planning check box

.clang-tidy
- disable all checks
- to allow selective enabling afterwards (otherwise many undesired checks are enabled too)
- order checks
=> cleanup .clang-tidy

moveit_ros/move_group/src/move_group.cpp
When a move_group capability is not found, both pluginlib and move_group prints the list of available types. This PR removes this redundancy:
```
[ERROR] ros.moveit_ros_move_group: Exception while loading move_group capability 'dummy/unknown': According to the loaded plugin descriptions the class dummy/unknown with base class type move_group::MoveGroupCapability does not exist. Declared types are  move_group/ApplyPlanningSceneService move_group/ClearOctomapService move_group/ExecuteTaskSolutionCapability move_group/MoveGroupCartesianPathService move_group/MoveGroupExecuteService move_group/MoveGroupExecuteTrajectoryAction move_group/MoveGroupGetPlanningSceneService move_group/MoveGroupKinematicsService move_group/MoveGroupMoveAction move_group/MoveGroupPickPlaceAction …
```
=> move_group: remove redundant list of capabilities

moveit_planners/chomp/chomp_interface/CMakeLists.txt
Followup to https://github.com/ros-planning/moveit/pull/1251#discussion_r240041450
@rhaschke
=> chomp: explicitly set variable as empty when unused

.travis.yml, moveit_ros/perception/mesh_filter/CMakeLists.txt
Apparently [`TEST_BLACKLIST` doesn't work on Indigo to disable tests](https://travis-ci.org/ros-planning/moveit/jobs/459651275#L1452).
Using environment variable `TRAVIS` to disable mesh-filter tests (similarly as in Kinetic / Melodic, #982).
=> fix Travis Indigo

moveit_experimental/CMakeLists.txt, moveit_experimental/package.xml
As suggested in https://github.com/ros-planning/moveit/pull/1251#discussion_r240238940, comment-out all stuff in moveit_experimental, as there is nothing built.
=> moveit_experimental: commenting out dependencies

moveit_core/constraint_samplers/test/test_constraint_samplers.cpp
Just accidentally noticed that `DisplayTrajectory` is not used in there.
=> remove obsolete include

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/robot_state_benchmark.cpp
With #1096, 6cc3d62c7ae713413d8df7d4cf9ff09c43b5b486, I slightly improved FK in RobotState, exploiting the fact that the last row of the transform matrix is always `[0 0 0 1]`, performing a `3x4` * `4x4` matrix multiplication. However, this improvement also requires an initialization of this row, once.
This PR fixes this and also improves the corresponding timing tests.
=> fix uninitialized RobotState transforms

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_ros/planning/planning_components_tools/CMakeLists.txt, moveit_ros/planning/planning_components_tools/src/print_planning_scene_info.cpp, moveit_ros/planning_interface/test/python_move_group.test
There was already a ``moveit_print_planning_model_info`` utility so I copied that and adapted it as a debugging tool for the planning_scene attached objects
=> New command line utility tool to print planning scene info

moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/ompl_interface.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h, moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp
The `last_planning_context_` is not used inside the MoveIt codebase (anymore).
=> OMPL Interface: remove last_planning_context_

MIGRATION.md, moveit_ros/planning/rdf_loader/include/moveit/rdf_loader/rdf_loader.h, moveit_ros/planning/rdf_loader/src/rdf_loader.cpp, moveit_ros/planning/robot_model_loader/include/moveit/robot_model_loader/robot_model_loader.h, moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
`urdf::Model::initXml()` is highly inefficient, as it first serializes the string and eventually
parses it again (see https://github.com/ros/urdf/issues/24#issue-389498748). We should discourage and eventually remove the TinyXML API and solely rely on parsing from string.
For now, this is just a proof-of-concept that the MoveIt source repo doesn't need the TinyXML support.
A user-friendly approach would deprecate the TinyXML API first, but, maybe, that's not really necessary?
Opinions?
=> [proposal] RDFLoader / RobotModelLoader: remove parsing of TinyXML documents

moveit_core/utils/CMakeLists.txt
Without this I get sporadic build failures because the JointLimits.h message header isn't generated before the test library is compiled.
This should be cherry picked to kinetic-devel.
=> Moveit test lib depends on message generation

moveit_core/CMakeLists.txt
Originated from: https://github.com/ros-planning/moveit/issues/1
Provides a CMake target to generate a coverage analysis of moveit_core.
Usage: `catkin_make -DENABLE_COVERAGE_TESTING=ON moveit_core_coverage`
=> Add coverage analysis for moveit_core

moveit_commander/src/moveit_commander/move_group.py
I needed to access the get_named_target_values function, so I just exposed it. Related issue: #1063 
=> Expose get_named_targets and get_named_target_values functions

MIGRATION.md, moveit_ros/robot_interaction/include/moveit/robot_interaction/robot_interaction.h, moveit_ros/robot_interaction/src/robot_interaction.cpp
Removed stuff deprecated already in 2014 (d9285878c71321b3c35853a265c7c55ccfbc4540).
=> cleanup RobotInteraction

moveit_core/planning_scene/src/planning_scene.cpp
There was a bug here where the object gets removed in between `getWorld()->hasObject(id)` and `getWorld()->getObject(id)` which resulted in segfaults. 
This PR fixes the issue by calling `getObject` and then checking if the pointer is empty. 
=> addressing race condition where the object is being removed

moveit_setup_assistant/src/tools/rotated_header_view.cpp, moveit_setup_assistant/src/widgets/navigation_widget.cpp, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.h
- GUI change only. This improves the `NavigationWidget` in the Setup Assistant for dark themes, ~~without changing anything when using a white theme~~.
- Can be cherry-picked but it is not necessary.
- Tested with Kubuntu 18.04.
~~The detection of a dark/white theme is done by comparing the luminance value of the widgets background color.~~ QPalette colors are used so that colors always match.
[after_white](https://user-images.githubusercontent.com/5566160/47720735-e0b02480-dc4e-11e8-8f8c-eb0739396d1c.png)
[after_dark](https://user-images.githubusercontent.com/5566160/47720741-e443ab80-dc4e-11e8-919c-d9d35b293e0f.png)
=> MSA: support dark themes

.docker/ci/Dockerfile
This will speed up the CI build, which doesn't need to install the clang tools anymore.
=> Dockerfile: install clang tools

moveit_kinematics/CMakeLists.txt, moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt, moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp, moveit_kinematics/lma_kinematics_plugin/src/lma_kinematics_plugin.cpp, moveit_kinematics/package.xml, moveit_kinematics/srv_kinematics_plugin/src/srv_kinematics_plugin.cpp
Remove obsolete dependencies in moveit_kinematics and add python-lxml as suggested in https://github.com/ros-planning/moveit/pull/1320#discussion_r250704050. This is a squash-commit candidate ;-)
=> Cleanup dependencies

moveit_core/trajectory_processing/src/iterative_spline_parameterization.cpp
The iterative spline parameterization is missing an update to the robot states of the trajectory after iterating over each point. These leads to lots of warnings of the following kind:
```
[ WARN] [1547043223.679662634, 8.816000000] [/move_group]: Returning dirty collision body transforms
```
This PR adds the missing `update()` call (just one line).
I did not auto-format with clang as this changed lines unrelated to my PR. 
=> Added missing robot state update to iterative spline parameterization

MIGRATION.md, moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h, moveit_core/robot_model/src/joint_model_group.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_kinematics/cached_ik_kinematics_plugin/src/measure_ik_call_cost.cpp, moveit_ros/manipulation/pick_place/src/pick.cpp, moveit_ros/manipulation/pick_place/src/place.cpp, moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp, moveit_ros/planning/kinematics_plugin_loader/include/moveit/kinematics_plugin_loader/kinematics_plugin_loader.h, moveit_ros/planning/kinematics_plugin_loader/src/kinematics_plugin_loader.cpp, moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/robot_interaction/include/moveit/robot_interaction/kinematic_options.h, moveit_ros/robot_interaction/src/kinematic_options.cpp, moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.cpp, moveit_setup_assistant/src/widgets/group_edit_widget.h, moveit_setup_assistant/src/widgets/planning_groups_widget.cpp
As originally pointed out in https://github.com/ros-planning/moveit/pull/725, both `RobotState::setFromIK()` and (all?) actual kinematics solvers in `searchPositionIK()` perform _random seeding_ if IK attempts fail, until the given timeout is reached. In `setFromIK()` the number of attempts was - additionally to the timeout - limited by a max number of attempts.
@v4hn suggested to remove the random sampling from `RobotState` as all important IK solvers (KDL, IKFast, TracIK) perform this random seeding internally anyway, and sometimes (IKFast) they rely on it.
This PR removes the random sampling from `RobotState::setFromIK()` and, simultaneously, removes the notion of max IK attempts from MoveIt. Thus, the number of attempts can only be limited by a timeout or appropriate measures in IK …
=> Remove (redundant) random seeding and #attempts from RobotState::setFromIK

.travis.yml, moveit_core/collision_distance_field/CMakeLists.txt, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_common_distance_field.h, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_world_distance_field.h, moveit_core/collision_distance_field/src/collision_distance_field_types.cpp, moveit_core/collision_distance_field/src/collision_robot_distance_field.cpp, moveit_core/collision_distance_field/src/collision_world_distance_field.cpp, moveit_core/constraint_samplers/test/pr2_arm_kinematics_plugin.h, moveit_core/robot_state/CMakeLists.txt, moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/chainiksolver_vel_mimic_svd.hpp, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/chainiksolver_pos_lma_jl_mimic.h, moveit_kinematics/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin/chainiksolver_vel_pinv_mimic.h, moveit_ros/planning/robot_model_loader/CMakeLists.txt, moveit_setup_assistant/CMakeLists.txt
This PR enables more checkers in Travis using the new features of https://github.com/ros-planning/moveit_ci/pull/45.
- increase Travis timeout (90min - 5min margin)
- update Travis distro to Xenial as suggested by Travis folks
- add catkin_lint (currently failing)
- enable warnings checker (failing on clang)
Fixes for clang warnings will immediately follow.
=> Travis: enable warnings and catkin_lint checker

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_trajectory/src/robot_trajectory.cpp
This addresses a long-standing issue in the trajectory container.
Without this patch, the trajectory's time profile is broken after calling `reverse()`
and robot controllers that respect velocities in specified trajectories,
e.g. default PR2 and TIAGo, will generate execution trajectories with highly oscillating velocity-profile.
This should be cherry-picked to `melodic-devel` of course.
=> invert waypoint velocities on reverse

.clang-tidy, .travis.yml
In https://github.com/ros-planning/moveit/pull/1185 @BryceStevenWilley  introduced some naming conventions, I don't agree with, namely enforcing UPPER_CASE for all constant variables. I think we agreed, that UPPER_CASE is reserved for macros, maybe static const variables as well. However, const members should be lower_case as other variables as well.
This PR also removes the very time-consuming code analysis checks (clang-analyzer-*). They are nice to have locally, but they don't provided automatic fixes and thus are not useful on Travis.
Some remarks on the next steps can be found in https://github.com/ros-planning/moveit/issues/28#issuecomment-451624912.
=> Travis: enable clang-tidy-fix

moveit_core/CMakeLists.txt, moveit_kinematics/cached_ik_kinematics_plugin/CMakeLists.txt, moveit_planners/chomp/chomp_interface/CMakeLists.txt, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/visualization/motion_planning_rviz_plugin/CMakeLists.txt, moveit_ros/visualization/rviz_plugin_render_tools/CMakeLists.txt, moveit_ros/visualization/trajectory_rviz_plugin/CMakeLists.txt
https://github.com/fkie/catkin_lint/issues/62 has been resolved and catkin_lint 1.5.6 has been released.
Thus, we can remove some catkin_lint suppressions again.
=> remove catkin_lint suppressions

moveit_core/robot_model/include/moveit/robot_model/joint_model_group.h, moveit_core/robot_model/src/joint_model_group.cpp, moveit_core/robot_model/src/robot_model.cpp
Due to an early escape from the loop (after the first found eef for a group), MoveIt!
wasn't aware of other eef names (with possibly a different `parent_link`) associated to a group.
=> allow multiple eefs per planning group

moveit_ros/move_group/CMakeLists.txt, moveit_ros/perception/CMakeLists.txt, moveit_ros/planning/CMakeLists.txt, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/current_state_monitor.h
Addresses #1350. boost::signals(1) was used by `tf` < 1.11.3, which is more than 5 years old now.
Also, we migrated to `tf2` already...
=> remove deprecated (and unused) boost::signals

moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/robot_state/test/robot_state_test.cpp
A trivial feature I made a long time ago, with unit tests
=> Graphically print current robot joint states with joint limits

moveit_setup_assistant/package.xml
Address #1371. Re-add some missing build dependencies removed in #1341.
=> MSA: re-add missing build dependencies

moveit_commander/src/moveit_commander/planning_scene_interface.py
Python's PlanningSceneInterface implementation was missing an add_cylinder() method.
Boxes, spheres, etc. were supported, but not cylinders.
=> python PlanningSceneInterface.add_cylinder()

moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp
This is an attempt to fix various chomp issues.
* 1st one is to fix a segfault when the main planner fails. In this case `res.trajectory_` is `NULL`.
Open issues:
* plan + exec behaves differently (fails) than separate plan and execute (when triggered from rviz plugin)
When running plan+exec, the initial RobotState seems to be undefined, while it is defined otherwise.
=> WIP: fix chomp issues

moveit_kinematics/test/test_kinematics_plugin.cpp
Kinematics unittests use random sampling, which might (randomly) cause the tests to fail.
This fix reduces randomness by using a fixed seed to sample robot states.
Additionally, the "searchIKWithCallback" test should resample dismissed samples as pointed out
in https://github.com/ros-planning/moveit_kinematics_tests/pull/16.
=> Reduce spurious unittest failures due to randomness

moveit_core/collision_detection_fcl/CMakeLists.txt, moveit_core/collision_detection_fcl/include/moveit/collision_detection_fcl/collision_detector_fcl_plugin_loader.h, moveit_core/collision_detection_fcl/src/collision_detector_fcl_plugin_loader.cpp, moveit_core/collision_detector_fcl_description.xml, moveit_core/package.xml
I mentioned at the maintainer's meeting that I had once made the FCL collision detector a plugin, as opposed to its currently hardcoded state. This is the simple change to make that happen, and gets us one step closer to being able to easily use different collision detectors, like [Bullet](https://github.com/bulletphysics/bullet3), in MoveIt.
To actually make this affect anything, you have to set the `collision_detector` param of the move group. In the generated `move_group.launch`, you can add 
```
<param name="collision_detector" value="FCL"/>
``` 
right after `jiggle_fraction` to use it. Then the plugin loader loads it [as seen here](
https://github.com/ros-planning/moveit/blob/822a991e0ea4f713fe672e3e337d7f0702bcc224/moveit_ros/planning/collision_plugin_loader/src/collision_plugin_load …
=> Fcl as a Plugin

.travis.yml, moveit_kinematics/cached_ik_kinematics_plugin/include/moveit/cached_ik_kinematics_plugin/detail/GreedyKCenters.h, moveit_kinematics/cached_ik_kinematics_plugin/src/ik_cache.cpp, moveit_kinematics/cached_ik_kinematics_plugin/src/measure_ik_call_cost.cpp, moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast.h, moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_mimic_svd.cpp, moveit_kinematics/test/test_kinematics_plugin.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/multivariate_gaussian.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/detail/projection_evaluators.h, moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h, moveit_planners/ompl/ompl_interface/src/detail/projection_evaluators.cpp, moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp, moveit_ros/manipulation/pick_place/include/moveit/pick_place/manipulation_plan.h, moveit_ros/move_group/include/moveit/move_group/move_group_context.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/filter_job.h, moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/gl_renderer.h, moveit_ros/perception/mesh_filter/src/gl_renderer.cpp, moveit_ros/perception/semantic_world/src/semantic_world.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/robot_interaction/include/moveit/robot_interaction/interaction_handler.h, moveit_ros/warehouse/warehouse/src/import_from_text.cpp
Having the warnings check enabled in Travis and motivated by [warnings on gentoo](https://answers.ros.org/question/317202/moveit-segfaults-due-to-eigen/?answer=317607#post-id-317607), I increased the warning level for the whole build (previously we only used extended warnings for moveit_core) and fixed the corresponding warnings.
=> fix more warnings

moveit_core/trajectory_processing/CMakeLists.txt, moveit_core/trajectory_processing/include/moveit/trajectory_processing/time_optimal_trajectory_generation.h, moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp, moveit_core/trajectory_processing/test/test_time_optimal_trajectory_generation.cpp, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_optimal_parameterization.cpp, moveit_ros/planning/planning_request_adapters_plugin_description.xml
This is an effort to finish PR #809 by @mikeferguson for integrating the [time-optimal trajectory parameterization](https://github.com/tobiaskunz/trajectories) method (published [here](http://www.golems.org/projects/traj.html)).
The branch is retargeted to melodic and I implemented a function for computing acceleration values (the original version doesn't do this).
Left TODOs:
\- Sponsored by Acutronic and PickNik -
=> Add time-optimal trajectory parameterization (continues #809)

MIGRATION.md
Make it clear that future migration notes go in a new section
=> Document release in MIGRATION.md

moveit_core/robot_state/src/robot_state.cpp
As pointed out at [ROS answers](https://answers.ros.org/question/317202/moveit-segfaults-due-to-eigen), the memory alignment of RobotState variables is not sufficient for new AVX support in Eigen, which requires 32- or even 64-byte alignment instead of the default 16-byte alignment.
This PR makes the alignment dependent on the corresponding variable `EIGEN_MAX_ALIGN_BYTES`.
https://eigen.tuxfamily.org/dox/classEigen_1_1aligned__allocator.html
=> Fix alignment of Eigen transforms

moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp, moveit_core/constraint_samplers/test/test_constraint_samplers.cpp, moveit_core/kinematic_constraints/test/test_constraints.cpp, moveit_core/robot_model/test/test.cpp, moveit_core/robot_state/test/test_aabb.cpp, moveit_core/trajectory_processing/test/test_time_parameterization.cpp, moveit_core/utils/include/moveit/utils/robot_model_test_utils.h, moveit_core/utils/src/robot_model_test_utils.cpp
Addresses #1386. 
Fixes the fact robot URDF and SRDF paths were hardcoded to the non-standard PR2 locations. Now uses the PR2 as a non-standard if case, and uses the newer normal locations of URDF in `<robot>_description/urdf/<robot>.urdf` and SRDF in `<robot>_moveit_config/config/<robot>.srdf`.
=> Fixed to handle normal robot urdf paths

moveit_core/robot_model/src/joint_model_group.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp, moveit_planners/chomp/README.md
This is a more computationally efficient version of the previously used isValidVelocityMove() functions added in https://github.com/ros-planning/moveit/pull/294
This allows faster Descartes-type functionality
=> New isValidVelocityMove() for checking time between two waypoints given velocity

MIGRATION.md, moveit_commander/src/moveit_commander/move_group.py, moveit_commander/test/python_moveit_commander.py, moveit_commander/test/python_moveit_commander_ns.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/test/python_move_group.py, moveit_ros/planning_interface/test/python_move_group_ns.py, moveit_ros/planning_interface/test/robot_state_update.py
The `MoveGroupInterface.plan()` was out of line in its behaviour from the C++ class: now it returns a tuple of 4 as such: `(success flag : boolean, trajectory message : RobotTrajectory, planning time : float, error code : MoveitErrorCodes)`. 
Up to now, users of this function could only tell if a `plan()` call was successful by processing the trajectory message (some planners return trajectories regardless of a failed plan!).
It would be nice to add some tests too.
=> moveit_commander.MoveGroupInterface plan() to better align with C++ MoveGroup::plan()

CODEOWNERS
This adds a CODEOWNERS file as described [here](https://help.github.com/en/articles/about-code-owners) which will automatically assign reviewer(s) according to its rules. Each line in this file is a file pattern followed by one or more github usernames, github teamnames, or e-mail addresses affiliated with a github account. These users/teams must have write permission to the repository.
Order is important; the user(s) in the last matching pattern in CODEOWNERS for a file will be that file's owner(s). For each file in a PR, its owner(s) will be added as reviewers.
This CODEOWNERS file was generated by assigning files under a package.xml to the maintainer e-mails listed in that package.xml. The default owners for files not matching any pattern is the maintainer e-mail list in moveit_core's …
=> Add CODEOWNERS file for automatic reviewer assignment

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
As pointed out in #845, the signature and semantics of `getJointValueTarget()` doesn't match the one of the corresponding setter, which renders both functions rather useless. As I pointed out in https://github.com/ros-planning/moveit/pull/845#issuecomment-382644155 a proper solution of this issue, should consider: 
- Add a new method `MoveGroupInterface::getJointValueTarget(std::vector<double>&)` that matches the corresponding `setJointValueTarget(const std::vector<double>&)` method and should use `RobotState::copyJointGroupPositions(const JointModelGroup*, std::vector<double>&)` to do so.
- Depreacate the old method `MoveGroupInterface::getJointValueTarget()`
(currently returning the full `RobotState`) and 
- Instead add a better-named method `MoveGroupInterface::getJointStateTarget()` …
=> improve [get|set]JointValueTarget in python wrapper

moveit_planners/chomp/chomp_interface/src/chomp_planning_context.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_planner.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
Tracking down a `Found empty JointState message` from the chomp planner, I stumbled over some smaller issues. This PR
- introduces a (slightly) more verbose variable name to distinguish a MotionPlanResponse (res) from its message counterpart
- removes explicit time parameterization from the chomp planner (time parameterization is configured in the planning pipeline)
- adds a TODO to switch the API of `ChompPlanner::solve` to use real planning_interface datatypes (instead of their moveit_msgs counterparts). This will save some unnecessary serializations. As far as I can see, both usages in chomp_optimizer_adapter and chomp_interface, actually use native types originally. @bmagyar, what do you think of this idea?
Fixing this, will finally resolve the error message, as this one comes from …
=> small fixes to chomp planner

moveit_core/CMakeLists.txt, moveit_core/collision_distance_field/test/test_collision_distance_field.cpp, moveit_core/package.xml, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_core/utils/CMakeLists.txt, moveit_core/utils/src/robot_model_test_utils.cpp, moveit_planners/ompl/ompl_interface/test/test_state_space.cpp, moveit_setup_assistant/test/moveit_config_data_test.cpp
This fixes an issue with the test utils where it was only getting built during testing and wasn't being exported as a library. 
This enables https://github.com/ros-planning/moveit_tutorials/pull/295 to build and run as expected
=> fixing the test utilities in moveit core

.github/CODEOWNERS
The goal of CODEOWNERS is to spread the review workload more evenly across maintainers and make it clearer who should do the review. However, after just one day of being deployed @rhaschke created a small [pull request](https://github.com/ros-planning/moveit/pull/1406) that then auto-tagged 4 reviewers. This is opposite of our intention. Upon further investigation, I believe this feature will best work if 1, or max 2 people are assigned to each CODEOWNER rule. 
To achieve this, I've split up two of our large packages into its subcomponent folders (moveit_core and moveit_ros_planning) and attempted to spread out reviewers between those. 
If you feel like other people should also review your code, you can always request additional reviewers manually. This feature is only to ensure that …
=> CODEOWNERS: Split up moveit_core and moveit_ros_planning into subfolders

moveit_core/planning_scene/src/planning_scene.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp
Due to a typo, I was trying to create a CollisionObject with an undefined frame_id. Interestingly, MoveIt just silently ignored this message on the `/collision_object` topic.
After a while of debugging, it turned out that the PlanningSceneMonitor employs a MessageFilter, which caches messages if the pose cannot be transformed into the planning frame.
But, as the (1024-elem) cache is never cleared (except if new messages arrive, which is not so often for CollisionObject messages), objects with invalid frames were silently ignored.
This PR removes the MessageFilter and adds a corresponding error message in `PlanningScene::processCollisionObjectAdd`.
This will have the side effect, that TF messages arriving after the CollisionObject message will not be considered anymore for resolving.
=> remove MessageFilter for /collision_object messages

moveit_core/collision_distance_field/test/test_collision_distance_field.cpp, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_core/robot_model/test/test.cpp, moveit_core/robot_state/test/robot_state_benchmark.cpp, moveit_core/robot_state/test/robot_state_test.cpp, moveit_core/robot_state/test/test_aabb.cpp, moveit_core/robot_state/test/test_kinematic_complex.cpp, moveit_core/utils/include/moveit/utils/robot_model_test_utils.h, moveit_planners/ompl/ompl_interface/test/test_state_space.cpp, moveit_setup_assistant/test/moveit_config_data_test.cpp
This fixes #1409, which lifted libmoveit_test_utils to the default build. To this end, @mlautman removed the need to access `MOVEIT_TEST_RESOURCES_DIR` from moveit_resources/config.h, but he missed to remove the include from all sources, causing this issue: https://github.com/ros-planning/moveit_robots/issues/74#issuecomment-475852651.
=> fix #1409: remove obsolete moveit_resources/config.h

moveit_commander/src/moveit_commander/planning_scene_interface.py
This augments #789.
* `CollisionObject` in `remove_world_object` requires `__submit()` with `attach=False`
* Use new `__submit()` API for `add_cylinder()` as well. This was missing due to two parallel PRs
=> cleanup python PlanningSceneInterface

moveit.rosinstall
The tutorials are broken in local build because lack of master branch from source install.
=> Update rosinstall for master branches

moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp
Fixes #1119.
As proposed in #1119 I implemented quaternion normalization when adding a new collision object and also when providing a new pose (move operation). Instead of using `tf2::fromMsg` as before I wrote a new function which includes orientation normalization and replaced it in the appropriate spots.
=> Normalize quaternions when adding new or moving collision objects (#1119)

moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp
- initialize values of RobotState in computeRelativeTransform()
- add tolerance for comparison to identity
see #1448
=> Fix IKFastPlugin initialization. Fixes #1448

moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection/src/world.cpp, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/robot_state.cpp
This makes some parameters in the robot state and collision world clearer, as requested by @mlautman in #1060, in a separate PR as requested by @rhaschke in #1439. This PR changes nothing except the internal names.
Can be cherry-picked to kinetic and melodic.
=> Clarify "id" parameter in RobotState & collision world

moveit_core/planning_scene/src/planning_scene.cpp
Detaching an attached collision object can cause segfaults in melodic. 
The segfault was found running Melodic on 18.04 
In this method, `attached_body` is a raw pointer to an `AttachedBody` in `robot_state_`. 
The planning scene saves the `attached_body`'s `shapes_` vector with `const std::vector<shapes::ShapeConstPtr>& shapes = attached_body->getShapes();`. However, when `robot_state_->clearAttachedBody(name)` is called, it deletes the `AttachedBody` causing the underlying `ShapeConstPtr`s to be freed. Then when `world_->addToObject(name, shapes, poses)` is called, it segfaults as the data in the `shapes_` vector is no longer available. 
By moving `world_->addToObject(name, shapes, poses)` before`robot_state_->clearAttachedBody(name)`, we create another shared pointer to the same …
=> Detaching attached collision object bugfix

moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
* Retained current hard-coded 5 second limit
* Used double to conform to python accessible API instead of `ros::WallDuration(int, int)`
* API is extended, remains conformant to previous releases
Would be nice if this was applied to Kinetic, Lunar and Melodic (all distros maintained next month)
=> [Python wrapper] Added custom time limit for wait_for_servers in MoveGroupInterface

moveit_commander/src/moveit_commander/move_group.py
d649771a65 introduced the wrong exception to handle in go(), causing some tutorials to fail: https://github.com/ros-planning/moveit_tutorials/issues/301. This PR catches the correct exception (TypeError).
=> fix moveit_commander

moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp
Fixes https://github.com/ros-planning/moveit/issues/1048. When I had [this problem](https://answers.ros.org/question/299979/moveit-plan-fails-after-attaching-an-object-but-not-from-rviz-or-after-restarting-requesting-node/), I would have appreciated a more helpful error message. @v4hn requested a PR, so I made this.
The summary of the ROS answers post is that I forgot to call `clearPoseTargets` after changing the end effector link of the `move_group`, so that constraints were active on multiple links of the robot. I added an error message that displays if planning fails and multiple constraints are set.
You can test that the message fires correctly by adding the lines below in [this part](https://github.com/ros-planning/moveit_tutorials/blob/master/doc/move_group_interface/src/move_group_i …
=> Add user warning to planning pipeline when multiple constraints are set and planning fails

.docker/ci/Dockerfile, .docker/experimental/Dockerfile, .docker/source/Dockerfile
To enable https://github.com/ros-planning/moveit_ci/pull/62, define `ROS_UNDERLAY` in the source container. The `CATKIN_WS` environment variable is not used anymore by `moveit_ci` and is thus removed.
=> docker: remove CATKIN_WS, define ROS_UNDERLAY

moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp
Removes the check as requested by @rhaschke in #1443 which was merged too early.
=> Make warning display check more sensible

moveit_core/planning_scene/src/planning_scene.cpp
There was a bug in moveit_visual_tools where adding a collision object after initializing the planning scene resulting in the following error: `robot_state.cpp:998: const Isometry3d& moveit::core::RobotState::getFrameTransform(const string&) const: Assertion `checkLinkTransforms()' failed.`
This error is caused by the robot state in the planning scene holding dirty link transforms after initialization. 
This PR fixes the underlying issue
=> update robot state transforms when initializing a planning scene

moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp
follow_joint_trajectory_controller_handle: add missing space in warning
=> TYPO: missing space

moveit_planners/chomp/chomp_interface/include/chomp_interface/chomp_planning_context.h, moveit_planners/chomp/chomp_interface/src/chomp_planning_context.cpp, moveit_planners/chomp/chomp_interface/test/chomp_moveit_test.cpp, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_planner.h, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_trajectory.h, moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_utils.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_planner.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp, moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp
This PR comprises several independent commits to improve the Chomp code, namely
- some code cleanup, reducing redundancy and explicit loops
- fix start state handling: 
- An empty start state should be accepted. In this case, the current state should be used. Fixes #1452
- Checking start state constraints was plain wrong, resulting in #1470.
- Avoid extra conversion from/to MotionPlanResponse _message_
=> Fix several Chomp issues

moveit_core/collision_detection/include/moveit/collision_detection/world.h, moveit_core/collision_detection/src/world.cpp, moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/utils.h, moveit_core/kinematic_constraints/src/utils.cpp, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/robot_model/include/moveit/robot_model/robot_model.h, moveit_core/robot_model/src/robot_model.cpp, moveit_core/robot_state/include/moveit/robot_state/attached_body.h, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_state/src/attached_body.cpp, moveit_core/robot_state/src/conversions.cpp, moveit_core/robot_state/src/robot_state.cpp, moveit_ros/planning/planning_request_adapter_plugins/CMakeLists.txt, moveit_ros/planning/planning_request_adapter_plugins/src/resolve_constraint_frames.cpp, moveit_ros/planning/planning_request_adapters_plugin_description.xml, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/visualization/motion_planning_rviz_plugin/src/motion_planning_frame_objects.cpp, moveit_setup_assistant/templates/moveit_config_pkg_template/launch/ompl_planning_pipeline.launch.xml
This PR supercedes #1060 and implements #1041. It includes all the changes requested in the last thread and now targets the correct branch. It requires [this PR](https://github.com/ros-planning/moveit_msgs/pull/50) to `moveit_msgs`.
In short, this PR adds subframes to CollisionObjects so that one can write "move the tip of object A to somewhere on object B". In the animation below, the cylinder tip is moved to each side of the box in this manner:
I made a test package [here](https://github.com/felixvd/moveit_tutorials/tree/add-named-frames), which you can run with `rosrun moveit_tutorials subframes_tutorial`. You can reproduce the animation above by entering the numbers 2, 3, 4, 5.
**Small changelog:**  
I added a version of `getFrameTransform` to `robot_state.cpp` which combines the …
=> Add named frames to CollisionObjects (v2)

moveit.rosinstall
We added these back when there were a lot of big changes happening in those repos, but I don't think we need them anymore. Or at least, for now.
This should speed up Travis builds.
=> Reduce scope of moveit.rosinstall

moveit_kinematics/ikfast_kinematics_plugin/scripts/auto_create_ikfast_moveit_plugin.sh
Due to new [ROS GPG keys](https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454), the IKFast generator tool [fails in Travis](https://travis-ci.org/ros-planning/moveit/jobs/543158027). Hence, we need to update the keys used in the corresponding docker image as well.
Needs to be back-ported to Melodic.
=> ikfast: fix ROS apt-key in OpenRAVE docker image

.docker/ci/Dockerfile, .docker/source/Dockerfile
Because [ROS Indigo has reached EOL in April 2019](http://wiki.ros.org/Distributions), `rosdep update` doesn't pull any package information for Indigo anymore and our [docker images fail to build](https://cloud.docker.com/u/moveit/repository/docker/moveit/moveit/builds).
To fix this, I added the option `--include-eol-distros` to these calls.
Alternatively, we should disable and remove Indigo docker images. However, I think there might be still many people using these Indigo branches.
=> docker: rosdep update --include-eol-distros

.travis.yml
- Couple clang-tidy-fix to clang-based build to avoid spurious warnings
- Require clang-tidy-fix to pass
=> Improve Travis config for clang-tidy-fix

moveit_commander/src/moveit_commander/move_group.py, moveit_commander/test/python_moveit_commander.py, moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/package.xml, moveit_ros/planning_interface/test/python_move_group.py
This is a cherry-pick of #1501 from Kinetic. If Travis passes, melodic-devel can be fast-forwarded.
=> Add get_jacobian_matrix to moveit_commander (#1501)

moveit_ros/move_group/src/default_capabilities/apply_planning_scene_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/execute_trajectory_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/get_planning_scene_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/query_planners_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/state_validation_service_capability.cpp
- use namespace definition to reduce verboseness of individual method signatures
- use capability name for ROS console messages
=> Cleanup move_group capabilities

moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_mimic_svd.cpp, moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp
This PR fixes an issue introduced in 5bedb7a31db8ab4ac7e474de762e5dfc42ad4d13:
- correctly count mimic joints
- don't resize extra_joint_weights vector
This fixes https://github.com/seed-solutions/aero-ros-pkg/issues/400.
=> KDL IK solver: fix handling of mimic joints

moveit_kinematics/kdl_kinematics_plugin/src/chainiksolver_vel_mimic_svd.cpp, moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp
Backport of #1490 .
The code that originally introduced the problem was merged in melodic-devel.
- correctly count mimic joints
- don't resize extra_joint_weights vector
Fixes an issue introduced in 5bedb7a31db8ab4ac7e474de762e5dfc42ad4d13.
=> KDL IK solver: fix handling of mimic joints (#1490)

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/demo.cpp, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Add functions to set fields in the pick and place goals, namely `place_eef` and `allow_gripper_support_collision`. Also some minor formatting changes by clang-format.
See also issue #631
=> Add functions to set pick and place goal fields

moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp
These changes were created by replacing `"moveit::planning_interface::"` with `""`
and clang-formatting everything.
=> Remove redundant namespaces in move_group_interface.cpp

moveit_setup_assistant/src/widgets/configuration_files_widget.cpp
The static_transform_publisher node in tf2_ros does not take a rate. The 10th argument was being treated as the child link.
https://github.com/ros/geometry2/blob/c4a64e0c6ea8fb0a8b0c6a032e509ebc449b0519/tf2_ros/src/static_transform_broadcaster_program.cpp#L75
=> static transform publisher does not take a rate

moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_trajectory.h, moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp, moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp
Looks like #1473 introduced a new chomp issue: Initializing the chomp trajectory from an OMPL trajectory (when used as an adapter), was using the wrong function to access joint positions.
This fixes https://github.com/ros-planning/moveit/issues/1452#issuecomment-504662578.
Additionally, the new trajectory is interpolated to yield smooth results also when the initialized solution is returned.
=> Fix chomp adapter

moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h, moveit_planners/chomp/chomp_optimizer_adapter/src/chomp_optimizer_adapter.cpp, moveit_ros/planning/planning_pipeline/src/planning_pipeline.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_iterative_spline_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_optimal_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/empty.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_bounds.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_collision.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/fix_start_state_path_constraints.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/fix_workspace_bounds.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/resolve_constraint_frames.cpp
This PR adds support for running multiple planning pipelines with different configurations at the same time. The planning including planning request adapters from separate namespaces. While the configuration of the planner plugin can already be scoped by passing a child namespace to the planning pipeline, the parameters of the planning request adapters are always queried from the private node handle from within the constructor. The parameter lookup is now moved to a new virtual `initialize()` function (empty by default) which expects the node handle to use. The planning pipeline calls this function on all constructed planning request adapters.
=> Allow ROS namespaces for planning request adapters: pass a NodeHandle for their initialization

moveit_core/utils/CMakeLists.txt
The library internally creates RobotModel objects
and thus should link the constructor.
---
I just tried to build a fresh current master workspace on Lunar-Linux with clang++ and hit this error:
```
Errors     << moveit_ros_planning:make ros/melodic/moveit/logs/moveit_ros_planning/build.make.001.log
/usr/bin/ld: ros/melodic/moveit/install/lib/libmoveit_test_utils.so: undefined reference to `moveit::core::RobotModel::RobotModel(std::shared_ptr<urdf::ModelInterface> const&, std::shared_ptr<srdf::Model const> const&)'
/usr/bin/ld: ros/melodic/moveit/install/lib/libmoveit_test_utils.so: undefined reference to `moveit::core::RobotModel::~RobotModel()'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** …
```
=> link moveit_robot_model from moveit_test_utils

moveit_commander/src/moveit_commander/move_group.py, moveit_commander/test/CMakeLists.txt, moveit_commander/test/python_time_parameterization.py, moveit_commander/test/python_time_parameterization.test, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Enable to select Time Parametrization Algorithm via `algorithm` argument in `retime_trajectory` method of Python MoveGroupCommander.
Ref: Time Parametrization Algorithms:
http://docs.ros.org/melodic/api/moveit_tutorials/html/doc/time_parameterization/time_parameterization_tutorial.html#time-parameterization-algorithms
Example use case:
https://github.com/mmurooka/moveit_tutorials/blob/time-parametrization-tutorial-master/demo_rs007n/scripts/demo_adept_motion_rs007n.py#L93-L102
（This PR contains https://github.com/ros-planning/moveit/pull/1506 .）
=> Select time parametrization algorithm in retime_trajectory

moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h, moveit_ros/planning/plan_execution/src/plan_execution.cpp
Fixes memory leak reported in #1526. Alternative to #1528, which removed TrajectoryMonitor completely.
@jschleicher, could you please validate again?
=> PlanExecution: Return executed trajectory

moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h, moveit_ros/planning/plan_execution/src/plan_execution.cpp
This backports #1538 to fix the associated memory leak.
Do we want to backport the re-enabled feature to send tracked trajectories in Result messages also to kinetic-devel? Alternatively, we could [disable recording](https://github.com/ros-planning/moveit/pull/1528) there to avoid potential performance losses.
=> backport #1538 trajectory recording / memory leak

.docker/gui-docker
This is a replacement for #1495, updating the gui-docker script to work with [`nvidia-docker 2`](https://github.com/NVIDIA/nvidia-docker/wiki) as well. Both versions, 1 and 2, of nvidia-docker are supported now.
I also added support for DRI-based cards.
=> gui-docker: Update to nvidia-docker version 2

moveit_ros/planning/planning_request_adapter_plugins/src/add_iterative_spline_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_optimal_parameterization.cpp, moveit_ros/planning/planning_request_adapter_plugins/src/add_time_parameterization.cpp
We switched to a new time parameterization and noticed that it sometimes failed on our input -- but instead of returning that planning failed, planning succeeded and the resulting trajectory had all times set to 0. This PR makes the time parameterization plugins adjust the return boolean appropriately.
- [ y ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
=> Return failed planning result if time parameterization fails

moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/configuration_files_widget.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
On Windows, `boost::filesystem::path::native()` will return `std::wstring` while the code expects `std::string`, thus I replaced the `native()` usage with `string()` to accommodate it.
=> [Windows][melodic-devel] Use boost::filesystem::path::string() to return std::string.

moveit_ros/benchmarks/include/moveit/benchmarks/BenchmarkExecutor.h, moveit_ros/benchmarks/scripts/moveit_benchmark_statistics.py, moveit_ros/benchmarks/src/BenchmarkExecutor.cpp
I'm working on extending the benchmark interface and measurement functions with the following goals/items:
**Simplify setting up a benchmark without warehouse (f20c07e)**
With the current implementation this would require overriding the function `initializeBenchmarks()`.
I added another virtual function `loadBenchmarkQueryData()` that allows initializing the planning scene and constraints only without the need to create the BenchmarkRequests as well.
**Compare results across experiments (8ae9a25, 11ad204)**
Currently the results are stored in separate log files which can be written to a database file storing the result of a single experiment. I extended the python script to accept multiple log files and to write all benchmarks into the same file. Also I added a pseudo experiment …
=> MoveIt benchmark improvements

moveit_experimental/jog_arm/include/jog_arm/jog_calcs.h, moveit_experimental/jog_arm/src/jog_arm/jog_calcs.cpp
Remove dependence on move_group action server by getting the joint model names through joint_model_group_ instead.
closes #1563
Uses joint_model_group_ instead of MoveGroupInterface to get joint names
=> Get joint model names from joint_model_group_

moveit_experimental/jog_arm/include/jog_arm/low_pass_filter.h, moveit_experimental/jog_arm/src/jog_arm/low_pass_filter.cpp
Fixes Issue #1471 about filter overshooting by changing the 2nd order Butterworth low pass filter to 1st order.
=> Change 2nd order Butterworth low pass filter to 1st order

moveit_experimental/jog_arm/config/sia5_simulated_config.yaml, moveit_experimental/jog_arm/include/jog_arm/jog_arm_data.h, moveit_experimental/jog_arm/include/jog_arm/jog_calcs.h, moveit_experimental/jog_arm/src/jog_arm/jog_calcs.cpp, moveit_experimental/jog_arm/src/jog_arm/jog_ros_interface.cpp
A suddenHalt() function for critical issues like joint limits. Otherwise, decelerations are low-pass filtered.
=> Sudden stop for critical issues, filtered deceleration otherwise

moveit_ros/benchmarks/README.md, moveit_ros/benchmarks/examples/demo1.yaml, moveit_ros/benchmarks/examples/demo2.yaml, moveit_ros/benchmarks/examples/demo_fanuc.launch, moveit_ros/benchmarks/examples/demo_obstacles.yaml, moveit_ros/benchmarks/examples/demo_panda.launch, moveit_ros/benchmarks/examples/demo_panda_all_planners.launch, moveit_ros/benchmarks/examples/demo_panda_all_planners.yaml, moveit_ros/benchmarks/examples/demo_panda_all_planners_obstacles.launch, moveit_ros/benchmarks/include/moveit/benchmarks/BenchmarkExecutor.h, moveit_ros/benchmarks/include/moveit/benchmarks/BenchmarkOptions.h, moveit_ros/benchmarks/src/BenchmarkExecutor.cpp, moveit_ros/benchmarks/src/BenchmarkOptions.cpp, moveit_ros/benchmarks/src/RunBenchmark.cpp
Based on #1510 and #1530 this adds support for running benchmarks on full planning pipelines.
This only requires minor changes in the configuration, in particular specifying pipeline namespaces in the launch files and using this names instead of plugin identifiers inside the yaml files.
If approved, I will add appropriate changes for the tutorial.
Please review the last commit bc689be only. All other changes are included from #1510.
=> Benchmark planning pipelines instead of plugins only

moveit.rosinstall
I'm hoping we [make some changes to moveit_msgs](https://github.com/ros-planning/moveit_msgs/pull/46) soon, so I've just switched that repo to use a master branch instead.
=> Switch moveit_msgs to new 'master' branch

moveit_ros/planning/plan_execution/cfg/PlanExecutionDynamicReconfigure.cfg, moveit_ros/planning/plan_execution/src/plan_execution.cpp, moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/trajectory_monitor.h, moveit_ros/planning/planning_scene_monitor/src/trajectory_monitor.cpp
Implements https://github.com/ros-planning/moveit/pull/1538#issuecomment-508770275.
@v4hn, should we disable the monitoring by default in `PlanExecution`?
=> TrajectoryMonitor: zero sampling frequency disables recording

moveit_ros/planning_interface/planning_scene_interface/src/planning_scene_interface.cpp
Turns out, the `PlanningSceneInterface` never waited for its services to be available.
However, all but two functions of the class utilize this class (and fail if the service is not setup yet).
As the original goal of the `apply*` function family was to get rid of random `sleep` statements in the code base, I consider it important that there is no need to wait when using the class methods.
=> psi: wait for services

moveit_setup_assistant/include/moveit/setup_assistant/tools/moveit_config_data.h, moveit_setup_assistant/src/tools/moveit_config_data.cpp, moveit_setup_assistant/src/widgets/controller_edit_widget.cpp
This PR improves the controllers screen by hiding not useful controller options, and renaming `moveit_sim_controllers` to more appropriate names.
=> Add joint state controller config by default

moveit_ros/occupancy_map_monitor/src/occupancy_map_monitor.cpp
Trigger the octomap update when loaded through /move_group/load_map service
=> Update occupancy grid when loaded from file

moveit/CMakeLists.txt, moveit_planners/moveit_planners/CMakeLists.txt, moveit_plugins/moveit_plugins/CMakeLists.txt, moveit_ros/moveit_ros/CMakeLists.txt, moveit_runtime/CMakeLists.txt
Fixes https://github.com/ros-planning/moveit/issues/1619 
catkin_make requires very specific text in the metapackage cmakelists files. We broke that by upping the required cmake version. This just reverts that change.
=> Use standard cmake text for metapackages

moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
Use QDir::currentPath() rather than getenv("PWD")
Please see issue #1497 
=> Use QDir::currentPath() rather than getenv("PWD")

moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h, moveit_core/robot_state/src/robot_state.cpp, moveit_core/utils/src/robot_model_test_utils.cpp, moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp, moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
This change is to replace the `gcc` extension and alternative operator usage.
* Replace alternative operator with [`primary tokens`](https://en.cppreference.com/w/cpp/language/operator_alternative).
* Replace `variable length array` with `std::vector`.
* Don't do `abi::__cxa_demangle` when it is using `MSVC` toolchain.
=> [Windows][master] remove GCC extension and alternative operator usage.

moveit_setup_assistant/src/tools/moveit_config_data.cpp
Signed-off-by: Daniel Wang <daniel.wang@canonical.com>
this pull request address https://github.com/ros-planning/moveit/issues/1578 to avoid `iterator controller_it` point to random elements
=> fix the invalid iterator issue

moveit_commander/src/moveit_commander/move_group.py, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp, moveit_ros/planning_interface/test/python_move_group.py
I needed to expose the `reference_point_position` parameter of the `getJacobian` function in Python, so I added it as an optional parameter. Tested on a UR5, worked as expected.
Can be cherry-picked to kinetic and melodic just like #1501, where the `get_jacobian_matrix` was added that this PR modifies.
=> Add parameter to get_jacobian_matrix

moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp, moveit_ros/visualization/rviz_plugin_render_tools/include/moveit/rviz_plugin_render_tools/robot_state_visualization.h
This PR is related to [PR#56](https://github.com/ros-planning/moveit_visual_tools/pull/56)
So after updating the DisplayRobotState msg to include a new field [see](https://github.com/ros-planning/moveit_msgs/pull/55), and updating [MoveItVisualTools::hideRobot()](https://github.com/ros-planning/moveit_visual_tools/blob/master/src/moveit_visual_tools.cpp#L1528) to toggle the .hide rather than using a virtual_joint that moves the robot very far away location in Rviz; there's a need to add the feature in the Rviz Display,
I think that one solution could be by updating the robot visibility `robot_->setVisualVisible(!state_msg->hide)` inside [RobotStateDisplay::newRobotStateCallback](https://github.com/ros-planning/moveit/blob/2505cf4e4783386fc828553d60cd6f78accda4bb/moveit_ros/visualization/ro …
=> Update newRobotStateCallback to use the new the DisplayRobotState msg

moveit_commander/src/moveit_commander/planning_scene_interface.py
Moveit commander python planning_scene_interface crashed when we remove attached object, this was caused by the request function. Request was adding AttachedObjectCollision to the world collision object instead of robot state collision object.
=> (fix) moveit_commander python planning_scene_interface for attached obj

moveit_core/planning_request_adapter/include/moveit/planning_request_adapter/planning_request_adapter.h
The method was introduced in #1530, together with [a TODO](https://github.com/ros-planning/moveit/pull/1530/files#diff-9247374d69dc34d55ae1a420105cd85dR68) to make it pure virtual "in O-turtle".
[A Windows-compatibility pr](https://github.com/ros-planning/moveit/pull/1583#discussion_r308193285) noticed that the current functionality is not available in Windows, as it uses `cxxabi.h`.
I would propose to either go for the pure virtual method directly or just implement an empty default implementation (apparently this was dismissed in #1530).
=> pure virtual `planning_request_adapter::initialize()`

moveit_core/kinematic_constraints/include/moveit/kinematic_constraints/utils.h, moveit_core/kinematic_constraints/src/utils.cpp, moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/planning_scene/src/planning_scene.cpp, moveit_core/planning_scene/test/test_planning_scene.cpp, moveit_core/utils/CMakeLists.txt, moveit_core/utils/include/moveit/utils/message_checks.h, moveit_core/utils/src/message_checks.cpp, moveit_planners/ompl/ompl_interface/src/generate_state_database.cpp, moveit_ros/manipulation/pick_place/src/pick.cpp, moveit_ros/manipulation/pick_place/src/place.cpp, moveit_ros/move_group/src/default_capabilities/cartesian_path_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp, moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp, moveit_ros/move_group/src/default_capabilities/state_validation_service_capability.cpp, moveit_ros/planning/plan_execution/src/plan_execution.cpp, moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp, moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp
Builds on top of #1625 (although it could be isolated) and only consists of one commit.
I will rebase here once #1625 is merged.
[As pointed out by @davetcoleman](https://github.com/ros-planning/moveit/pull/1625#issuecomment-521980815) it seems weird to keep simple test functions like `isEmpty` within the full `PlanningScene` class.
This patch proposes to collect them in a new header in `moveit/utils/message_checks.h`.
Please review.
=> moveit::core::isEmpty

moveit_ros/planning/planning_components_tools/src/display_random_state.cpp, moveit_ros/planning/planning_components_tools/src/publish_scene_from_text.cpp, moveit_ros/planning/planning_scene_monitor/demos/demo_scene.cpp, moveit_ros/planning_interface/move_group_interface/src/demo.cpp, moveit_setup_assistant/src/widgets/start_screen_widget.cpp
In some code paths, it uses `POSIX` [`sleep`](http://pubs.opengroup.org/onlinepubs/009695399/functions/sleep.html). However, for `non-POSIX` systems, the `sleep` may not exist. This change is to use the abstract `ros::Duration::sleep` for portability.
=> [windows][master] Use ros::Duration::sleep for portability.

moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_env_distance_field.h, moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_env_hybrid.h, moveit_core/collision_distance_field/src/collision_env_distance_field.cpp, moveit_core/collision_distance_field/src/collision_env_hybrid.cpp
Travis fails due to `performance-unnecessary-value-param` which has been introduced through the new unified environment in #1584. This fixes the issue.
=> Fix clang-tidy for unified collision environment

MIGRATION.md
The migration notes for the unified collision environment were not up-to-date.
=> Changed migration notes for new unified collision environment

moveit_commander/bin/moveit_commander_cmdline.py
For Python, `readline` is not available on Windows. This change is to fallback using [`pyreadline`](https://pypi.org/project/pyreadline/) instead.
=> [windows][master] Fallback readline usage to pyreadline for Windows.

moveit_commander/src/moveit_commander/interpreter.py
After this [PR](https://github.com/ros-planning/moveit/pull/790) the MoveGroupCommander.plan() now returns [success, trajectory, planning_time, error_code] which leads to a run-time error when executing this [line](https://github.com/ros-planning/moveit/blob/master/moveit_commander/src/moveit_commander/interpreter.py#L349)
=> Handle the updated plan() function of MoveGroupCommander

moveit_experimental/jog_arm/include/jog_arm/jog_arm_data.h, moveit_experimental/jog_arm/include/jog_arm/jog_calcs.h, moveit_experimental/jog_arm/src/jog_arm/jog_calcs.cpp, moveit_experimental/jog_arm/src/jog_arm/jog_ros_interface.cpp, moveit_experimental/jog_arm/test/arm_setup/config/jog_settings.yaml
- Only wait for the message we try to smooth with the low-pass filter (JointState). This also allows the initial jog command to be of the JointJog type.
- Do not assume the command to be cartesian when the zero_joint_cmd_flag is set, could be a JointJog command with zero velocity
- valid_nonzero_command flag is set when either zero_cartesian_cmd_flag **or** zero_joint_cmd_flag is not set
- Remove unused publish_delay parameter
=> Do not wait for command msg to start spinning in jog_arm

moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp
The step width of debug images was copied from the input depth image, but the encoding might be different resulting in a wrong step width. With this PR the step width is calculated correctly.
=> depth_image_octomap_updater: correctly set properties of debug images

moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h
Fix #1650. The potential is a piecewise function as follows:
To have a smooth transition at zero, we need
```c++
double gradient_magnitude = diff / clearance;
```
as was stated in the comment.
=> chomp: fix potential calculation

MIGRATION.md
One extra sentence for the migration notes added which states the fact that collision checks don't take a `CollisionRobot` as an argument anymore as it is implicitly contained in the new collision environment.
=> Migration notes for unified collision environment

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
The double unlock caused spurious errors. This PR should be cherry-picked to melodic.
=> Fix double mutex unlock in JogArm

moveit.rosinstall
The Melodic version of moveit.rosinstall should build the melodic-devel branch of MoveIt.
This fixes an issue introduced in #1369, which was [breaking docker source images recently](https://cloud.docker.com/u/moveit/repository/registry-1.docker.io/moveit/moveit/builds/0c5108f0-7cbc-4dbd-acba-26284211ef4e).
=> Fix moveit.rosinstall

moveit_ros/perception/mesh_filter/src/gl_renderer.cpp, moveit_ros/perception/mesh_filter/src/mesh_filter_base.cpp
Currently, the pixel transfer function is set accordingly to the encoding of the input sensor data in the filtering step. This seems to be correct for rendering the sensor data only, but causes errors when rendering the robot model and when visualizing the filtered data and robot model as depth images.
This PR resets the pixel transfer function after sensor data has been rendered.
This also partially fixes #1109 and #374 for me (using Mesa OpenGL). Some tests still fail because of numerical inaccuracies.
As the mesh filter does depth calculations distributed over multiple places and, hence, is hard to debug, a review of this patch by someone who is more familiar with the mesh filter would be highly appreciated.
Examples:
Visualization of depth images without the PR (white: input depth …
=> depth_image_octomap_updater: reset depth transfer function to standard values

.docker/README.md, .docker/gui-docker
While updating the Docker documentation ([this PR](https://github.com/ros-planning/moveit.ros.org/pull/282)) to include the changes from #1532, I noticed that that page should be referenced and made some minor changes that I believe are helpful when using this script.
The change from `default_container` to `default_moveit_container` is already part of the other PR, so it would be good if at least that bit was included. The name change is for clarity when listing containers via `docker ps -a`.
=> Add docker documentation

moveit_ros/visualization/rviz_plugin_render_tools/src/trajectory_visualization.cpp
When using the REALTIME mode to display the planned path the program would stop at the last or second to last waypoint and is unable to re-play the trajectory when using the trajectory slider plugin.
This pull request fixes the REALTIME playback mode to always finish playing the full trajectory and has the ability to properly pause and continue playback using the trajectory slider plugin.
Please let me know if you would like me to add any tests, features or changes.
Thanks,
-Marq
=> fixed REALTIME planned path trajectory playback

moveit_ros/planning/planning_scene_monitor/src/current_state_monitor.cpp
I've run into some issues where velocities are not being reset as published by the joint states topic only because subsequent positions where equal. In practice, this probably only affects simulation environments but still I think this is undesired behavior and should be fixed.
=> Always copy dynamics if enabled in CurrentStateMonitor

CODE_OF_CONDUCT.md
- Customize naming of people involved with the MoveIt project specifically. We don't really call anyone founders or mentors, rather just maintainers and contributors. This is a concept from a different community.
- Clarify that this CoC is based on Djangos, which is a fairly modified version of Speak Ups, and theirs is a fairly modified version of Fedora and Python's. So we should have a full chain of references.
follow up of https://github.com/ros-planning/moveit/pull/1684
=> Code of conduct tweaks

moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp, moveit_setup_assistant/CMakeLists.txt, moveit_setup_assistant/package.xml, moveit_setup_assistant/src/tools/moveit_config_data.cpp
This builds on @henningkayser's PR #1629. Due to changes in OMPL, only that first commit of that other PR is now necessary. This PR requires OMPL to be built from source at the moment. I am planning to release a new version of OMPL soon, though. 
This PR allows you configure AnytimePathShortening like so in your ompl_planning.yaml:
```
planner_configs:
AnytimePathShortening:
type: geometric::AnytimePathShortening
shortcut: true
hybridize: true
planners: PRM,PRM,PRM[max_nearest_neighbors=5],RRTConnect[goal_bias=.2],RRTConnect,BiEST,BiEST,BiEST
```
Note how several planning instances can be created, even multiple of the same type with different parameters.
[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. …
=> Add OMPL planner 'AnytimePathShortening', take #2

moveit_experimental/moveit_jog_arm/src/jog_calcs.cpp
Fixes a segfault issue with jog_arm where the fix bounds method tries to access invalid indices inthe velocity vector. Not sure if this is the best way to fix this. @AndyZe
=> fixing jog_arm segfault

moveit_ros/occupancy_map_monitor/package.xml
it is still at 1.0.1 while the old version from `moveit_ros_perception` is at 1.0.2 . This creates confusion
=> Update version of occupancy_map_monitor

moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_execution.h, moveit_ros/planning/plan_execution/src/plan_execution.cpp
This differentiates between checks caused by scene updates
and checks caused by changing trajectory components.
=> plan_execution: refine logging for invalid paths

moveit_ros/planning/trajectory_execution_manager/include/moveit/trajectory_execution_manager/trajectory_execution_manager.h, moveit_ros/planning/trajectory_execution_manager/src/trajectory_execution_manager.cpp
#1481  
My project was in huge need of canceling trajectory execution in quite often manner, over direct message via "stop" event on "/trajectory_execution_event" topic, or via move group interface `stop() ` method. I added one more mutex for protecting `execution_thread_` variable and it worked. Definitely it is not the optimal and the most elegant solution, but is quite effective. Long simulation period confirmed it has no memory leaks. 
=> Add execution thread mutex.

moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h, moveit_ros/planning_interface/move_group_interface/src/move_group_interface.cpp, moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
Improved const correctness in `move_group_interface` by adding `const` qualifier to member functions which do not modify the logical state. This PR also fixes couple instances where non-const iterators were compared against const iterators.
The interface defines move constructors which are now marked as noexcept. Long iterator types have been replaced with an auto type to improve readability of the code.
=> Improve move_group_interface const correctness

moveit_ros/planning_interface/CMakeLists.txt, moveit_ros/planning_interface/move_group_interface/CMakeLists.txt
=> Fix Travis: treat eigenpy as a system dependency

moveit_ros/visualization/robot_state_rviz_plugin/include/moveit/robot_state_rviz_plugin/robot_state_display.h, moveit_ros/visualization/robot_state_rviz_plugin/src/robot_state_display.cpp, moveit_setup_assistant/src/widgets/setup_assistant_widget.cpp
... to actually show the robot of the RobotStateDisplay (which is hidden initially since #1625).
Fixes b0f01b2dc79f99f5650933834c8e50905bdbe168.
Addresses https://github.com/ros-planning/moveit/issues/1736#issuecomment-554953490.
=> Fixup #1625: in MSA explicitly call setVisible(true)

moveit_core/utils/CMakeLists.txt
otherwise this can fail when building with moveit_msgs in one workspace.
=> add missing dependencies to library

moveit_ros/perception/point_containment_filter/include/moveit/point_containment_filter/shape_mask.h
Just made ShapeMask members protected, so that users can subclass it and make use of the existing data members and private classes.
This of course means making the C++ API public and saying it is stable.
=> Allow subclassing of point_containment_filter::ShapeMask.

moveit_core/distance_field/include/moveit/distance_field/distance_field.h, moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h, moveit_core/macros/include/moveit/macros/deprecation.h, moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h, moveit_core/robot_state/include/moveit/robot_state/robot_state.h, moveit_core/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h, moveit_ros/planning_interface/move_group_interface/include/moveit/move_group_interface/move_group_interface.h
This PR addresses #1229 and replaces existing usages of MOVEIT_DEPRECATED with [[deprecated]]. Additionally, a compiler warning is generated when the deprecation.h file is included.
=> Updating deprecation method
